### ISSUE TITLE
Initial Node Pool Metadata

### ISSUE THREAD

**Issue by gfthybridlabs** [terraform-google-modules/terraform-google-kubernetes-engine#1000]
Hi,

We have policies enabled that mean we must disable serial-port-logging, enable-guest-attributes etc. I add these to the node-pool definitions:-

```
node_pools_metadata = {
  all = {
    serial-port-logging-enable = false
    enable-guest-attributes = false
    disable-legacy-endpoits = true
  }
}
```

But the default-pool that gets created still has those attached (unless I have done it wrong) so the cluster creation fails.

How can I add those to the default-pool before it gets deleted and replaced with my node pools ?

Thanks

**Comment by morgante** [comment]
What value do you have for `remove_default_node_pool`?

We might need to fix the metadata here - https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/autogen/main/cluster.tf.tmpl#L250.

**Comment by gfthybridlabs** [comment]
Thanks. It's set to "true"

**Comment by morgante** [comment]
Thanks. If you're able to fix this a pull request would be appreciated.

**Comment by gfthybridlabs** [comment]
I'll see if I have the skills to do that. Hard coding a "metadata = {map}" object of K/V pairs works fine so just need to expose that as a variable.
