### ISSUE TITLE
workload-identity module with use_existing_gcp_sa and gcp_sa_name set

### ISSUE THREAD

**Issue by msonnleitner** [terraform-google-modules/terraform-google-kubernetes-engine#1002]
When using the workload-identity module with variables `gcp_sa_name` and `use_existing_gcp_sa` set, it seems that instead of `gcp_sa_name` `name` is used. Should there not be used the computed value `gcp_given_name` as well?

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/29bdc55b9f67943faa15230fc649acdf35977dbc/modules/workload-identity/main.tf#L35

**Comment by morgante** [comment]
Good catch, #1003 should fix this.
