### ISSUE TITLE
output the private endpoint

### ISSUE THREAD

**Issue by xophere** [terraform-google-modules/terraform-google-kubernetes-engine#1005]
Maybe this isn't possible as I can't seem to find it anywhere.  Is the only way to get this to run a command line option against the k8's cluster?  Seems like it is pretty clear if I have a private cluster I need to configure things to talk to the private not the public endpoint.

**Comment by bharathkkb** [comment]
You can use our [auth submodule](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/auth) with `use_private_endpoint` to generate auth for the private endpoint or if you just want the endpoint our [private cluster submodules should already output](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/be610cb07b836f86033523b145500a36806f9b2b/modules/beta-private-cluster/outputs.tf#L49) that value. Feel free to re open if still an issue.
