### ISSUE TITLE
Add support for "guest_accelerator" in container_node_pool.node_config

### ISSUE THREAD

**Issue by dkozlov** [terraform-google-modules/terraform-google-kubernetes-engine#101]
https://www.terraform.io/docs/providers/google/r/container_node_pool.html#node_config
https://www.terraform.io/docs/providers/google/r/container_cluster.html#guest_accelerator

**Comment by aaron-lane** [comment]
Fixed by #157.

**Comment by aaron-lane** [comment]
Fixed by #197.
