### ISSUE TITLE
disabling master authorized network after it is enabled

### ISSUE THREAD

**Issue by SabySen** [terraform-google-modules/terraform-google-kubernetes-engine#1012]
So we created a private GKE cluster with private end point. we enabled the master authorized network as below
in the tfvars
```
master_authorized_networks = [
  {
    cidr_block   = "10.158.10.10/32",
    display_name = "master-enabled-nw"
  },
]
```
then we re ran the terraform with the master authorized network removed like so
```
master_authorized_networks = []
```
it gives a peculiar error 
Error: googleapi: Error 400: Master authorized networks must be enabled if private endpoint is enabled., badRequest
  with module.gke.google_container_cluster.primary,
 on ../modules/private-cluster/cluster.tf line 22, in resource "google_container_cluster" "primary":

On further digging into it we found that the same is replicated when you run the gcloud comand as below. Note how the master authorized network is blank.
```
gcloud container clusters update <cluster> \
 --enable-master-authorized-networks \
 --master-authorized-networks "" \
 --region=<region>
```
where as the below should have been executed
```
gcloud container clusters update <cluster> \
 --enable-master-authorized-networks \
 --region=<region>
```

Any idea what we are doing wrong?

**Comment by morgante** [comment]
It looks like you're running into https://github.com/hashicorp/terraform-provider-google/issues/4093

First try upgrading to the latest version of Terraform and the provider. If that doesn't fix it, please file an issue on the provider.

As a workaround, you can just put your private IP range in the master authorized networks.

**Comment by SabySen** [comment]
@morgante I am unable understand. I think we are on the latest google provider and the version.
provider version is 3.79.0 and terraform 1.0.4. Is it not resolved in this version?

**Comment by morgante** [comment]
File an issue on the provider then.
