### ISSUE TITLE
Cloud DNS for GKE Clusters

### ISSUE THREAD

**Issue by mark-aops** [terraform-google-modules/terraform-google-kubernetes-engine#1013]
Hi All

We are using Cloud DNS for our GKE cluster, and it's now available via the terraform provider. Do you plan to implement this within the module and if so do you have an estimated release date?

Thanks
Mark.

**Comment by bharathkkb** [comment]
@mark-aops  We dont have an estimate at this point but happy to review a PR adding this to beta modules.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#dns_config
