### ISSUE TITLE
downtime caused by network tags or othe NodePool  parameters

### ISSUE THREAD

**Issue by shako92** [terraform-google-modules/terraform-google-kubernetes-engine#1016]
We are using beta private cluster module.

And when tried to add new network tags, module did create a new NodePool, and then stopped every node in the existing NodePool at the same time which caused significant downtime.

Our assumption is the native gke behavior is different and also native NodePool resource wouldnt have done this and it would have used Surge parameter to update existing NodePool in place, one by one without mass outage.

Is there a way to avoid such disruptions? 
Is there a way to use native surged update?
What would be you suggestions to avoid such cases?

**Comment by shako92** [comment]
Hm actually it seems like native update on existing NodePool is not yet in GA:
https://cloud.google.com/kubernetes-engine/docs/how-to/update-existing-nodepools

**Comment by morgante** [comment]
Your Terraform plan would show that the node pools needed to be recreated to apply the change. As your link notes, dynamic updates are not yet GA or supported in the Terraform provider.

If you want an alternative, you can use the "update-variant" module versions (ex. https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/private-cluster-update-variant) which create new node pools before destroying the old one.

Especially for production environments, it is highly recommended that you read the Terraform plan before applying to confirm that resources being deleted are acceptable.
