### ISSUE TITLE
Deprecation warning for workload_metadata_config parameter

### ISSUE THREAD

**Issue by wyardley** [terraform-google-modules/terraform-google-kubernetes-engine#1024]
I'm getting the following as permadrift with https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/beta-private-cluster and Google provider v3.88.0:

```diff
~ resource "google_container_node_pool" "pools" {
[…]
   ~ node_config {
[…]
     ~ workload_metadata_config {
       - mode     = "GKE_METADATA" -> null
```

If I explicitly set `node_metadata = "GKE_METADATA_SERVER"`, I get a deprecation warning about node_metadata being deprecated for mode, presumably from:

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/660ddc9afc9ed8a308d9388a08eff3c36af551a0/modules/beta-private-cluster/cluster.tf#L234

Either way, I can “apply” the drift, but it shows up on the next plan / apply. Is there a way to avoid this?

**Comment by wyardley** [comment]
@morgante won't the deprecation warning
```
│ Warning: Deprecated Attribute
│ 
│   with module.gke.google_container_cluster.primary,
│   on .terraform/modules/gke/modules/beta-private-cluster/cluster.tf line 227, in resource "google_container_cluster" "primary":
│  227:     node_config {
│ 
│ Deprecated in favor of mode.
```

be an issue in either case (esp. if the module is supporting both old and new versions of the provider)?

**Comment by brandondtb** [comment]
FYI, regarding version pinning, I only needed to pin the `google` provider to the version prior to the latest, `3.87.0` in order to avoid these updates.

**Comment by wyardley** [comment]
Hrm. I tried pinning one version back and didn’t have any luck, but will try it again.

**Comment by JCPistell** [comment]
FYI, upgrading to 3.90.0 does indeed seem to resolve this issue, but now I'm getting a deprecation warning for basic auth. Reported here: terraform-google-modules/terraform-google-kubernetes-engine#1042

**Comment by JCPistell** [comment]
The issue has been fixed in 3.90.1: https://github.com/hashicorp/terraform-provider-google/pull/10479

**Comment by mike-serchenia** [comment]
using 3.90.1
gets another error: [terraform-google-kubernetes-engine/issues/1045](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1045)

**Comment by FalconerTC** [comment]
This is broken again in 4.0+
