### ISSUE TITLE
Unable to create workload identity binding and belonging GSA in any other projects then the GCP project which has the GKE cluster

### ISSUE THREAD

**Issue by jonas-vadebo** [terraform-google-modules/terraform-google-kubernetes-engine#1041]
Use Case

We are a SRE team, we manage some shared GKE clusters. Our users run their workload in these clusters, but they do not run their GCP resources/buckets, databases etc...) in out managed GKE project. They manage their own Terraform code in their own projects, and need to be able to create Workload Identity SA + binding in their own projects, which points to the Workload pool which is in another GPC Project. Basically, we need to be able to override the behaviour today and add another PROJECT_ID to this row. 

k8s_sa_gcp_derived_name = "serviceAccount:${var.project_id}.svc.id.goog[${var.namespace}/${local.output_k8s_name}]"

**Comment by morgante** [comment]
You can set a different `project_id` value.

**Comment by jonas-vadebo** [comment]
@morgante I do not think you understand. What we need is a way to create the GSA in my-project-a this project does not contain the workload identity pool. But we still need to be able to tell the module whats the project id for the workload identity pool, which in this case would be my-project-b

GSA would be created in **project-a**, with the workload identity binding having the value 
k8s_sa_gcp_derived_name ="serviceAccount:${**project-b**.svc.id.goog[${var.namespace}/${local.output_k8s_name}]"

**Comment by jonas-vadebo** [comment]
We do not create the GSA and bindings in all same projects since a) we want the dev teams to be able to own their own TF config for their projects and b) limitation of 100 GSAs/ project if i remember correctly.

**Comment by jonas-vadebo** [comment]
I have a fix in a feature branch, but I am not able to push this feature branch of course because of permissions reasons.

**Comment by morgante** [comment]
@jonas-vadebo You submit a pull request from forks: https://gist.github.com/Chaser324/ce0505fbed06b947d962
