### ISSUE TITLE
Deprecation warning for Basic Auth when using Google/Google-Beta Provider 3.90.0

### ISSUE THREAD

**Issue by JCPistell** [terraform-google-modules/terraform-google-kubernetes-engine#1042]
After upgrading to Google/Google-Beta Provider version 3.90.0 I began to receive the following warning when using this module:

```
Warning: Attribute is deprecated

  on .terraform/modules/looker_gke/modules/beta-private-cluster-update-variant/cluster.tf line 22, in resource "google_container_cluster" "primary":
  22: resource "google_container_cluster" "primary" {

Basic authentication was removed for GKE cluster versions >= 1.19.
```

I tested on both versions `17.0.0` and `17.1.0` for the `private-cluster` and `beta-private-cluster` submodules

**Comment by rileykarson** [comment]
Resolved in https://github.com/hashicorp/terraform-provider-google/pull/10479, https://github.com/hashicorp/terraform-provider-google-beta/pull/3820. These should go out as provider version `3.90.1` within the next ~hour.

**Comment by JCPistell** [comment]
Upgrading to 3.90.1 did the trick. Thanks!
