### ISSUE TITLE
Cloud Logging - option to configure

### ISSUE THREAD

**Issue by lukpep** [terraform-google-modules/terraform-google-kubernetes-engine#1054]
is there an option to configure Cloud Logging via the module?
![CleanShot 2021-11-08 at 16 01 45](https://user-images.githubusercontent.com/2960580/140765616-f39c7d7c-5ca9-465c-97e8-4c5b5c82a789.png)
I would like to restrict logging only to system - preferably not via the GCP console ;-)

**Comment by lukpep** [comment]
Ok - i can see that beta clusters may have this in next module release:
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1028

**Comment by rwong2888** [comment]
@lukpep can we add this to the other modules, particularly `private cluster`?

**Comment by lukpep** [comment]
it's there :)

![CleanShot 2022-06-23 at 17 32 09](https://user-images.githubusercontent.com/2960580/175339756-c2ea87d4-be99-44fe-8eda-ecd40a6fca0d.png)

**Comment by rwong2888** [comment]
@lukpep your screenshot is showing `beta-private-cluster`. I am asking particularly about `private-cluster`. I did not see it mentioned in [private cluster submodule page](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest/submodules/private-cluster).

If it is indeed there, then perhaps the doc needs updating then?

Also, what is the difference between `logging_enabled_components` and `monitoring_enabled_components` in the original [PR](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1028/files)?
