### ISSUE TITLE
Unable to delete Workload Identity module after creation

### ISSUE THREAD

**Issue by afamagln** [terraform-google-modules/terraform-google-kubernetes-engine#1060]
I have created some resources using **terraform-google-workload-identity** - Google service account, kubernetes service account and IAM binding. 
The problem I am having is deleting these resources. When I remove the module from the manifest, it returns the following error: `Error: Cycle: module.kubernetes.google_container_cluster.primary[0], module.kubernetes.provider["registry.terraform.io/hashicorp/kubernetes"], module.kubernetes.module.my-app-workload-identity.kubernetes_service_account.main[0] (destroy)` which isn't detailed.

I suspect this is to do with the dependency between the resources it created which causes issues when deleting. 

Module
```
 module "my-app-workload-identity" {
   source     = "terraform-google-modules/kubernetes-engine/google//modules/workload-identity"
   name       = "abc-wi"
   namespace  = "default"
   project_id = var.project_id
   roles      = ["roles/editor",]
   cluster_name = google_container_cluster.primary[0].name
 }

**Comment by morgante** [comment]
Can you share your full Terraform config?

**Comment by bwburch** [comment]
Was there ever a fix for this error? I'm getting the same thing when I remove a workload identity from the list.
