### ISSUE TITLE
No option to enable Dataplane V2 in the safer-cluster module

### ISSUE THREAD

**Issue by jtangney** [terraform-google-modules/terraform-google-kubernetes-engine#1064]
### TL;DR

Module beta-private-cluster includes a variable to enable Dataplane V2 as below

datapath_provider = "ADVANCED_DATAPATH"

However this is var is not exposed in the safer-cluster module.

### Terraform Configuration

```hcl
module "gke" {
  source            = "terraform-google-modules/kubernetes-engine/google//modules/safer-cluster"
  
  project_id        = var.project_id
  name              = var.cluster_name
  release_channel   = "REGULAR"
  regional          = false
  region            = var.region
  zones             = var.zones
  network           = google_compute_network.vpc.name
  subnetwork        = google_compute_subnetwork.subnet.name
  ip_range_pods     = "pods"
  ip_range_services = "services"
  master_ipv4_cidr_block = var.master_ipv4_cidr_block
  
  # Dataplane V2
  datapath_provider = "ADVANCED_DATAPATH"
}
```

### Terraform Version

```sh
Terraform v1.0.6
on darwin_amd64
```

**Comment by jtangney** [comment]
I think explicitly setting to V2 makes sense. While it's not yet the default, it is recommended. So I think justified for safer-cluster.

**Comment by jawnsy** [comment]
I'd love to contribute this! It seems like a straightforward change, since `beta-private-cluster` used by `safer-cluster` already supports a configurable datapath.

A downside, of course, as already indicated by the breaking label, is that existing clusters would have to be destroyed and re-created to use the new setting. If we avoid making it a configurable option, then it's not possible for users to upgrade to the new version of the module without also re-creating their cluster.

**Comment by morgante** [comment]
> I'd love to contribute this! It seems like a straightforward change, since beta-private-cluster used by safer-cluster already supports a configurable datapath.

Yes, it should be a simple change. I'd be happy to review a PR!

> If we avoid making it a configurable option, then it's not possible for users to upgrade to the new version of the module without also re-creating their cluster.

Indeed. It might be better if we actually expose it as a variable (defaulted to true) so that existing users have an upgrade path.

**Comment by somethingnew2-0** [comment]
Implementing here https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1085

**Comment by somethingnew2-0** [comment]
This can be closed out now 😄

**Comment by jawnsy** [comment]
@somethingnew2-0 Thanks for implementing this!
