### ISSUE TITLE
Set image_type=COS_CONTAINERD by default

### ISSUE THREAD

**Issue by froblesmartin** [terraform-google-modules/terraform-google-kubernetes-engine#1069]
### TL;DR

As of https://cloud.google.com/kubernetes-engine/docs/concepts/node-images#cos-variants the COS variant is deprecated, therefore the default one used should be COS_CONTAINERD.

### Additional information

If this is right, I can open an MR to change it.

**Comment by morgante** [comment]
We can switch this in the next breaking release.
