### ISSUE TITLE
Support for Istio

### ISSUE THREAD

**Issue by tmc** [terraform-google-modules/terraform-google-kubernetes-engine#107]
This module doesn't seem to expose https://www.terraform.io/docs/providers/google/r/container_cluster.html#istio_config and it should.

**Comment by jpdesigndev** [comment]
Now there's `cloudrun_config` as well (something I need).

Perhaps there is a more future-proof mechanism for supporting `beta` features without having to play catch-up in this module. I don't know enough about terraform / this module's architecture to know.

Anyone have thoughts about how to get these in without requiring this modules to change every time there is a new `_config` item?

**Comment by aaron-lane** [comment]
Fixed by #124
