### ISSUE TITLE
'Autoscaling profile' parameter not present

### ISSUE THREAD

**Issue by juan-vg** [terraform-google-modules/terraform-google-kubernetes-engine#1076]
### TL;DR

The "Autoscaling profile" parameter (which is under Cluster Automation section) is not present

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#autoscaling_profile
```

### Additional information

![imagen](https://user-images.githubusercontent.com/17771395/143584493-630150c9-9fee-48e5-bdba-ae58c53bdb8d.png)

**Comment by morgante** [comment]
You can set autoscling profile, as shown here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/e53a949347417c1025eb433bc61c2a3e62e3df1c/examples/node_pool/variables.tf#L71
