### ISSUE TITLE
var.grant_registry_access requires devstorage.read_only access scope

### ISSUE THREAD

**Issue by teamgrowinfo** [terraform-google-modules/terraform-google-kubernetes-engine#1079]
### TL;DR

If `grant_registry_access` is `true` then access scope `https://www.googleapis.com/auth/devstorage.read_only` must be granted (via `node_pools_oauth_scopes`).

### Additional information

Maybe this is something to just clarify in the documentation.

**Comment by morgante** [comment]
Since the default value of `cloud_platform` is inclusive of `devstorage.read_only`, I'm not sure any change is warranted.
