### ISSUE TITLE
Export the name of the created VPC Peering

### ISSUE THREAD

**Issue by grieshaber** [terraform-google-modules/terraform-google-kubernetes-engine#1082]
### TL;DR

If a private cluster is created, a VPC Peering is created between the Google managed VPC for the control-plane and the VPC, where the nodes are spawned into. 
For further work, regarding access to the control-plane via VPN (via a shared vpc setup), it would be very helpful to export the name of the created VPC-Peering. 

As stated in the documentation, the output of the google_container_cluster ressource does already provide the peering Name:
```
In addition, the private_cluster_config allows access to the following read-only fields:

    peering_name - The name of the peering between this cluster and the Google owned VPC.
```

**Comment by morgante** [comment]
I'd be happy to review a PR adding this.

**Comment by grieshaber** [comment]
It seems, that this is already done for private clusters (where the peering is created). I'll close this issue.
