### ISSUE TITLE
Use TravisCI to run checks

### ISSUE THREAD

**Issue by pratikmallya** [terraform-google-modules/terraform-google-kubernetes-engine#11]
It should be really straightforward to setup a TravisCI integration so tests run on every PR and give a status check; this would greatly help external contributors (who may not be familiar with testing) to refine their PR's until tests Pass and then finally ask for review.

Note that TravisCi integration is free for Public repos on Github.com

**Comment by ryanckoch** [comment]
Most definitely! This is currently in our backlog.

**Comment by Jberlinsky** [comment]
Closing, since we've integrated Concourse here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/48
