### ISSUE TITLE
Documentation generation broken

### ISSUE THREAD

**Issue by tmc** [terraform-google-modules/terraform-google-kubernetes-engine#112]
As of 0f780cc5c01342631116573566cb82de8f54a7cd `make generate_docs` fails with

```
2019/03/22 10:23:51 At 17:1: expected: IDENT | STRING got: LBRACE
```

**Comment by thefirstofthe300** [comment]
A PR is [already in review](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/110) to get this error fixed.  It should be merged soon.

**Comment by aaron-lane** [comment]
Closing as duplicate of #110.
