### ISSUE TITLE
null provider breaks module on macOS M1/arm64

### ISSUE THREAD

**Issue by hazcod** [terraform-google-modules/terraform-google-kubernetes-engine#1134]
### TL;DR

The current `terraform-google-modules/kubernetes-engine/google//modules/workload-identity` module uses an old(er) version of the `null` provider,  which does not work on macOS arm64/m1.

### Expected behavior

Everything works.

### Observed behavior

```│ Error: failed to read schema for module.helm.module.dev_web_identity.module.annotate-sa.module.gcloud_kubectl.null_resource.upgrade in registry.terraform.io/hashicorp/null: failed to instantiate provider "registry.terraform.io/hashicorp/null" to obtain schema: timeout while waiting for plugin to start```

![image](https://user-images.githubusercontent.com/5222512/151151998-7ed7c1d1-cde0-4ebf-b90b-4a0c32cf4a7e.png)

### Terraform Configuration

```hcl
module "foo" {
    source     = "terraform-google-modules/kubernetes-engine/google//modules/workload-identity"
}
```

### Terraform Version

```sh
Terraform v1.1.4
on darwin_arm64
```

**Comment by bharathkkb** [comment]
Thanks for the report @hazcod 
Version 3.1 of the null provider looks like its [latest](https://github.com/hashicorp/terraform-provider-null/tags) and we do not have any constraints on the null provider version. This seems to be a provider issue, please open it here https://github.com/hashicorp/terraform-provider-null
