### ISSUE TITLE
Support ConfigConnector addon in beta module

### ISSUE THREAD

**Issue by andrewnazarov** [terraform-google-modules/terraform-google-kubernetes-engine#1141]
### TL;DR

It would be great to have support for the ConfigConnector addon as it's available in the provider (in Beta).

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#config_connector_config
```

**Comment by jmymy** [comment]
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/547

**Comment by andrewnazarov** [comment]
Oh, what a fault! Can't believe I missed this. I'm sorry for the noise.
