### ISSUE TITLE
Anthos Service Mesh integration integration in to safer-cluster-update-variant 

### ISSUE THREAD

**Issue by yugandhar-btc** [terraform-google-modules/terraform-google-kubernetes-engine#1153]
I would like to know related to “isitio” in cluster, since the support for isitio is stopped. 

Do we have to opt for Anthos?
Please advise or provide implementation steps for Anthos through terraform scripts which we have used in the below repo and also  do we need bother about the existing long running cluster ?

Our Repo: https://github.com/GoogleCloudPlatform/fda-mystudies

Terraform Resources:-

terraform-google-modules/kubernetes-engine/google//modules/safer-cluster-update-variant

**Comment by morgante** [comment]
If you want to use ASM, you can use the separate ASM submodule: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/asm
