### ISSUE TITLE
Private cluster timeout

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-kubernetes-engine#116]
Private cluster fails with a timeout when posting the config map (when `network_policy` is set to `true`:

```
1 error(s) occurred:

* module.gke.kubernetes_config_map.ip-masq-agent: 1 error(s) occurred:

* kubernetes_config_map.ip-masq-agent: Post https://192.168.134.2/api/v1/namespaces/kube-system/configmaps: dial tcp 192.168.134.2:443: i/o timeout
```

I think this might be linked to the missing feature for VPC Transitive peering that prevents an on-prem network from reaching the GKE master when it's private.

**Comment by thefirstofthe300** [comment]
@ocervell Are you attempting to talk to the master from a network other than the VPC to which the GKE cluster is attached?

**Comment by ocervell** [comment]
Yeah, running this from my local. Which confirms it fails because the VPC Transitive peering feature is not GA yet. 

Let's add a warning in the docs that the Terraform for this should run in the same VPC where the cluster is created, and will fail from a peered VPC or from an on-prem network connected through VPN ?

**Comment by morgante** [comment]
Note added in #121
