### ISSUE TITLE
Support Managed Service for Prometheus

### ISSUE THREAD

**Issue by mbarrien** [terraform-google-modules/terraform-google-kubernetes-engine#1167]
### TL;DR

Managed Service for Prometheus was recently [announced for general availability](https://cloud.google.com/blog/products/devops-sre/easy-managed-prometheus-metrics-service-for-kubernetes). Both the Terraform provider and this module should support it.

### Terraform Resources
Corresponding issue opened with Google provider to support this. 
https://github.com/hashicorp/terraform-provider-google/issues/11224

**Comment by bharathkkb** [comment]
Thanks for the FR @mbarrien 
We will wait for support in the provider.

**Comment by kriswuollett** [comment]
Not stale.

**Comment by JCPistell** [comment]
FYI - As of the 4.25.0 release this is now available in the beta provider.

https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.25.0

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1307
