### ISSUE TITLE
Node pool always recreated with any terraform apply

### ISSUE THREAD

**Issue by trudesea** [terraform-google-modules/terraform-google-kubernetes-engine#1171]
Hi,

This is more than likely a newb to terraform issue but I thought I'd ask.   Whenever I make any change to any tf file the gke module always wants to recreate the node pool, even if my change is not related to the node pool.

this is the code section:

```
node_pools_oauth_scopes = {
    all = []

    default-node-pool = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }
```
It does this in the init:

 ```
~ node_config {
          ~ oauth_scopes      = [
              - "https://www.googleapis.com/auth/logging.write",
              - "https://www.googleapis.com/auth/monitoring",
            ] -> (known after apply) # forces replacement
            tags              = [
                "gke-cluster",
            ]
          ~ taint             = [] -> (known after apply)
            # (10 unchanged attributes hidden)
            # (2 unchanged blocks hidden)
        }

```
Is this something I need to lifecyle?  Rebuilding the nodepool takes about 30min and doing that each time you make a change such as a label or tag  introduces too much downtime.

Thanks

**Comment by morgante** [comment]
Try removing `node_pools_oauth_scopes` from your config, since you're not changing the default anyways.

**Comment by trudesea** [comment]
> Try removing `node_pools_oauth_scopes` from your config, since you're not changing the default anyways.

that did the trick, thank you
