### ISSUE TITLE
New ASM module error

### ISSUE THREAD

**Issue by szihai** [terraform-google-modules/terraform-google-kubernetes-engine#1175]
### TL;DR

Running a simple test module on the new ASM module version 20, encountered errors.

### Expected behavior

ASM getting installed.

### Observed behavior

 Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connect: connection refused
│
│   with module.test-asm.kubernetes_namespace.system,
│   on .terraform/modules/test-asm/modules/asm/main.tf line 34, in resource "kubernetes_namespace" "system":
│   34: resource "kubernetes_namespace" "system" {
│

### Terraform Configuration

```hcl
module test-asm {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/asm"
  version = "20.0.0"

  project_id                = "xxx"
  cluster_name              = "xxxxx"
  cluster_location          = "us-east4-a"
  fleet_id                  = "xxxxx"
}
```

### Terraform Version

```sh
Terraform v1.1.6
on linux_amd64
```

**Comment by bharathkkb** [comment]
Thanks for the report @szihai 
Have you configured the k8s provider to use the correct cluster? https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/774fc12df6cb9f801caf72cd0ac6dfdbe723da46/examples/simple_zonal_with_asm/main.tf#L21-L27

**Comment by szihai** [comment]
It works. Thank you!
