### ISSUE TITLE
Cannot update a node pool count

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-kubernetes-engine#118]
Tried to create a private cluster with 1 node pool with 3 nodes initially, and a min = 1, max = 3 --> this worked.
Tried to update the node pool with 30 nodes initially, and a min=1, max=300 --> This fails with the following error:
![Screen Shot 2019-03-26 at 2 54 52 PM](https://user-images.githubusercontent.com/9629314/55029201-7d48d980-4fd7-11e9-9933-8dce892e032c.png)

Workaround: comment out the GKE cluster module call, `terraform apply`, uncomment the GKE cluster module call.

**Comment by morgante** [comment]
This seems like a provider issue - could you file an issue there?
