### ISSUE TITLE
How do you enable-workload-identity in hub? 

### ISSUE THREAD

**Issue by richiefrich** [terraform-google-modules/terraform-google-kubernetes-engine#1187]
### TL;DR

How do you enable-workload-identity in hub module as I am not seeing this on the README page. 
As ASM needs this now, or my setup of ASM. Thanks in advance!

### Terraform Configuration

```hcl
module "hub-primary" {
  source                            = "terraform-google-modules/kubernetes-engine/google//modules/hub"
  version                           = "19.0.0"

  cluster_name                      = module.primary-cluster.name
  cluster_endpoint                  = module.primary-cluster.endpoint
  enable_gke_hub_registration       = var.enable_gke_hub_registration
  gke_hub_membership_name           = "${module.primary-cluster.name}-membership"
  gke_hub_sa_name                   = "${module.primary-cluster.name}-sa"
  hub_project_id                    = var.project_id
  location                          = module.primary-cluster.location
  project_id                        = var.project_id
  labels                            = "name=value"
}
```

### Terraform Version

```sh
Terraform v1.1.3
```

**Comment by richiefrich** [comment]
thats already enable by default as with the description [1] below, so I am confused as to why when I install update ASM it tells me I need to run the following `gcloud container hub memberships register --gke-cluster=us-central1-a/uat-01 --enable-workload-identity uat-01-membership`

[1] **The workload pool to attach all Kubernetes service accounts to. (Default value of enabled automatically sets project-based pool [project_id].svc.id.goog)**

**Comment by morgante** [comment]
How are you installing ASM? Can you share your full configuration?

**Comment by richiefrich** [comment]
Morgante,

`module "asm-primary" {
  source                    = "terraform-google-modules/kubernetes-engine/google//modules/asm"
  version                   = "19.0.0"
  asm_version               = var.asm_version
  project_id                = var.project_id
  enable_all                = true
  managed_control_plane     = true
  cluster_endpoint          = module.primary-cluster.endpoint
  cluster_name              = module.primary-cluster.name
  location                  = module.primary-cluster.location
  enable_cluster_labels     = true
  enable_gcp_apis           = true
  enable_gcp_iam_roles      = false
  enable_gcp_components     = true
}
`

**Comment by morgante** [comment]
It looks like you're still using the v19 version. We completely rewrote the ASM module for v20 - can you give it a try and see if it fixes your issue?

**Comment by richiefrich** [comment]
Sure I will upgrade thanks!

**Comment by richiefrich** [comment]
it seem this version is broken for me also.

```[](NAME                                          CREATED AT

controlplanerevisions.mesh.cloud.google.com   2022-03-31T08:48:00Z

customresourcedefinition.apiextensions.k8s.io/controlplanerevisions.mesh.cloud.google.com

condition met

Error from server (NotFound): error when creating "STDIN": namespaces

"istio-system" not found

+ cleanup

+ rm -rf /tmp/kubectl_wrapper_18165_4537
```


the TF part is below
```
module "asm-primary" {
  source                    = "terraform-google-modules/kubernetes-engine/google//modules/asm"
  version                   = "20.0.0"
  project_id                = var.project_id
  cluster_name              = module.primary-cluster.name
  cluster_location          = module.primary-cluster.location
}
```

**Comment by morgante** [comment]
@Monkeyanator Any ideas? The script should be creating istio-system, so I'm not sure why that's not working.

**Comment by richiefrich** [comment]
If there is anything I can try I will as i will need to move to 20.0.0 soon.. the issue is i dont have time to debug why its not making the namespace. I see in the script it should be.

**Comment by richiefrich** [comment]
@morgante  yes I do have that role. Whats funny is I apply ASM to two clusters. and the one it does fine the 2nd I get the error I posted.
