### ISSUE TITLE
simple ASM cluster

### ISSUE THREAD

**Issue by yugandhar-btc** [terraform-google-modules/terraform-google-kubernetes-engine#1205]
Iam trying to create simple ASM cluster and my _main.tf_ is below ,what i have done is , i just declarer variables in my main.tf , usually I think it should work, could you please help me what went wrong please?

![image](https://user-images.githubusercontent.com/69250111/162476427-d6b599e2-a34d-4f25-9533-e1fb93fb300a.png)

ERROR:- 

![image](https://user-images.githubusercontent.com/69250111/162476000-e905ccb7-1340-4bd9-9cd1-87ac46832324.png)

### Terraform Configuration

```hcl
module "asm" {
  source            = "terraform-google-modules/kubernetes-engine/google//modules/asm"
  channel           = "regular"
  multicluster_mode = "connected"
  enable_cni        = false

}
```

### Terraform Version

```sh
Terraform v0.13.0
```

**Comment by apeabody** [comment]
Hi @yugandhar-btc thanks for the report.  I believe that the function [`anytrue`](https://www.terraform.io/language/functions/anytrue) requires Terraform v0.14 or later, and it appears from above you are using Terraform v0.13.0.

Could you please re-try with Terraform v0.14 or later, and if it is still failing provide an updated example?

**Comment by yugandhar-btc** [comment]
@apeabody Thank you!! So much.. and  _tf plan_ is successfully initialized

But while iam applying the _tf apply_ i cloud see below error, could you please help with this? thanks in advance!!!  

module.asm.kubernetes_namespace.system: Creating...
Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connect: connection refused

 on .terraform/modules/asm/modules/asm/main.tf line 34, in resource "kubernetes_namespace" "system":
  34: resource "kubernetes_namespace" "system" {

**Comment by apeabody** [comment]
Hi @yugandhar-btc 

I suspect the underlying kubernetes provider maybe defaulting to `localhost` as noted in your error.  I've opened #1208 to investigate.

If you are attempting to use with an existing GKE cluster, you might try adding the following with the correct values for your GKE cluster:
```
data "google_client_config" "default" {}

provider "kubernetes" {
  host                   = "https://${module.gke.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(module.gke.ca_certificate)
}
```
Alternatively you might want to look at this [example](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/simple_zonal_with_asm/main.tf) which creates a GKE cluster with ASM.

**Comment by apeabody** [comment]
Hi @yugandhar-btc - The documentation has been updated to include the required [Kubernetes provider configuration](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/asm).
