### ISSUE TITLE
The Kubernetes provider appears to fallback to localhost cluster

### ISSUE THREAD

**Issue by apeabody** [terraform-google-modules/terraform-google-kubernetes-engine#1208]
### TL;DR

When using the [asm](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/asm) submodule without a provider "kubernetes" {} it appears to [silently fallback to localhost](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1479).

### Expected behavior

Either require variables or clear failure reason

### Observed behavior

The provider attempts to create a cluster namespace on `localhost`.

### Terraform Configuration

```hcl
module "asm" {
  source            = "terraform-google-modules/kubernetes-engine/google//modules/asm"
  project_id        = var.project_id
  cluster_name      = module.gke.name
  cluster_location  = module.gke.location
}
```

### Terraform Version

```sh
Terraform v1.1.7
```

### Additional information

#1205

**Comment by bharathkkb** [comment]
As discussed offline lets start by adding an example provider config to the usage section https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/asm#usage. Here is another example not related to asm but similar https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1203

**Comment by apeabody** [comment]
Closing as we updated the sub-module user documentation and also reported to the upstream provider.
