### ISSUE TITLE
auth.tf in autopilot clusters isn't generated

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#1229]
### TL;DR

The auth.tf file in the autogenerated autopilot modules is not generated from the template.

### Terraform Configuration

```hcl
N/A
```

### Terraform Version

```sh
N/A
```

**Comment by dhess** [comment]
Is this why the Google security group with Kubernetes RBAC isn't enabled properly? If so, I just noticed this myself.

**Comment by morgante** [comment]
No, I don't think that is related. Can you file a separate issue about what you're seeing?
