### ISSUE TITLE
Add support for private Google CAS in the ASM module

### ISSUE THREAD

**Issue by thedebugger** [terraform-google-modules/terraform-google-kubernetes-engine#1254]
### TL;DR

Hi, ASM module doesn't support private Google CAS. Request is add that support like ASM cli. Happy to provide more info if needed

**Comment by Monkeyanator** [comment]
Since there's not a declarative way to configure the CA right now, the Terraform module doesn't support it. This is being actively worked on and I'll update once there is a timeline estimate.
