### ISSUE TITLE
Declaring COS_CONTAINERD in safer-cluster-update-variant

### ISSUE THREAD

**Issue by yugandhar-btc** [terraform-google-modules/terraform-google-kubernetes-engine#1256]
### TL;DR

How to declaring node image type in safer-cluster-update-varian

[safer-cluster-update-variant](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/safer-cluster-update-variant)

**Comment by bharathkkb** [comment]
Hi @yugandhar-btc 
Safer cluster internally uses `beta-private-cluster-update-variant` and it should default to `COS_CONTAINERD`. 
 https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/aee12e7175d6adf6d73c3bb5808399537ae56b48/modules/beta-private-cluster-update-variant/cluster.tf#L252 You can override it as needed via node_pools[]. image_type https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/aee12e7175d6adf6d73c3bb5808399537ae56b48/modules/safer-cluster-update-variant/variables.tf#L126
