### ISSUE TITLE
Support to install Managed Control and Data Plane

### ISSUE THREAD

**Issue by joca318** [terraform-google-modules/terraform-google-kubernetes-engine#1270]
### TL;DR

When you install the ASM you have an option named Managed Control and Data Plane but, there's not option to do that using [terraform-google-kubernetes-engine](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine)

### Terraform Resources

```markdown
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine
```

### Detailed design

```markdown
https://cloud.google.com/service-mesh/docs/managed/auto-control-plane-with-fleet
```

### Additional information

https://cloud.google.com/service-mesh/docs/managed/auto-control-plane-with-fleet

**Comment by mathieu-benoit** [comment]
Hi @joca318, to install/leverage ASM MCP on your GKE cluster, you could leverage this ASM module https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/asm. Have you seen/trie it?
For MDP, it's just an `annotation` on your `Namespaces`: https://cloud.google.com/service-mesh/docs/managed/configure-managed-anthos-service-mesh#managed-data-plane

**Comment by bharathkkb** [comment]
Closing as https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/asm is available.
