### ISSUE TITLE
Update Autopilot cluster modules README usage blocks

### ISSUE THREAD

**Issue by jacks-reid** [terraform-google-modules/terraform-google-kubernetes-engine#1271]
### TL;DR

The README usage blocks for both the `beta-autopilot-private-cluster` and `beta-autopilot-public-cluster` modules have outdated inputs. The `filestore_csi_driver` and `enable_autopilot` arguments shown are not found within `variables.tf`. 

In addition,  I believe the `enable_vertical_pod_autoscaling` variable should be enabled in the usage block otherwise the Autopilot cluster will error at creation time with: `Error 400: Autopilot clusters require vertical pod autoscaler to be enabled., badRequest`.

### Terraform Configuration

```hcl
module "gke" {
  source                          = "../../modules/beta-autopilot-public-cluster/"
  project_id                      = var.project_id
  name                            = "${local.cluster_type}-cluster"
  regional                        = true
  region                          = var.region
  network                         = module.gcp-network.network_name
  subnetwork                      = local.subnet_names[index(module.gcp-network.subnets_names, local.subnet_name)]
  ip_range_pods                   = local.pods_range_name
  ip_range_services               = local.svc_range_name
  release_channel                 = "REGULAR"
  filestore_csi_driver            = false # delete me
  enable_autopilot                = true # delete me
  enable_vertical_pod_autoscaling = true # add me
}
```

### Terraform Version

```sh
Terraform v1.2.1
```

**Comment by GusPrice** [comment]
I noticed this too, I think `enable_autopilot` is there for the eventual merge of the beta into main. I do think the module is also missing support for node service accounts, which are supposed to work in Autopilot according to:
https://github.com/hashicorp/terraform-provider-google/issues/9505
