### ISSUE TITLE
Support exclusion_options

### ISSUE THREAD

**Issue by ericyz** [terraform-google-modules/terraform-google-kubernetes-engine#1272]
### TL;DR

Support [exclusion_options](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#exclusion_options) in the module

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#exclusion_options
```

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1273, thanks @ericyz!
