### ISSUE TITLE
Improve autopilot test for checking if a cluster is running

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-kubernetes-engine#1280]
### TL;DR

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/a8b6f2001ac94a24f4e2c7b402e713e1173a999a/test/integration/simple_autopilot_public/controls/gcloud.rb#L34-L36 is eventually consistent. We should poll upto maxTimes with a timeout to prevent flakes.

"verify simple-autopilot-public-local": expected: "RUNNING"
"verify simple-autopilot-public-local": got: "RECONCILING"

### Terraform Configuration

```hcl
N/A
```

### Terraform Version

```sh
N/A
```

**Comment by apeabody** [comment]
@bharathkkb I'd suggest that RECONCILING is a valid state for this check, would you be open to this as a solution?

`expect(data['status']).to eq('RUNNING').or eq('RECONCILING')`

**Comment by bharathkkb** [comment]
@apeabody yeah that works, added to PR
