### ISSUE TITLE
So what happened to the ASM label?

### ISSUE THREAD

**Issue by richiefrich** [terraform-google-modules/terraform-google-kubernetes-engine#1283]
### TL;DR

How can I pull the ASM version now that you removed the labels?

I see I can use revision_name as output but that only tells me 

 ```bash
 + revision_name = "asm-managed"
```

I really need the version number where can I pull that from, as I dont see it on 

```bash
gcloud container clusters describe
```

### Terraform Configuration

```hcl
module "asm-primary" {
  source                    = "terraform-google-modules/kubernetes-engine/google//modules/asm"
  version                   = "21.1.0"
  project_id                = var.project_id
  cluster_name              = module.primary-cluster.name
  cluster_location          = module.primary-cluster.location
}
```

### Terraform Version

```sh
terraform version
Terraform v1.1.9
```

**Comment by bharathkkb** [comment]
@richiefrich Could you elaborate on the issue? Were you looking for a way to pull ASM version info via Terraform?

**Comment by richiefrich** [comment]
Yes I would really like a way to pull the managed ASM version via Terraform
