### ISSUE TITLE
Add exclusion_options option for maintenance_exclusion setting

### ISSUE THREAD

**Issue by vasrem** [terraform-google-modules/terraform-google-kubernetes-engine#1297]
### TL;DR

Currently there is no support for https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#exclusion_options whenever someone uses `maintenance_exclusion`. This is not flexible enough since it defaults to `NO_MINOR_UPGRADES` according to https://cloud.google.com/kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions#scope_of_maintenance_to_exclude.

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#exclusion_options
```

### Detailed design

```markdown
This is a change in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/37b5da85b06d289abf6eeafcbb2df3cfec998bec/autogen/main/cluster.tf.tmpl#L262-L269. 

This change probably introduces breaking API change since the variable type needs to be expanded https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/37b5da85b06d289abf6eeafcbb2df3cfec998bec/autogen/main/variables.tf.tmpl#L111-L115.

This change requires google provider version >= 4.22.0
https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4220-may-24-2022
```

**Comment by bharathkkb** [comment]
Happy to review a PR adding this

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1273

**Comment by vasrem** [comment]
I'm sorry for the duplicate issue, I didn't notice
