### ISSUE TITLE
Examples link in module registry does not work

### ISSUE THREAD

**Issue by mlschechter** [terraform-google-modules/terraform-google-kubernetes-engine#130]
In the main `README`, the following text is displayed in the module registry on terraform.io: "There are multiple examples included in the examples folder but simple usage is as follows".

The link for the examples (https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/examples/) returns a 404 if you click on it.

**Comment by morgante** [comment]
I think this feedback should be passed to HashiCorp or the module registry, since they're essentially not parsing the README's relative links correctly.

**Comment by mlschechter** [comment]
I've created https://github.com/hashicorp/terraform/issues/20930

Thanks!
