### ISSUE TITLE
Error: local-exec provisioner error  - ASM Module 

### ISSUE THREAD

**Issue by jobyglcoud** [terraform-google-modules/terraform-google-kubernetes-engine#1343]
**Source Code** 
source  = "terraform-google-modules/kubernetes-engine/google//modules/asm"
version = "22.0.0"

**Error: local-exec provisioner error**
│ 
│   with module.asm.module.asm.module.cpr.module.gcloud_kubectl.null_resource.run_command[0],
│   on .terraform/modules/asm.asm.cpr/main.tf line 231, in resource "null_resource" "run_command":
│  231:   provisioner "local-exec" {
│ 
│ Error running command 'PATH=/google-cloud-sdk/bin:$PATH
│ .terraform/modules/asm.asm.cpr/modules/kubectl-wrapper/scripts/kubectl_wrapper.sh
│ false false .terraform/modules/asm.asm/modules/asm/scripts/create_cpr.sh
│ asm-managed regular true false
│ ': exit status 1. Output: + '[' 10 -lt 5 ']'
│ + CLUSTER_NAME=gke-cluster-01
│ + LOCATION=<location>
│ + PROJECT_ID=<project name>
│ + INTERNAL=false
│ + USE_EXISTING_CONTEXT=false
│ +
│ ENABLE_IMPERSONATE_SERVICE_ACCOUNT=.terraform/modules/asm.asm/modules/asm/scripts/create_cpr.sh
│ + IMPERSONATE_SERVICE_ACCOUNT=asm-managed
│ + shift 5
│ + false
│ + RANDOM_ID=31806_23127
│ + export TMPDIR=/tmp/kubectl_wrapper_31806_23127
│ + TMPDIR=/tmp/kubectl_wrapper_31806_23127
│ + trap cleanup EXIT
│ + mkdir /tmp/kubectl_wrapper_31806_23127
│ + export KUBECONFIG=/tmp/kubectl_wrapper_31806_23127/config
│ + KUBECONFIG=/tmp/kubectl_wrapper_31806_23127/config
│ ++ grep -o -
│ ++ wc -l
│ + LOCATION_TYPE=2
│ + CMD='gcloud container clusters get-credentials
│ <clustername> --project <project name>'
│ + [[ .terraform/modules/asm.asm/modules/asm/scripts/create_cpr.sh == true
│ ]]
│ + [[ 2 -eq 2 ]]
│ + CMD+=' --zone <zone name>'
│ + false
│ + gcloud container clusters get-credentials gke-cluster-01
│ --project <project name>1 --zone <zone name>
│ Fetching cluster endpoint and auth data.
**│ ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403,
│ message=Required "container.clusters.get" permission(s) for
│ "projects/<project name>/zones/<zone name>/clusters/gke-cluster-01".**

**Comment by szihai** [comment]
Looks like the account/service account you run the script does not have enough IAM permissions to execute the script.
