### ISSUE TITLE
Readme for Autopilot modules reference unused "enable_autopilot" input

### ISSUE THREAD

**Issue by grsiepka** [terraform-google-modules/terraform-google-kubernetes-engine#1352]
In the Readme examples for both the beta-autopilot-private-cluster and beta-autopilot-public-cluster, there's reference to an input: enable_autopilot = true, however that doesn't seem to be a valid input (maybe at one time it was?)  and its not listed in the list of inputs in the module documentation.

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/beta-autopilot-private-cluster/README.md#usage

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/beta-autopilot-public-cluster/README.md#usage

**Comment by bharathkkb** [comment]
@grsiepka thanks for the report! Yes IIRC this is now a local since we split out into dedicated module. We should clean up the readme.

**Comment by akshaybathija-github** [comment]
Pr #1368 raised to fix the issue, will confirm once merged

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1368
