### ISSUE TITLE
ASM integration to safer-cluster-update-variant

### ISSUE THREAD

**Issue by yugandhar-btc** [terraform-google-modules/terraform-google-kubernetes-engine#1357]
### TL;DR

Can you please help me with the code to integrate the ASM to safer-cluster-update-variant

### Terraform Resources

```markdown
terraform 0.14.0
```

**Comment by bharathkkb** [comment]
Hi @yugandhar-btc 
Did you encounter any issues? I think it will mostly be similar to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/simple_zonal_with_asm/main.tf. Something I can think is you would need control plane access when enable_private_endpoint is set.

**Comment by bharathkkb** [comment]
Feel free to reopen if you need anything else!

**Comment by yugandhar-btc** [comment]
@bharathkkb the recommendation is to use only **safer-cluster-update-variant** ,can you please help me what is differences between safer-cluster-update-variant & simple_zonal_with_asm cluster , are they both same ?
