### ISSUE TITLE
Suggest `network_policy` be enabled by default

### ISSUE THREAD

**Issue by bgeesaman** [terraform-google-modules/terraform-google-kubernetes-engine#138]
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/autogen/variables.tf#L106

Suggest enabling it by default on newly created clusters by default.  Recommended by the CIS GCP Benchmark to be enabled. See: https://www.cisecurity.org/benchmark/google_cloud_computing_platform/

Pros: Allows for support of `NetworkPolicy` objects if they are applied without having to modify the cluster.
Cons: The slight overhead of Calico agents and Typha in the cluster if `NetworkPolicy` is unused.

**Comment by morgante** [comment]
+1

**Comment by aaron-lane** [comment]
Is #315 sufficient or do we want this to be the default on all modules?

**Comment by morgante** [comment]
Let's default to true.
