### ISSUE TITLE
Enable cluster autoscaling without cluster auto-provisioning

### ISSUE THREAD

**Issue by Al77056** [terraform-google-modules/terraform-google-kubernetes-engine#1380]
### TL;DR

Some of our workloads are tested only on certain type of nodes, such as those that support cpu pinning and / or low latency networks. Currently these features are supported only by c2 and c2d nodes. We create special node pools to run these workloads, and would like to change the autoscaling profile to "optimize utilization" without enabling the auto-provisioning feature.

**Comment by g-awmalik** [comment]
@Al77056 - this is actually available right now. This is how you would set it using one of the *beta* modules:

```
cluster_autoscaling = {
    enabled             = false
    autoscaling_profile = "OPTIMIZE_UTILIZATION"
    ...
}
```

[`cluster_autoscaling.enabled`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#enabled) is the flag to set node auto provisioning.

Feel free to reopen if your desired output something else.
