### ISSUE TITLE
master_global_access_config was promoted to GA

### ISSUE THREAD

**Issue by ei-grad** [terraform-google-modules/terraform-google-kubernetes-engine#1382]
### TL;DR

`master_global_access_config` and probably some other fields shouldn't be in beta since they have been promoted to GA long ago (until 4.0.0 release, which is the oldest entry in current [CHANGELOG](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md)):

https://github.com/hashicorp/terraform-provider-google/pull/8303

> container: promoted `master_global_access_config`, `tpu_ipv4_cidr_block`, `default_snat_status` and `datapath_provider` fields of `google_container_cluster` to GA.

**Comment by bharathkkb** [comment]
Thanks for the report @ei-grad 
Happy to promote these fields.

**Comment by DrFaust92** [comment]
this can be closed, all of these are GA in the module. @apeabody
