### ISSUE TITLE
Support cost allocation

### ISSUE THREAD

**Issue by jawnsy** [terraform-google-modules/terraform-google-kubernetes-engine#1392]
### TL;DR

Add support for the new cost allocation feature

### Additional information

The [latest 4.35.0 release of the Google provider](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.35.0) includes [a new attribute](https://github.com/hashicorp/terraform-provider-google/pull/12416) to add support for the [GKE cost allocation](https://cloud.google.com/kubernetes-engine/docs/how-to/cost-allocations) feature, which logs GKE usage data to BigQuery for reporting.

**Comment by bharathkkb** [comment]
Thanks for the report @jawnsy 
Happy to review a PR adding this

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1413
