### ISSUE TITLE
Importing existing kube clusters seems to be forbidden

### ISSUE THREAD

**Issue by pratikmallya** [terraform-google-modules/terraform-google-kubernetes-engine#14]
importing clusters seems to fail with this error:
```
terraform import module.prod_cluster.google_container_cluster.primary $PROJECT/$REGION/$CLUSTER

Error: Provider "kubernetes" depends on non-var "local.cluster_endpoint". Providers for import can currently
only depend on variables or must be hardcoded. You can stop import
from loading configurations by specifying `-config=""`.
```

This is a huge problem because it breaks the `terraform import` functionality

**Comment by morgante** [comment]
This is unfortunately because we initialize the kubernetes provider for you.

Can you get around it by specifying `-config=""`?

**Comment by aaron-lane** [comment]
Hi @pratikmallya.

I'm closing this issue due to a lack of activity. Please reopen it if you would like to continue the discussion.

**Comment by Nosmoht** [comment]
Can we reopen the issue? I've the same problem. Using `-config=""` doesnt help at all.

**Comment by evkuzin** [comment]
Check this [PR](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/242)
Looks working and it fix this issue

**Comment by bharathkkb** [comment]
provider configs removed by #777
