### ISSUE TITLE
allow node base os image type to be specified in google_container_node_pool resources

### ISSUE THREAD

**Issue by chrisadkin** [terraform-google-modules/terraform-google-kubernetes-engine#1414]
### TL;DR

Please add an image_type attribute to the google_container_node_pool which takes the image of the node base os.

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool
```

### Detailed design

```markdown
N/A - simple change
```

**Comment by billyfoss** [comment]
I believe this is already supported under the node_config parameter
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_node_config

**Comment by chrisadkin** [comment]
That is great news, should image_type not be mentioned here ?:

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool

**Comment by bharathkkb** [comment]
@chrisadkin This is captured in the nodepools var docs here https://github.com/terraform-google-modules/terraform-google-kubernetes-engine#node_pools-variable
