### ISSUE TITLE
can't provision cluster with shared vpc

### ISSUE THREAD

**Issue by namcxn** [terraform-google-modules/terraform-google-kubernetes-engine#142]
terraform apply with error
> 1 error(s) occurred:
> 
> * module.gke.google_container_cluster.primary: 1 error(s) occurred:
> 
> * google_container_cluster.primary: googleapi: Error 400: The user does not have access to service account "terraform@xxxx.iam.gserviceaccount.com". Ask a project owner to grant you the iam.serviceAccountUser role on the service account., badRequest

`The user` what ?

sevices account `terraform@xxxx.iam.gserviceaccount.com` owner project

my config with share-vpc

> module "gke" {
>   source             = "./modules/tf-moduel-k8s-2.0.0"
>   project_id         = "${var.project}"
>   name               = "${local.cluster_type}-cluster${var.cluster_name_suffix}"
>   region             = "${var.region}"
>   network            = "${var.network}"
>   network_project_id = "${var.network_project_id}"
>   subnetwork         = "${var.subnetwork}"
>   ip_range_pods      = "${var.ip_range_pods}"
>   ip_range_services  = "${var.ip_range_services}"
>   service_account    = "${var.compute_engine_service_account}"
> }

Tks

**Comment by namcxn** [comment]
Resolved. Closed

**Comment by ravigude** [comment]
@namcxn , I am having the same issue. How did you solve the issue ?

**Comment by namcxn** [comment]
> @namcxn , I am having the same issue. How did you solve the issue ?

I was add all scopes for cluster

`node_pools_oauth_scopes = {
    all = [
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
      "https://www.googleapis.com/auth/service.management.readonly",
      "https://www.googleapis.com/auth/servicecontrol",
      "https://www.googleapis.com/auth/trace.append",
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/monitoring.write",
      "https://www.googleapis.com/auth/cloud_debugger",
    ]
    default-node-pool = []
  }`
