### ISSUE TITLE
add Backup for GKE option for private-cluster module 

### ISSUE THREAD

**Issue by tomekzielins** [terraform-google-modules/terraform-google-kubernetes-engine#1450]
### TL;DR

Since Backup for GKE service has moved from BETA to GA please add option to use variable gke_backup_agent_config  in private_cluster variant. Similarly as it is done beta-private-cluster variant. 

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#gke_backup_agent_config
```

**Comment by shubhamkr619** [comment]
@bharathkkb Please assign this to me
