### ISSUE TITLE
Add dns_config support in beta-autopilot-private-cluster module

### ISSUE THREAD

**Issue by Chris-Perrin** [terraform-google-modules/terraform-google-kubernetes-engine#1458]
### TL;DR

Dns_config support was added via PR [feat: cloud-dns support](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1317). Discussed [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1013). Would like this to be made available in beta-autopilot-private-cluster module.

**Comment by okguru1** [comment]
bump - was this actually completed? can't see this configuration exposed: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/beta-autopilot-private-cluster/variables.tf
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/fd233e5cddd9098b6e6520b0671eb16f77a5c187/modules/beta-autopilot-private-cluster/cluster.tf#L22

**Comment by micahtmiller** [comment]
Can this be re-opened?  It looks like the work to expose dns_config has been completed for the standard cluster configs, but  not for autopilot.
