### ISSUE TITLE
Gateway Controller is GA

### ISSUE THREAD

**Issue by nlamirault** [terraform-google-modules/terraform-google-kubernetes-engine#1462]
### TL;DR

Since Gateway Controller is GA, it would be interesting to have it in the configuration options.

https://cloud.google.com/blog/products/containers-kubernetes/google-kubernetes-engine-gateway-controller-is-now-ga?hl=en

**Comment by bharathkkb** [comment]
Thanks for the report @nlamirault 
Looks like this is being added to the provider in https://github.com/GoogleCloudPlatform/magic-modules/pull/6875. Happy to review a PR once this is added to the provider.

**Comment by tuunit** [comment]
@nlamirault my terraform provider change to enable the gateway controller workflow https://github.com/GoogleCloudPlatform/magic-modules/pull/6875 was merged. I can already start implementing it for this module with my local build but we will have to wait for the next official terraform provider release.

**Comment by tuunit** [comment]
@nlamirault @lauraseidler Gateway API is now part of the latest terraform google provider: https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.47.0

I'll have a look at integrating it into this module now. All the best and happy christmas 🎄

**Comment by tuunit** [comment]
@nlamirault @lauraseidler PR is open #1510
