### ISSUE TITLE
Create full examples and run them regularly

### ISSUE THREAD

**Issue by docwhat** [terraform-google-modules/terraform-google-kubernetes-engine#1466]
### TL;DR

In order to encourage the use of the opinionated GKE Terraform module we should provide working **full** examples that can be deployed.  These examples should be run regularly as an integration test to catch regression and changes in the upstream providers.

### Detailed design

```markdown
The current examples are incomplete.  They cannot be cut and pasted into a new terraform setup and "Just Work™️".

I propose that complete examples are created.

These examples should be run regularly (e.g., on change by a GitHub Action) against a real GCP account to show they work.  The output of the runs should be captured and linked in the READMEs for each example.

This should make adoption much easier for new users since they will have a complete working example, and they will be able to look at the output of the GitHub Action runs to see what is happening.
```

### Additional information

While the kitchen tests are helpful, they aren't enough to understand what's going on for someone learning both GCP, GKE providers, and the GKE modules.

**Comment by bharathkkb** [comment]
@docwhat thanks for the feedback. We have full examples like https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/simple_regional_with_networking which only require a project_id. Does that satisfy your usecase?

Most of our examples are e2e tested although we don't expect users to interact with the tests directly.

**Comment by docwhat** [comment]
Well, considering I'm having a hard time getting the simple autopilot up and working, I guess it isn't.  I've theorized that the problem is that my project isn't set up correctly, but the feedback from the failure isn't helping me. ☹️

**Comment by docwhat** [comment]
Maybe if there was a way to dump the account permissions and the project configuration (without revealing secrets) that would be useful. 

I think you could scrape them from the Terraform state before tearing everything down and add that info to the test results.

**Comment by docwhat** [comment]
Thanks for the offer.  I have moved on several steps since then.  Overall, there is a lack of reconciling what I see in the web UI, in `gcloud`, and in Terraform.  I can't dump/list out a bunch of the states to see how they line up.

Since there are so many knobs and settings in gcp and gke it makes it hard to understand what isn't working.
