### ISSUE TITLE
Binary authorization parameter seams to be skipped

### ISSUE THREAD

**Issue by DS-KrzJon** [terraform-google-modules/terraform-google-kubernetes-engine#1468]
Module: terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster-update-variant
Version: 22.0.0 in comparission to 23.3.0

We are using enable_binary_authorization   = true  as fixed value, but the cluster created in the past (TF CLI 1.2.1 and Module 22.0.0) is now disabling the enable_binary_authorization  (TF CLI 1.3.2 and Module 23.3.0).

GKE Version (Stable 1.23.11-gke.300)
![image](https://user-images.githubusercontent.com/99729487/202770445-d4697d6b-b03b-4ab3-a009-03ed8d6c9c06.png)

Is there a quick workaround? Is it really broken?
In the past I saw only the information that enable_binary_authorization  will be deprecated in favour of binary_authorization. Maybe someone who knows more could check what's goin on. It's very annoing issue.

**Comment by bharathkkb** [comment]
I believe that is expected, do you see a diff of the new block getting created too?
```
      + binary_authorization {
          + evaluation_mode = "PROJECT_SINGLETON_POLICY_ENFORCE"
        }
```
as explained by the author here
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1332#issuecomment-1192976207
