### ISSUE TITLE
Support for node pool upgrade strategy

### ISSUE THREAD

**Issue by max-f-z** [terraform-google-modules/terraform-google-kubernetes-engine#1472]
### TL;DR

could we add support for gke node pool settings for upgrade strategy? [gke blue green upgrade strategy](https://cloud.google.com/kubernetes-engine/docs/how-to/node-pool-upgrade-strategies#configure-blue-green-upgrades) is out & recently supported in [terraform provider v4.44.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.44.0)

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool
```

### Detailed design

```markdown
N/A
```

**Comment by abalasub1312** [comment]
i am working on it.

**Comment by ProgEsteves** [comment]
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1551

**Comment by ProgEsteves** [comment]
Still waiting complete reviews to merge.
