### ISSUE TITLE
Include threads per core configuration for GKE clusters

### ISSUE THREAD

**Issue by axcosta** [terraform-google-modules/terraform-google-kubernetes-engine#1474]
### TL;DR

I'm not sure if this is already being handled somewhere, but I haven't seen yet for this module the configuration documented at https://cloud.google.com/kubernetes-engine/docs/how-to/configure-smt, where it is possible to determine number of threads per core that GKE nodes will have for given cluster. Please advise.

**Comment by bharathkkb** [comment]
@axcosta Looks like the support for that feature is being added to the provider in https://github.com/GoogleCloudPlatform/magic-modules/pull/6808. Once added to the provider, happy to review a PR adding it here.

**Comment by accole** [comment]
@bharathkkb https://github.com/GoogleCloudPlatform/magic-modules/pull/6808 has been completed - can we prioritize this support?  My customer specifically is looking to leverage this within the beta-private-cluster-update-variant
