### ISSUE TITLE
add managed_prometheus to terraform-google-modules/kubernetes-engine/google//modules/private-cluster

### ISSUE THREAD

**Issue by naresh-gn** [terraform-google-modules/terraform-google-kubernetes-engine#1497]
### TL;DR

beta-private-cluster has option to enable managed prometheus in GKE but private-cluster does not have it.

### Terraform Resources

```markdown
terraform-google-modules/kubernetes-engine/google//modules/private-cluster
```

### Detailed design

```markdown
add managed_prometheus option for terraform-google-modules/kubernetes-engine/google//modules/private-cluster
```

**Comment by nmatare** [comment]
+1 for feature

**Comment by IIBenII** [comment]
added with this PR: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1505
