### ISSUE TITLE
Remove default node pools and manage them explicitly

### ISSUE THREAD

**Issue by pratikmallya** [terraform-google-modules/terraform-google-kubernetes-engine#15]
The default node pools cause trouble with managing the cluster. It seems like a better architecture to manage the node pools explicitly. Does it make sense to use the `remove_default_node_pool` parameter for the `google_container_cluster` and add just manage the node pools explicitly?

ref: https://github.com/terraform-providers/terraform-provider-google/issues/475#issuecomment-383529139

**Comment by morgante** [comment]
We definitely encourage explicitly managing the node pools, as shown in the examples: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/node_pool

Regarding the `remove_default_node_pool` parameter, I believe we ran into some trouble with bootstrapping using it. @ryanckoch can share more. The approach we have today is, I believe, to create a default node pool with 0 nodes.

**Comment by pratikmallya** [comment]
Oh, would love to hear about what the issues were with using that parameter @ryanckoch :)

**Comment by AdrienWalkowiak** [comment]
I would love to see this fixed too!

**Comment by miles-** [comment]
I'd also like to help get this fixed - what was the issue with the `remove_default_node_pool` parameter? @ryanckoch

**Comment by morgante** [comment]
@ryanckoch Can you chime in here?

**Comment by aaron-lane** [comment]
Fixed by #55.
