### ISSUE TITLE
gpu nodepool with gpu_sharing_strategy & max_shared_clients_per_gpu not possible

### ISSUE THREAD

**Issue by kdngit12** [terraform-google-modules/terraform-google-kubernetes-engine#1506]
### TL;DR

gpu nodepool with gpu_sharing_config including gpu_sharing_strategy & max_shared_clients_per_gpu currently cannot be created as these parameters cannot be passed/configured like the one from resource "google_container_node_pool"

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool

...
guest_accelerator {
      type  = "nvidia-tesla-a100"
      gpu_partition_size = "1g.5gb"
      count = 1
      gpu_sharing_config {
        gpu_sharing_strategy = "TIME_SHARING"
        max_shared_clients_per_gpu = 2
      }
}	
...
```

### Additional information

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodeConfig

**Comment by s04** [comment]
Bump! Hoping this get's exposed soon :)

**Comment by nthnb** [comment]
Bump!

**Comment by rsaget** [comment]
Hey, any news on this ?

**Comment by em-le-ts** [comment]
Hey, any news for this feature?
Thanks
