### ISSUE TITLE
Use NoExecute instead of NO_EXECUTE in node pool

### ISSUE THREAD

**Issue by arthurgustin** [terraform-google-modules/terraform-google-kubernetes-engine#152]
When creating `nodepool` with taints, I'd expect writing `NoExecute` as stated in the doc https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

But it throws in the console:

`expected node_config.0.taint.0.effect to be one of [NO_SCHEDULE PREFER_NO_SCHEDULE NO_EXECUTE], got NoExecute`

**Comment by morgante** [comment]
Can you clarify what the issue is here? I don't think it's a bug in this module.

**Comment by arthurgustin** [comment]
It's not an issue, just something I find inconsistent

**Comment by morgante** [comment]
Got it, I think it's an upstream issue with the provider and/or GKE API rather than this module.
