### ISSUE TITLE
Disable Master authorized network

### ISSUE THREAD

**Issue by mholleville** [terraform-google-modules/terraform-google-kubernetes-engine#153]
Hi ! is it possible to disable `master_authorized_networks_config` ? We have Saas CI and we needed her to be able to access the cluster. Unfortunately, because it’s a service, we don’t have an associated CIDR

**Comment by morgante** [comment]
Would allowing additional CIDR blocks to the authorized config be sufficient? (This could include `0.0.0.0/0`.)

**Comment by aaron-lane** [comment]
@mholleville does @morgante's proposal satisfy your use case?

**Comment by gabriel8fm** [comment]
Hi @morgante @aaron-lane, I am getting the same. I need to allow from the external IP address of the private GKE cluster but I'm facing the below error when trying to specify on the module configuration:

`Error: Error waiting for resuming GKE cluster: Invalid master authorized networks: network "0.0.0.0/0" is not a reserved network, which is required for private endpoints`

I am using the **beta-private-cluster**.

Does anyone know a solution for this case?

**Comment by gabriel8fm** [comment]
> Hi @morgante @aaron-lane, I am getting the same. I have to allow access from the external IP address to the private GKE cluster, but I'm facing the below error when trying to specify on the module configuration:
> 
> `Error: Error waiting for resuming GKE cluster: Invalid master authorized networks: network "0.0.0.0/0" is not a reserved network, which is required for private endpoints`
> 
> I am using the beta-private-cluster.
> 
> Does anyone know a solution for this case?

It was something wrong in my tf state file. Once I removed the `module.gke.google_container_cluster.primary` it is passing ok with plan/apply.
