### ISSUE TITLE
Add support for GKE Protect/Security Posture

### ISSUE THREAD

**Issue by jawnsy** [terraform-google-modules/terraform-google-kubernetes-engine#1586]
### TL;DR

Add support for GKE Security Posture, formerly known as GKE Protect

### Terraform Resources

>The protect_config block supports:
>
>workload_config - (Optional, Beta) WorkloadConfig defines which actions are enabled for a cluster's workload configurations. Structure is documented below
>
>workload_vulnerability_mode - (Optional, Beta) Sets which mode to use for Protect workload vulnerability scanning feature. Accepted values are WORKLOAD_VULNERABILITY_MODE_UNSPECIFIED, DISABLED, BASIC.
>
>The protect_config.workload_config block supports:
>
>auditMode - (Optional, Beta) WorkloadConfig defines the flags to enable or disable the workload configurations for the cluster. Accepted values are MODE_UNSPECIFIED, DISABLED, BASIC.

Documentation link: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#protect_config

### Additional information

Requires TPG 4.40.0 and was introduced inhttps://github.com/hashicorp/terraform-provider-google/issues/12778

**Comment by NissesSenap** [comment]
Work ongoing
