### ISSUE TITLE
Support disk_type in cluster_autoscaling (Node Auto-provisioning)

### ISSUE THREAD

**Issue by nthnb** [terraform-google-modules/terraform-google-kubernetes-engine#1588]
### TL;DR

Would it be possible to add functionality to support disk_type for Node Auto-provisioning? 

It could be specified like so:
  cluster_autoscaling = {
    disk_type = "pd-ssd"
  }
  
This is currently supported in the google_container_cluster Terraform resource. Thanks!

### Terraform Resources

```markdown
Currently google_container_cluster Terraform resource supports this:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#cluster_autoscaling
```

**Comment by unix-way** [comment]
This parameter would indeed be very useful
