### ISSUE TITLE
asm: error creating Feature: Resource already exists

### ISSUE THREAD

**Issue by loeffel-io** [terraform-google-modules/terraform-google-kubernetes-engine#1590]
### TL;DR

terraform ref: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_feature#name
module ref: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/asm/hub.tf#L31

`google_gke_hub_feature` name must be unique. It's not possible to use this module for multiple clusters in the same project.

### Terraform Configuration

```hcl
--
```

### Terraform Version

```sh
--
```

**Comment by loeffel-io** [comment]
could belong to https://github.com/hashicorp/terraform-provider-google/issues/13825 or https://github.com/hashicorp/terraform-provider-google/issues/10934

**Comment by gtsorbo** [comment]
@loeffel-io The servicemesh `gke_hub_feature` should only be created once per fleet (i.e. once per project). Set `var.enable_mesh_feature = false` to avoid enabling the feature again when installing ASM on subsequent clusters. Additional clusters should still be registered to the fleet and follow through the rest of installation as part of this module
