### ISSUE TITLE
Refactor/flatten duplicate resources

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#161]
Currently, the "zonal" and "regional" clusters are defined using separate resources. Now that Terraform has a single "location" parameter which can be used for either we can collapse the two cluster resources into a single resource (using that parameter).

Some work was already done on this here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/147

**Comment by kopachevsky** [comment]
## Container Cluster

For GKE cluster params I would propose to switch following vars:

```hcl
    variable "regional" {
      type        = bool
      description = "Whether is a regional cluster (zonal cluster if set false. WARNING: changing this after cluster creation is destructive!)"
      default     = true
    }

    variable "region" {
      type        = string
      description = "The region to host the cluster in (required)"
    }

    variable "zones" {
      type        = list(string)
      description = "The zones to host the cluster in (optional if regional cluster / required if zonal)"
      default     = []
    }
```

To:

```hcl
    variable "location" {
      type        = bool
      description = "The location (region or zone) in which the cluster master will be created, as well as the default node location. "
      default     = true
    }

    variable "node_locations" {
      type        = list(string)
      description = "The list of zones in which the cluster's nodes should be located.  (required)"
    }
```

This naming aline zonal/regional cluster config with **google_container_cluster** terraform resource fields. https://www.terraform.io/docs/providers/google/r/container_cluster.html

## Node Pool

In current implementation for each defined node pool only first element of **var.zones** array used to define zone or region location:

```hcl

/******************************************
  Create zonal node pools
 *****************************************/
resource "google_container_node_pool" "zonal_pools" {
  provider = google-beta
  count    = var.regional ? 0 : length(var.node_pools)
  name     = var.node_pools[count.index]["name"]
  project  = var.project_id
  zone     = var.zones[0]
  // .... other properties ......
}

```

This means user can't define several node pools located in different zones for zonal and multi-zonal clusters

Proposition here is to add **location** property for **node_pools** param:

```hcl
module "gke" {
  node_pools = [
    {
      name            = "pool-01"
      location   = "us-central1-a"
      node_count = 2
    },
    {
      name            = "pool-02"
      location   = "us-central1-b"
      node_count = 2
    },
  ]
  // .... other properties ......
}
```

This change will align Node Pools settings with **google_container_node_pool** TF resource. https://www.terraform.io/docs/providers/google/r/container_node_pool.html#location

**Comment by morgante** [comment]
@kopachevsky I'm not clear why this should require any variable changes (and that is not the ask).

We should keep the API surface identical. This is merely an internal change in how the module is implemented.
