### ISSUE TITLE
No ability to use node_pool_auto_config outside of auto pilot cluster.

### ISSUE THREAD

**Issue by Jedsman** [terraform-google-modules/terraform-google-kubernetes-engine#1649]
There is currently no way to specify node_pool_auto_config settings for other cluster types such as private clusters. We have enabled node auto provisioning, but cannot add NAP tags to the automatically provisioned node pools.

This just needs the same logic as is used in the auto pilot module adding to other modules, such as private clusters.

**Comment by raanand-dig** [comment]
this missing config just ruied my day

**Comment by alyssahardy** [comment]
This appears to still be an issue.

**Comment by MyMirelHub** [comment]
There is a draft #1841 which also provisions `node_pool_auto_config` in the case where it is not an autopilot cluster and `cluster_autoscaling` is enabled
