### ISSUE TITLE
asm: Allow the kubernetes_namespace resource to define custom labels/annotations

### ISSUE THREAD

**Issue by julianxhokaxhiu** [terraform-google-modules/terraform-google-kubernetes-engine#1678]
### TL;DR

I'd like if possible to have the possibility to customize labels and/or annotations in [the namespace that is being created](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/asm/main.tf#L39).

This is at the moment required because of one monitoring system I'm using that requires a label at the namespace level.

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/namespace
```

### Detailed design

```tf
variable "system_namespace_annotations" {
  type = map
  default = {}
}

variable "system_namespace_labels" {
  type = map
  default = {}
}

resource "kubernetes_namespace" "system" {
  count = var.create_system_namespace ? 1 : 0

  metadata {
    name = "istio-system"
    annotations = var.system_namespace_annotations
    labels = var.system_namespace_labels
  }
}
```

**Comment by torbendury** [comment]
This is especially a 
 for us since we use a monitoring tool which automatically adds their own injection label to the namespace. On every Terraform rollout, this label is removed because the asm module can't be made aware of it.

**Comment by julianxhokaxhiu** [comment]
Still valid.

**Comment by torbendury** [comment]
This issue is still valid and should be fixed.
