### ISSUE TITLE
Support for default_max_nodes_per_host

### ISSUE THREAD

**Issue by algermissen** [terraform-google-modules/terraform-google-kubernetes-engine#170]
Hi,
I would like to add default_max_nodes_per_host parameter. I have created a branch for this: https://github.com/algermissen/terraform-google-kubernetes-engine/tree/add-default-max-pods-per-node

However, I had to hard-code the beta-provisioner and this prevents me from raising a PR.

Can you give any advice how you would like to have it integrated? Currently it is dependent on another condition and adding to that will make everything less clear.

Please provide direction and I'll adjust and raise PR.

**Comment by aaron-lane** [comment]
Hi @algermissen. Thank you for your interest in contributing! 

We are considering a redesign of this module in the near future which may require use of the beta provider for both public and private clusters, so this is not an unprecedented change. Please propose your change and we will try to include it when the new version is released.

**Comment by algermissen** [comment]
Hi @aaron-lane PR is here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/174

**Comment by morgante** [comment]
Fixed by #220.
