### ISSUE TITLE
Missing gpu_driver_installation_config

### ISSUE THREAD

**Issue by alyssahardy** [terraform-google-modules/terraform-google-kubernetes-engine#1723]
### TL;DR

Per https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#create-gpu-pool-auto-drivers, to auto-install the drivers, one must add gpu_driver_installation_config to the nodepool configuration under guest_accelerator.

```
guest_accelerator {
  type  = var.gpu_type
  count = 1
  gpu_driver_installation_config {
    gpu_driver_version = var.gpu_driver_version
  }
}
```

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster.html#gpu_driver_installation_config
```

**Comment by mahaddad** [comment]
+1 - It's not clear how to auto install drivers with terraform. There seems to be a few options discussed here: https://cloud.google.com/kubernetes-engine/docs/how-to/gpus - but what's the recommended workaround in the meantime?

**Comment by alyssahardy** [comment]
Google suggests using the kubectl provider to apply the manifest. Set the url to either the stable or latest url. The example is latest.
```
provider "kubectl" {
  host                              = format("https://%s", module.gke.endpoint)
  cluster_ca_certificate = base64decode(module.gke.ca_certificate)
  token                            = data.google_client_config.current.access_token
  load_config_file          = false
}

data "http" "nvidia_driver_installer_manifest" {
  url   = "https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded-latest.yaml"
}

resource "kubectl_manifest" "nvidia_driver_installer" {
  yaml_body = data.http.nvidia_driver_installer_manifest.response_body
}
```

**Comment by S4ckBr** [comment]
Could it be reopened? We would like to use this feature in the module.
