### ISSUE TITLE
Support `advanced_datapath_observability_config`

### ISSUE THREAD

**Issue by Markieta** [terraform-google-modules/terraform-google-kubernetes-engine#1755]
### TL;DR

Add inputs for the block:

```HCL
advanced_datapath_observability_config {
  enable_metrics # true | false
  relay_mode # DISABLED | INTERNAL_VPC_LB | EXTERNAL_LB
}
```

### Terraform Resources

- [google_container_cluster#advanced_datapath_observability_config](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#advanced_datapath_observability_config)
- [Class AdvancedDatapathObservabilityConfig](https://cloud.google.com/python/docs/reference/container/latest/google.cloud.container_v1.types.AdvancedDatapathObservabilityConfig)

**Comment by Jojoooo1** [comment]
Would be very great to have this feature!
