### ISSUE TITLE
additional_pod_ranges_config

### ISSUE THREAD

**Issue by baiyibing123** [terraform-google-modules/terraform-google-kubernetes-engine#1788]
### TL;DR

additional_pod_ranges_config- (Optional) Configs other pod secondary ranges at the cluster level. For Autopilot clusters and standard clusters, secondary Pod IP address assignment is not required to control node pools. The structure is recorded as follows.
When to support it

### Additional information

additional_pod_ranges_config- (Optional) Configs other pod secondary ranges at the cluster level. For Autopilot clusters and standard clusters, secondary Pod IP address assignment is not required to control node pools. The structure is recorded as follows.
When to support it

**Comment by baiyibing123** [comment]
For GKE Autopilot clusters with version 1.26 or later, you can add more Pod IPv4 ranges by creating additional secondary ranges and assigning them to the cluster.
When to support

**Comment by szihai** [comment]
Are you talking about this:https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/variables.tf#L140
It's already added.
