### ISSUE TITLE
Add monitoring_enabled_components to beta-autopilot-private-cluster module

### ISSUE THREAD

**Issue by panystro** [terraform-google-modules/terraform-google-kubernetes-engine#1793]
### TL;DR

Configuring cluster monitoring packages in beta-autopilot-private-cluster module variant is not possible at the moment. This setting exists in the main module but not in this submodule. Requesting to add this same functionality to the mentioned submodule. 

### Terraform Resources

monitoring_enabled_components is equivalent to monitoring_config terraform resource

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_monitoring_config 
```
As mentioned above, configuring this is already possible in the main module.

**Comment by m3adow** [comment]
This also applies to the `safer-cluster-update-variant` module.

**Comment by ve4eslav** [comment]
This has already been done for standard clusters. Could you duplicate this for autopilot clusters as well.
Thank you.
