### ISSUE TITLE
Custom Node Pools gets recreated even without any changes in subsequent Terraform runs

### ISSUE THREAD

**Issue by bibinwilson** [terraform-google-modules/terraform-google-kubernetes-engine#189]
I am using custom node pools by setting, `remove_default_node_pool    = true`. When i run terraform again, the custom node pools gets recreated even without any changes in the terraform configuration.

**Expected behaviour:** Custom node pools should not get recreated unless there is a change.

**Comment by morgante** [comment]
Can you please share your Terraform configuration and the output of `terraform plan`?

**Comment by bibinwilson** [comment]
Hi,

My issue got rectified when I added "disable-legacy-endpoints = "true""

my setup needed custom metadata and disable-legacy-endpoints metadata was not part of it. It fixed the issue.
