### ISSUE TITLE
Provide networking example

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#195]
Currently, we create networks in the test fixtures.

It would be helpful to adapt at least one of the examples themselves to include network creation (using the network module) to demonstrate how the GKE module and network module can work together.

The `simple_regional` example could do this.

**Comment by aaron-lane** [comment]
This could jive nicely with the move to ephemeral test projects.

**Comment by bharathkkb** [comment]
Hi @aaron-lane @morgante 
Is this being worked on?

**Comment by morgante** [comment]
Not currently! Feel free to pick it up.
