### ISSUE TITLE
Create a service account for nodes if one isn't provided.

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#2]
We need a holistic solution here which permanently removes the dependency on the default service account. Including:

1. Adding a top-level variable of `service_account` which accepts three values:
a. the email of a custom Service Account,
b. `default-compute` (the default compute service account), or
c. `create` - automatically creates a service account for use

This top-level service account will be default for all node pools which don't explicitly provided.

These flags can optionally be implemented incrementally.

**Comment by Jberlinsky** [comment]
@morgante Picking this up.

One quick clarification -- I read this as `create` should create a service account **for the cluster** for use, that is to say that it will have the cluster name in the service account ID. Please let me know if you had something else in mind.

**Comment by morgante** [comment]
Correct.

**Comment by morgante** [comment]
One addendum: I would still like us to do some discovery on why a service account is even required. GCE VMs do *not* all require service accounts, so it's not clear why the module would break without a service account at all.

**Comment by Jberlinsky** [comment]
Based on https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#use_least_privilege_sa, the service account is necessary to enable Stackdriver for monitoring and logging, and pulling images from GCR.

**Comment by aaron-lane** [comment]
Fixed by #80.
