### ISSUE TITLE
Support min_cpu_platform in auto_provisioning_defaults

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-kubernetes-engine#2034]
### TL;DR

Expose https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#min_cpu_platform for beta modules

**Comment by vhespanha** [comment]
Can you assign it to me?

**Comment by DrFaust92** [comment]
Closed via https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/2208 

cc @apeabody
