### ISSUE TITLE
gcfs_config variable forces replacement

### ISSUE THREAD

**Issue by dominykasn** [terraform-google-modules/terraform-google-kubernetes-engine#2048]
### TL;DR

gcfs_config variable forces replacement to node pools when importing 

### Expected behavior

Importing without issues when gcfs is disabled in GUI and in gcloud CLI

### Observed behavior

When importing plan shows forced replacement to node pool, image streaming is disabled in GCP GUI and in gcloud CLI
```          
- gcfs_config { # forces replacement
              - enabled = false -> null
            }
```

### Terraform Configuration

```hcl
module "gke" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"
  version = "~> 32.0.0"

  ....
  node_pools = [
    {
      name = "n2d-c8-m32"
      image_type = "COS_CONTAINERD"
      enable_secure_boot = true
      enable_gcfs = false
    },
```

### Terraform Version

```sh
Terraform v1.8.4
```

**Comment by AlvaroGG0** [comment]
Working on it already: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1976

**Comment by dominykasn** [comment]
Nice, I also have a pull request open for similar issue https://github.com/GoogleCloudPlatform/magic-modules/pull/11553

**Comment by dominykasn** [comment]
@apeabody can I open a new pull request in this repository to change [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1976) ? From what I can see the PR is being only rebased 🤔

**Comment by apeabody** [comment]
This should be fixed by https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.2.0

**Comment by wyardley** [comment]
I saw the fix with 6.2.0 supporting updating in place (will test with 6.2.0 shortly), but the thing that's odd to me is that I already explicitly had `enable_gcfs = false` in my config with version 32 of the module, and I seem to get a planned diff force replacement by all of removing that (allowing default), setting it to `true`, _or_ setting it to `false`.

**Comment by apeabody** [comment]
> I saw the fix with 6.2.0 supporting updating in place (will test with 6.2.0 shortly), but the thing that's odd to me is that I already explicitly had `enable_gcfs = false` in my config with version 32 of the module, and I seem to get a planned diff force replacement by all of removing that (allowing default), setting it to `true`, _or_ setting it to `false`.

Hi @wyardley - I believe that particular issue with `enable_gcfs = false` should be resolved by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1976 in [v33](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/releases/tag/v33.0.0).

**Comment by wyardley** [comment]
@apeabody thanks!

fwiw, I was seeing this with `33.0.1`. I'm having some issues with OpenTofu registry not having 6.2.0, but I'll try again once that's available.

**Comment by wyardley** [comment]
@apeabody thanks for the additional quick fix 🙏
