### ISSUE TITLE
Incomplete documentation for terraform_docs.sh dependancy

### ISSUE THREAD

**Issue by Dev25** [terraform-google-modules/terraform-google-kubernetes-engine#209]
As part of the migration to Terraform 0.12 #177, https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/177/commits/eb0a0e77bcfd84d3581d76b36b338ecc1ff0a96e#diff-e9cfabf9b162cebf5922498a77b8f766R103 introduced a depedancy on a file from https://github.com/antonbabenko/pre-commit-terraform which is not mentioned in the README. 

Trying to run `make generate_docs` on master without the script in your $PATH will lead to errors, `terraform_docs.sh` is required because upstream terraform-docs does not support Terraform 0.12.

**Comment by morgante** [comment]
FYI we're planning to standardize on using Docker images to run all tests, which should solve this.

**Comment by aaron-lane** [comment]
This will be fixed by #251.

**Comment by aaron-lane** [comment]
Fixed by #262.
