### ISSUE TITLE
Output variables are available before nodes are up

### ISSUE THREAD

**Issue by kevensen** [terraform-google-modules/terraform-google-kubernetes-engine#212]
In most (if not all) cases, the output variables are available before the nodes of the cluster are up.  For example, the `endpoint` variable is populated as soon as it is known to Terraform (makes sense).

It would be helpful to not populate these variables until the nodes are up in a node pool.  Or add an output variable that is along the lines of `pods_schedualable` to provide a check whether or not other resources can be deployed in the cluster.

**Comment by kevensen** [comment]
Would love feedback on this thought.  The GKE REST API provides a status in the response [object](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster).  Would it be reasonable to set a variable (e.g. module.gke.ready) if the [state](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.Status) is RUNNING?

**Comment by kevensen** [comment]
Or have the output variable be module.gke.state?

**Comment by morgante** [comment]
One of the issues is that I think the cluster actually slips between RUNNING and RECONCILING as it spins up node pools so we can't simply wait for it to become 'RUNNING' the first time.

**Comment by kevensen** [comment]
boo

**Comment by morgante** [comment]
That being said, I think added `depends_on` to the outputs similar to the internal dependencies should help make this a bit better: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/masq.tf#L43

**Comment by kevensen** [comment]
How would that work?

output variable --> [triggered in] --> null resource --> [depends on] --> [all that](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/masq.tf#L43)

**Comment by kevensen** [comment]
nm.  I think I figured it out.

https://www.terraform.io/docs/configuration/outputs.html#depends_on-explicit-output-dependencies

**Comment by morgante** [comment]
Yeah, do you think you could open a PR?

**Comment by kevensen** [comment]
I am working on it as we speak

**Comment by kevensen** [comment]
I am thinking of making the `endpoint` output variable "depend on" these resources.  Do you think we ought make another variable?

**Comment by morgante** [comment]
Probably all the variables should, but you can start with whichever ones are important for your use case.

**Comment by kevensen** [comment]
understood.

**Comment by kevensen** [comment]
merged and closed
