### ISSUE TITLE
Query on inspec tests for GKE

### ISSUE THREAD

**Issue by edward2a** [terraform-google-modules/terraform-google-kubernetes-engine#213]
Hi all,

I have been trying to do some comprehensive tests using inspec-gcp, but it has not satisfied my needs due to, I believe, improper handling of the API and/or Ruby SDK data.

I see that your tests are obtaining the GKE cluster description as a JSON directly from the API (as shown [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/test/integration/simple_zonal/controls/gcloud.rb) , is there any particulars for this?

Thank you,
Ed

**Comment by morgante** [comment]
In this case, our approach is simply to embed the gcloud command inside the tests. This is the key line: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/test/integration/simple_zonal/controls/gcloud.rb#L22

**Comment by edward2a** [comment]
@morgante I noticed what the case is, what I was wondering is why this approach not use inspec-gcp, although I guess it is due to inspec-gcp not really covering the whole of the test cases.

**Comment by aaron-lane** [comment]
@edward2a that is correct. inspec-gcp does not yet provide full coverage of GCP with resources.
