### ISSUE TITLE
Enable Secret Manager 

### ISSUE THREAD

**Issue by mskuratowski** [terraform-google-modules/terraform-google-kubernetes-engine#2157]
### TL;DR

Hi, 

How can I enable Secret Manager addon in terraform code? I can't find any option to do so.

When I enable it manually and then run terrafom code than I see in the plan:
`secret_manager_config { enabled = true -> null }`

**Comment by wyardley** [comment]
It looks like the module currently supports it, but only in the beta variants of the module (to be used with the beta Google provider). So in the short term, that's the easiest fix if you can do it (e.g., `beta_private_cluster` vs `private_cluster`).

Seems like it's now GA as of [6.1.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.1.0), so probably when 5.x support is fully dropped, I think in the next major release after 34.0.0, this could be changed to GA in this module too.

I have gone ahead and made a PR (#2159) that will add this support in GA. I think once #2126 etc. go in, it won't need to be a breaking change of its own.
