### ISSUE TITLE
Host node pools within specific zones for a regional cluster

### ISSUE THREAD

**Issue by stevemenezes** [terraform-google-modules/terraform-google-kubernetes-engine#2173]
### TL;DR

Is there a way we could leverage node_locations to take specific zone values and not all? From what I understand, [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/beta-private-cluster/main.tf#L46) just gets all zones for a regional cluster? My end goal is basically having a particular node pool in a subset of zones.

For example: If cluster is in region us-east1, where zones could be `us-east1-b,us-east1-c,us-east1-d`, I would like to have a node pool in a subset of zones `us-east1-b,us-east1-d`.

**Comment by Crazy-Hopper** [comment]
Taking into account [this line](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/0ebdfda69591a525018ee9c4a41b353bb2777fa6/modules/beta-private-cluster/cluster.tf#L618) you could easily do it by passing node_locations like this:
```
node_locations = join(",", [
  "us-east1-b",
  "us-east1-d",
])
```

**Comment by stevemenezes** [comment]
Thanks that worked
