### ISSUE TITLE
Deploying GKE private cluster using Shared VPC

### ISSUE THREAD

**Issue by viharikrishna** [terraform-google-modules/terraform-google-kubernetes-engine#224]
Hello,

I’ve got a 
Host project - Shared VPC with subnets shared across service projects.
Service project - Using one of the subnet

I've a separate terraform repo controlling all the networking configuration on the host project and a separate terraform repo for the resources in service projects. 
Now, In case of spinning a private GKE cluster in service project, Peering is established between the our VPC network and google VPC network. Since I’m spinning the cluster using my terraform code in the service project this info is not part of host project state file. When any changes made in host project that will wipe out the peering since it is not stored in the state file of host project’s.

How to overcome this situation?

**Comment by morgante** [comment]
Can you clarify the peering you're referring to? This module should work fine with a Shared VPC use case (including if the host project is stored in another Terraform config).

**Comment by viharikrishna** [comment]
Hello Morgante, 

I was referring to
"Your VPC network contains the cluster nodes, but a separate VPC network in a Google-owned project contains the master. The two VPC networks are connected using VPC Network Peering."

In this case

1. Does host project allows this to perform on the network? Since in the host project, I've only got permission to use a given subnet for my GKE. 

2. Even If it establishes the peering, It is stored in my terraform state file which is in the service project and not in the terraform state of host project. My understanding is that when any changes made to the network on the host project and perform terraform apply It will wipe our the peering that was established.

**Comment by morgante** [comment]
Got it, how this works is the peering is done on your behalf by the GKE Service Agent. There isn't a direct configuration update to your network made through this module (and hence nothing ends up in either state file).

To get this to work, the step you need to take is to grant the GKE Service Agent in your service project the `container.hostServiceAgentUser` role on the host project.

These docs explain it: https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc#grant_host_service_agent_role
If you use the Google Project Factory, it's implemented here: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/main.tf#L485
