### ISSUE TITLE
Certain fields may be missing from google's API call while refreshing state

### ISSUE THREAD

**Issue by richardmcsong** [terraform-google-modules/terraform-google-kubernetes-engine#226]
In particular, addonsConfig.istioConfig, PodSecurityPolicyConfig, VerticalPodAutoscaling seem to sometimes be missing. I've raised a Google support ticket, and they've confirmed that it seems to be expected behaviour for now. This behaviour will raise errors when this module checks for those fields.

**Comment by morgante** [comment]
Can you open a provider ticket? I'm confused on what we would do in the module to address this.

**Comment by richardmcsong** [comment]
I was looking at the block from main.tf lines 243-265, if we could make sure that those fields actually exist in the object before looking up their value, and assign a default if the field doesn't exist, then we could prevent the error from being raised

**Comment by morgante** [comment]
I don't quite follow. This doesn't seem like a module error, those values are optional and shouldn't require an input.

Please share the actual error you're getting.

**Comment by richardmcsong** [comment]
I apologize for the delay. I've been getting this error:
```
Error: Invalid index

  on .terraform/modules/gke/modules/beta-private-cluster/main.tf line 229, in locals:
 229:     regional = element(concat(google_container_cluster.primary.*.addons_config.0.istio_config.0.disabled, [""]), 0)

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/gke/modules/beta-private-cluster/main.tf line 234, in locals:
 234:     regional = element(concat(google_container_cluster.primary.*.pod_security_policy_config.0.enabled, [""]), 0)

The given key does not identify an element in this collection value.
```

**Comment by morgante** [comment]
Can you share your config and the plan info as well? We need more to be able to reproduce. Thanks.
