### ISSUE TITLE
Support for SecurityGroups - authenticator_groups_config

### ISSUE THREAD

**Issue by jerckov** [terraform-google-modules/terraform-google-kubernetes-engine#227]
It will be nice if there will be support for SecurityGroup beta feature:

https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#google-groups-for-gke
https://www.terraform.io/docs/providers/google/r/container_cluster.html#authenticator_groups_config
https://github.com/terraform-providers/terraform-provider-google/issues/3407

Any plans for this?

**Comment by morgante** [comment]
Yes, #217 is in progress to add this.

**Comment by jerckov** [comment]
Cool! Looking forward for it!

**Comment by morgante** [comment]
Fixed by #217
