### ISSUE TITLE
Allow cluster service account to be overridden without specifying in `var.node_pools`

### ISSUE THREAD

**Issue by Jberlinsky** [terraform-google-modules/terraform-google-kubernetes-engine#23]
When a service project is created with [terraform-google-project-factory](https://github.com/terraform-google-modules/terraform-google-project-factory), it does not have a default compute instance, which breaks the default usage thereof. Specifying it as part of `var.node_pools` does not work in all circumstances, as the tags & taints do not get read in properly.

**Comment by morgante** [comment]
#2 is related.

**Comment by aaron-lane** [comment]
Fixed by #80.
