### ISSUE TITLE
Automatically update labels for sandboxed node pools

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#252]
This is a follow up to #240.

Based on https://github.com/terraform-providers/terraform-provider-google/issues/4210, if sandboxing is enabled then the control plain will add this label to the cluster automatically: `sandbox.gke.io/runtime" = "gvisor`.

This causes a permadiff. We should fix this by automatically injecting that label into the config if the sandbox flag is `true` on the module.

**Comment by nick4fake** [comment]
Working on it.

**Comment by paulpalamarchuk** [comment]
@morgante This label cannot be set for the node pool.
Error:
```
Error: error creating NodePool: googleapi: Error 400: Node label "sandbox.gke.io/runtime" is reserved for gke sandbox., badRequest
```

**Comment by morgante** [comment]
@paulpalamarchuk Without this label, are we seeing a diff on labels post-apply?

**Comment by paulpalamarchuk** [comment]
@morgante Yes. TF state don't have that label

**Comment by morgante** [comment]
Got it. Please focus on moving the resource block (and adding a test).

I will take care of the label issue.

**Comment by paulpalamarchuk** [comment]
Shall I create test (fixtures, etc.) for the "sandbox" config?

**Comment by morgante** [comment]
Just add the flag + test to an existing suite such as `simple_regional_beta`.
