### ISSUE TITLE
Consider deprecating zones/region

### ISSUE THREAD

**Issue by umairidris** [terraform-google-modules/terraform-google-kubernetes-engine#259]
I believe support for `null` in Terraform 0.12 (https://www.hashicorp.com/blog/terraform-0-12-conditional-operator-improvements) can remove the need for zones, region and regional vars.

I wonder if we can:
- Add a new `location`field. Directly set in the cluster for `location`
- Set default of kubernetes_version to null. Directly set in the cluster for `min_master_version`.
- Add new field `node_locations`. Directly set in the cluster for `node_locations`.

This should simplify the module quite a bit both from users perspective as well as in code by matching the terraform resource. I believe the current module also triggers a change whenever the latest master kubernetes version is changed, which should not be the case if the user has not set a min version, since it is optional in the terraform resource.

One problem is how to do this in a user friendly way. Can we release a new version? Or perhaps keep the existing vars and mark them deprecated?

**Comment by morgante** [comment]
Can you share the use case for deprecating zones/region? I prefer to be explicit and have people either choose a region or zone.

FYI in the upcoming 5.0.0 release we use `location` under the hood.

**Comment by umairidris** [comment]
Not any specific use case. I was first looking into the terraform google_container_cluster resource and saw they deprecated zone/region in favour of location which is simpler to use, so when I came to see this module I expected it to be the same interface.

**Comment by morgante** [comment]
Ah, the primary benefit of that refactor was specifically to make it simpler for use cases like this where we want to toggle between regional/zonal on the same resource.

For end users, I think the explicit region/zone definition is preferable. I'm going to close this for now, but please comment/reopen if anyone feels it's a major issue.

**Comment by kevensen** [comment]
@morgante Any chance we can reconsider this?

**Comment by morgante** [comment]
@kevensen Can you explain why you want to?

I remain of the opinion that specifying either `region` or `zone` explicitly is preferable to a catch-all `location` variable.

**Comment by morgante** [comment]
Correct.

if you're still seeing errors with v5.0.0, please do open an issue here.
