### ISSUE TITLE
Can't Add GPU Accelerator to Node Pool part of Regional Cluster

### ISSUE THREAD

**Issue by DanielWozniak** [terraform-google-modules/terraform-google-kubernetes-engine#263]
I currently have a regional cluster. For this cluster I would like to create a new node pool which contains a GPU accelerator. The problem with this is that in the google documentation it states:

For regional clusters that run GPUs, there is currently no region which has any GPU type in three zones. If you want to run GPUs in a regional cluster, you need to specify zones using the --node-locations flag

When I specify the location in the module like so
```
node_pools = [
    {
      name              = "node-pool-name"
      machine_type      = "n1-highmem-32"
      min_count         = 0
      max_count         = 1
      disk_size_gb      = 100
      disk_type         = "pd-standard"
      image_type        = "COS"
      accelerator_count = 2
      accelerator_type  = "nvidia-tesla-p100"
      auto_repair       = true
      auto_upgrade      = true
      preemptible       = false
      location          = "us-east1-b"
    },
  ]
```

For some reason the location is not getting picked up and in the plan we get:
```
      + location            = "us-east1"
      + max_pods_per_node   = (known after apply)
      + name                = "node-pool-name"
      + name_prefix         = (known after apply)
      + node_count          = (known after apply)
      + project             = "project-name"
      + region              = (known after apply)
      + version             = (known after apply)
      + zone                = (known after apply)
```
Even after running the apply it still doesn't get picked up and the following error gets thrown:
```
module.gke.google_container_node_pool.pools[1]: Creating...

Error: error creating NodePool: googleapi: Error 400: Accelerator type "nvidia-tesla-p100" does not exist in zone us-east1-d., badRequest
```
Would this be a bug in the module? Or is there something that I might be missing?

**Comment by DanielWozniak** [comment]
Went over the code and looks like the problem is that node pool doesn't accept a location. What ever location is specified in the cluster is used directly in the node pool. I've created a branch with some changes but while testing I can't seem to even get the cluster to create using the master branch. For some reason the cluster gets created with an error code 13 with the message INTERNAL(not very helpful), then proceeds to deleting the cluster.

**Comment by rileykarson** [comment]
FYI, node pool locations (that are different than the cluster locations) will be supported as part of the next provider release: https://github.com/GoogleCloudPlatform/magic-modules/pull/2320

**Comment by morgante** [comment]
Interesting, I didn't know we supported the ability to run different node pools in different locations. Looks like we should be able to add this with the next provider release, thanks for the heads up!

**Comment by DanielWozniak** [comment]
Ah, makes sense. For some reason when I read the description of location in the [docs](https://www.terraform.io/docs/providers/google/r/container_node_pool.html), I assumed you could specify something other than the clusters location. Even though it clearly says `in which the cluster resides`. 
Thanks, for clearing things up guys. Any idea when this might be part of this module?

**Comment by morgante** [comment]
@DanielWozniak Likely 2-3 weeks, depending on when the provider release lands.

**Comment by DanielWozniak** [comment]
Sounds good. In the meantime I suppose we can close this issue.

**Comment by DanielWozniak** [comment]
Hi All,

Since the feature has been released in version 2.16.0 could I request this be added to the module.
More specifically, being able to specify which zone is used in the node pool.

I've tried working on this myself however for some reason im not even able to create a simple cluster before even adding any changes I get a simple
```
Error: Error waiting for creating GKE cluster: Failed to create cluster

  on .terraform/modules/gke/cluster.tf line 22, in resource "google_container_cluster" "primary":
  22: resource "google_container_cluster" "primary" {
```

For some reason after 20 seconds of trying to create the cluster it just starts deleting itself, without giving any helpful message of why this is happening.

**Comment by morgante** [comment]
@DanielWozniak Is this no longer needed?

**Comment by morgante** [comment]
Ok I've marked it as an Enhancement. We'll put it in our backlog.

**Comment by morgante** [comment]
I've actually moved this into #290.
