### ISSUE TITLE
Add submodule to set up ACM

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#268]
We should add a new submodule which can be used to [install ACM](https://cloud.google.com/anthos-config-management/docs/how-to/installing) on a cluster.

This would involve:
1. Deploying the ACM operator
2. Automatically creating an [SSH keypair](https://www.terraform.io/docs/providers/tls/r/private_key.html) for the operator, uploading it to the cluster (as a secret)
3. Configuring the operator by creating a `ConfigManagement` resource in the cluster with these required values filled in:
- spec.clusterName
- spec.git.syncRepo
- spec.git.secrectType (hardcode to ssh to start)
- spec.git.policyDir

The module inputs should include:
- cluster ID/self-link
- sync repo
- policy directory
- sync branch (default master)

Outputs should include:
- SSH public key (to give the cluster access to git)

**Comment by kopachevsky** [comment]
Biggest obstacle implementing this feature is lack of CRD support in terraform provider https://github.com/terraform-providers/terraform-provider-kubernetes/issues/215
workaround would be to do stuff with local-exec to run
`kubectl apply -f config-management-operator.yaml`
