### ISSUE TITLE
Allow setting node locations on individual node pools

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#290]
As added [upstream](https://github.com/GoogleCloudPlatform/magic-modules/pull/2320), we need to update this module to support specifying `node_locations` on individual node pools (that potentially differ from the cluster's overall locations).

This will unblock #263.

**Comment by bharathkkb** [comment]
@morgante I can pick this up next if no one else has started

**Comment by morgante** [comment]
@bharathkkb Go ahead, thanks!

**Comment by bharathkkb** [comment]
@morgante quick question about this. I was trying to implement it like below but seems like I cant have arrays and strings within a single map.

```
node_pools = [
   {
      name               = "my-node-pool"
      node_locations     = ["us-west1-a", "us-west1-c"]
      .....
    }]
```

 For taints, tags etc which requires lists we have used a different variable. Should I use that approach here?
```
node_pools = [
    {
      name               = "my-node-pool"
      .....
    }]
  node_pools_locations={
      my-node-pool = ["us-west1-a", "us-west1-c"]
    }
```

**Comment by morgante** [comment]
I'd suggest we simply comma-separate the locations in a string, as the simplest approach.

**Comment by bharathkkb** [comment]
Yes that makes sense. Thanks

**Comment by aaron-lane** [comment]
By the by, I've opened #306 to address the limitation of `node_pools` using maps rather than objects.
