### ISSUE TITLE
Running on Terraform Cloud Fails due to gcloud/jq dependency

### ISSUE THREAD

**Issue by mhamrah** [terraform-google-modules/terraform-google-kubernetes-engine#293]
The wait-for-cluster.sh script uses gcloud and jq, which is not available in certain environments (specifically Terraform Cloud). Is there a way to remove it or make it optional? Would prefer to not have to download those binaries into a runtime environment, which we don't have control over.

**Comment by morgante** [comment]
Thankfully we're working on #278 which should fix this.
