### ISSUE TITLE
Creating multiple clusters across regions (way to loop?)

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-kubernetes-engine#299]
Is there a way to loop over the creation of modules where only `region/zone` and `name` differ? Or must you have 1 module block per cluster necessarily?

**Comment by morgante** [comment]
Unfortunately `count` and loops are not supported on modules (see https://github.com/hashicorp/terraform/issues/953), so you will need to have a separate block per cluster.

One potential approach you can take is to make a simple internal module which wraps this module and sets shared values while accepting region and name as inputs. Somewhat like our WIP [safer cluster module](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/272/files#diff-718be5f983927d6eb01b3224c2b9a4baR32).

**Comment by naseemkullah** [comment]
Thanks @morgante!
