### ISSUE TITLE
Make node_pool_labels, node_pool_tags, and node_pool_taints all optional

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#3]
Desired flow:
1. Defaults are available for the entire variable.
2. I can override the variable for one node pool without having to set a value for the whole variable.

**Comment by kiran002** [comment]
Could you elaborate a bit more? Because from the definition all of these variable seem to have default values (https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/variables.tf#L167-L170) and if i am not wrong, that should enough correct?

**Comment by morgante** [comment]
This might be out of date, but the specific desire is:
1. Defaults are available for the entire variable.
2. I can override the variable for one node pool without having to set a value for the whole variable.

**Comment by evkuzin** [comment]
@morgante @aaron-lane It could be move to done actually. 
Now you could just add block of tags/labels/taints with name of pool and it will not affect other pools
```
variable "node_pools_labels" {
  type        = map(map(string))
  description = "Map of maps containing node labels by node-pool name"

  default = {
    all               = {}
    default-node-pool = {}
  }
}
```

**Comment by evkuzin** [comment]
@morgante exactly you need to create object with name equal to node pool name and set it to {} 
```
labels = merge(
      {
        "cluster_name" = var.name
      },
      {
        "node_pool" = var.node_pools[count.index]["name"]
      },
      var.node_pools_labels["all"],
      var.node_pools_labels[var.node_pools[count.index]["name"]],
    )
```

**Comment by morgante** [comment]
So this has not been fixed.

As stated in the original issue, the ask is that I don't have to specify `node_pools_labels` at all if I don't want to set any custom labels.

**Comment by evkuzin** [comment]
Okay, I understand now.

**Comment by naseemkullah** [comment]
I find myself having to do this with clusters whose `default-pool` is deleted and custom pools `default` and `preemptible` are added.

```

  node_pools_metadata = {
    all         = {}
    default     = {}
    preemptible = {}
  }

  node_pools_labels = {
    all = {
      env = var.env
    }
    default     = {}
    preemptible = {}
  }

  node_pools_taints = {
    all         = []
    default     = []
    preemptible = []
  }

  node_pools_tags = {
    all         = []
    default     = []
    preemptible = []
  }
```

My understanding is that  #269 will allow me to not specify the empty values, is that correct?
