### ISSUE TITLE
required permissions list is inaccurate

### ISSUE THREAD

**Issue by ideasculptor** [terraform-google-modules/terraform-google-kubernetes-engine#302]
If using a host vpc project, you will see an error about missing `compute.subnetworks.get` on the host project.  There are a number of roles that provide that permission - roles/compute.networkUser, for example.

error message is as follows:

```
Error: Error waiting for creating GKE cluster: Google Compute Engine: Required 'compute.subnetworks.get' permission for 'projects/<host project id>/regions/us-central1/subnetworks/<subnetwork>'
```

**Comment by morgante** [comment]
We do mention that "If you are using a Shared VPC, the APIs must also be activated on the Shared VPC host project and your service account needs the proper permissions there."

But we should be more explicit about this.

Note that project factory handles granting the required permissions: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/main.tf#L435

**Comment by ideasculptor** [comment]
Ultimately, the problem was that I had used the network module in order to manually bind the service project to multiple host projects, and that module was explicitly breaking the service account permissions, rather than assigning the networkUser role correctly.

So I spent the afternoon figuring out what was wrong with that module which needs documentation provided that talks about how to compute the correct service account names and use it correctly in a gke context (the example does not), given the damage it does if you run it (it uses iam_binding instead of iam_member and obliterates anything that may have been set up correctly by project-factory). 

Once I understood how that module was misbehaving, I spent my evening updating the project-factory to break out the vpc sharing code into a utility module so that the utility module can be called for multiple host projects, but is called for a single host project when the project-factory module is used.  There's a PR about to be awaiting approval for that.

A recurring theme is that the examples are often way too simple.  All too often, they leave important details as incoming variables, with no documentation as to how those incoming variables should actually be populated.

An example or documentation that actually mentions the GKE specific service accounts that MUST be included in host_subnet_users in that module would have saved me another full day of development time.  Tests or examples that actually build a production-ready environment instead of throwaway examples would likely uncover most of the problems in the fabric modules that I keep encountering.

**Comment by eahrend** [comment]
@ideasculptor what did you have to do to resolve this? I tried modifying the service account I'm using to create the GKE cluster and I'm still getting that error. Do you have any code snippets I can use?

**Comment by bharathkkb** [comment]
Hi @eahrend 
We have a list [here](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc#summary_of_roles_granted_on_subnets). Additionally we also have [an example](https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/examples/gke_shared_vpc) within Project Factory that makes use of [shared_vpc_access submodule](https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/shared_vpc_access) to grant the necessary roles.

**Comment by ideasculptor** [comment]
I don't remember, offhand, but the codebase I was working on is open-source - https://github.com/ideasculptor/gcloud-templates/tree/master/gke and the repo which plugs all the pieces together is here: https://github.com/ideasculptor/gcloud-reference-arch.  I'll save you digging through it - it looks like the configuration repo wasn't setting any value for project_roles explicitly, which is the set of roles that gets added to service account created by the GKE module, but I hardcoded the defaults to be the following:
```
variable "project_roles" {
  type        = list(string)
  description = "Project-scope roles that should be added to the service account"
  default     = [
    "roles/cloudtrace.agent",
    "roles/monitoring.metricWriter",
    "roles/logging.logWriter"
  ]
}
```

So it seems I thought those to be a reasonable set of default roles to add.  I don't know if they were all necessary to get it to work or just one - and I haven't touched this codebase since last December, so things have likely moved on a bit - but it's a decent place to start for your experiments.

**Comment by eahrend** [comment]
@ideasculptor sounds good, I'll take a look.


@bharathkkb Yeah, I checked the project-factory, but I'm trying to create the host project and the service projects in one go, which is why I initially used the network module to manually attach the subnets/projects to the host project. I'm gonna take a stab at doing this and see if we can just leverage project factory to create/update a host vpc.
https://github.com/terraform-google-modules/terraform-google-project-factory/issues/422
