### ISSUE TITLE
initial_node_count and node_count both set when node pool autoscaling is disabled

### ISSUE THREAD

**Issue by thecodejunkie** [terraform-google-modules/terraform-google-kubernetes-engine#311]
Hi

I've noticed that if `autoscaling=false` is set on a node pool, then `initial_node_count` will be set to `1` (and not `0` as documented in #297) and so is `node_count`, which causes an error since both can't be set. What is the intended behavior here?

Thanks

**Comment by thecodejunkie** [comment]
Actually, even for a node pool with autoscaling it seems to be set to `initial_node_count  = 1` so it doesn't seem like it doesn't have a default value of `0` not being optional

**Comment by morgante** [comment]
That PR is not yet merged because it is incorrect, so I wouldn't rely on it for documentation.

As such, the best reference is still the actual code: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/cluster.tf#L140

From this, you can see that if autoscaling is disabled we will set both `initial_node_count` and `node_count` to the `min_count` provided.

Could you share the error message you see and your config?

**Comment by thecodejunkie** [comment]
@morgante I believe it's this error I am seeing

https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/vendor/github.com/terraform-providers/terraform-provider-google/google/resource_container_node_pool.go#L474

I will re-run my script to verify

**Comment by thecodejunkie** [comment]
Looking at the code, this line https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/cluster.tf#L146 will set `node_count` to `min_count` if `autoscaling` is `false`

**Comment by thecodejunkie** [comment]
Yep. just tried re-running and got this

> Error: Cannot set both initial_node_count and node_count on node pool default-pool

Looking at the plan I can see both being set

```
      + initial_node_count  = 1
      + instance_group_urls = (known after apply)
      + location            = "europe-west4"
      + max_pods_per_node   = (known after apply)
      + name                = "default-pool"
      + name_prefix         = (known after apply)
      + node_count          = 1
```

For my node pool

```
    {
      autoscaling        = false
      auto_upgrade       = false
      name               = local.default_pool_name
      machine_type       = var.default_node_pool.machine_type
      service_account    = (var.default_node_pool.service_account != "") ? var.default_node_pool.service_account : ""
      # initial_node_count = 0
    }
```

If I uncomment `initial_node_count = 0` then it works

**Comment by morgante** [comment]
Yup, looks like a bug!
