### ISSUE TITLE
add GKE metering (now in GA) for all module and submodule versions

### ISSUE THREAD

**Issue by gcamus59** [terraform-google-modules/terraform-google-kubernetes-engine#316]
GKE metering is not anymore a Beta feature, it's now in General Availability.
So, the feature should be available for use in every kind of modules.

It's already available in the beta' module versions. It seems that moving the code outside from the beta_cluster IF conditions (inside the autogen repository) will enable the feature for all module versions.

After beginning work on the modification in a pull request, I saw that the parameter is not yet available in the non beta google Terraform provider (see https://github.com/terraform-providers/terraform-provider-google/issues/4634)

**Comment by morgante** [comment]
Thanks, this should be easy to fix once https://github.com/terraform-providers/terraform-provider-google/issues/4634 is resolved.

**Comment by thomas-riccardi** [comment]
https://github.com/terraform-providers/terraform-provider-google/commit/a646d86669acdf34eedf8515521a3bf56d8b0c4b is now included in `google` 3.16.0.

Also, would it be possible to make `enable_network_egress_metering` configurable (which is set to true here whereas in the provider it defaults to false)? (And maybe `enable_resource_consumption_metering` too for completeness).

**Comment by gcamus59** [comment]
Thanks, I'll work on it this week and I will craft a pull request.
