### ISSUE TITLE
Document update variants

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#317]
In #256, we added support for node pools to be created before being destroyed in variants. We should provide documentation (in the respective READMEs) of what the update variants are useful for.

**Comment by morgante** [comment]
Potential language to include:

The benefit is that you always have some node pools active. We don't actually cordon/drain the traffic beyond what the GKE API itself will do, but we do make sure the new node pool is created before the old one is destroyed. The implications of this are that:
1. We append a random ID on the node pool names (since you can't have two simultaneously active node pools)
2. For a brief period, you'll have 2x as many resources/node pools
3. You will indeed need sufficient IP space (and compute capacity) to create both node pools

**Comment by ideasculptor** [comment]
Documentation of what will happen when changing node pool configurations in the non-update variants is also necessary, as I just discovered the hard way.
