### ISSUE TITLE
[GKE Hardening] Workload Identity vs Node Pool Scope

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-kubernetes-engine#319]
If we have Workload Identity, are there advantages in restricting node pool scopes?

**Comment by morgante** [comment]
In general, I consider scopes to be a mostly legacy concept. They're very broad/not granular and also can't easily be updated in the future.

Thus, I'd lead towards *not* restricting node pool scopes. Instead we should rely on Workload Identity + IAM.
