### ISSUE TITLE
LoadBalancerManualChange events - how to handle?

### ISSUE THREAD

**Issue by ideasculptor** [terraform-google-modules/terraform-google-kubernetes-engine#325]
If I enable the istio feature, and take a look at the istio-ingress and istio-ingressgateway both show events labeled as LoadBalancerManualChange type, which provide a gcloud command which will add the necessary firewall rule(s). 

I'm curious whether my service account is lacking a permission which would cause that to correctly happen without manual intervention, or do I need to set up an event handling pipeline which can trap those events and fire off those commands? Relying on a human to intervene manually seems sub-optimal. 

If an event handling pipeline seems an appropriate solution, is there an example of such a pipeline anywhere, perhaps in the yaml fabric modules?  If not, and I build one into one of the examples here, will that be likely to get merged or should I just worry about adding it to my own codebase?  I have never set up a trap for GKE events, or for running gcloud commands via a cloud-function or the like, so any pointers for similar functionality would be appreciated, if that is the correct solution to this problem, anyway.

**Comment by morgante** [comment]
This sounds like a permission issue. It sounds like the GKE Service Account might not have the right permission on your network to manage firewall rules: https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc#summary_of_roles_granted_on_subnets

**Comment by aaron-lane** [comment]
@ideasculptor does @morgante's suggestion solve your issue?

**Comment by ideasculptor** [comment]
I'm not entirely sure.  I got pulled into other things for the last few weeks and haven't actually had a chance to verify.  I did find a potential candidate role in the docs, which makes me think he's correct, but I haven't had opportunity to verify it.  But I actually have some time to play around with it this afternoon, so I'll give it a shot and get back to you.  

This has been open for a while, though.  You can close it.  If it doesn't proved solved, I'll let you know.
