### ISSUE TITLE
Add var to allow a pre-generated SSH key to be passed to the ACM module

### ISSUE THREAD

**Issue by thecodejunkie** [terraform-google-modules/terraform-google-kubernetes-engine#329]
The current implementation of the ACM module only allows you to generate a new SSH key or not to create the git-secret at all. Ideally it should be possible to pass in an `ssh_key` variable as well, so you have the ability to pass in a pre-generated key. 

Something like this would be nice functionality

* Was `ssh_key` provided?
   * Yes - > Use it
   * No -> Is `create_ssh_key` set to `true`?
      * Yes -> Generate one
      * No -> Do nothing

**Comment by morgante** [comment]
Would you want this to be the actual private key (contents) or a file path? I'm thinking contents would be more flexible (since you can always grab them from a file using `file()` in your config.

**Comment by thecodejunkie** [comment]
Oh sorry, forgot to mention that. Yes, I think the ideal would be to pass in the content of the file since it provides more flexibility in where the config originates from

**Comment by thecodejunkie** [comment]
@morgante what're your thoughts about completely replacing the `create_ssh_key` variable (and corresponding usage of `tls_private_key`) with a `ssh_key` variable? I feel that by introducing the ability to pass in a key, it should not be the responsibility for the ACM module to generate one for you. Either you grab your key from whatever location you wish or you make use of `tls_private_key` yourself and pass the output as the value to the `ssh_key` parameter?

I'm happy to take a stab at such a change if you want me to?

**Comment by morgante** [comment]
I'd prefer to not remove the `create_ssh_key` functionality. We can provide `ssh_key` as an additional option, but for testing/bootstrapping I think the in-module creation is helpful.
