### ISSUE TITLE
enabling istio requires extra roles on service account

### ISSUE THREAD

**Issue by ideasculptor** [terraform-google-modules/terraform-google-kubernetes-engine#332]
It should be trivial to just add a call like the following to the code where the GKE module is called:

```
module "projects-iam" {
  source      = "terraform-google-modules/iam/google//modules/projects_iam"

  project     = local.project_id
  mode        = "additive"
  bindings    = zipmap(
    var.project_roles,
    [ for s in var.project_roles :
      ["serviceAccount:${module.gke.service_account}"]
    ]
  )
}
```

But because the projects_iam module no longer works with dynamically computed values, even if var.project_roles is declared statically, it blows up because of the reference to module.gke.service_account.

So it isn't really possible to add the appropriate authorizations for istio in the code which launches the cluster.  The cluster module must do it, conditionally.

My project_roles variable is defined like this:

```
variable "project_roles" {
  type        = list(string)
  description = "Project-scope roles that should be added to the service account"
  default     = [
    "roles/cloudtrace.agent",
    "roles/monitoring.metricWriter",
    "roles/logging.logWriter"
  ]
}
```

I assume that at least one or two of those should already be getting set, regardless of ISTIO being present.  I suppose it is also possible that my use of logging.googleapis.com/kubernetes and monitoring.googleapis.com/kubernetes instead of the older, deprecated services for logging and monitoring could be the cause of mismatched permissions, but the module should still be setting up the correct permissions.  I got all kinds of errors in the logs due to missing authorizations until I added those 3.  I didn't add them separately to see which one(s) cleared it up.

It would be good if fabric modules could be used to assign authorizations to service accounts declared by fabric modules, but that is broken due to the removal of *_num variables and replacing `count` with `for_each`

**Comment by ideasculptor** [comment]
<img width="826" alt="Screen Shot 2019-11-19 at 12 15 54 AM" src="https://user-images.githubusercontent.com/484573/69129279-e4356a00-0a62-11ea-824a-f67f5acc2834.png">

**Comment by ideasculptor** [comment]
Fair enough.  I'll remove my extra roles and throw up a new cluster from scratch, and report back here with the iam assignments in the plan that gets generated.  I don't think this one is user error, since the service account is being created by the module.  I have plans this afternoon, so I'm not sure I'll get to it today. It'll probably be another late-night response tonight if it happens today at all.

To be honest, I think the fact that the cluster is unable to create firewall rules isn't going to be user error, either, since I eventually simplified my code down to be pretty much identical to the example.  The failures don't show up as errors anywhere except in the event log for the cluster, so you may just be failing to detect that condition in your tests.  Everything looks like it should work, but the network prevents access, so unless your tests actually attempt to send traffic through the LB, I don't think you'd detect it.  That page you linked me to does mention a role that I don't think is assigned, based on my memory of how those 2 service accounts get set up, but I think it doesn't get assigned by the fabric modules by default.  I'll let you know once I've checked it out and fixed it locally. 

Probably, you'll just get a PR from me fixing them both if they weren't mistakes on my part.

**Comment by laithrafids** [comment]
guys , any news on this ? or fork it ?

**Comment by morgante** [comment]
@laithrafids What's the issue you're seeing?

**Comment by laithrafids** [comment]
no issue , i will delete my comment thanks

**Comment by morgante** [comment]
Ok good. Just to confirm, module should work fine with Istio. If anyone sees otherwise, please do comment and we will reopen.
