### ISSUE TITLE
Upgrade to provider version 3.0.0

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#338]
We will have to update the configuration to support 3.0.0 provider versions, based on this upgrade doc: https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html

**Comment by bharathkkb** [comment]
@morgante I can pick this up next

**Comment by morgante** [comment]
Thanks @bharathkkb!

**Comment by raj-saxena** [comment]
@bharathkkb what is the ETA on this? I am facing troubles trying to use this module with other modules that use versions `3.0`.
