### ISSUE TITLE
Enable easier shared VPC usage

### ISSUE THREAD

**Issue by davidrymkiewicz** [terraform-google-modules/terraform-google-kubernetes-engine#34]
Ran into this issue with creating a GKE cluster.

`1 error(s) occurred:
* module.prod-gke-cluster.google_container_cluster.primary: 1 error(s) occurred:
* google_container_cluster.primary: googleapi: Error 404: Not found: GAIA email lookup., notFound`

TF Debug output in attached file
[debug.log](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/files/2601389/debug.log)

```
module "dev-gke-cluster" {
  source = "github.com/terraform-google-modules/terraform-google-kubernetes-engine"
  name = "gke-dev"
  kubernetes_version = "latest"
  project_id = "${google_project.dev-project.project_id}"
  region = "${var.region}"
  network = "${google_compute_network.dev-network.name}"
  subnetwork = "${google_compute_subnetwork.dev-app-subnet.name}"
  network_project_id = "${google_compute_shared_vpc_host_project.shared_vpc.project}"
  ip_range_pods = "${google_compute_subnetwork.dev-app-subnet.secondary_ip_range.0.range_name}"
  ip_range_services = "${google_compute_subnetwork.dev-app-subnet.secondary_ip_range.1.range_name}"
  regional = true
  horizontal_pod_autoscaling = true
  network_policy = true 
  master_authorized_networks_config = [{
    cidr_blocks = [{ cidr_block = "0.0.0.0/0" display_name = "all" }]  
  }]
  node_pools = [
    {
      name = "default-node-pool"
      machine_type    = "n1-standard-2"
      min_count = 1
      max_count = 3
      disk_size_gb = 100
      disk_type = "pd-standard"
      image_type = "COS"
      auto_repair = true
      auto_upgrade = true
    },
  ]
}

**Comment by davidrymkiewicz** [comment]
I figured out the root cause, and its caused by a disabled kubernetes API. Additionally, I ran into an issue with IAM permissions within a shared VPC architecture. Since the module already supports shared VPC architecture, would it be possible to include the IAM permissions and the ` google_project_service` resource within the module itself... sample code below:

```
resource "google_project_service" "gke_project_service" {
    project = "${google_project.gke_project.project_id}"
    service = "container.googleapis.com"
    depends_on = [
        "google_project.gke_project"
    ]
}

resource "google_project_service" "network_project_service" {
    project = "${google_project.network_project.project_id}"
    service = "container.googleapis.com"
    depends_on = [
        "google_project.network_project"
    ]
}

resource "google_project_iam_member" "host_service_agent" { 
 	project = "${google_project.network_project.project_id}"
 	role    = "roles/container.hostServiceAgentUser" 
 	member  = "serviceAccount:service-${google_project.gke_project.number}@container-engine-robot.iam.gserviceaccount.com" 
    depends_on = [ 
		"google_project.gke_project",
		"google_project.network_project"
	]
}

resource "google_project_iam_member" "compute_network_user_container" { 
 	project = "${google_project.network_project.project_id}"
 	role    = "roles/compute.networkUser" 
 	member  = "serviceAccount:service-${google_project.gke_project.number}@container-engine-robot.iam.gserviceaccount.com"
    depends_on = [ 
		"google_project.gke_project",
		"google_project.network_project"
	]
}

resource "google_project_iam_member" "compute_network_user_cloudservices" { 
 	project = "${google_project.network_project.project_id}"
 	role    = "roles/compute.networkUser" 
 	member  = "serviceAccount:${google_project.gke_project.number}@cloudservices.gserviceaccount.com"
    depends_on = [ 
		"google_project.gke_project",
		"google_project.network_project"
	]
}```

**Comment by morgante** [comment]
Hey @davidrymkiewicz, please take a look at #35 and see if it makes sense as a response.

**Comment by morgante** [comment]
Re-opening so we can later automate this more, as per this comment: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/35#issuecomment-443739473

**Comment by morgante** [comment]
Closing this out would require, as mentioned above:
- Adding an (optional) invocation of the [project services module](https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/project_services/examples/project_services) to activate needed APIs
- Adding a (optional) submodule for enabling GKE shared VPC which grants the necessary roles to the the GKE service accounts

**Comment by aaron-lane** [comment]
@cray0000 please pass this along to the new team member.

**Comment by grugnog** [comment]
Noting here that while there is now https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/shared_vpc_access this only works on the default service account.
Hence it would still be helpful for the kubernetes module to create shared VPC access for the service account this module creates when create_service_account is enabled (which it is by default).

**Comment by erichaase** [comment]
@morgante I'm also getting the `Error: googleapi: Error 404: Not found: GAIA email lookup., notFound` error when creating a GKE cluster using this Terraform module. I've verified that I've satisfied all of the bullets in the `Requirements` in the `README.md`. Any pointers on ways I can troubleshoot this?

**Comment by morgante** [comment]
Can you share your Terraform configuration?

**Comment by rch2020** [comment]
I ran into the issue when I used the below:-

  #dynamic "authenticator_groups_config" {
  #  for_each = [
  #    for x in [var.gsuite_domain_name] : x if var.gsuite_domain_name != null
  #  ]
  #
  #  content {
  #    security_group = "gke-security-groups@${authenticator_groups_config.value}"
  #  }
  #}

When the below block was removed, the above error did not occur.
  "authenticatorGroupsConfig": {
   "enabled": true,
   "securityGroup": **"gke-security-groups@null"**
  }

**Comment by hayorov** [comment]
@rch2020 , @morgante  I've created a new issue with an appropriate summary and relevant description https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/793

I bet that some procedure update here https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#groups-setup-gsuite cause the problem with "Not found: GAIA email lookup.",
