### ISSUE TITLE
[GKE Hardening] Shielded GKE nodes

### ISSUE THREAD

**Issue by thecodejunkie** [terraform-google-modules/terraform-google-kubernetes-engine#343]
Shielded GKE nodes should be supported in the beta providers https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#shielded_nodes

**Comment by bharathkkb** [comment]
I believe shielded nodes were added in beta modules with #300

**Comment by thecodejunkie** [comment]
@morgante this does not appear to be available in the version (5.1.1) that's published in the Terraform registry. Any plans on putting out a new version soon? Thanks!
