### ISSUE TITLE
Remove Default Node Pool: Error - Node created without a route

### ISSUE THREAD

**Issue by medarz** [terraform-google-modules/terraform-google-kubernetes-engine#345]
When forcing to delete the default node pool, via:

`remove_default_node_pool          = true`

and the new pool is being created,  I got an error saying:

**Node created without a route**

This happens just to one of the nodes in the pool. The status in the node is *NetworkUnavailable*
I also tried the same configuration withouth removing the pool, and the cluster is created without issues.

**Comment by omazin** [comment]
Hi @medarz, can you post the exact configuration you used?

**Comment by omazin** [comment]
Tested creating a `simple_regional` and a `simple_regional_private` clusters with `remove_default_node_pool` set to `true`. Couldn't reproduce the error. Status in all nodes is 'Ready'.
Looking at the issue description is sounds like it could be some asynchronous issues when a node is being created before all routes are created.

**Comment by bharathkkb** [comment]
Closing this out as we could not repro. @medarz feel free to reopen for further investigation
