### ISSUE TITLE
ip_allocation_policy conflicts with cluster_ipv4_cidr

### ISSUE THREAD

**Issue by andrewnazarov** [terraform-google-modules/terraform-google-kubernetes-engine#349]
I'm on version 5.1.1 of the module.
Planning the configuration taken with some little changes from the usage example raising the following errors:

```
Error: "ip_allocation_policy": conflicts with cluster_ipv4_cidr

  on .terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-ab02f24/cluster.tf line 22, in resource "google_container_cluster" "primary":
  22: resource "google_container_cluster" "primary" {



Error: "cluster_ipv4_cidr": conflicts with ip_allocation_policy

  on .terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-ab02f24/cluster.tf line 22, in resource "google_container_cluster" "primary":
  22: resource "google_container_cluster" "primary" {
```

**Comment by andrewnazarov** [comment]
Ok, it was caused by the wrong version of the google provider. I didn't specify the version in my provider block, so 3.0.0-beta.1 was used instead.

**Comment by Slutzky** [comment]
I'm still getting this error 

`Error: "ip_allocation_policy": conflicts with cluster_ipv4_cidr

  on container_cluster.tf line 1, in resource "google_container_cluster" "tfer--test":
   1: resource "google_container_cluster" "tfer--test" {

Error: "cluster_ipv4_cidr": conflicts with ip_allocation_policy

  on container_cluster.tf line 1, in resource "google_container_cluster" "tfer--test":
   1: resource "google_container_cluster" "tfer--test" {
`

And I'm using the following `version = "~>v3.4.0"` in provider.tf

**Comment by morgante** [comment]
Please share your Terraform config, `terraform version`, and plan + debug output.

**Comment by Slutzky** [comment]
sure, 

```Terraform version v0.12.18```


**Terraform plan :**

```(⎈ |gke_dantest1_europe-west4-a_test:nginx-example)➜  europe-west4 terraform plan

Warning: Interpolation-only expressions are deprecated

  on container_node_pool.tf line 2, in resource "google_container_node_pool" "tfer--infrastructure_static":
   2:   cluster            = "${google_container_cluster.tfer--infrastructure.name}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Error: "cluster_ipv4_cidr": conflicts with ip_allocation_policy

  on container_cluster.tf line 1, in resource "google_container_cluster" "tfer--infrastructure":
   1: resource "google_container_cluster" "tfer--infrastructure" {



Error: "ip_allocation_policy": conflicts with cluster_ipv4_cidr

  on container_cluster.tf line 1, in resource "google_container_cluster" "tfer--infrastructure":
   1: resource "google_container_cluster" "tfer--infrastructure" {
```

container_cluster.tf 

```
resource "google_container_cluster" "tfer--infrastructure" {
  addons_config {
    horizontal_pod_autoscaling {
      disabled = "false"
    }

    http_load_balancing {
      disabled = "false"
    }

    network_policy_config {
      disabled = "false"
    }
  }

  cluster_autoscaling {
    enabled = "false"
  }

  cluster_ipv4_cidr         = "10.32.0.0/14"
  default_max_pods_per_node = "110"
  enable_kubernetes_alpha   = "false"
  enable_legacy_abac        = "false"
  initial_node_count        = "0"

 ip_allocation_policy {
    cluster_ipv4_cidr_block  = "10.32.0.0/14"
    services_ipv4_cidr_block = "10.0.0.0/20"
    use_ip_aliases           = "false"
  }

  location        = "europe-west4"
  logging_service = "logging.googleapis.com/kubernetes"

  master_auth {
    client_certificate_config {
      issue_client_certificate = "true"
    }
  }

  monitoring_service = "monitoring.googleapis.com/kubernetes"
  name               = "infrastructure"
  network            = "projects/sre-infra/global/networks/default"

  network_policy {
    enabled  = "true"
    provider = "CALICO"
  }

  node_locations = ["europe-west4-a", "europe-west4-b", "europe-west4-c"]
  node_version   = "1.16.0-gke.20"
  project        = "sre-infra"
  subnetwork     = "projects/sre-infra/regions/europe-west4/subnetworks/default"

  vertical_pod_autoscaling {
    enabled = "true"
  }
} ```

**Comment by morgante** [comment]
Your Terraform config is not using this module, so it's not an issue with this module.

You should file an issue on the provider.

**Comment by Slutzky** [comment]
sorry, I didn't mention it before, I imported the *.tf file using the following command : 

```
terraformer import google --resources=gke --connect=true --regions=europe-west4-b --projects=test 
``` 
After import , I just run 

```
terraform plan
```
and then I get the error that I showed above. 

But thanks for the prompt response! I will contact the provider for this issue.

**Comment by josephlim75** [comment]
According to terraform documentation at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster,  you cannot define both `cluster_ipv4_cidr` and `ip_allocation_policy` at the same time.  You must choose either `VPC_NATIVES` or `ROUTES` networking mode.

`
cluster_ipv4_cidr - (Optional) The IP address range of the Kubernetes pods in this cluster in CIDR notation (e.g. 10.96.0.0/14). Leave blank to have one automatically chosen or specify a /14 block in 10.0.0.0/8. This field will only work for routes-based clusters, where ip_allocation_policy is not defined.
`

**Comment by tadeasbronis** [comment]
Can You please reopen the issue. This is still a problem

**Comment by vehbi-restelica** [comment]
Since both: the **cluster_ipv4_cidr** argument and **ip_allocation_policy** block are optional in terraform's google_container_cluster resource, you can just comment/delete the **cluster_ipv4_cidr** and leave the ipv4_cidr defined only in **ip_allocation_policy**. 

This will fix the issue.
