### ISSUE TITLE
Release frequency

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-kubernetes-engine#357]
Hi, is there a rule on how often this module gets released?
It would be nice to have more frequent releases.

**Comment by aaron-lane** [comment]
Hi @naseemkullah! There is currently no schedule in place for module releases as our modules are maintained on a best-effort basis. We do try to release from master as frequently as possible but it doesn't always work out. That being said, we are close to releasing 6.0.0!

**Comment by naseemkullah** [comment]
Thanks for letting me know, looking forward to 6.0.0!
