### ISSUE TITLE
Remove/update quoted type constraints for tf 0.12.14+ support

### ISSUE THREAD

**Issue by ivankorn** [terraform-google-modules/terraform-google-kubernetes-engine#358]
Quoted type constraints are [deprecated since 0.12.14](https://github.com/hashicorp/terraform/blob/v0.12.16/CHANGELOG.md#01214-november-13-2019): 
In a variable block, a type constraint "map" should be written as map(string), "list" as list(string), and "string" as just string.

Can you please update the code base in order to get rid of the warning message below? 

```
Warning: Quoted type constraints are deprecated

  on .terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-ab02f24/variables.tf line 209, in variable "upstream_nameservers":
 209:   type        = "list"

Terraform 0.11 and earlier required type constraints to be given in quotes,
but that form is now deprecated and will be removed in a future version of
Terraform. To silence this warning, remove the quotes around "list" and write
list(string) instead to explicitly indicate that the list elements are
strings.
```

**Comment by aaron-lane** [comment]
Thanks @ivankorn. Let's update all instances of untyped variables and variables with deprecated types to conform to Terraform 0.12 standards.
