### ISSUE TITLE
Constrain only the minimum allowed version

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-kubernetes-engine#359]
Hi,

I use a thin wrapper around this module as follows:

In `main.tf` I have defined the google-beta provider pinned to `v2.20.0` as well as:
```
module gke_us_east {
  source       = "../../modules/zonal-cluster"
[...]
}
```
Then my  zonal-cluster module(which is a wrapper around this repo)'s `maint.tf`:

```
module "gke" {
  source                  = "terraform-google-modules/kubernetes-engine/google//modules/beta-public-cluster"
  version                 = "6.0.0"
[...]
```

I am currently faced with the following issue:
```
No provider "google-beta" plugins meet the constraint "v2.20.0,~> 2.18.0".
```
Which was introduced by the new constraint within this module for  `google-beta provider ~> 2.18.0`, which seems like the right thing to do, but I am unsure how to workaround my setup's issue. 

Taken from output of `terraform providers`:
```
└── module.gke_us_east
    ├── provider.google
    ├── provider.kubernetes
    └── module.gke
        ├── provider.google (inherited)
        ├── provider.google-beta ~> 2.18.0
        ├── provider.kubernetes
        ├── provider.null
        └── provider.random
```

**Comment by morgante** [comment]
Sorry for the issue!

It looks like we're [pinning](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/autogen/versions.tf.tmpl#L22) to `~> 2.18.0` which is too pessimistic. We should pin to `~> 2.18` instead.

**Comment by naseemkullah** [comment]
Ah I see! Just read up this terraform documentation on [provider versions](https://www.terraform.io/docs/configuration/terraform.html#specifying-a-required-terraform-version) and indeed:
> Re-usable modules should constrain only the minimum allowed version, such as >= 0.12.0.

**Comment by naseemkullah** [comment]
`~> 2.18` would be anything above `2.18.0` but anything less than `3.0.0` is that right?

Would it be better to ping to `>=2.18.0` ? `3.0.0` is right around the corner after all

**Comment by morgante** [comment]
We don't support 3.0.0 yet, but once we do we can definitely update it for that.
