### ISSUE TITLE
Support for preemptible nodes

### ISSUE THREAD

**Issue by lantier** [terraform-google-modules/terraform-google-kubernetes-engine#36]
Is it in the roadmap for support?
I think this can solve without minor issues: 
```
node_config {
    preemptible    = "${lookup(var.node_pools[count.index], "preemptible", false)}"
}

**Comment by morgante** [comment]
Yeah, we can definitely add this. PR's welcome as well!

**Comment by czka** [comment]
Code changes should not be accepted without respective doc updates. Only accidentally I have learned that preemptible nodes are already supported in this modules. I have almost wasted my time trying to add an already existing feature. Now I'm wasting it writing this comment.

**Comment by morgante** [comment]
@czka Point well taken. As an immediate measure I added it to the usage example (f05796430a3307fa13eaa2d68ca65e43de8bc357). Longer term, we need to improve documentation of the node_pools variable (#45).
