### ISSUE TITLE
Support for disabling basic auth & client certificate

### ISSUE THREAD

**Issue by miles-** [terraform-google-modules/terraform-google-kubernetes-engine#37]
There isn't currently a way to disable basic authentication and the creation of a client certificate at cluster creation time. It looks like both of these can be accomplished by setting a `master_auth` config.

https://www.terraform.io/docs/providers/google/r/container_cluster.html#master_auth

**Comment by morgante** [comment]
Yes, I think it's a good idea to add this. Do you think we would want it as a default?

**Comment by miles-** [comment]
Yes I think it makes sense to disable both by default. When creating a cluster via the GCP console, both options have recommendations to disable them. Also, they will be disabled by default in 1.12.

![2018-12-04-17 16 49](https://user-images.githubusercontent.com/428901/49476629-89bae380-f7e8-11e8-88d0-c4f0336877fa.png)

**Comment by morgante** [comment]
1. For basic auth, I think we should go with `enable_basic_auth = false` as the default going forward. This *will* generate a diff for existing module users, but that is acceptable as they can choose to either explicitly encode the desire to enable basic auth or require the new version.

2. Client certificates sound slightly more destructive and we use them internally, so let's *start* by adding an `enable_client_certificate` variable with a default of `true`.

Also, as per the docs it *does* seem to be possible to enable cluster cert but disable basic auth so we need to support that scenario: https://www.terraform.io/docs/providers/google/r/container_cluster.html#client_certificate_config

**Comment by coryodaniel** [comment]
Yep, I got that support in my first pass! Thanks for the input, sounds like a good approach to me.

**Comment by aaron-lane** [comment]
Fixed by #40.
