### ISSUE TITLE
Error: var.zones is empty list of string

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-kubernetes-engine#370]
Although I'm able to create clusters just fine, when I try to import a non related resource into a non related module within the same root directory, I get:

```
Error: Invalid index

  on .terraform/modules/gke_us_central.gke/terraform-google-modules-terraform-google-kubernetes-engine-3212e3b/modules/beta-public-cluster/main.tf line 37, in locals:
  37:   region   = var.region == null ? join("-", slice(split("-", var.zones[0]), 0, 2)) : var.region
    |----------------
    | var.zones is empty list of string

The given key does not identify an element in this collection value.
```

As you may notice, I am using a thin wrapper around the beta-public-cluster module, I pass in the value of `zones` in this wrapper, which is a 1 element array of zones.

Any idea what may be going on?

**Comment by naseemkullah** [comment]
I was able to work around this, by commenting out my various thin-wrapper-around-this-module 
 module instantiations, import the non-related resource, then uncomment the modules.

If there is any further insight as to what might be happening please let me know, if not feel free to close this issue.

**Comment by morgante** [comment]
I'm not really sure what could be causing this, I suspect it might be related to the pass-through.

Closing for now, but if anyone else encounters it we can reopen and investigate.

**Comment by omazin** [comment]
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/294

**Comment by jamesthimont** [comment]
@morgante  in `safer-cluster-update-variant/main.tf` the zones entry below is missing
```
module "gke" {
  source             = "../beta-private-cluster-update-variant/"
  project_id         = var.project_id
  name               = var.name
  regional           = var.regional
  region             = var.region
  ***zones              = var.zones***
  network            = var.network
```
