### ISSUE TITLE
Add safer-cluster-update-variant

### ISSUE THREAD

**Issue by skinlayers** [terraform-google-modules/terraform-google-kubernetes-engine#372]
I'll take a crack at adding this to ./autogen.

**Comment by morgante** [comment]
Thanks!

**Comment by skinlayers** [comment]
@morgante It looks like `./modules/safer-cluster` is not part of the `./autogen` system, so I wanted to solicit some input before I moved forward. Because `safer-cluster` wraps `beta-private-cluster` and significantly differs from the other submodules, integrating `safer-cluster` would require significant changes to the templates and probably `./helpers/generate_modules` as well.  Would it be better to create separate templates for `safer-cluster`? I could either put them in a subdirectory (e.g. `./autogen/safer-cluster/`), and make a few changes to `./helpers/generate_modules/generate_modules.py`, OR add a prefix to the `safer-cluster` templates e.g. `./autogen/safer-cluster-cluster.tf.tmpl`.

Thoughts? Comments? Is there a better approach that I'm missing?

**Comment by morgante** [comment]
Yes, this will require a bit of rework to the autogen system but it shouldn't be *too* bad.

Here's what I would suggest:
1. Move the existing autogen to `./autogen/main`
2. Add a `./autogen/safer-cluster` folder with the safer cluster config
3. Update the [helper script(https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/helpers/generate_modules/generate_modules.py) to generate both.

**Comment by skinlayers** [comment]
Here's my initial attempt: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/378

**Comment by skinlayers** [comment]
@morgante The work around allowed me to create the infra, but I ran into the same problem when attempting to then run `make docker_test_integration `. I ended up making a few more changes to accommodate my immediate needs. I'll attempt to interactively step through the tests as described in the contribution guide.

**Comment by skinlayers** [comment]
Branch was merged. `safer-cluster-update-variant` should be available in the next release.
