### ISSUE TITLE
question: grant_registry_access to another project's registry out of the box

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-kubernetes-engine#379]
What is the recommended approach to give fresh clusters gcr access to a project other than the one they are in (without using default compute sa for clusters)? 

I understand that one needs to bind the newly created tf-managed gke service account to the objectViewer role of the image repo project's cloudbuild bucket. But that seems like a manual step right now.

I am currently in the process of separating my environment(dev,qa,stage,prod) by project (good or bad idea?), and am thinking of using a shared image repo among them (good or bad idea?).

**Comment by morgante** [comment]
Yes, using a shared image project is a comment pattern.

You can actually do this using the `registry_project_id` variable. This will automatically grant the service account the required permissions on that shared project.

**Comment by naseemkullah** [comment]
Great, thank you!
