### ISSUE TITLE
GKE tests failing due to legacy logging and monitoring defaults in autogen

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-kubernetes-engine#384]
GKE tests failing to converge due to defaults that point to the old monitoring/logging api.
I was able to fix it by defaulting to logging/monitoring.googleapis.com/kubernetes
`Error 400: Legacy monitoring is not supported in clusters running Kubernetes 1.15 or above`

**Comment by jasonbisson** [comment]
Updating to logging/monitoring.googleapis.com/kubernetes worked for me too.
