### ISSUE TITLE
Update examples to include example of setting service account

### ISSUE THREAD

**Issue by coryodaniel** [terraform-google-modules/terraform-google-kubernetes-engine#39]
I was setting up a cluster with this module using the examples as a reference and kept running into issues about the service account not existing (I set up the project with the project factory).

As noted in the [README](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blame/master/README.md#L42)<sup>1</sup> the node pools should specify the service account. I got tripped up on this since it wasn't in the examples. 

It could be helpful to add a note in the examples or in the examples' README.

Looks like issue #23 would also resolve this.

*Footnotes:*

1. pardon the blame view, needed to link to the line in the readme

**Comment by morgante** [comment]
I think we should address this via #2 and simply always require that a Service Account be either created or passed in.

Relying on the default service account is brittle and unstable.

**Comment by aaron-lane** [comment]
Fixed by #80.
