### ISSUE TITLE
Could not find default credentials

### ISSUE THREAD

**Issue by minaf1** [terraform-google-modules/terraform-google-kubernetes-engine#390]
Hello.
I tried running the example deployService by changing the variables.tf file with the relevant variables from the root readme.  I am using terraform v0.12.   I keep getting this error: 
Error: google: could not find default credentials. 

My credentials is a json service account from gcp and I put it in deployService directory.  I tried referring to the credentials like the following in variables.tf :
`  variable "compute_engine_service_account" {
      default = "service-account.json"
  }`

**Comment by morgante** [comment]
Hi there! In order to use Terraform with GCP, you need to provide credentials. The different mechanisms for doing so are explained here: https://www.terraform.io/docs/providers/google/guides/provider_reference.html#credentials-1

You'll want to set an environment variable pointing to your key file.

**Comment by minaf1** [comment]
I just tried your suggestion. It finally passes the terraform plan command.
