### ISSUE TITLE
Generate kubeconfig from output

### ISSUE THREAD

**Issue by yashbhutwala** [terraform-google-modules/terraform-google-kubernetes-engine#393]

**Comment by morgante** [comment]
Can you clarify your ask here?

**Comment by yashbhutwala** [comment]
Right now, afaik, there is no way to take the output of this module and turn it into a valid `~/.kube/config` file.  Correct me if I'm wrong :)

**Comment by morgante** [comment]
The outputs include the `ca_certificate` and `endpoint`, which should be sufficient to construct a kubeconfig file: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine#outputs

**Comment by yashbhutwala** [comment]
Is that enough to generate a kubeconfig file, what about `client-certificate-data` and `client-key-data`
