### ISSUE TITLE
How to Add GPU to google_container_node_pool resource

### ISSUE THREAD

**Issue by nathanwilk7** [terraform-google-modules/terraform-google-kubernetes-engine#396]
I would like to add GPU's to a `google_container_node_pool` resource, but I was unable to find documentation for how to do so (maybe just looking in the wrong place or misunderstanding something). I'm filing this issue to ask for help understanding how to specify the GPU request. Specifically, I'd like to create a new `google_container_node_pool` with 1 GPU per node for an existing GKE cluster that already has a number of other CPU only `google_container_node_pool`s.

I did see some documentation for adding GPUs via the `google_container_cluster` resource as `guest_accelerators`. I also saw a [GitHub issue](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/263) where gpu's are added to `node_pools`. We could probably figure out how to refactor our current setup to work with one of those methods, but it wasn't obvious to me how to do use them with our current setup.

Our current setup looks more or less like the below:
```
resource "google_container_cluster" "my_cluster" {
  ...
}

resource "google_container_node_pool" "my_cpu_node_pool" {
  cluster  = google_container_cluster.my_cluster.name
  ...
}

```

I tried the two resource definitions below as guesses, but the errors I got when I ran `terraform plan` suggest I guessed wrong:
```
resource "google_container_node_pool" "my_gpu_node_pool" {
  cluster  = google_container_cluster.my_cluster.name
  ...
  guest_accelerator {
    type = "nvidia-tesla-k80"
    count = 1
  }
}
```
AND
```
resource "google_container_node_pool" "my_gpu_node_pool" {
  cluster  = google_container_cluster.my_cluster.name
  ...
  accelerator_type = "nvidia-tesla-k80"
  accelerator_count = 1
}
```
Please don't hesitate to reach out, I'm happy to answer questions and provide any useful details. Thank you in advance for your help and time!

**Comment by morgante** [comment]
If you are directly creating resources yourself and not using this module, then please file issues on the provider not this module.

**Comment by YeshuGarg1** [comment]
@morgante Were you able to figure this out? I am also stuck at the same place
