### ISSUE TITLE
Workload Identity config per node pool

### ISSUE THREAD

**Issue by tuananhnguyen-ct** [terraform-google-modules/terraform-google-kubernetes-engine#398]
I'm using beta-private-cluster and unable to disable workload identity per node pool, is there any related documentation or example on how to configure that? I can only use `node_metadata              = "GKE_METADATA_SERVER"` at cluster level to configure/enable for all node pools at once.

**Comment by Dev25** [comment]
Existing issue https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/265

Since the for_each PR still hasn't been merged yet, i'll create another PR just with those the changes.
