### ISSUE TITLE
gcloud executable requirement, removal of jq

### ISSUE THREAD

**Issue by marshallford** [terraform-google-modules/terraform-google-kubernetes-engine#401]
Hello,

I'd like to discuss the possibility of using the [gcloud](https://github.com/terraform-google-modules/terraform-google-gcloud) module as a replacement for the `wait-for-cluster.sh` script. Perhaps a solution similar to this PR: https://github.com/terraform-google-modules/terraform-google-project-factory/pull/343.

I am a TFE customer and would like to avoid opting out of the "wait for cluster" feature via `skip_provisioners`. Thoughts? I'm thinking you could avoid requiring `jq` by doing something like this:

```
gcloud container clusters list --filter=name:<CLUSTER_NAME> --format="value(status)"
```

If this of interest I would be more than happy to put a PR together.

Thanks.

**Comment by morgante** [comment]
Yes, I'd definitely like to move to using the `gcloud` module for this.

Note that the `gcloud` module *does* include `jq`. Happy to look at a PR for this though, either way.
