### ISSUE TITLE
Output master_ipv4_cidr_block

### ISSUE THREAD

**Issue by kcatro** [terraform-google-modules/terraform-google-kubernetes-engine#409]
On GKE it's possible to run into issues with using webhooks on private clusters. Examples include [prometheus](https://github.com/helm/charts/tree/master/stable/prometheus-operator#running-on-private-gke-clusters) or [cert-manager](https://cert-manager.io/docs/installation/compatibility/#gke).

The solution is to configure a firewall rule permitting (IIUC) access from hosted masters to GKE nodes, but the master CIDR block is not being output, so it's somewhat messy currently to glue a firewall module and terraform-google-kubernetes-engine module together.

Outputting the master_ipv4_cidr_block would aid in configuring a firewall rule more cleanly.

**Comment by morgante** [comment]
This makes sense, I'd be happy to accept a PR adding this.

**Comment by kravvcu** [comment]
Added #427
