### ISSUE TITLE
Enable workload identity by default

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#425]
We should consider enabling workload identity by default on beta clusters, by providing a non-null default for `identity_namespace`.

**Comment by morgante** [comment]
We should default to the project based namespace (which is currently the only option supported by Workload Identity).

**Comment by Dev25** [comment]
Speaking of enabling security features by default, Shielded GKE nodes will be enabled as default starting from GKE 1.18 according to Cloud SDK. On beta modules could we also set `enable_shielded_nodes` to true at the same time we roll out the next breaking change/this issue.

**Comment by morgante** [comment]
Agreed, I think that's a good addition as well.

**Comment by bharathkkb** [comment]
@Dev25 sg, I will add this as well.
