### ISSUE TITLE
rror: Error running command '.terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-064f308/scripts/wait-for-cluster.sh

### ISSUE THREAD

**Issue by jsdevalx** [terraform-google-modules/terraform-google-kubernetes-engine#426]
Almost unchanged example script from (commented node_pool_taint_section only):
https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/7.1.0

terraform --version
Terraform v0.12.20
+ provider.google v3.7.0
+ provider.google-beta v3.7.0
+ provider.kubernetes v1.10.0
+ provider.null v2.1.2
+ provider.random v2.2.1

Windows 10 platform.

module.gke.null_resource.wait_for_cluster[0]: Creating...
module.gke.null_resource.wait_for_cluster[0]: Provisioning with 'local-exec'...
module.gke.null_resource.wait_for_cluster[0] (local-exec): Executing: ["cmd" "/C" ".terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-064f308/scripts/wait-for-cluster.sh terraform-project-init gke-test-1"]
module.gke.null_resource.wait_for_cluster[0] (local-exec): '.terraform' is not recognized as an internal or external command,
module.gke.null_resource.wait_for_cluster[0] (local-exec): operable program or batch file.

Error: Error running command '.terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-064f308/scripts/wait-for-cluster.sh terraform-project-init gke-test-1': exit status 1. Output: '.terraform' is not recognized as an internal or external command,
operable program or batch file.

**Comment by hornetmadness** [comment]
Same issue, this poped up after I deleted the nope pool and recreated it.

`module.bastion_host.google_compute_instance.public_instance[0]: Destroying... [id=projects/salesloft-qa-252014/zones/us-central1-a/instances/bastion-qa-cluster-1-1]
module.gke.google_container_node_pool.pools[0]: Destroying... [id=us-central1/qa-cluster-1/default-node-pool]
module.bastion_host.google_compute_instance.public_instance[0]: Still destroying... [id=projects/salesloft-qa-252014/zones/us-c...al1-a/instances/bastion-qa-cluster-1-1, 10s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 10s elapsed]
module.bastion_host.google_compute_instance.public_instance[0]: Still destroying... [id=projects/salesloft-qa-252014/zones/us-c...al1-a/instances/bastion-qa-cluster-1-1, 20s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 20s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 30s elapsed]
module.bastion_host.google_compute_instance.public_instance[0]: Still destroying... [id=projects/salesloft-qa-252014/zones/us-c...al1-a/instances/bastion-qa-cluster-1-1, 30s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 40s elapsed]
module.bastion_host.google_compute_instance.public_instance[0]: Still destroying... [id=projects/salesloft-qa-252014/zones/us-c...al1-a/instances/bastion-qa-cluster-1-1, 40s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 50s elapsed]
module.bastion_host.google_compute_instance.public_instance[0]: Still destroying... [id=projects/salesloft-qa-252014/zones/us-c...al1-a/instances/bastion-qa-cluster-1-1, 50s elapsed]
module.bastion_host.google_compute_instance.public_instance[0]: Destruction complete after 58s
module.bastion_host.google_compute_address.instances[0]: Destroying... [id=projects/salesloft-qa-252014/regions/us-central1/addresses/bastion-qa-cluster-1-0]
module.bastion_host.google_compute_disk.instances[0]: Destroying... [id=projects/salesloft-qa-252014/zones/us-central1-a/disks/bastion-qa-cluster-1-1]
module.bastion_host.google_compute_disk.instances[0]: Destruction complete after 0s
module.bastion_host.google_compute_disk.instances[0]: Creating...
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 1m0s elapsed]
module.bastion_host.google_compute_disk.instances[0]: Provisioning with 'local-exec'...
module.bastion_host.google_compute_disk.instances[0] (local-exec): Executing: ["/bin/sh" "-c" ":"]
module.bastion_host.google_compute_disk.instances[0]: Provisioning with 'local-exec'...
module.bastion_host.google_compute_disk.instances[0] (local-exec): Executing: ["/bin/sh" "-c" ":"]
module.bastion_host.google_compute_disk.instances[0]: Creation complete after 3s [id=projects/salesloft-qa-252014/zones/us-central1-a/disks/bastion-qa-cluster-1-1]
module.bastion_host.google_compute_address.instances[0]: Destruction complete after 3s
module.bastion_host.google_compute_address.instances[0]: Creating...
module.bastion_host.google_compute_address.instances[0]: Creation complete after 4s [id=projects/salesloft-qa-252014/regions/us-central1/addresses/bastion-qa-cluster-1-1]
module.bastion_host.google_compute_instance.public_instance[0]: Creating...
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 1m10s elapsed]
module.bastion_host.google_compute_instance.public_instance[0]: Creation complete after 9s [id=projects/salesloft-qa-252014/zones/us-central1-a/instances/bastion-qa-cluster-1-1]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 1m20s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 1m30s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 1m40s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 1m50s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 2m0s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 2m10s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 2m20s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 2m30s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 2m40s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 2m50s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 3m0s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 3m10s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 3m20s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 3m30s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 3m40s elapsed]
module.gke.google_container_node_pool.pools[0]: Still destroying... [id=us-central1/qa-cluster-1/default-node-pool, 3m50s elapsed]
module.gke.google_container_node_pool.pools[0]: Destruction complete after 3m57s
module.gke.google_container_node_pool.pools[0]: Creating...
module.gke.google_container_node_pool.pools[0]: Still creating... [10s elapsed]
module.gke.google_container_node_pool.pools[0]: Still creating... [20s elapsed]
module.gke.google_container_node_pool.pools[0]: Still creating... [30s elapsed]
module.gke.google_container_node_pool.pools[0]: Still creating... [40s elapsed]
module.gke.google_container_node_pool.pools[0]: Still creating... [50s elapsed]
module.gke.google_container_node_pool.pools[0]: Still creating... [1m0s elapsed]
module.gke.google_container_node_pool.pools[0]: Still creating... [1m10s elapsed]
module.gke.google_container_node_pool.pools[0]: Still creating... [1m20s elapsed]
module.gke.google_container_node_pool.pools[0]: Still creating... [1m30s elapsed]
module.gke.google_container_node_pool.pools[0]: Creation complete after 1m37s [id=projects/salesloft-qa-252014/locations/us-central1/clusters/qa-cluster-1/nodePools/default-node-pool]

Error: leftover module module.serviceAccount in state that should have been removed; this is a bug in Terraform and should be reported`

**Comment by morgante** [comment]
@hornetmadness Can you open an issue on Terraform core? This sounds like a bug there, not in the module.

**Comment by dmanas0** [comment]
Same problem here. Did someone find a workaround or something?

**Comment by abdelhegazi** [comment]
@hornetmadness have you got this sorted btw either here or within terraform if you opened an issue/

**Comment by ivanblack19** [comment]
Have the same issue, Any help ?

```
Terraform v0.13.2
Initializing plugins and modules...
module.xxxx_cluster_us-central1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0]: Destroying... [id=3731077962842910667]
module.xxxx_cluster_europe_west1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0]: Destroying... [id=232885473266699705]
module.xxxx_cluster_us-central1.module.gke.modulxxxxxe.gcloud_wait_for_cluster.null_resource.run_command[0]: Provisioning with 'local-exec'...
module.xxxx_cluster_us-central1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): Executing: ["/bin/sh" "-c" "PATH=/google-cloud-sdk/bin:$PATH\n.terraform/modules/xxxx_cluster_us-central1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh project-flux-testing xxxxxflux-xxxx-us-central1\n"]
module.xxxx_cluster_europe_west1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0]: Provisioning with 'local-exec'...
module.xxxx_cluster_europe_west1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): Executing: ["/bin/sh" "-c" "PATH=/google-cloud-sdk/bin:$PATH\n.terraform/modules/xxxx_cluster_europe_west1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh project-flux-testing xxxxxflux-xxxx-europe-west1\n"]
module.xxxx_cluster_asia_southeast1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0]: Destroying... [id=6186861843613652654]
module.xxxx_cluster_asia_southeast1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0]: Provisioning with 'local-exec'...
module.xxxx_cluster_us-central1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): /bin/sh: 2: .terraform/modules/xxxx_cluster_us-central1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh: not found
module.xxxx_cluster_asia_southeast1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): Executing: ["/bin/sh" "-c" "PATH=/google-cloud-sdk/bin:$PATH\n.terraform/modules/xxxx_cluster_asia_southeast1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh project-flux-testing xxxxxflux-xxxx-asia-southeast1\n"]

module.xxxx_cluster_asia_southeast1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): /bin/sh: 2: .terraform/modules/xxxx_cluster_asia_southeast1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh: not found

module.xxxx_cluster_europe_west1.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): /bin/sh: 2: .terraform/modules/xxxx_cluster_europe_west1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh: not found


Error: Error running command 'PATH=/google-cloud-sdk/bin:$PATH
.terraform/modules/xxxx_cluster_europe_west1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh project-flux-testing xxxxxflux-xxxx-europe-west1
': exit status 127. Output: /bin/sh: 2: .terraform/modules/xxxx_cluster_europe_west1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh: not found




Error: Error running command 'PATH=/google-cloud-sdk/bin:$PATH
.terraform/modules/xxxx_cluster_asia_southeast1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh project-flux-testing xxxxxflux-xxxx-asia-southeast1
': exit status 127. Output: /bin/sh: 2: .terraform/modules/xxxx_cluster_asia_southeast1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh: not found




Error: Error running command 'PATH=/google-cloud-sdk/bin:$PATH
.terraform/modules/xxxx_cluster_us-central1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh project-flux-testing xxxxxflux-xxxx-us-central1
': exit status 127. Output: /bin/sh: 2: .terraform/modules/xxxx_cluster_us-central1.gke/terraform-google-kubernetes-engine-11.0.0/modules/beta-private-cluster/scripts/wait-for-cluster.sh: not found

```

**Comment by bharathkkb** [comment]
Hi @jsdevalx 
With https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/401 we have switched over to using the gcloud module which hopefully addresses the issue. Feel free to reopen if needed. 
@ivanblack19 That error does not seem related to the original issue, if you are still having this error, feel free to open an issue.
