### ISSUE TITLE
can't provision a cluster with less than than 2 "zones"

### ISSUE THREAD

**Issue by czka** [terraform-google-modules/terraform-google-kubernetes-engine#43]
```
$ terraform --version
Terraform v0.11.11
+ provider.google v1.19.1
```

With code as pasted in the bottom-most section of this ticket, which seems valid as per your docs and examples, I'm getting the following error at `terraform plan`:
```
Error: Error running plan: 1 error(s) occurred:

* module.gke.local.cluster_type_output_zonal_zones: local.cluster_type_output_zonal_zones: Resource 'google_container_cluster.zonal_primary' does not have attribute 'additional_zones' for variable 'google_container_cluster.zonal_primary.*.additional_zones'
```

Why is user forced to specify more than 1 zone? This is supposed to be a generic module after all.

```
variable "default-scopes" {
  type = "list"

  default = [
    "https://www.googleapis.com/auth/monitoring",
    "https://www.googleapis.com/auth/devstorage.read_only",
    "https://www.googleapis.com/auth/logging.write",
    "https://www.googleapis.com/auth/service.management.readonly",
    "https://www.googleapis.com/auth/servicecontrol",
    "https://www.googleapis.com/auth/trace.append",
  ]
}

module "gke" {
  source                     = "github.com/terraform-google-modules/terraform-google-kubernetes-engine?ref=master"
  ip_range_pods              = ""                 #TODO
  ip_range_services          = ""                 #TODO
  name                       = "cluster-you-name-it"
  network                    = "vpc-you-name-it"
  project_id                 = "project-you-name-it"
  region                     = "europe-west1"
  subnetwork                 = "vpc-sub-you-name-it"
  zones                      = ["europe-west1-c"]
  monitoring_service         = "monitoring.googleapis.com/kubernetes"
  logging_service            = "logging.googleapis.com/kubernetes"
  maintenance_start_time     = "04:00"
  kubernetes_version         = "1.11.3-gke.18"
  horizontal_pod_autoscaling = true
  regional                   = false

  node_pools = [
    {
      name               = "core"
      machine_type       = "n1-standard-2"
      oauth_scopes       = "${var.default-scopes}"
      min_count          = 1
      max_count          = 20
      auto_repair        = true
      auto_upgrade       = false
      initial_node_count = 20
    },
    {
      name               = "cc"
      machine_type       = "custom-6-23040"
      oauth_scopes       = "${var.default-scopes}"
      min_count          = 0
      max_count          = 20
      auto_repair        = true
      auto_upgrade       = false
      initial_node_count = 20
      preemptible        = true
      node_version       = "1.10.9-gke.7"
    },
  ]

  node_pools_labels = {
    all  = {}
    core = {}
    cc   = {}
  }

  node_pools_tags = {
    all  = []
    core = []
    cc   = []
  }

  node_pools_taints = {
    all  = []
    core = []
    cc   = []
  }
}
```

**Comment by morgante** [comment]
I don't think it's supported to have a regional cluster with a single zone. For that case, I think you would want to create a zonal cluster, as per this example: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/simple_zonal

**Comment by czka** [comment]
@morgante Why do you think I want to have a regional cluster? I've set `regional                   = false`.

**Comment by bzub** [comment]
I'm hitting this issue as well, although it only started happening after a `terraform destroy` in which the previously created cluster was deleted already outside of terraform (gcloud cli). So there may be some resources left over in my GCP project that get picked up when terraform refreshes. `terraform show` is empty so I don't think it's a state issue on the terraform side.

**Comment by bzub** [comment]
This interpolation basically interpolates a non-existent list element at index `1` when `var.zones` has a length of only one.
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/60baab8401f68c0a193b1b95ca4f8df1ba2d9ee5/cluster_zonal.tf#L27

I'm assuming that's part of the issue, since this local variable ends up with no zones instead of the singular zone provided to the module's `zone` variable.
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/60baab8401f68c0a193b1b95ca4f8df1ba2d9ee5/main.tf#L54

**Comment by morgante** [comment]
Thanks for identifying the issue - that does indeed look like what needs to be fixed.

**Comment by ogreface** [comment]
Potential fix in: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/50

**Comment by czka** [comment]
#50 works for me.
