### ISSUE TITLE
private-cluster does not allow changing default_max_pods_per_node

### ISSUE THREAD

**Issue by chanuka-techo** [terraform-google-modules/terraform-google-kubernetes-engine#435]
This is more of a question than an issue. Is there any reason for limiting the private-cluster default_max_pods_per_node to 110, which is the default?

**Comment by bharathkkb** [comment]
Previously it was in beta and hence only supported on the beta clusters
I think we can add support now as this is now GA
https://github.com/GoogleCloudPlatform/magic-modules/pull/2429

**Comment by morgante** [comment]
Yup looks like we can roll this out for all.
