### ISSUE TITLE
null_resource.wait_for_cluster must be replaced

### ISSUE THREAD

**Issue by endorama** [terraform-google-modules/terraform-google-kubernetes-engine#446]
Hello, I'm facing some incongruence's in my terraform state due to the `wait_for_cluster` `null_resource` in the `private` module of this repo.

The terraform execution plan is:

```
Terraform will perform the following actions:

  # module.cluster.null_resource.wait_for_cluster[0] must be replaced
-/+ resource "null_resource" "wait_for_cluster" {
      ~ id       = "8404887862418893500" -> (known after apply)
      + triggers = {
          + "name"       = "REDACTED"
          + "project_id" = "REDACTED"
        } # forces replacement
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

I'm using 
```
  source = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"
  version = "~> 7.0"
```

I can't understand exactly why such a plan is made. 
Any hint or suggestion on how to solve it? 
Thanks!

**Comment by morgante** [comment]
This is merely a change to the module code (to fix a bug/change in new versions of Terraform).

Applying this plan is effectively a no-op and safe to do.

**Comment by endorama** [comment]
Thanks @morgante!

**Comment by cloud-rocket** [comment]
Any idea why this is happening and how to fix it?

I have a similar case, when terraform asks to replace the cluster during every execution.
Thanks!

**Comment by morgante** [comment]
@cloud-rocket Please share your Terraform plan. In this instance, the issue is *not* replacing the cluster just updating a null_resource (which is a safe no-op).

**Comment by cloud-rocket** [comment]
Sorry, you are actually right - the cluster was replaced for other reasons:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.gke.null_resource.wait_for_cluster[0] must be replaced
-/+ resource "null_resource" "wait_for_cluster" {
      ~ id       = "9208559240229461714" -> (known after apply)
      + triggers = {
          + "name"       = "####"
          + "project_id" = "####"
        } # forces replacement
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.gke.null_resource.wait_for_cluster[0]: Destroying... [id=9208559240229461714]


Error: 2 problems:

- Attempt to get attribute from null value: This value is null, so it does not have any attributes.
- Attempt to get attribute from null value: This value is null, so it does not have any attributes.

```

But it actually reports those 2 errors.

**Comment by morgante** [comment]
Try running `terraform state rm module.gke.null_resource.wait_for_cluster`.

**Comment by zolech** [comment]
I can confirm that manualy removing state as mentioned above resolved this issue.

**Comment by anne-nelson** [comment]
The 7.0 upgrade guide should be updated to reflect this.

**Comment by morgante** [comment]
Added a note here - https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/475
