### ISSUE TITLE
Cluster creation timing out 

### ISSUE THREAD

**Issue by joekhese** [terraform-google-modules/terraform-google-kubernetes-engine#447]
![image](https://user-images.githubusercontent.com/29741210/75569703-a235a000-5a23-11ea-986c-c6cf78f1f9ab.png)

**Comment by bharathkkb** [comment]
Hi @joekhese 
Can you share a minimal version of your tf files so I can try to reproduce?

**Comment by joekhese** [comment]
Hi, i resolved the issue. i just upgraded to the module's latest version and that fixes it.
thanks
