### ISSUE TITLE
Add optional firewall support

### ISSUE THREAD

**Issue by Dev25** [terraform-google-modules/terraform-google-kubernetes-engine#452]
Consider adding a opt in method for this module to create common/useful firewalls related to the cluster. I tend to always have to create 2 firewall rules due to running in a slightly more restricted VPC or for certain workloads (Admission Controllers).

### Explict Egress rule for cluster traffic.

GKE already creates a `Ingress` rule for the cluster and then relies on the fact there is a [implicit](https://cloud.google.com/vpc/docs/firewalls#default_firewall_rules) allow-all-egress rule for VPCs by default. That assumption doesn't work when you are running locked down VPCs that create a `default-deny-all` egress rule (also w/ intranode visibility enabled)

```tf
resource "google_compute_firewall" "egress" {
  name      = "gke-${var.name}-allow-intra-cluster-egress"
  project   = var.network_project_id
  network   = var.network
  direction = "EGRESS"
  priority  = 2000
  target_tags = ["gke-${var.name}"]  
  destination_ranges = [
    # GKE Master - Only for Private clusters!
    var.master_ipv4_cidr_block,
    # GKE Node Subnet
    data.google_compute_subnetwork.gke_subnetwork.ip_cidr_range,
    # GKE Alias Ranges
    local.alias_ranges_cidr[var.ip_range_pods],
    local.alias_ranges_cidr[var.ip_range_services]
  ]

  allow { protocol = "tcp"}
  allow { protocol = "udp"}
  allow { protocol = "icmp"}
}
```

### Allow non 443 ports for GKE Master -> nodes due to admission controllers

This is for when cluster workloads include webhooks/admission controllers that run on non 443 ports. Without this you will end up seeing timeouts and pods are blocked from being created.

https://github.com/kubernetes/kubernetes/issues/79739

Examples: 9443 (Elasticsearch Operator https://github.com/elastic/cloud-on-k8s/issues/896), 15017 (Istio 1.5+ https://github.com/istio/istio/issues/19532)

```tf
# Allow GKE master to hit non 443 ports for Webhooks/Admission Controllers
# https://github.com/kubernetes/kubernetes/issues/79739
resource "google_compute_firewall" "master_webhooks" {
  name      = "gke-${var.name}-allow-master-webhooks"
  project   = var.network_project_id
  network   = var.network
  direction = "INGRESS"
  priority  = 2000

  allow {
    protocol = "tcp"
    ports    = var.webhook_ports
  }

  source_ranges = [var.master_ipv4_cidr_block] # Public Cluster: "${module.gke.endpoint}/32"
  target_tags   = ["gke-${var.name}"]
}
```

**Comment by morgante** [comment]
Your second rule definitely sounds like a good addition (assuming we have variables to control it).

For your first rule, what will break if you *don't* have this rule? Will GKE itself break, or just some applications? I'm reticent to override firewall rules when many organizations have alternative/preferred egress paths.

**Comment by Dev25** [comment]
The TF examples above were more or less pulled out of my current usage, for upstreaming it most would be controlled by variables and opt in e.g.

```tf
firewall_create_intra_cluster_egress_rule = false # Create 1. if true
firewall_allow_ingress_webhook_ports = [] # Create 2. if non empty w/given ports
firewall_priority = 2000
```

Regarding 1, my scenario was with a VPC with a `default-deny-all-egress` + allowing common outbound ports (80/443), so its not a completely locked down VPC.

Spinning up a GKE cluster with `enable_intranode_visibility` will break the cluster. I've not yet tested without IV, but i suspect it will still break to a lesser degree for traffic between nodes rather then all pod traffic.

Specifically i was seeing `kube-system` workloads getting `CrashLoopBackOff`, DNS will break along with any pod <-> pod traffic.

e.g. DNS breaks since you can't hit UDP/53 to the kube-dns pods, the kube-dns pods themselves manage to work fine because VPC firewalls _always_ allow access to the [metadata server](https://cloud.google.com/vpc/docs/firewalls#firewall_rules_in).

Example of getting I/O timeouts during DNS resolution
```
connection error: desc = "transport: Error while dialing dial tcp: lookup istio-galley.istio-system.svc on 10.250.0.10:53: read udp 10.240.0.45:47715->10.250.0.10:53: i/o timeout"
```

I did raise a support case last summer regarding the intranode/egress stuff, i don't think that got anywhere unfortunately. Ideally GKE itself creates a Egress rule for internal cluster traffic just like how it manages the Ingress rules.

This rule workaround is pretty similar to those Ingress rules managed by GKE because it restricts the destination to the cluster CIDR + cluster specific network tags

**Comment by morgante** [comment]
Got it, in that case I think both firewall rules make sense (provided they can be disabled).

**Comment by haf** [comment]
1000+ for this; https://github.com/kubernetes/kubernetes/issues/79739#issuecomment-564794016
