### ISSUE TITLE
Error when using  default_max_pods_per_node with private-cluster module

### ISSUE THREAD

**Issue by spirrello** [terraform-google-modules/terraform-google-kubernetes-engine#458]
When I use this the default_max_pods_per_node variable I get the following error.  According to [this page](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/private-cluster) it's supported.

**module version:** 7.3.0

**ERROR**
```
Error: Unsupported argument

  on gke-module.tf line 79, in module "gke-cluster-01":
  79:   default_max_pods_per_node = 20

An argument named "default_max_pods_per_node" is not expected here.
```

**Terraform code snippet**
```
module "gke-cluster-01" {
  source = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"

  project_id                 = var.project_id
  name                       = "gke-cluster-01"
  regional                   = true
  region                     = var.region
  network                    = var.k8s-network-01["network_name"]
  subnetwork                 = var.k8s-network-01["subnetwork"]
  ip_range_pods              = var.k8s-network-01["pod_range"]
  ip_range_services          = var.k8s-network-01["svc_range"]
  create_service_account     = false
  service_account            = ""
  http_load_balancing        = true
  horizontal_pod_autoscaling = true
  network_policy             = true
  enable_private_endpoint    = true
  enable_private_nodes       = true
  master_ipv4_cidr_block     = "172.16.0.0/28"
  default_max_pods_per_node = 20
  remove_default_node_pool = true
```

**Comment by bharathkkb** [comment]
Hi @spirrello 
Looks like we havent cut a new release yet with default_max_pods_per_node in GA modules.

**Comment by spirrello** [comment]
While I have your attention....do you know when the `beta-private-cluster` module will go GA?  That one actually does work when using the `default_max_pods_per_node` variable.

**Comment by mouglou** [comment]
got the same here ;)
thanks @bharathkkb . will wait for the update.

**Comment by morgante** [comment]
> While I have your attention....do you know when the beta-private-cluster module will go GA? 

The beta module itself will never go GA: it's designed to capture functionality/features which are in beta.

Instead, individual features/flags are promoted to the GA module when they reach maturity.

**Comment by jmymy** [comment]
was added in latest release

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/releases/tag/v8.0.0
