### ISSUE TITLE
deploy_service example prefixes endpoint with https://

### ISSUE THREAD

**Issue by MajorBreakfast** [terraform-google-modules/terraform-google-kubernetes-engine#461]
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/025f8b7eae93651a2c23ef770654782222cd61b7/examples/deploy_service/main.tf#L28

Is adding `https://` in front actually needed? For me, `endpoint` contains just a string containing an IP and it works without the `https://` in front.

- If it's needed, I'd like to create a PR that adds a comment that explains why it's required
- If it's not needed, I'd like to create a PR that removes it and thus makes the example more minimalistic

**Comment by bharathkkb** [comment]
@MajorBreakfast I dont think its needed; This example works file with out it.
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/025f8b7eae93651a2c23ef770654782222cd61b7/examples/workload_identity/main.tf#L28

**Comment by morgante** [comment]
Yeah I think it's fine with or without it. Happy to accept a PR removing it.
