### ISSUE TITLE
Enable peering_name for private clusters

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-kubernetes-engine#478]
Enable passing `peering_name` as an argument in the `private_cluster_config` https://www.terraform.io/docs/providers/google/r/container_cluster.html#peering_name

**Comment by rileykarson** [comment]
`peering_name` is a read-only field: https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/google-beta/resource_container_cluster.go#L766-L769

(a configurable field will be marked optional or required)

**Comment by bharathkkb** [comment]
Ah good catch :) looks like I missed the read-only part
I will circle back with the user who needed this
