### ISSUE TITLE
Beta variants broken due to bug with google-beta provider

### ISSUE THREAD

**Issue by dhdersch** [terraform-google-modules/terraform-google-kubernetes-engine#479]
Hello,

It appears that using the data source `google_compute_zones` no longer works for the `google-beta` provider (though it does work for the `google` provider).

I am using the `beta-private-cluster-update-variant` to deploy a cluster, but I get this error:

```
Error: googleapi: Error 403: Required 'compute.zones.list' permission for 'projects/<redacted>', forbidden

  on .terraform\modules\<redacted>\terraform-google-kubernetes-engine-7.3.0\modules\beta-private-cluster-update-variant\main.tf line 22, in data "google_compute_zones" "available":
  22: data "google_compute_zones" "available" {
```

The service account I am using definitely has these permissions on the project. I tested using `gcloud beta zones list --project <project_id>`.

I am using the following version of Terraform and providers:

```
Terraform v0.12.24
+ provider.google v3.9.0
+ provider.google-beta v3.9.0
+ provider.kubernetes v1.10.0
+ provider.null v2.1.2
+ provider.random v2.2.1
```

**Comment by morgante** [comment]
Please file an issue on the provider, as I suspect this is probably either a provider bug or an issue with your SA permissions.

**Comment by dhdersch** [comment]
The provider `google-beta` does not seem to have a place to file issues.

**Comment by morgante** [comment]
You can file issues on the main repo for both: https://github.com/terraform-providers/terraform-provider-google/issues

**Comment by dhdersch** [comment]
For anyone that runs into this (until the `google-beta` provider is fixed), my workaround is as follows:

Go to the .terrafrom/modules repo and find the appropriate module and change the following code in `main.tf` from

```tf
data "google_compute_zones" "available" {
  provider = google-beta
  project = var.project_id
  region  = local.region
}
```

to the following:

```tf
data "google_compute_zones" "available" {
  project = var.project_id
  region  = local.region
}
```

Which allowed my `plan` and `apply` to proceed.

**Comment by morgante** [comment]
Since it's such an easy fix, I opened up a quick PR: #480

**Comment by dhdersch** [comment]
Hey @morgante , I actually think your original assessment was correct. It seemed to be a service account issue on my end.

**Comment by morgante** [comment]
@dhdersch Thanks for confirming.
