### ISSUE TITLE
Failures on plan/apply with imported clusters

### ISSUE THREAD

**Issue by dpatrick** [terraform-google-modules/terraform-google-kubernetes-engine#494]
Hi team

I'm having problems when attempting to import clusters that were created outside of this module (via a previous in-house module). The import statement succeeds, but when attempting to run terraform plan or terraform apply, it errors out with invalid index.

I'm using the `beta-private-cluster-update-variant module v8.1.0`

And the exact errors I get are (with real cluster info removed)

```
module.gke.google_container_cluster.primary: Refreshing state... [id=projects/my-project/locations/us-central1/clusters/my-cluster]

Error: Invalid index

  on .terraform/modules/gke/terraform-google-kubernetes-engine-8.1.0/modules/beta-private-cluster-update-variant/main.tf line 109, in locals:
 109:   cluster_output_http_load_balancing_enabled        = google_container_cluster.primary.addons_config.0.http_load_balancing.0.disabled
    |----------------
    | google_container_cluster.primary.addons_config[0].http_load_balancing is empty list of object

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/gke/terraform-google-kubernetes-engine-8.1.0/modules/beta-private-cluster-update-variant/main.tf line 110, in locals:
 110:   cluster_output_horizontal_pod_autoscaling_enabled = google_container_cluster.primary.addons_config.0.horizontal_pod_autoscaling.0.disabled
    |----------------
    | google_container_cluster.primary.addons_config[0].horizontal_pod_autoscaling is empty list of object

The given key does not identify an element in this collection value.
```

Any suggestions on how to resolve this problem? For reference, the cluster I'm importing should _mostly_ match the plan I've written

**Comment by bharathkkb** [comment]
Hi @dpatrick 
I can try to repro. Could you share the following?
- An example config of how you are using `beta-private-cluster-update-variant module`
- The GKE version of your imported cluster
- The google provider version
- Do you have `http_load_balancing` and `horizontal_pod_autoscaling` currently enabled or disabled on your imported cluster

**Comment by dpatrick** [comment]
@bharathkkb  Thanks for the quick response!

- The cluster is GKE version 1.14.10-gke.31
- Using Google provider version 3.14.0 (both beta and regular)
- `http_load_balancing` and `horizontal_pod_autoscaling` are both currently enabled on the cluster

I'm calling the module like below (with some internal identifierschanged)
```
module "gke" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster-update-variant"
  version = "v8.1.0"

  project_id      = local.project_id
  name            = "my-cluster"
  region          = local.region
  regional        = "true"
  network         = local.network
  subnetwork      = data.google_compute_subnetwork.subnet-primary.name
  release_channel = "REGULAR"
  master_ipv4_cidr_block       = "172.16.0.0/28"
  ip_range_pods                = local.subnetwork_pods_name
  ip_range_services            = local.subnetwork_services_name
  http_load_balancing          = true
  horizontal_pod_autoscaling   = true
  network_policy               = true
  enable_private_endpoint      = false
  enable_private_nodes         = true
  enable_shielded_nodes        = true
  create_service_account       = false
  authenticator_security_group = "email@company"
  configure_ip_masq            = "true"
  identity_namespace           = "enabled"
  node_metadata                = "GKE_METADATA_SERVER"
  remove_default_node_pool     = true

  node_pools = [
    {
      name               = "node_pool"
      machine_type       = "n1-standard-8"
      initial_node_count = 1
      min_count          = 1
      max_count          = 3
      image_type         = "COS"
      auto_repair        = true
      auto_upgrade       = true
      service_account    = "service_account@project"
    },
  ]

  node_pools_labels = {
    all = {
      cost-center = "shared"
    }
  }
```

**Comment by dpatrick** [comment]
I dug a little deeper on this and took a look at the state file. It looks like the error is correct that these objects are empty in the state. From the state file...
```
"addons_config": [
  {
    "cloudrun_config": [],
    "dns_cache_config": [],
    "horizontal_pod_autoscaling": [],
    "http_load_balancing": [],
    "istio_config": [],
    "kubernetes_dashboard": [],
    "network_policy_config": [
      {
        "disabled": true
      }
    ]
  }
],
```

For the sake of testing, I manually edited `http_load_balancing` and `horizontal_pod_autoscaling`  to have object config which would match their current state, but terraform still complains with the same error.  That leads me to guess it is doing some validation against the GCP API which isn't returning what it wants.

**Comment by bharathkkb** [comment]
@dpatrick so I tried to reproduce, but I was unable to. I can successfully import it via
`terraform import module.gke.google_container_cluster.primary projects/test-gke-import-issue/locations/us-central1/clusters/my-cluster-2` and then run a plan which did not complain. My imported state file addons look like this
```json
"horizontal_pod_autoscaling": [
                  {
                    "disabled": false
                  }
                ],
                "http_load_balancing": [
                  {
                    "disabled": false
                  }
                ],
```
Could you try running a gcloud command and see what the json representation looks like
`gcloud beta --project=$PROJECT_ID container clusters --region=$REGION describe $CLUSTER_NAME --format=json`
Additionally could you also try running a targeted plan at just the google_container_cluster resource and see what happens?
`terraform plan -target=module.gke.google_container_cluster.primary`

**Comment by dpatrick** [comment]
Hmm... weird that you were unable to reproduce. When running the gcloud describe I actually don't see either of those two addons in the output there either.
```
  "addonsConfig": {
    "kubernetesDashboard": {
      "disabled": true
    },
    "networkPolicyConfig": {
      "disabled": true
    }
  },
```

To my great shock, using target worked; It successfully planned. It wants create the available zones and service account suffix resources in addition to changing the cluster. I'm going to continue down the target road and see if I can't get terraform to be fully happy with the cluster

**Comment by bharathkkb** [comment]
Great, I think after the targeted apply google_container_cluster.primary.addons_config[0].http_load_balancing will no longer be an empty list; lmk how it goes.
It's also really odd that the API itself is not returning those keys.

**Comment by dpatrick** [comment]
Definitely really weird. I actually have three clusters that were created with the old terraform plan and all three exhibit this same behavior upon import into this module. My first cluster I was able to target (and manually modify to enable release channels via the beta commands) successfully and a plan output no longer sees any changes. No need to recreate, it added the missing addon config blocks just fine.

The second cluster I've started to work on. It is claiming it needs to recreate due to the `dns_cache_config` addon being added (It is disabled on the cluster and in the plan; not sure why I didn't see this happen with the other cluster) I'm continuing to experiment though.

**Comment by bharathkkb** [comment]
Glad to hear it worked out :)

**Comment by mazzy89** [comment]
Seems I'm facing the same issue. I'm trying to import an existing cluster and this is the error:

```sh
╷
│ Error: Invalid index
│
│   on .terraform/modules/gke/main.tf line 114, in locals:
│  114:   cluster_output_http_load_balancing_enabled        = google_container_cluster.primary.addons_config[0].http_load_balancing[0].disabled
│     ├────────────────
│     │ google_container_cluster.primary.addons_config[0].http_load_balancing is empty list of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵

╷
│ Error: Invalid index
│
│   on .terraform/modules/gke/main.tf line 115, in locals:
│  115:   cluster_output_horizontal_pod_autoscaling_enabled = google_container_cluster.primary.addons_config[0].horizontal_pod_autoscaling[0].disabled
│     ├────────────────
│     │ google_container_cluster.primary.addons_config[0].horizontal_pod_autoscaling is empty list of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.
```
