### ISSUE TITLE
request to know how to disable auto-upgrade of master by some parameter

### ISSUE THREAD

**Issue by sudipju** [terraform-google-modules/terraform-google-kubernetes-engine#513]
We are using your project for our to-be production cluster:
https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/7.3.0
We observe sometimes it takes 25 min to create the cluster but sometimes also around 3 minutes.

Long timeframe:
 
module.gke.google_container_cluster.primary: Still modifying... [id=projects/swish-2-poc2/locations/europe-west2/clusters/internal-loadbalancer, 23m10s elapsed]

 
Short timeframe:
module.gke.google_container_cluster.primary: Creation complete after 2m53s [id=projects/swish-2-poc2/locations/europe-north1/clusters/uat-comparison-test-cluster]

We noticed when it updates master then it takes longer time. 

Is there anyway **to disable auto-upgrade of master by setting some parameter** in https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/7.3.0

Thanks in advance for your help.

Sample settings:
```
module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google"
  version                    = "7.3.0"
  project_id                 = var.project_id
  region                     = var.region
  name                       = var.name
  network                    = "default"
  subnetwork                 = "default"
  ip_range_pods              = ""
  ip_range_services          = ""
  http_load_balancing        = false
  horizontal_pod_autoscaling = true
#  kubernetes_dashboard       = true
  network_policy             = false
  maintenance_start_time     = "00:00"
  remove_default_node_pool   = true

  node_pools = [
    {
      name               = "default-node-pool"
#      name               = "worker-node-pool"
      machine_type       = var.machine_type
      min_count          = var.min_count
      max_count          = var.max_count
      disk_size_gb       = var.disk_size_gb
      disk_type          = var.disk_type
      auto_repair        = true
      auto_upgrade       = false
      service_account    = var.service_account
      preemptible        = true
      initial_node_count = var.initial_node_count
    },
  ]

  node_pools_oauth_scopes = {
    all = []

    default-node-pool = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }

  node_pools_labels = {
    all = {}

    default-node-pool = {
      default-node-pool = true
      role = "ingress-controller"
    }
  }

  node_pools_metadata = {
    all = {}

    default-node-pool = {
      node-pool-metadata-custom-value = "my-node-pool"
    }
  }

  node_pools_tags = {
    all = []

    default-node-pool = [
      "default-node-pool",
    ]
  }
}

data "google_client_config" "default" {
}
```

**Comment by morgante** [comment]
Hi I don't think this is related to the master *version* upgrade.

Instead I suspect it's based on GKE requiring the master instance be resized as your node pool size. Unfortunately there's no way to influence/control the master sizing via Terraform.
