### ISSUE TITLE
maintenance_start_time not set for safer-cluster

### ISSUE THREAD

**Issue by dmaasland** [terraform-google-modules/terraform-google-kubernetes-engine#518]
Hiya,

I'm trying to create a GKE cluster based on the safer-cluster module. Everything seems to be working, but the "maintenance_start_time" after creation stays at the default 05:00, as opposed to the 03:00 I've set it to. Perhaps I'm doing something wrong but I cannot find any other way of doing things. My current relevant config:

```
module "gke" {
  source                          = "terraform-google-modules/kubernetes-engine/google//modules/safer-cluster"
  version                         = "9.0.0"
  project_id                      = var.project_id
  name                            = "${local.cluster_type}-cluster-${random_string.suffix.result}"
  regional                        = true
  region                          = var.region
  network                         = module.gcp-network.network_name
  subnetwork                      = module.gcp-network.subnets_names[index(module.gcp-network.subnets_names, local.subnet_name)]
  ip_range_pods                   = local.pods_range_name
  ip_range_services               = local.svc_range_name
  master_ipv4_cidr_block          = "172.16.0.0/28"
  enable_private_endpoint         = false
  enable_shielded_nodes           = true
  release_channel                 = "REGULAR"
  maintenance_start_time          = "03:00"
  istio                           = false
  cloudrun                        = false
  sandbox_enabled                 = false
  enable_vertical_pod_autoscaling = true
  horizontal_pod_autoscaling      = true

  pod_security_policy_config = [
    {
      enabled = false
    }
  ]

  master_authorized_networks = [
    {
      cidr_block   = "10.60.0.0/17"
      display_name = "VPC"
      },
  ]

  node_pools = [
    {
      name                   = "${local.cluster_type}-node-pool"
      machine_type           = var.machine_type
      min_count              = 1
      max_count              = 100
      local_ssd_count        = 0
      disk_size_gb           = 100
      disk_type              = "pd-standard"
      image_type             = "COS_CONTAINERD"
      auto_repair            = true
      auto_upgrade           = true
      create_service_account = true
      preemptible            = var.preemptible
      initial_node_count     = 1
    },
  ]


}
```

After applying the cluster ends up with:

```
Maintenance window	
From 5:00 AM to 9:00 AM
Daily
```

What am I missing here? :)

**Comment by morgante** [comment]
Can you share your Terraform plan?

**Comment by dmaasland** [comment]
Yes!

[plan.txt](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/files/4620501/plan.txt)
If I run plan after deploy -> "No changes. Infrastructure is up-to-date." If I change the time:
```
      ~ maintenance_policy {
          ~ daily_maintenance_window {
                duration   = "PT4H0M0S"
              ~ start_time = "03:00" -> "04:00"
            }
        }
```

But the start time isn't shown as 03:00 on the GKE dashboard.

**Comment by morgante** [comment]
Hmm it looks like we're setting this correctly in the module - please file a bug on the provider.

**Comment by bharathkkb** [comment]
@morgante @dmaasland I believe this is working as intended. Please let me know if my testing is flawed.

The start time is based on [UTC](https://cloud.google.com/kubernetes-engine/docs/how-to/maintenance-windows-and-exclusions#maintenance-window) and I set `03:00` as the start time. GKE requires a 4-hour maintenance window. My GKE cluster UI showed `Maintenance window	
From 10:00 PM to 2:00 AM
Daily`. `03:00 UST` is `10:00PM CDT` and it adds 4 hours on this seems to add up. What timezone are you based in @dmaasland?

**Comment by dmaasland** [comment]
O my god. It's UTC. Of course it's UTC. I somehow figured it would magically know what timezone I'm in and offset it to match. Doesn't help that "03:00" (what I'd set it to) matches the default "05:00" in my timezone.

It works just fine, I'm just an idiot. Thank you all for your swift replies.

I hate timezones.
