### ISSUE TITLE
Modify IP table rules when creating GKE cluster

### ISSUE THREAD

**Issue by cumrun** [terraform-google-modules/terraform-google-kubernetes-engine#520]
I have this need to add remove entries or update completly iptable rules in destination GKE cluster when using kubernetes-engine module.
i tried a couple of ways including ip masq options and none masq CIDRs and but no success yet.
possibly override feature of terraform helps but I do not want to use it as long as there is better option with module itself.

I use the root module and not sub modules.

I wonder if you have any suggestion.

**Comment by morgante** [comment]
What's the IP table change you want to make?

**Comment by cumrun** [comment]
there is an entry on table nat and IP-MASQ chain which prevent internal ip addresses of pods to be masquerade. I want to remove that one. it is something like this:
-A IP-MASQ -d 10.0.0.0/8 -m comment --comment "ip-masq: RFC 1918 reserved range is not subject to MASQUERADE" -j RETURN

why I need to masquerade internal IP of pods when traffic goes out of the node is because of following.
I installed a glowroot collector on another virtual machine in other gcp region. the glowroot agent inside pod needs to communicate with glowroot collector on port 8181. surprisingly from within pod I can ping the glowroot collector internal IP address but pod does not have access to port 8181 of glowroot collector. as I checked with tcpdump the traffic for some reason is not reached to vm machine which glowroot collector is installed except the pod ips being subject of masquerade when going out of node. for icmp request everything is ok and they comunicate to each other without any problem(I mean vm and pod). by the way when I manually append to masquerade all to POSTROUTING chain or remove above rule, everything is OK.

apparently somewhere else drops packets and prevent to further trip when it is not icmp. I don't think it is inside worker nodes but I don't have any clue where it can be.

**Comment by morgante** [comment]
Can you set `configure_ip_masq` to `true` and `ip_masq_link_local` to false?

**Comment by cumrun** [comment]
If I don't say wrong, I did it already but no success.
I see again the above entry in IP-MASQ chain.
I will do it again and let you know the result.

**Comment by cumrun** [comment]
I created a completely new cluster with application installed on it.Unfortunately the same situation after setting

configure_ip_masq = true 
ip_masq_link_local = false

the same entry in IP-MASQ chain and everything the same.
As I said before I need to add an entry somewhere relevant and appropriate that when ip is pods internal IP and interface is INTERNAL_IP interface source IP be subject of masquerade.
