### ISSUE TITLE
disk type = "pd-ssd". However with gce-csi = true result in storage class = pd-standard

### ISSUE THREAD

**Issue by c0ffeec0der** [terraform-google-modules/terraform-google-kubernetes-engine#526]
With: 

gce_pd_csi_driver           = true
  node_pools = [
    {
      disk_type           = "pd-ssd"
    }
  ]

The node disk is correct

![image](https://user-images.githubusercontent.com/64681762/82427896-e7fa8580-9ab3-11ea-8294-7502f9b0dfb3.png)

However, cluster storage class is incorrect

![image](https://user-images.githubusercontent.com/64681762/82427999-095b7180-9ab4-11ea-85b9-51f2b0ac2ebe.png)

Looking up api doc 

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.GcePersistentDiskCsiDriverConfig

GCE CSI storage class is not exposed

Solution : Forward this issue to api team for expose and afterwards terraform code can be updated

**Comment by Dev25** [comment]
Hey @c0ffeec0der you seem to be mixing things up here

Node Pool disk types: `pd-ssd/pd-standard` (GCE disk types)
Default GKE Storage class: `standard` 
Default CSI Storage Class: `singlewriter-standard`

By default the CSI driver only installs a default storageclass, if you want to use extra features (SSD, Regional Disks) then you need to specify your own `storageclass` config.

https://cloud.google.com/kubernetes-engine/docs/how-to/gce-pd-csi-driver#using
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#createvolume-parameters
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/tree/master/examples/kubernetes

**Comment by c0ffeec0der** [comment]
Hello @Dev25, okay i see. Thank you for the info
