### ISSUE TITLE
enabling workload identity on an existing node pool without its recreation 

### ISSUE THREAD

**Issue by cldlrn** [terraform-google-modules/terraform-google-kubernetes-engine#529]
hello

Enabling workload identity on an existing node pool causes its deletion and recreation .
Please enable adding this feature in place
Thanks

Best regards

**Comment by morgante** [comment]
Can you share your plan file?

Unfortunately I don't know if it's possible to update in-place, but workload identity is the new default.

**Comment by bharathkkb** [comment]
It is possible via gcloud without recreating, not sure if there is a force-recreate on the provider. I can take a look.

**Comment by cldlrn** [comment]
thanks for your answer. I found that this issue was resolved in latest version of gcp terraform provider v3.23.0
regards
