### ISSUE TITLE
Can't provision kubernetes service account with workload identity module from different vpc network

### ISSUE THREAD

**Issue by pperez** [terraform-google-modules/terraform-google-kubernetes-engine#550]
Hello,
I've been trying the workload-identity module, is a total lifesaver for what i'm trying to accomplish. The only issue i've run into is that it doesn't supports the usage of an api proxy to deploy the kubernetes service account (This works great if i use it from a GCE running in the same project), so, it's not working with my use case, does anyone know any workaround that could help me with this?

**Comment by morgante** [comment]
It uses the `kubernetes` provider so if you're adding the proxy info to your kubeconfig that should work: https://www.terraform.io/docs/providers/kubernetes/index.html

@bharathkkb Any additional ideas?

**Comment by pperez** [comment]
Great! I'll give it a try, thanks!

**Comment by pperez** [comment]
Seems like kubectl will support that on 1.19, for the time being setting up https_proxy and no_proxy worked, thanks :)

**Comment by bharathkkb** [comment]
We should also document this as users may want to use private gke cluster + WI module until https://github.com/kubernetes/kubernetes/pull/81443
