### ISSUE TITLE
Set auto_provisioning_defaults.service_account ? (beta-public)

### ISSUE THREAD

**Issue by lemaral** [terraform-google-modules/terraform-google-kubernetes-engine#560]
When enabling node autoprovisioning, the service account for it stays at "default" and nodes in "automatic" node pools have no rights on Google APIs (e.g. pull from private GCR)
I would have expected that the service account would be set to the same one that is created for the "regular" node pools so that pods scheduled or rescheduled on the automatic node pools would work the same (at least by default).
I believe it is in auto_provisioning_defaults.service_account

**Comment by morgante** [comment]
Yes we should fill in this property: https://www.terraform.io/docs/providers/google/r/container_cluster.html#service_account

Happy to review a PR.

**Comment by morgante** [comment]
Fixed by #639.
