### ISSUE TITLE
google_container_cluster.primary: googleapi: Error 400: Legacy monitoring is not supported in clusters running Kubernetes 1.15 or above., badRequest

### ISSUE THREAD

**Issue by satwik123** [terraform-google-modules/terraform-google-kubernetes-engine#565]
Getting below error 

Error: Error applying plan:

1 error(s) occurred:

* module.gke.google_container_cluster.primary: 1 error(s) occurred:

* google_container_cluster.primary: googleapi: Error 400: Legacy monitoring is not supported in clusters running Kubernetes 1.15 or above., badRequest

**Comment by morgante** [comment]
Please post your module config.

You most likely have to specify `monitoring_service = "monitoring.googleapis.com/kubernetes"`.

**Comment by satwik123** [comment]
@morgante I am using below repository module .

https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/9.3.0

**Comment by morgante** [comment]
Right I need your actual module config. What variable/settings you used to invoke...

**Comment by satwik123** [comment]
@morgante I am using below definition file , through which I am passing my variables to module 

module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google"
  version					 = "2.0.1"
  project_id                 = "${var.project_id}"
  name                       = "gke-test-cluster"
  region                     = "us-central1"
  zones                      = ["us-central1-a", "us-central1-b", "us-central1-f"]
  network                    = "${var.vpc_net}"
  subnetwork                 = "${var.subnet}"
  ip_range_pods              = "${var.pod_range}"
  ip_range_services          = "${var.service_range}"
  http_load_balancing        = false
  horizontal_pod_autoscaling = true
  network_policy             = true

  node_pools = [
    {
      name               = "default-node-pool"
      machine_type       = "n1-standard-2"
      min_count          = 1
      max_count          = 100
      local_ssd_count    = 0
      disk_size_gb       = 100
      disk_type          = "pd-standard"
      image_type         = "COS"
      auto_repair        = true
      auto_upgrade       = true
      service_account    = "project-service-account@<PROJECT ID>.iam.gserviceaccount.com"
      preemptible        = false
      initial_node_count = 80
    },
  ]

  node_pools_oauth_scopes = {
    all = []

    default-node-pool = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }

  node_pools_labels = {
    all = {}

    default-node-pool = {
      default-node-pool = true
    }
  }

  node_pools_metadata = {
    all = {}

    default-node-pool = {
      node-pool-metadata-custom-value = "my-node-pool"
    }
  }

  node_pools_tags = {
    all = []

    default-node-pool = [
      "default-node-pool",
    ]
  }
}

**Comment by morgante** [comment]
You're using a very old version of this module. Please upgrade to the latest: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/CHANGELOG.md#930-2020-06-11

**Comment by satwik123** [comment]
@morgante I have one constrain , I can only use terraform version 0.11 not 0.12 , so what's the compatible module version I can use here ? also while using latest module (9.3.0) I am getting bellow error

Error downloading modules: Error loading modules: module gke: Error parsing .terraform/modules/4eac95d2aad2ca59ffd57ec7f3313ae9/terraform-google-kubernetes-engine-9.3.0/auth.tf: At 23:14: Unknown token: 23:14 IDENT google

Also I have one more question , Where I can mention Kubernetes version that need to be installed , as I am not getting any variable where I am passing Kubernetes cluster version , do I need to download the module first & modify the same ? else could you please provide  me private GKE cluster module reference .

**Comment by satwik123** [comment]
@morgante I found the latest module version 3.0.0 compatible with Terraform version  0.11 , but while applying the same , I am getting the same issue as below 

`* google_container_cluster.primary: googleapi: Error 400: Legacy monitoring is not supported in clusters running Kubernetes 1.15 or above., badRequest
`

**Comment by morgante** [comment]
We don't provide any ongoing support for Terraform 0.11, as 0.12 has been out for over a year.

You can try overriding the monitoring service by adding this to your config: `monitoring_service = "monitoring.googleapis.com/kubernetes"`

**Comment by satwik123** [comment]
@morgante I just included "monitoring_service" variable on the code as below & I am getting bellow error now :
`* google_container_cluster.primary: googleapi: Error 400: "logging.googleapis.com/kubernetes" and "monitoring.googleapis.com/kubernetes" can only be set together (was "logging.googleapis.com" and "monitoring.googleapis.com/kubernetes")., badRequest`


```
module "gke" {

  source                     = "terraform-google-modules/kubernetes-engine/google"

  version                    = "3.0.0"

  project_id                 = "${var.project_id}"

  name                       = "${var.cluster_name}"

  region                     = "us-central1"

  zones                      = ["us-central1-a", "us-central1-b", "us-central1-f"]

  network                    = "${var.vpc_net}"

  subnetwork                 = "${var.subnet}"

  ip_range_pods              = "${var.pod_range}"

  ip_range_services          = "${var.service_range}"

  http_load_balancing        = false

  horizontal_pod_autoscaling = false

  network_policy             = false

  monitoring_service         = "monitoring.googleapis.com/kubernetes" 

. . . . . . . . . 
```

**Comment by morgante** [comment]
You can also do `logging_service = "logging.googleapis.com/kubernetes"`.

**Comment by satwik123** [comment]
@morgante Thanks for you help , finally its working now , so tell me one thing **monitoring_service** , **logging_service** are required variables , not optional , so why its not mentioned / updated in README file ?

**Comment by satwik123** [comment]
@morgante  One more question , what are the variables (options) I need to pass to create complete private GKE cluster with "Master authorised networks" range ?
