### ISSUE TITLE
Regression in new module

### ISSUE THREAD

**Issue by WillBeebe** [terraform-google-modules/terraform-google-kubernetes-engine#567]
Hi,

I can't find `null_resource.wait_for_cluster` anywhere in the source code. It looks like it was there before, but when trying to use this module from the master branch the outputs that depend on this fail.

`null_resource.wait_for_cluster.id`

**Comment by morgante** [comment]
It's been moved to this module: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/cluster.tf#L252

But I'm not sure why the output isn't failing. That should've failed tests.

**Comment by bharathkkb** [comment]
@morgante  Looks like outputs may have never been validated due to an issue in core and hence our tests passed. 
https://github.com/hashicorp/terraform/pull/25261
