### ISSUE TITLE
configure additional firewall rules for a safer-cluster(-update-variant)

### ISSUE THREAD

**Issue by avthart** [terraform-google-modules/terraform-google-kubernetes-engine#569]
It is currently not possible to enable `add_cluster_firewall_rules` and configure additional firewall rules for a safer-cluster(-update-variant). Is this by design?

**Comment by morgante** [comment]
What's the error you get? @Dev25 have you seen this?

**Comment by Dev25** [comment]
Hmm looks like it was never added to `autogen/safer-cluster`, just a oversight. Should be a fairly simple PR to add this in.
