### ISSUE TITLE
Safer cluster with IAP bastion unreachable in a Continuous Deployment Pipeline using Terraform Helm provider

### ISSUE THREAD

**Issue by saranicole** [terraform-google-modules/terraform-google-kubernetes-engine#572]
I'm testing out using the safer cluster with IAP bastion setup in a CD pipeline using the Terraform Helm provider.  Everything provisions fine until it gets to the Terraform Helm provider trying to install a release, then the build fails with "cluster unreachable".

If the cluster is only supposed to be reachable via the bastion, is it even possible for a CD tool (as opposed to running Terraform from a local machine) to access it to provision it with Helm?  If so, how?  I don't think the unreachable error is due to auth since I used the GKE Auth module with the "token" output which didn't make any difference.

**Comment by bharathkkb** [comment]
Hi @saranicole 
If I am understanding correctly, you are setting up the safer cluster with IAP bastion and then using the TF Helm to install a release. 

In that case the recommended approach would be to make sure that the IP address of the runner VM running the CD workflow has access [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/796bd15a3b7ddc6c57bc63698cd446b5b8e47df8/examples/safer_cluster_iap_bastion/cluster.tf#L28). More docs on private cluster connectivity [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/private_clusters.md#private-cluster-endpoints). I think it would be a great idea to have a parameter to concat, so feel free to submit a PR.

Another way to do this would be to open an ssh tunnel after you have completed the  safer cluster with IAP bastion setup and in the next CD stage configure the proxy like in #550, but I think the approach above is cleaner.

**Comment by saranicole** [comment]
Hi @bharathkkb 
Great, that helps a lot.  Running this on Gitlab may be an option then as Gitlab exposes "CI_SERVER_HOST" as an environment variable.  There would still have to be something doing the translation to an IP though.  Would you envision the parameter as a list of host ips like "extra_host_ips"?

**Comment by bharathkkb** [comment]
@saranicole you can also do a CIDR range instead of an IP like [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/796bd15a3b7ddc6c57bc63698cd446b5b8e47df8/examples/safer_cluster/main.tf#L53).  I think a list of objects like we do here https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/796bd15a3b7ddc6c57bc63698cd446b5b8e47df8/variables.tf#L75
seems reasonable. And we can concat with the bastion CIDR for this setup. @morgante WDYT?

**Comment by morgante** [comment]
Adding the bastion CIDR makes sense.

**Comment by saranicole** [comment]
I realized this is a bit of a chicken and egg problem because the Terraform plan is failing due to "Kubernetes cluster unreachable" ahead of the apply which would add the runner's IP to the cluster.  Without being able to add the runner's ip ahead of time the runner will fail in its initial check of trying to access the cluster.

Unless this is something I'm missing with kubeconfig I think I'm stuck with a public endpoint.

**Comment by saranicole** [comment]
Unfortunately this looks like a bigger problem than just kubeconfig, in that the managed SaaS service can't reach the internal network that the pods are sitting in, regardless of whether the IP address is added to master authorized networks.  It seems like this simply can't be done with the setup I'm looking for, so I am left with either settling for a public cluster or self-hosting a CD solution that can sit inside the cluster's network.

I'll leave this open a while longer in case anyone has insights into how others solved this problem.

**Comment by morgante** [comment]
@saranicole Where are you attempting to deploy from? For a private cluster, it will need to be somewhere in your private network (on-prem or in GCP), but not over public IP space.

**Comment by bharathkkb** [comment]
@saranicole We also have some documentation [here](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#req_res_lim) w.r.t limitations and different configurations of private clusters.

**Comment by saranicole** [comment]
@morgante @bharathkkb  I thought I could have a public endpoint with a private cluster and deploy from Terraform Cloud, but this configuration evidently doesn't work.

I will pursue the self-hosted CD solution (Jenkins probably).  Thanks for the help!

**Comment by karlkfi** [comment]
> I thought I could have a public endpoint with a private cluster 

For posterity (@saranicole): public GKE clusters have both public and private IPs. You can use either or both. Inside the cluster the private IP is advertised via KubeDNS. One gotcha is that “gcloud container clusters get-credentials” will always configure kubeconfig with the public IP on a public cluster, but you can update the kubeconfig afterwards to point to the private IP if you want. 

Also note: you can’t switch between public and not-public clusters without recreate, but you can just always deploy public clusters with an empty master authorized network list. Then it’s effectively firewalled publicly until you need to open it for an exemption.
