### ISSUE TITLE
Services in Binary Authorization modules

### ISSUE THREAD

**Issue by imrannayer** [terraform-google-modules/terraform-google-kubernetes-engine#575]
Binary authorization module is enabling needed services in project with following two parameters using default value true:

disable_services_on_destroy
disable_dependent_services

This will cause problem if there are other attestors in same project. Is it possible to change the code in 
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/binary-authorization/main.tf

**from:**

```
module "project-services" {
  source  = "terraform-google-modules/project-factory/google//modules/project_services"
  version = "~> 8.0"

  project_id = var.project_id

  activate_apis = local.required_enabled_apis
}

```
**To:**

```
module "project-services" {
  source  = "terraform-google-modules/project-factory/google//modules/project_services"
  version = "~> 8.0"

  project_id = var.project_id
  activate_apis = local.required_enabled_apis
  disable_services_on_destroy = false
  disable_dependent_services  = false
} 
```

**Comment by morgante** [comment]
Yes I think that's a good idea, happy to accept a PR.
