### ISSUE TITLE
Unable to use terraform data resource as ssh_auth_key value

### ISSUE THREAD

**Issue by dpatrick** [terraform-google-modules/terraform-google-kubernetes-engine#576]
Hi!

I'm in the market to use the Config Sync (9.3.0) submodule with my clusters and I want to be able to pull an ssh key from Google secrets manager in the terraform plan (via the `google_secret_manager_secret_version` data resource). Right now, it looks like the module forces the input to be a file on the local system. 

Does anyone have any suggestions on how to accomplish this? Or would this need a change in the modules to be supported

**Comment by morgante** [comment]
The `ssh_auth_key` variable is actually the key value, not the path. So this should theoretically work.

**Comment by dpatrick** [comment]
Sorry, I forgot to add the error output I got. When I ran `terraform plan` I got...
```
error: Error in function call

  on .terraform/modules/config_sync/terraform-google-kubernetes-engine-9.3.0/modules/k8s-operator-crd-support/main.tf line 21, in locals:
  21:   private_key              = var.create_ssh_key && var.ssh_auth_key == null ? tls_private_key.k8sop_creds[0].private_key_pem : file(var.ssh_auth_key)
    |----------------
| var.ssh_auth_key is "SCRUBBED TO NOT SHARE KEY"
```

**Comment by morgante** [comment]
Looks like we had a regression! We should be accepting the key contents, not running `file(` around it. Happy to accept a PR.
