### ISSUE TITLE
How to enable master global access

### ISSUE THREAD

**Issue by SrikantPatil88** [terraform-google-modules/terraform-google-kubernetes-engine#579]
Hi Folks,

I want to enable master global access in a cluster, I checked the code but couldn't find the input to enable master_global_access.

Can someone please help me to add this in configuration.

Thanks in advance

**Comment by morgante** [comment]
We will need to add master_global_access config to the module:
https://www.terraform.io/docs/providers/google/r/container_cluster.html#master_global_access_config

Happy to review a PR.

**Comment by SrikantPatil88** [comment]
Hi Morgante,

Sorry if i am not understanding correctly,

I can add the changes and push a new branch or you guys will push the code in the master branch?
I tried but i do not have permission to push the code.

May be below changes need to be added or please correct,

File: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/v6.1.1/modules/beta-private-cluster/cluster.tf

-->
dynamic "private_cluster_config" {
    for_each = var.enable_private_nodes ? [{
      enable_private_nodes        = var.enable_private_nodes,
      enable_private_endpoint     = var.enable_private_endpoint
      master_ipv4_cidr_block      = var.master_ipv4_cidr_block
    }] : []

    content {
      enable_private_endpoint = private_cluster_config.value.enable_private_endpoint
      enable_private_nodes    = private_cluster_config.value.enable_private_nodes
      master_ipv4_cidr_block  = private_cluster_config.value.master_ipv4_cidr_block
       dynamic "master_global_access_config" {
           for_each = var.master_global_access_config
             content {
               enabled   = master_global_access_config.value.enabled
        }
      }
    }
  }
#####################
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/v6.1.1/modules/beta-private-cluster/variables.tf

-->
variable "master_global_access_config" {
  type        = list(object({ enabled = bool }))
  description = "enabled - Enable the cluster master  globally or not."

  default = [{
    "enabled" = true
  }]
}

Please let me know if the code is not okay and process to get access to upload the changes and raise PR.

Thanks You

**Comment by morgante** [comment]
@SrikantPatil88 Please see the [contributing guide](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/CONTRIBUTING.md) and [forking](https://gist.github.com/Chaser324/ce0505fbed06b947d962).

**Comment by SrikantPatil88** [comment]
Hi Morgante,

Thanks for providing the information.

Actually i do not have testing environment now, will have to set up and follow the guide to test and raise PR.

Thanks,
