### ISSUE TITLE
git-creds secret created with additional character when using config sync module

### ISSUE THREAD

**Issue by dpatrick** [terraform-google-modules/terraform-google-kubernetes-engine#580]
Hello again,

I'm running into a strange bug and I can't seem to track down exactly what is causing it. When I create the config sync module using a custom value for `ssh_auth_key`, the terraform successfully completes, however in the cluster the `git-creds` secret that is created isn't identical the value I inject.

After decoding the secret's value from the cluster, I found that at the very end of the secret, the module has added a `%` character. This is causing problems with config sync since the credentials it is provided don't match the key necessary to clone from my git repo. 

I've uninstalled and reinstalled the module and reproduced this behavior. I also went a step further and looked at the terraform state file. In the state file for the `module.config_sync.module.configsync_operator.module.k8sop_creds_secret` object, the extra character is not present in the provisioner command. My instinct at this point is telling me the problem might be with the gcloud terraform module that this uses to create the kubernetes secret.

Any help or guidance would be greatly appreciated!

* Config Sync Module Version 9.4.0

**Comment by bharathkkb** [comment]
I took a quick look [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/4b3f60985ac90265c79a4c5378f8a688f642de96/modules/k8s-operator-crd-support/main.tf#L72) but didnt notice anything out of the ordinary. 
@morgante any ideas? Also is there a reason why we dont  [use the native k8s secret resource ](kubernetes_secret)?

**Comment by morgante** [comment]
I suspect the wrapper script might be injecting it accidentally.

I agree we should probably just switch over to the native secret resource.

**Comment by dpatrick** [comment]
Hi folks!

I was about to take a look at converting this to use the native k8s secret object instead of the wrapper script, but wanted to check in and make sure that solution is still the suggested way of handling this.

**Comment by morgante** [comment]
I think using the native k8s object is probably still a good idea. Happy to look at a PR!

**Comment by dpatrick** [comment]
So I started work to make this a native secret object. But in my testing, that actually didn't resolve the problem. The secret is still created with the added character at the end. I'm not sure how to proceed at this point, or where the problem could be coming from.

**Comment by morgante** [comment]
How are you injecting the `ssh_auth_key` value? You might want to test adding an output which reflects it back, because i suspect your issue might be coming from outside the module code.

**Comment by dpatrick** [comment]
I did another test in which I allowed the module to create the tls secret, which did succeed. I then took the values from the keypair that the module generated, and updated my repo and terraform to manually use that keypair. Once again, the secret was created with the additional character at the end.

I've been injecting the private key two ways in my testing. First as literal string in the terraform file. And (the ultimate solution) pulling from a terraform data resource which references google secrets manager. Both ways it ends up with the extra character on the cluster. 

`ssh_auth_key   = data.google_secret_manager_secret_version.config-sync-key.secret_data`

```
data "google_secret_manager_secret_version" "config-sync-key" {
  project = "blah"
  secret  = "gke-config-sync-private-key"
}
```

**Comment by morgante** [comment]
If you add an output, is the extra character there?

```
output "secret" {
  value = data.google_secret_manager_secret_version.config-sync-key.secret_data
}
```

**Comment by dpatrick** [comment]
When I do that, the output does not have the extra `%` at the end

**Comment by dpatrick** [comment]
Alright. So as a final test to try and eliminate potential pain points... I took the setup completely out of the module. I ran the following terraform file

```
resource "kubernetes_secret" "k8sop_creds_secret" {
  metadata {
    name = "git-creds"
    namespace = "default"
  }
  type = "Opaque"
  data = {
    "ssh" = (data.google_secret_manager_secret_version.config-sync-key.secret_data)
  }
}

data "google_secret_manager_secret_version" "config-sync-key" {
  project = "blah"
  secret  = "gke-config-sync-private-key"
}

provider "google" {
  version = "~> 3.32.0"
  project = "blah"
}

provider "kubernetes" {
  version                = "~> 1.10, != 1.11.0"
  load_config_file       = true
}

output "secret" {
  value = data.google_secret_manager_secret_version.config-sync-key.secret_data
}
```

And the secret was still created in the cluster with the extra character added to the end (while the output was still the correct value that it should be) Any tips on where to go from here? It's definitely not a problem with this module at this point.

**Comment by morgante** [comment]
Thanks for investigating further. Unfortunately it does seem like this probably isn't a module issue at this point, so I'm going to close.

My recommendation would be to investigate further to see if this issue also occurs if you use `kubectl` to directly create the secret (outside Terraform). At that point, it seems plausible that this might be an issue with your secret encoding process.

**Comment by dpatrick** [comment]
I appreciate all of your help in trying to work through this. I finally found that the issue was not having a newline at the end of the manually supplied cert value. 🤦

**Comment by morgante** [comment]
@dpatrick Glad you got it working!
