### ISSUE TITLE
Can not get Load Balancer's address

### ISSUE THREAD

**Issue by rkarpuzov** [terraform-google-modules/terraform-google-kubernetes-engine#583]
Hello,
I am trying to use the GKE module for testing purposes as-is in the example docs. But both of module.gke.endpoint and data.google_container_cluster.testcluster.endpoint return same IP, which I can not use it. 
I must log into the GKE console and get it on hand -> My project -> Kubernetes Engine -> services and Ingress -> the terraform-example's endoint in the table

BR,
Rossen

**Comment by morgante** [comment]
Hi, this module doesn't deploy a load balancer so getting the address would be out of scope.
