### ISSUE TITLE
Unable to create GKE Nodepool with windows LTSC nodepool as image_type

### ISSUE THREAD

**Issue by HarshalRane23** [terraform-google-modules/terraform-google-kubernetes-engine#587]
In GKE, I am unable to create windows nodepool with windows LTSC as image type even though i have the required COS image_type nodepool already present for it. Below is the error msg
Error: error creating NodePool: googleapi: Error 400: Shielded Instance features are only supported on node using COS, COS_CONTAINERD, UBUNTU or UBUNTU_CONTAINERD image type., badRequest
<img width="998" alt="Screenshot 2020-07-05 at 10 49 02 PM" src="https://user-images.githubusercontent.com/24963384/86538733-6b155500-bf15-11ea-9b67-7f08d532fe81.png">

**Comment by morgante** [comment]
Set `enable_shielded_nodes = false`.

**Comment by HarshalRane23** [comment]
Ok let me try.

**Comment by abdelhegazi** [comment]
@HarshalRane23 provisioning a cluster with windows node_pool requires at least one more linux node_pool for other critical services like controllers, DNS, kubeproxy ..etc

This is your issue, you seem to have only one item in your pools list you  need to add one more with linux see example below:

```
  node_pools = [
    {
      name               = "linux-node-pool"
      machine_type       = var.nodepool_instance_type
      min_count          = 1
      max_count          = 10
      disk_size_gb       = 100
      disk_type          = "pd-standard"
      image_type         = "COS"                                  
      auto_repair        = true                                   
      auto_upgrade       = true                                 
      service_account    = google_service_account.gke_cluster_sa.email
      preemptible        = var.preemptible
      initial_node_count = 1
    },
    {
      name               = "windows-node-pool"
      machine_type       = var.nodepool_instance_type
      min_count          = 1
      max_count          = 10
      disk_size_gb       = 100
      disk_type          = "pd-standard"
      image_type         = "WINDOWS_LTSC"
      auto_repair        = true                                   
      auto_upgrade       = true                                   
      service_account    = google_service_account.gke_cluster_sa.email
      preemptible        = var.preemptible
      initial_node_count = 1
  
    }
  ]

```

**Comment by morgante** [comment]
@HarshalRane23 Did the above suggestion help?

**Comment by abdelhegazi** [comment]
if it helps, I had lots of issues provisioning a cluster with windows node_pools, follow  this issue up https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/632  I got my issue resolved at the end it was similar to yours

**Comment by HarshalRane23** [comment]
@morgante @abdelhegazi  Apologies for the delayed response, lost this mail that issue was resolved on 8th July only.
` shielded_instance_config { 
               enable_integrity_monitoring = false,
               enable_secure_boot          = false 
            }` 
The issue was with **shielded_instance_config** Windows node does not support these features. so I disabled it and it worked as expected.
I have the code ready so in the future, no faces this issue while deploying windows node in GKE using terraform, Let me a good repository to share my working code, I am happy to share the code

**Comment by morgante** [comment]
@HarshalRane23 If you're able to contribute it as an example (in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples), that could certainly be helpful.

Closing this issue since the underlying issue was solved.
