### ISSUE TITLE
Issue with IpAllocationPolicy

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#593]
Tests are showing this:

```
       Error: googleapi: Error 400: DefaultMaxPodsConstraint can only be used if IpAllocationPolicy.UseIpAliases is true., badRequest
       
         on ../../../modules/beta-public-cluster/cluster.tf line 22, in resource "google_container_cluster" "primary":
         22: resource "google_container_cluster" "primary" {
```

Possibly related to https://github.com/terraform-providers/terraform-provider-google/issues/6744.

**Comment by SamwelOpiyo** [comment]
I am getting the same error with module `git::https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git//modules/beta-public-cluster?ref=v9.4.0`. It was working before for another cluster just a few days ago. Looks like I will need to downgrade the provider.

**Comment by SamwelOpiyo** [comment]
Adding the required providers block to the parent `versions.tf` file solved the issue:

```
terraform {
  ...

  required_providers {
    google-beta = ">= 3.23.0, <4.0.0, != 3.29.0"
  }
}
```
