### ISSUE TITLE
ASM Module Fails to destroy

### ISSUE THREAD

**Issue by PsychoSid** [terraform-google-modules/terraform-google-kubernetes-engine#604]
Hi,

When trying to destroy a GKE cluster setup with ASM the destroy will fail with:-

```
Error: Error running command 'PATH=<mypath>/.terraform/modules/asm.asm_install/terraform-google-gcloud-1.1.1/cache/94f77b98/google-cloud-sdk/bin:$PATH
.terraform/modules/asm/terraform-google-kubernetes-engine-10.0.0/modules/asm/scripts/kubectl_wrapper.sh https://<IP> <token-removed> kubectl delete ns istio-system
': exit status 1. Output:   -Dd, --decode   decodes input
W0716 13:55:11.407977   22416 loader.go:223] Config not found: /tmp/kubectl_wrapper_9336_20830/config
W0716 13:55:11.408498   22416 loader.go:223] Config not found: /tmp/kubectl_wrapper_9336_20830/config
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

I know I am logged in locally and can access the k8s API / gCloud etc.

This leaves the terraform state in a bad way and I have to manually delete the resources and the state file.

Any ideas ?

Thanks

**Comment by morgante** [comment]
@bharathkkb PTAL

**Comment by bharathkkb** [comment]
@PsychoSid I believe this is happening due to the `destroy_cmd_body` caching the old `data.google_client_config.default.access_token`.  I have set up a cluster to test for reproduction and will update here.
Additionally, I will be trying out this approach which should eliminate this problem.
