### ISSUE TITLE
Create an Anthos Hub submodule

### ISSUE THREAD

**Issue by cgrant** [terraform-google-modules/terraform-google-kubernetes-engine#605]
Suggest extracting out the [Anthos Hub Registration](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/asm/main.tf#L67-L83) section into its own module so it can be used after the cluster creation and thus be enabled for both ASM and ACM modules. 

The general flow for Anthos is:
- Provision a cluster
- Register it with Anthos Hub
- Enable Features (any)
  - ACM
  - ASM
  - Ingress
  ...

**Comment by PsychoSid** [comment]
Hi,

This would be very good for my use case where I am building cluster(s) with ASM, and ACM right now it would provide a little more structure.

Thanks.

**Comment by bharathkkb** [comment]
fixed via #611 and removed from ASM in #665
