### ISSUE TITLE
Disable maintenance_start_time

### ISSUE THREAD

**Issue by debek** [terraform-google-modules/terraform-google-kubernetes-engine#607]
How can I disable maintenance? The empty field doesn't work.

**Comment by bharathkkb** [comment]
This is a limitation with the way we are defining the `maintenance_policy` block today
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/8a9f9041c8f18ff7a873873e9b19e03dcdfe7d2a/autogen/main/cluster.tf.tmpl#L182. Once `maintenance_policy` block is defined, it need `daily_maintenance_window` for GA or one of `daily_maintenance_window` or `recurring_window` for beta. 

@morgante thoughts on making the`maintenance_policy` a nested dynamic block? We can check if `maintenance_policy` block needs to be created before creating  inner `daily_maintenance_window` or `recurring_window`.

**Comment by morgante** [comment]
The maintenance window simply controls *when* maintenance occurs, not if it occurs.

If you want to avoid/minimize maintenance you should disable auto-upgrade and other such functionality. More info here: https://cloud.google.com/kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions
