### ISSUE TITLE
[question] How to correctly set ip_pod_ranges and ip_service_ranges

### ISSUE THREAD

**Issue by miguelvr** [terraform-google-modules/terraform-google-kubernetes-engine#610]
Hello,

From the documentation, it's not clear how to set up the required variables `ip_pod_ranges` and `ip_services_ranges`

I'm a total noob when it comes to networking, but I've been trying to figure out how to make a setup equivalent to the default in the GCP console.

I've set both the `network` and `subnetwork` values to "default", to mimic the GCP console values but I can't figure out how to set the IP ranges.

Can someone help me out?

Thanks!

**Comment by cgrant** [comment]
Try empty vars
```
ip_range_pods       = ""
ip_range_services   = ""
```

**Comment by morgante** [comment]
For this module. our best practice is to explicitly manage the secondary ranges. You should add secondary ranges to your default subnet and add their name in here.

More details in the docs: https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips#range_management

**Comment by miguelvr** [comment]
@cgrant that works! thanks!

@morgante in the link you sent, the first thing that appears is a managed option by Google, which determines the ranges for you. For me, this would be ideal as I don't really want to be managing my cluster's network. Is there a strong reason for not setting the ranges as empty?

**Comment by morgante** [comment]
@miguelvr Our recommendation when using Terraform is to model your infrastructure comprehensively, if you leave it to Google to allocate then you don't have control over which ranges are being used.

Since it's working for you, it's fine to leave as-is though.
