### ISSUE TITLE
dns_cache_config gives error: Blocks of type "dns_cache_config" are not expected here.

### ISSUE THREAD

**Issue by pravargauba** [terraform-google-modules/terraform-google-kubernetes-engine#619]
This is very strange. In the addons_config block if I add dns_cache_config it gives the error that the block is not expected here, while other add on configs seems to be working fine.
```
  addons_config {
    http_load_balancing {
      disabled = false
    }

    dns_cache_config {
      enabled = var.dns_cache
    }

    horizontal_pod_autoscaling {
      disabled = true
    }
  }
```
The above fails with below error.
```
Pravar-Gauba:terraform_gke_cluster pravargauba$ terraform plan

Error: Unsupported block type

  on main.tf line 40, in resource "google_container_cluster" "gke_cluster":
  40:     dns_cache_config {

Blocks of type "dns_cache_config" are not expected here.
```

However if I do, 
```
  addons_config {
    http_load_balancing {
      disabled = false
    }

    horizontal_pod_autoscaling {
      disabled = true
    }
  }
```
This seems to be working fine. Indentation/syntax everything is correct, not so sure where the problem is.
Its been a day I am wrapping my head around it but not leading to any conclusion. Please help.
@bharathkkb

**Comment by bharathkkb** [comment]
Hi @pravargauba 

It looks like you are using the native resource and not this module. If you were using one of the [beta](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/beta-public-cluster), you can set `dns_cache = true`. Additionally, I would confirm that you are using the [beta provider](https://www.terraform.io/docs/providers/google/guides/provider_versions.html#using-the-google-beta-provider) and [a version <](https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/CHANGELOG.md#3140-march-23-2020) `3.14.0`

**Comment by pravargauba** [comment]
Hi @bharathkkb 
Thanks for the response. `3.14 `version gets it all working. Was using a previous version of terraform google beta provider.
