### ISSUE TITLE
errors downloading ASM module

### ISSUE THREAD

**Issue by sp185503** [terraform-google-modules/terraform-google-kubernetes-engine#623]
Hi,

I'm getting the following errors when I tried to use the ASM module...I also tried pinning it to v10.0.0 but got the same error.

**Error:**

```
Error: Failed to download module

Could not download module "asm-asm-conf-us-central1-1" (main.tf:243) source
code from
"https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/archive/v11.0.0.tar.gz//*?archive=tar.gz":
bad response code: 404.

```

**main.tf**
```
module "asm-asm-conf-us-central1-1" {
  source           = "terraform-google-modules/kubernetes-engine/google//modules/asm"

  project_id       = var.project_name
  cluster_name     = module.asm-conf-us-central1-1.gke-name
  location         = module.asm-conf-us-central1-1.location
  cluster_endpoint = module.asm-conf-us-central1-1.endpoint
}
```

**Comment by bharathkkb** [comment]
Hi @sp185503 
This might be an issue on your end, I just tried a quick `init` with your snippet which worked for me. 
![image](https://user-images.githubusercontent.com/10992720/89824993-8b8a8d80-db19-11ea-89d3-6e076b737188.png)

**Comment by sp185503** [comment]
@bharathkkb Sorry for wasting your time.....it was an issue on my end.  I was trying to fix my git profile to address some other issue and must of goofed something else up.

Thanks!
