### ISSUE TITLE
Disable Default SNAT

### ISSUE THREAD

**Issue by zioproto** [terraform-google-modules/terraform-google-kubernetes-engine#624]
This is a feature request to support the `Disable Default SNAT` option.

![Screenshot 2020-08-12 at 12 22 07](https://user-images.githubusercontent.com/789701/90004808-91f24400-dc96-11ea-8a0a-3d0d8fd524f9.png)

The support in the Terraform Provider has been already merged:
https://github.com/GoogleCloudPlatform/magic-modules/pull/3758

**Comment by bharathkkb** [comment]
Happy to review a PR for this. An example PR adding something similar: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/528
