### ISSUE TITLE
master_global_access_config is going to be applied each run

### ISSUE THREAD

**Issue by m0ps** [terraform-google-modules/terraform-google-kubernetes-engine#629]
master_global_access_config is going to be applied during each terraform run
```
      ~ private_cluster_config {
            enable_private_endpoint = true
            enable_private_nodes    = true
            master_ipv4_cidr_block  = "XXX.XXX.XXX.XXX/28"
            peering_name            = "gke-XXXXXXXXXXXXX-XXXX-XXXX-peer"
            private_endpoint        = "XXX.XXX.XXX.XXX"
            public_endpoint         = "XXX.XXX.XXX.XXX."

          + master_global_access_config {
              + enabled = true
            }
        }
```
It was introduced in v11.0 release.

The same issue was with pod_security_policy_config, but it was fixed in v10.0 release (https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/commit/6069ece9cd12acbbba8ff16ab0cbc9b17bc47985)

**Comment by morgante** [comment]
What configuration are you using?

**Comment by m0ps** [comment]
I didn't define this option in my configuration, it enabled by default.

**Comment by morgante** [comment]
Hmm it looks like this is actually a provider issue since I don't see any issue with the block we're generating. Please file an issue there: https://github.com/hashicorp/terraform-provider-google/issues

**Comment by morgante** [comment]
As a workaround, you can disable master global access with `master_global_access_enabled = false`.

**Comment by bharathkkb** [comment]
I think there might be a bug based on my spot check. Toggling `master_global_access_enabled = false` after initially creating does not actually make it false. I will dig into later to confirm but it does seem like a provider issue.

**Comment by caarlos0** [comment]
same here with 11.1.0... any workarounds?
