### ISSUE TITLE
Document GKE/K8s version compatibility

### ISSUE THREAD

**Issue by starkenburgs** [terraform-google-modules/terraform-google-kubernetes-engine#634]
If there are any compatibility restrictions between versions of the modules and version of GKE/K8s (or lack of restrictions) in the Compatibility section of the README, in order help avoid any ambiguity.

 https://github.com/terraform-google-modules/terraform-google-kubernetes-engine#compatibility

**Comment by morgante** [comment]
There are no restrictions, we will add them if there are.

**Comment by bharathkkb** [comment]
Restrictions if any will be documented. Closing this as I am not aware of any that needs to be documented.
