### ISSUE TITLE
has no vertical pod autoscaling

### ISSUE THREAD

**Issue by kolesnikovIV** [terraform-google-modules/terraform-google-kubernetes-engine#643]
current module has no vertical pod autoscaling support, but Terraform has, let's add.
https://www.terraform.io/docs/providers/google/r/container_cluster.html#vertical_pod_autoscaling
Here is my PR.
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/642

**Comment by bharathkkb** [comment]
vpa support added via https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/758
