### ISSUE TITLE
Promote previously beta features to GA modules

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-kubernetes-engine#644]
Quite a few beta features are now GA and we should enable these in our GA modules.
TODO:
- release_channel https://github.com/hashicorp/terraform-provider-google/pull/6955
- database_encryption https://github.com/terraform-providers/terraform-provider-google/pull/6757
- workload_identity_config https://github.com/hashicorp/terraform-provider-google/pull/6490
- enable_shielded_nodes https://github.com/terraform-providers/terraform-provider-google/pull/6303
- node_locations
- enable_binary_authorization

**Comment by mik-laj** [comment]
+1

**Comment by edwardday7** [comment]
+1 Would love the workload identity features without having to use the beta module since it's GA now.
