### ISSUE TITLE
[bug] enable_gke_hub_registration variable not respected in asm module

### ISSUE THREAD

**Issue by cloud-pharaoh** [terraform-google-modules/terraform-google-kubernetes-engine#661]
#611 introduced an issue where the enable_gke_hub_registration variable is no longer respected and the ASM module will try to register the cluster even when set to false.

I have 2 solutions:
1. Less elegant but compatible with 0.12
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/compare/master...CloudPharaoh:hub_enable_asm?expand=1

2. Requires 0.13
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/compare/master...CloudPharaoh:hub_enable_asm_13?expand=1

**Comment by cloud-pharaoh** [comment]
@bharathkkb can you take a look at these solutions and let me know which one to submit PR for.

**Comment by morgante** [comment]
We're not ready to require 0.13, so your first approach is probably better.

**Comment by bharathkkb** [comment]
Hi @cloud-pharaoh 
We can remove GKE hub from ASM. If users want they can now use the hub submodule directly. There is some context here #611

**Comment by bharathkkb** [comment]
fixed by #665
