### ISSUE TITLE
Best way to do Anthos GKE Cluster with ASM / ACM

### ISSUE THREAD

**Issue by PsychoSid** [terraform-google-modules/terraform-google-kubernetes-engine#663]
Hi,

Looking for any "best" way of applying this as I have tried various ways but am getting issues such as [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/626)

If I use GKE/Hub/ASM/ACM modules I get duplicate SA accounts (as this hub membership is still in ASM)

With Policy Controller / Gatekeeper enabled I get issues with the ASM parts against the gatekeeper validating webhook for example.

Trying to set module dependencies with TF13 doesn't work due to local count issues.

So just trying to pull all this together into a one-shot pass if anyone has any ideas on how 👍 

Many thanks.

**Comment by bharathkkb** [comment]
Hi @PsychoSid 

> getting issues such as [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/626)

I have not had a chance yet, but I will add a check to kubectl module as [discussed here
](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/626#issuecomment-677423005)
> If I use GKE/Hub/ASM/ACM modules I get duplicate SA accounts (as this hub membership is still in ASM)

Now that we have the hub submodule, we are looking to remove it from ASM https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/661

> Policy Controller / Gatekeeper enabled I get issues with the ASM parts against the gatekeeper validating webhook


Could you expand a bit more on this?

> Trying to set module dependencies with TF13 doesn't work due to local count issues.

Is this a known TF13 issue? Is the error `Invalid count argument`?

**Comment by gfthybridlabs** [comment]
Hi,

Thanks for this, appreciate the help.

1. Great, thanks again.

2. That would make sense.

3. Not had the time to spin up my test cluster today will do by Monday. It's around the "istio-system" namespace and the webhook. I will get more information. When I do it manually I exclude a bunch of namespaces from Policy Controller / Gatekeeper - this is one of them !

4. That's exactly it.

I will get more info on point 3 over the weekend.

Cheers.

**Comment by bharathkkb** [comment]
Just an update regarding 4. This should now be fixed https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/664.
