### ISSUE TITLE
"Provider configuration not present" errors after upgrading module version

### ISSUE THREAD

**Issue by NightmareCinema** [terraform-google-modules/terraform-google-kubernetes-engine#668]
terraform version `v0.13.2`

I was trying to upgrade my `beta-private-cluster-update-variant` and `beta-public-cluster-update-variant` from `v10.0.0` to `v11.1.0` and suddenly got hit by the following errors:

```
Error: Provider configuration not present

To work with
module.gcloud_delete_default_kube_dns_configmap.null_resource.module_depends_on[0]
its original provider configuration at
provider["registry.terraform.io/-/null"] is required, but it has been removed.
This occurs when a provider configuration is removed while objects created by
that provider still exist in the state. Re-add the provider configuration to
destroy
module.gcloud_delete_default_kube_dns_configmap.null_resource.module_depends_on[0],
after which you can remove the provider configuration again.


Error: Provider configuration not present

To work with module.gcloud_delete_default_kube_dns_configmap.random_id.cache
its original provider configuration at
provider["registry.terraform.io/-/random"] is required, but it has been
removed. This occurs when a provider configuration is removed while objects
created by that provider still exist in the state. Re-add the provider
configuration to destroy
module.gcloud_delete_default_kube_dns_configmap.random_id.cache, after which
you can remove the provider configuration again.
```

Never had these errors before... would appreciate the life saving help.

**Comment by morgante** [comment]
Can you try adding a `required_providers` block in your Terraform config, as per [this](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations)?

```
terraform {
  required_providers {
    null = {
      source  = "hashicorp/null"
    }
    random = {
      source  = "hashicorp/random"
    }
  }
}
```

**Comment by NightmareCinema** [comment]
> terraform {
>   required_providers {
>     null = {
>       source  = "hashicorp/null"
>     }
>     random = {
>       source  = "hashicorp/random"
>     }
>   }
> }

That didn't seem to help sadly...
I'm curious as to whether am I the only one with `terraform version v0.13.x` dealing with this since I don't see any other complaints about it

**Comment by morgante** [comment]
How about adding a block like this?

```
provider "null" { }
provider "random { }
```

**Comment by NightmareCinema** [comment]
> How about adding a block like this?
> 
> ```
> provider "null" { }
> provider "random { }
> ```
> 
> Also be sure to run `terraform init`.

That works! Many thanks @morgante !
Can this change be made to the module itself though?

**Comment by morgante** [comment]
No, Terraform doesn't encourage including provider configuration directly in modules: https://www.terraform.io/docs/configuration/modules.html#providers-within-modules

**Comment by sreejesh123** [comment]
Similar issue  but error is slightly different. any help would be appreciated .. To work with module.gke.google_container_cluster.primary its original provider
configuration at provider["registry.terraform.io/hashicorp/google-beta"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.gke.google_container_cluster.primary, after which you can remove the
provider configuration again.

**Comment by MaXIP21** [comment]
you can use 
terraform state list

then delete the state by running
terraform state rm
