### ISSUE TITLE
docker_build_terraform make target missing

### ISSUE THREAD

**Issue by czka** [terraform-google-modules/terraform-google-kubernetes-engine#67]
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blame/master/README.md#L251:
> make docker_build_terraform

```
$ make docker_build_terraform
make: *** No rule to make target 'docker_build_terraform'.  Stop.`
```

A missing target in the `Makefile` or a doc error?

**Comment by Jberlinsky** [comment]
@czka Thanks for sending this in. You're correct that we missed updating a line in the README with a recent commit. I'll get this fixed up right away.
