### ISSUE TITLE
Migrate module to terraform 0.13

### ISSUE THREAD

**Issue by ivankorn** [terraform-google-modules/terraform-google-kubernetes-engine#677]
0.13 is here, with `for_each`, `depends_on` for whole modules and custom variables validation.

While `for_each` is more about code cleanup, the vars constraints should really speed-up re-using of the module as we can make API design reflected on vars constraints as well (combinations of variables, possible values etc). 
F.e. [new precise variables validation](https://www.hashicorp.com/blog/custom-variable-validation-in-terraform-0-13) would help with avoiding [such situations](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/675#issuecomment-693737731)

**Comment by bharathkkb** [comment]
+1 I think we will be targeting this sometime late Q4

**Comment by bharathkkb** [comment]
Also on a different note, the variable validation is scoped to the defined variable. I am wondering how we can use that to validate the situation you mentioned above, i.e prevent user from setting both `release_channel` and `auto_upgrade`. I can see this being useful in other modules as well.

**Comment by ivankorn** [comment]
> Also on a different note, the variable validation is scoped to the defined variable. I am wondering how we can use that to validate the situation you mentioned above, i.e prevent user from setting both `release_channel` and `auto_upgrade`. I can see this being useful in other modules as well.

[The new syntax](https://www.hashicorp.com/blog/custom-variable-validation-in-terraform-0-13) allows calling functions within condition of the validation block and even more cool those functions can accept variables as parameters as well. So we should be able to pretty flexible validate vars against other vars.

**Comment by morgante** [comment]
I'm not sure we should "upgrade" to Terraform 0.13 for its own sake (we already _support_ 0.13). Instead I'd like to see any upgrade be tied to direct code or feature enhancements.

**Comment by bharathkkb** [comment]
@morgante yes I believe we were trying to figure out a way to prevent some GKE misconfigs from occurring by using the new validation feature in 0.13.

@ivankorn I meant that we wont be able to validate across two variables. Consider an example like this
```hcl
variable "test_var_1" {
  type        = number
  description = "test var that checks if test_var_1 is greater than 1 and test_var_2 is greater than 2"

  validation {
    condition     = var.test_var_2 > 2 && var.test_var_1 > 1
    error_message = "Oops either test_var_1 is less than 1 or test_var_2 is less than 2."
  }
}
variable "test_var_2" {
  type        = number
  description = "a number greater than 2"
}
```
this throws an error
```

Error: Invalid reference in variable validation

  on test.tf line 6, in variable "test_var_1":
   6:     condition     = var.test_var_2 > 2 && var.test_var_1 > 1

The condition for variable "test_var_1" can only refer to the variable itself,
using var.test_var_1.
```
In our case here we would need both the `var. release_channel` and `var. auto_upgrade` to make a validation, right?

**Comment by DeviaVir** [comment]
Wanted to leave a note here that it looks like this module does not support Terraform 0.13's count as it currently stands:

```
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Module does not support count

  on us.tf line 29, in module "gke":
  29:   count = local.create_us

Module "gke" cannot be used with count because it contains a nested
provider configuration for "kubernetes", at
.terraform/modules/gke/modules/beta-private-cluster/auth.tf:29,10-22.

This module can be made compatible with count by changing it to receive all of
its provider configurations from the calling module, by using the "providers"
argument in the calling module block.
```

Documentation: https://www.terraform.io/docs/configuration/modules.html#legacy-shared-modules-with-provider-configurations

As far as I am able to interpret, we need to replace/remove the `kubernetes` provider configuration out of the module and make sure it is passed by the passing module.. which seems hard to do in this case as the provider configuration is based on the module.

**Comment by xingao267** [comment]
> Wanted to leave a note here that it looks like this module does not support Terraform 0.13's count as it currently stands:
> 
> ```
> The Terraform configuration must be valid before initialization so that
> Terraform can determine which modules and providers need to be installed.
> 
> Error: Module does not support count
> 
>   on us.tf line 29, in module "gke":
>   29:   count = local.create_us
> 
> Module "gke" cannot be used with count because it contains a nested
> provider configuration for "kubernetes", at
> .terraform/modules/gke/modules/beta-private-cluster/auth.tf:29,10-22.
> 
> This module can be made compatible with count by changing it to receive all of
> its provider configurations from the calling module, by using the "providers"
> argument in the calling module block.
> ```
> 
> Documentation: https://www.terraform.io/docs/configuration/modules.html#legacy-shared-modules-with-provider-configurations
> 
> As far as I am able to interpret, we need to replace/remove the `kubernetes` provider configuration out of the module and make sure it is passed by the passing module.. which seems hard to do in this case as the provider configuration is based on the module.

I'm seeing the same issue with `depends_on`.
