### ISSUE TITLE
Change Machine Type of Default Node Pool

### ISSUE THREAD

**Issue by adhil0** [terraform-google-modules/terraform-google-kubernetes-engine#680]
Is there a way to change the machine type of the default node pool using this module, like you can using the `google_container_cluster` Terraform resource? Ex: 
``` 
resource "google_container_cluster" "primary" {
  name                     = "${var.project_id}-gke"
  location                 = var.zone
  remove_default_node_pool = false
  node_config {
    machine_type = var.default_machine_type 
  }
```
Or am I better off creating a new node pool?

**Comment by morgante** [comment]
Our recommended practice is that you make a separate node pool (using the `node_pools` variable) and explicitly manage that instead.
