### ISSUE TITLE
ASM module add set gcloud.project.environProjectNumber

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-kubernetes-engine#683]
ASM install now has an additional command `kpt cfg set asm gcloud.project.environProjectNumber ${ENVIRON_PROJECT_NUMBER}` that needs to added in script

**Comment by therealmitchconnors** [comment]
Can we escalate this above P2?  This is a hard blocker for using Terraform to install ASM.

**Comment by morgante** [comment]
@bharathkkb Could you PTAL?
