### ISSUE TITLE
GKE ASM Module - Internal Load Balancer for Istio Gateway

### ISSUE THREAD

**Issue by RaccoonDev** [terraform-google-modules/terraform-google-kubernetes-engine#684]
Hi,

Is there a way to configure Istio gateway to be Internal Load Balancer instead of Public Load Balancer?

The feature is very needed to protect the resources from being publicly available. If the feature already there, please add that to the configuration.

Best regards,
Dmytro

**Comment by gfthybridlabs** [comment]
I think setting the `cloud.google.com/load-balancer-type` annotation to `"internal"` will do it.

**Comment by bharathkkb** [comment]
Hi @RaccoonDev 
@gfthybridlabs is correct, that annotation should provision an ILB for the gateway. Feel free to reopen if any questions.

**Comment by arctiqaurora** [comment]
can this be an option for asm module?

**Comment by bharathkkb** [comment]
@arctiqaurora I have asked this in an issue were we are revamping the ASM module. Please follow that for updates.
