### ISSUE TITLE
node_locations not working for nodepool

### ISSUE THREAD

**Issue by willcocks** [terraform-google-modules/terraform-google-kubernetes-engine#685]
Seems to ignore what is set, and always creates in all zones.

Need to pin node pool to one zone in multi-zone cluster.

node_locations    = "europe-west3-b"    

results in nodes in a,b,c.

            "node_locations": [
              "europe-west3-a",
              "europe-west3-b",
              "europe-west3-c"
            ],

terraform-google-modules/kubernetes-engine/google 11.1.0

Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/google v3.39.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0

**Comment by morgante** [comment]
Can you try using the beta module? We currently only support setting `node_locations` in the beta modules.

**Comment by willcocks** [comment]
I can confirm that the beta works.

**Comment by bharathkkb** [comment]
This is also now in GA modules via #709 pending release.
