### ISSUE TITLE
How to add tag to nodes

### ISSUE THREAD

**Issue by SrikantPatil88** [terraform-google-modules/terraform-google-kubernetes-engine#686]
Hi Team,

There is some specific requirement in which we want to add network tag to the GKE nodes,
I know its possible in the "node config" but I believe its not available in the code.

Please let me know if it is already available? or need to update the code, if yes then i will raise a pull request for the same.

Thanks,

**Comment by morgante** [comment]
You can configure these using the `node_pools_tags`. Example here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/9d32d18b1c4c44dd0968968d18fa694a23d364bc/examples/node_pool_update_variant_beta/main.tf#L122

**Comment by SrikantPatil88** [comment]
Hi Morgante,

Thank you for the reply.

Just one question, When i update the tag it rebuild node pool, mean service will be down.
Is there any other option to add tags without having downtime or deleting nodes?

Thanks

**Comment by morgante** [comment]
No, nodes cannot have their tags changed without downtime.

If you want to keep your cluster stable, I recommend adding an additional node pool with the new settings then deleting the old node pool once your new pool is stable.

**Comment by SrikantPatil88** [comment]
Thank you @morgante for confirmation.
