### ISSUE TITLE
Feature Request: Add a TF output for the kubeconfig

### ISSUE THREAD

**Issue by tibers** [terraform-google-modules/terraform-google-kubernetes-engine#687]
I want to stand up a GKE cluster and then when we're ready to go - I want terraform to handle the installation of some apps via the helm module: https://registry.terraform.io/providers/hashicorp/helm/latest/docs

To do that, we either need to drop a kubeconfig on the disk somewhere, or feed helm the keys we've dropped somewhere. What I want to avoid doing though is a `local_exec` and just kinda sorta hoping it works. 

```
provider "helm" {
  kubernetes {
    config_path = "/path/to/kube_cluster.yaml"
  }
}
```

```
provider "helm" {
  kubernetes {
    host     = "https://104.196.242.174"
    username = "ClusterMaster"
    password = "MindTheGap"

    client_certificate     = file("~/.kube/client-cert.pem")
    client_key             = file("~/.kube/client-key.pem")
    cluster_ca_certificate = file("~/.kube/cluster-ca-cert.pem")
  }
}
```

**Comment by morgante** [comment]
Check out the auth submodule, it should give you what you need: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/auth
