### ISSUE TITLE
Terraform v0.13.4 defaults to old GKE version v1.15.12-gke.20

### ISSUE THREAD

**Issue by nicoleczhu** [terraform-google-modules/terraform-google-kubernetes-engine#696]
To reproduce: 
1. Install Terraform v0.13.4 with something like: 
```
sudo apt-get install unzip && \
  wget -q https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip -O ./terraform.zip && \
  unzip -o terraform.zip && \
  sudo install terraform /usr/local/bin
```
2. Declare resource "google_container_cluster" "gke"  with provider "google-beta", no other special configs
3. Deploy everything and note that the cluster version is `v1.15.12-gke.20`

Expected: 
It's not clear from documentation which official release channel Terraform defaults to: 
https://cloud.google.com/kubernetes-engine/docs/release-notes

I expected Version 1.16.13-gke.401, given the Oct 2 release notes that: **"Version 1.16.13-gke.401 is the new default version in the Stable channel."**

**Comment by morgante** [comment]
It sounds like you're not using the module. Provider issues should be filed on the provider: https://github.com/hashicorp/terraform-provider-google/issues
