### ISSUE TITLE
Invalid Indexes and 409 issues

### ISSUE THREAD

**Issue by PsychoSid** [terraform-google-modules/terraform-google-kubernetes-engine#697]
Hello,

My daily routine is to bring up my test lab using the modules you provide (thanks).

I run a "terraform init -upgrade" prior to this.

Due to some "RECONCILING" issues I bring up the VPC & GKE initially. Using the "gpc-network" and "gke" modules.

Then after that is up and completed I add the ASM module and "apply" again to register into the hub, and add the Service Mesh - today 2020/10/06 this now decides it needs to recreate the VPC and everything again ? This leads to duplicate problems with the named VPC already existing and 409 errors and a fail.

When just trying to "destroy" using the initial VPC/GKE modules I get the following error now:-
```
module.gke.random_string.cluster_service_account_suffix: Destruction complete after 0s

Error: Invalid index

  on gke.tf line 9, in module "gke":
   9:   subnetwork                  = module.gcp-network.subnets_names[0]
    |----------------
    | module.gcp-network.subnets_names is empty tuple

The given key does not identify an element in this collection value.
```

My code hasn't changed what may be the cause of this any ideas ?

Many thanks.
Paul

**Comment by PsychoSid** [comment]
I wonder if this is related to the changes released in the Google provider https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.42.0 ?

**Comment by PsychoSid** [comment]
Also getting errors like this if I run the VPC/GKE/ASM module together now (still get RECONCILING issues):-
```
Error: Error creating service account: googleapi: Error 409: Service account gke-hub-sa already exists within project projects/gft-anthos-demo., alreadyExists

  on .terraform/modules/asm/modules/hub/main.tf line 24, in resource "google_service_account" "gke_hub_sa":
  24: resource "google_service_account" "gke_hub_sa" {
```

**Comment by PsychoSid** [comment]
Turns out it looks like someone was messing around with the permissions on my GCS bucket for the state :( Sorry.

**Comment by morgante** [comment]
It seems like you might have lost your state somehow as it seems to be attempting to recreate the same infra. Can you try a fresh project (or wipe your state and project)?

**Comment by bharathkkb** [comment]
feel free to reopen if this is still happening. I may need a MCVE to repro and debug
