### ISSUE TITLE
Error: Failed to instantiate provider "google" to obtain schema: Unrecognized remote plugin message:

### ISSUE THREAD

**Issue by Vadims06** [terraform-google-modules/terraform-google-kubernetes-engine#698]
Hi All,

I just wanted to boot up the private GKE cluster using [this ](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/11.1.0/submodules/private-cluster)example, but I got the following errors:
What could be a reason for this? Please kindly help
`Downloading terraform-google-modules/kubernetes-engine/google 11.1.0 for gke...
- gke in .terraform/modules/gke
Downloading terraform-google-modules/gcloud/google 1.4.1 for gke.gcloud_delete_default_kube_dns_configmap...
- gke.gcloud_delete_default_kube_dns_configmap in .terraform/modules/gke.gcloud_delete_default_kube_dns_configmap/modules/kubectl-wrapper
- gke.gcloud_delete_default_kube_dns_configmap.gcloud_kubectl in .terraform/modules/gke.gcloud_delete_default_kube_dns_configmap
Downloading terraform-google-modules/gcloud/google 1.3.0 for gke.gcloud_wait_for_cluster...
- gke.gcloud_wait_for_cluster in .terraform/modules/gke.gcloud_wait_for_cluster

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "external" (hashicorp/external) 1.2.0...
- Downloading plugin for provider "random" (hashicorp/random) 2.3.0...
- Downloading plugin for provider "kubernetes" (hashicorp/kubernetes) 1.13.2...
- Downloading plugin for provider "google" (hashicorp/google) 3.42.0...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

* provider.external: version = "~> 1.2"
* provider.null: version = "~> 2.1"
* provider.random: version = "~> 2.3"

Terraform has been successfully initialized!

bash-4.4# terraform plan

Error: Failed to instantiate provider "external" to obtain schema: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

Error: Failed to instantiate provider "google" to obtain schema: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

Error: Failed to instantiate provider "kubernetes" to obtain schema: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

Error: Failed to instantiate provider "null" to obtain schema: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

Error: Failed to instantiate provider "random" to obtain schema: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

Error: Failed to instantiate provisioner "local-exec" to obtain schema: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.`
bash-4.4# terraform --version
Terraform v0.12.17
+ provider.external v1.2.0
+ provider.google v3.42.0
+ provider.kubernetes v1.13.2
+ provider.null v2.1.2
+ provider.random v2.3.0

**Comment by bharathkkb** [comment]
Hi @Vadims06 
There seems to be an issue specific to the environment where you are currently executing Terraform as it is not just the `google` provider and not related to the module. I would recommend trying it another env, using tf `0.12.29` and if it persists opening an issue in `hashicorp/terraform`
