### ISSUE TITLE
beta-private-cluster-update-variant should generate new node pool ID if node_pools_taints is changed

### ISSUE THREAD

**Issue by eripa** [terraform-google-modules/terraform-google-kubernetes-engine#699]
beta-private-cluster-update-variant does not currently generate a new node pool random suffix is `node_pools_taints` is changed. This results in a name conflict error, like:

```
Error: error creating NodePool: googleapi: Error 409: Already exists: projects/example-project/locations/us-west4/clusters/cluster1/nodePools/default-node-pool-aa6d., alreadyExists
```

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/26ea28db52ce5797da043a1c56dfb4575f49dac8/modules/beta-private-cluster-update-variant/cluster.tf#L294-L348

**Comment by morgante** [comment]
Thanks, it just needs to be added here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/autogen/main/cluster.tf.tmpl#L333

Happy to review a PR.

**Comment by jinoobaek-qz** [comment]
> Thanks, it just needs to be added here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/autogen/main/cluster.tf.tmpl#L333
> 
> Happy to review a PR.

Took a very naive stab at it. https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/717

**Comment by DrFaust92** [comment]
@apeabody can be closed

**Comment by apeabody** [comment]
Implemented in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/717
