### ISSUE TITLE
Support for Master Auth

### ISSUE THREAD

**Issue by pratikmallya** [terraform-google-modules/terraform-google-kubernetes-engine#7]
They seem to not be supported in this module... will they be in the future?

**Comment by morgante** [comment]
Yes, supporting private clusters is definitely on our roadmap (opened #8 to track it).

Master auth is definitely something we plan to add soon as well.

**Comment by pratikmallya** [comment]
@morgante is there a timeline for adding master auth support? If its not being added this week, I could craft a PR to enable it. I'm trying to move from an internal module to this one; just need some necessary features to make the move :)

**Comment by pratikmallya** [comment]
I guess I should have made the issue more descriptive... I don't care about Master Auth as much as the [master_authorized_networks_config](https://www.terraform.io/docs/providers/google/r/container_cluster.html#master_authorized_networks_config) i.e. the list of networks that are permitted to access the cluster.
