### ISSUE TITLE
Potetially incorrect source reference?

### ISSUE THREAD

**Issue by max-sixty** [terraform-google-modules/terraform-google-kubernetes-engine#700]
From https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/workload-identity#using-an-existing-kubernetes-service-account

I get an error running this:

```
module "my-app-workload-identity" {
  source    = "terraform-google-modules/terraform-google-kubernetes-engine/modules/workload-identity"
  use_existing_k8s_sa = true
  name                = "preexisting-sa"
  namespace           = "prod"
  project_id          = var.project_id
}
```

```
Error: Module not found

The module address
"terraform-google-modules/terraform-google-kubernetes-engine/modules/workload-identity"
could not be resolved.
```

Let me know if I'm doing something wrong, though. Thanks

**Comment by bharathkkb** [comment]
Thanks for the report @max-sixty Looks like we are missing a `/`

**Comment by max-sixty** [comment]
It's also a different source from the other example in that file — I'm new to TF so not sure whether they're equivalent?

**Comment by max-sixty** [comment]
Thanks @bharathkkb & @morgante !
