### ISSUE TITLE
Clusters of 1.17.9-gke.1504 and 1.17.9-gke.6300 become broken when helm provider authenticate through username & password & certificates

### ISSUE THREAD

**Issue by hronix** [terraform-google-modules/terraform-google-kubernetes-engine#702]
Maybe this is another google tech team problem but:
1. Sorry, don't know where to report 
2. I create cluster with this module

```tf
  source                     = "terraform-google-modules/kubernetes-engine/google"
  version                    = "11.1"
```

I install helm packages with helm provider

```tf
provider helm {
  version = "~> 1.3"

  kubernetes {
    load_config_file       = false
    host                   = "https://${module.gke.endpoint}"
    username               = random_string.username.result
    password               = random_password.password.result
    cluster_ca_certificate = base64decode(module.gke.ca_certificate)
    client_key             = base64decode(data.google_container_cluster.k8s.master_auth.0.client_key)
    client_certificate     = base64decode(data.google_container_cluster.k8s.master_auth.0.client_certificate)
  }
}
```

When I apply changes I can't get nodes info in second terminal. Google Cloud UI can't present nodes, workloads, services & ingress info. After some time master node says that it recover cluster.

The same script **works** fine on version **1.16.13-gke.401**

**Comment by bharathkkb** [comment]
@hronix thanks for the report. Just to clarify the cluster goes into repair after applying something using the helm provider and if you explicitly deploy a cluster with `1.16.13-gke.401` then everything is fine?

**Comment by hronix** [comment]
@bharathkkb that's right

**Comment by bharathkkb** [comment]
Does the master recover after a while? I would try with a bigger nodepool too as I have noticed with some issues if the control plane gets overloaded as Helm tries to deploy all k8s objects.
If you could provide a minimal repro (TF config + chart) I would be happy to test it on my end.

**Comment by hronix** [comment]
@bharathkkb sure, https://gist.github.com/hronix/6d94ab13484571d357f5efac04bfd58e

**Comment by hronix** [comment]
Today I tested new module version "12.0" with Kubernetes "1.17.9-gke.1504" - the same, I mean it **fails**.

Steps: 
1. terraform apply -var-file=serviceaccount.json -target=module.gke
2. You can get nodes info (kubectl get nodes), can see workloads in Google Cloud UI.
3. terraform apply -var-file=serviceaccount.json -target=helm_release.cert_manager -> It fails with `Error: unable to build kubernetes objects from release manifest: Get https://35.238.82.159/openapi/v2?timeout=32s: unexpected EOF`. You can't get nodes info, neither see Workloads info in Google Cloud UI.

**Comment by davem-git** [comment]
I seem to be having an issue too.  I get these when i try to access the client_key and client_cert

```Error: Attempt to index null value

  on versions.tf line 56, in provider "helm":
  56:     client_key             = base64decode(data.google_container_cluster.cluster.master_auth.0.client_key)
    |----------------
    | data.google_container_cluster.cluster.master_auth is null

This value is null, so it does not have any indices.


Error: Attempt to index null value

  on versions.tf line 57, in provider "helm":
  57:     client_certificate     = base64decode(data.google_container_cluster.cluster.master_auth.0.client_certificate)
    |----------------
    | data.google_container_cluster.cluster.master_auth is null

This value is null, so it does not have any indices.
```

**Comment by bharathkkb** [comment]
@hronix thanks for the config, I will try a repro to see if its related to the module.

@davem-git This does not seem related to the original issue. Are you using [our `auth` submodule](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/auth)? Does the SA you are using have `container.clusters.getCredentials` permission?

**Comment by davem-git** [comment]
I was incorrect and got it working.

I didn't need this, which is where i went wrong and thought it was similar.

```
kubernetes {
    load_config_file       = false
    host                   = "https://${module.gke.endpoint}"
    username               = random_string.username.result
    password               = random_password.password.result
    cluster_ca_certificate = base64decode(module.gke.ca_certificate)
    client_key             = base64decode(data.google_container_cluster.k8s.master_auth.0.client_key)
    client_certificate     = base64decode(data.google_container_cluster.k8s.master_auth.0.client_certificate)
  }
}
```
I needed this 

```
Provider "helm" {
  version = "= 1.2.3"
  kubernetes {
    load_config_file       = false
    host                   = module.gke.endpoint
    token                  = data.google_client_config.default.access_token
    cluster_ca_certificate = base64decode(module.gke.ca_certificate)
  }
}
```

**Comment by bharathkkb** [comment]
@hronix I noticed that you are using the `basic_auth_username`, `basic_auth_password` and `issue_client_certificate = true`. You should only need the `module.gke.ca_certificate` and `token` to auth.  Could you try removing those and reconfigure helm provider like so
```
data "google_client_config" "provider" {}

provider helm {
  version = "~> 1.3"

  kubernetes {
    load_config_file       = false
    host                   = "https://${module.gke.endpoint}"
    cluster_ca_certificate = base64decode(module.gke.ca_certificate)
    token = data.google_client_config.provider.access_token
  }
}
```

**Comment by hronix** [comment]
I tested it on newly created cluster from example and it works well. I will try upgrade my test cluster and create new one, for more detailed testing. Will report back soon.

**Comment by hronix** [comment]
Well, new findings:
- terraform_provider_helm generates error: `Error: query: failed to query with labels: secrets is forbidden: User "client" cannot list resource "secrets" in API group "" in the namespace "cert-manager"` because *helm list* require secrets view permissions 
- for some reason provider threads service account as **client** (my name in format k8s-sa-test@k8s-test-xxxxxxxxx.iam.gserviceaccount.com) however I'm using service account with project/owner permissions and it's `cluster-admin` in RBAC

**Comment by hronix** [comment]
I can verify that [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/702#issuecomment-714798572) config works great with version 1.17.9-gke.6300 and 1.17.12-gke.1504. Thanks !
