### ISSUE TITLE
Terraform integration w/ASM script

### ISSUE THREAD

**Issue by zerobfd** [terraform-google-modules/terraform-google-kubernetes-engine#707]
We're working on a fully-featured script to install ASM in various environments over here: https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/tree/master/scripts/asm-installer

It would be cool if we could have the Terraform module use this one since we're maintaining it as different features/environments/etc get added. Right now it only handles GCP, but it does all of the validation/api enablement/etc. along with the install, with a few options.

I'd love to see what requirements you have for the Terraform module so we can make sure to add whatever you need.

**Comment by bharathkkb** [comment]
This is awesome and I would love to switch over to using that one. I'll take a dive through it tomorrow and sync with some requirements offline.

**Comment by bharathkkb** [comment]
@zerobfd as per our offline sync reassigning to you for tracking

**Comment by bharathkkb** [comment]
@zerobfd there was a recent ask if it would be possible to support ILB out of the box when deploying via TF. IIRC this involves just an annotation. Is this something within the scope of the new script? 
ref: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/684#issuecomment-714187576

**Comment by zerobfd** [comment]
Yep, starting soon-ish it will be available with one extra CLI option.

**Comment by PsychoSid** [comment]
+1 for me on this. I had to stop using the ASM module in favour of a local "istioctl  install -f <file>" to setup the options I needed for multi-cluster/CNI, a static IP for the IGW etc etc to the script in the original post which mentions an option for this as part of a revamped module would be much appreciated.

**Comment by abhinavrau** [comment]
@zerobfd I am working on modifying the current asm module to support this new script and I have an initial working version. I have a found couple of issues in the the 1.8 install_asm script that is blocking me sending the PR. 

I will open issues in the asm github project for these and update this thread so we can track.

**Comment by abhinavrau** [comment]
@zerobfd Opened [issue 480](https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/issues/480) on the asm packages project.

**Comment by bharathkkb** [comment]
Re opening this as https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/824 only ensures compatibility with existing module, not new features like upgrades supported by ASM script.
