### ISSUE TITLE
Put all nodepool options into one block

### ISSUE THREAD

**Issue by weeco** [terraform-google-modules/terraform-google-kubernetes-engine#710]
I use this GKE module to create clusters with multiple nodepools where each nodepool requires:
- Nodepool Labels
- Taints
- Network Tags

I'd like to specify these options in the object where I create/configure the nodepool as well, so that I don't need to refer it by nodepool name again and again. So instead of this:

```hcl
module "gke" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster"
  version = "~> 11.1"
  [...]
  node_pools = [{
      name = "foo"
      machine_type = "e2-standard-2"
    }
  ]

  node_pools_labels = {
    "foo" = {
      name             = "foo"
      preemptible      = false
    },
  }

  node_pools_taints = {
    "foo" = [
      {
        key      = "app"
        operator = "Equal"
        value    = "foo"
        effect   = "NoSchedule"
      }
    ]
  }

  node_pools_tags = {
    "foo" = ["foo", "bar"]
  }
}
```

I'd prefer this instead:

```hcl
module "gke" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster"
  version = "~> 11.1"
  [...]
  node_pools = [{
      name = "foo"
      machine_type = "e2-standard-2"
      labels = {
        name             = "foo"
        preemptible      = false
      }
      taints = [
        {
            key      = "app"
            operator = "Equal"
            value    = "foo"
            effect   = "NoSchedule"
        }
      ]
      tags = ["foo", "bar"]
    }
  ]
}
```

In the Google Cloud console these options also appear as option as part of the nodepool configuration and not as part of the cluster scoped configuration-

**Comment by morgante** [comment]
We'd love to have it work that way, but unfortunately node pools are defined as a map and therefore cannot contain lists/objects. See this [issue](https://github.com/hashicorp/terraform/issues/21384).
