### ISSUE TITLE
Having Trouble Authenticating to Kubernetes Provider using Auth Module

### ISSUE THREAD

**Issue by adhil0** [terraform-google-modules/terraform-google-kubernetes-engine#714]
I can't seem to connect to the cluster that I create using the gke module. The `terraform apply` command goes through successfully, but any kubectl command run afterwards returns an error: `Unable to connect to the server: dial tcp <IP-ADDRESS>: i/o timeout`
I have to manually run `gcloud container clusters get-credentials <CLUSTER-NAME> --region <REGION> --project <PROJECT_NAME>` to fix this.

my tf:
```
provider "google" {
  project     = var.project_id 
  region      = var.region
  zone        = var.zone
}

provider "kubernetes" {
  load_config_file = false

  cluster_ca_certificate = module.gke_auth.cluster_ca_certificate
  host                   = module.gke_auth.host
  token                  = module.gke_auth.token
}

provider "helm" {
  kubernetes {
    load_config_file = false

    cluster_ca_certificate = module.gke_auth.cluster_ca_certificate
    host                   = module.gke_auth.host
    token                  = module.gke_auth.token
  }
}

module "gke_auth" {
  source       = "terraform-google-modules/kubernetes-engine/google//modules/auth"
  project_id   = var.project_id
  cluster_name = module.gke.name
  location     = module.gke.location
  depends_on   = [module.gke]
}

module "gke" {
  source                            = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster"
  project_id                        = var.project_id
  name                              = "${var.project_id}-gke-2"
  region                            = var.region
  zones                             = [var.zone]
  network                           = "default"
  subnetwork                        = "default"
  ip_range_pods                     = ""
  ip_range_services                 = ""
  create_service_account            = false
  disable_legacy_metadata_endpoints = false
  remove_default_node_pool          = true
# Node pool config below
```
I've tried the solutions provided in #655, but nothing seems to be working. Does anyone have any suggestions?

**Comment by bharathkkb** [comment]
Hi @adhil0 
I see that you are using the `beta-private-cluster`. We have some docs around [private clusters](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/private_clusters.md) here. I believe in the case you will need to add the external ip of the machine you are using to run this config into your `master_authorized_networks` block.

**Comment by adhil0** [comment]
@bharathkkb Thanks for the help, I actually was supposed to be using `beta-public-cluster`, so thanks for pointing that out. However, I switched over to the public version, but I am still having the same issue. Is there anything else I can try?

**Comment by morgante** [comment]
It sounds like you're running the additional `kubectl` commands directly from your shell (ie. after Terraform finishes `apply`).

The auth module isn't actually meant to update your local Kubernetes context. It's meant for authenticating *within Terraform*.

**Comment by adhil0** [comment]
Okay, that makes a lot of sense, sorry for the confusion. Thanks @morgante and @bharathkkb for the help. If anyone in the future is reading this, this is the way I ended up updating the local K8S context:
```
resource "null_resource" "configure_kubectl" {
  provisioner "local-exec" {
    command = "gcloud container clusters get-credentials ${module.gke.name} --region ${var.region} --project ${var.project_id}"
  }
}
```

**Comment by ggmartins** [comment]
@adhil0 thanks for sharing your solution. I'm having the same problem here, but your solution tries to execute _get-credentials_ while the cluster is at RECONCILING state (gke):
```
null_resource.context (local-exec): Fetching cluster endpoint and auth data.
null_resource.context (local-exec): WARNING: cluster XXXX is not running. The kubernetes API may not be available.
null_resource.context (local-exec): kubeconfig entry generated for XXXX.
```
Can you comment on whether you're currently using **wait_for** statement as well? something along the lines below? https://www.hashicorp.com/blog/wait-conditions-in-the-kubernetes-provider-for-hashicorp-terraform
@morgante @bharathkkb, Thanks, G.

**Comment by adhil0** [comment]
@ggmartins Thanks for providing that link, I actually wasn't aware of **wait_for** statements. I'm not currently using any **wait_for** statements in my config, I have the `null_resource` block exactly as above. Now that you mention it, however, I do see that `WARNING: cluster XXXX is not running` message on occasion but it doesn't really seem to cause any problems in my personal config. Sorry I couldn't really help you
