### ISSUE TITLE
support for linux_node_config

### ISSUE THREAD

**Issue by Schnitzel** [terraform-google-modules/terraform-google-kubernetes-engine#715]
looks like the main terraform provider has support for `linux_node_config` in `node_configs`:
https://github.com/hashicorp/terraform-provider-google/issues/6773

our usecase for this is to set `vm.max_map_count: "262144"` sysctl settings for elasticsearch clusters, while we can do this via init containers, the `sysctl-monitor` of GKE complains about an unmanaged sysctl setting.

**Comment by bharathkkb** [comment]
Thanks for the report @Schnitzel 
SGTM and will be happy to review a PR

**Comment by m10ev** [comment]
Hi, I'm planning to work on this today. Could you assign me?
