### ISSUE TITLE
Add support for artifact registry

### ISSUE THREAD

**Issue by weeco** [terraform-google-modules/terraform-google-kubernetes-engine#719]
Currently it's possible to set the `registry_project_id` which grants storage.objectViewer so that the GKE service account can pull images from the container registry in the respective project. See: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/beta-private-cluster/variables.tf#L320-L324

If I want to use the artifact registry (which seems to be the successor of the container registry), I do need different IAM permissions - such as the Artifact Registry Reader permission.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/748
