### ISSUE TITLE
Double converge required for network policy to work

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#72]
As discussed in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/68#issuecomment-454953204, running `kitchen converge` twice is currently necessary to enable network policy/Calico.

This is an upstream issue in the API itself.

**Comment by thefirstofthe300** [comment]
Do we have a public issue for this particular upstream bug? It'd be nice to have some visibility into the work on the API.

**Comment by aaron-lane** [comment]
Fixed by #159.
