### ISSUE TITLE
Invalid count argument on safer cluster with shared VPC

### ISSUE THREAD

**Issue by mateuszm123111** [terraform-google-modules/terraform-google-kubernetes-engine#720]
Hi, I try to use module "safer-cluster-update-variant" with shared VPC network, as module itself doesn't support adding access to "container.hostServiceAgent.use" on shared VPC host project, I was trying to create service account by myself, and add it into config, so I used parameter: compute_engine_service_account to point into my service account, but it gives an error "Invalid count argument" 
`on .terraform/modules/kubernetes-engine/modules/beta-private-cluster-update-variant/sa.tf line 38, in resource "google_service_account" "cluster_service_account":
  38:   count        = var.create_service_account ? 1 : 0`

And it is strange because this module doesn't support "create_service_account" parameter, which is enabled by default, how can I deal with it? Any suggestions?

**Comment by morgante** [comment]
Please share your Terraform config.

**Comment by mateuszm123111** [comment]
Ok, so basically that's my gke.tf file

`module "kubernetes-engine" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/safer-cluster-update-variant"
  version = "11.1.0"

  project_id                  = module.project-factory.project_id
  name                        = "gke-${terraform.workspace}-cluster"
  region                      = var.region
  zones                       = var.zones
  network                     = "some-network"
  network_project_id          = "project-which-host-shared-vpc"
  kubernetes_version          = "latest"
  subnetwork                  = "some-subnet"
  ip_range_pods               = "some-subnet-sec"
  ip_range_services           = "some-subnet-sec"
  maintenance_start_time      = "04:00"
  node_pools                  = var.node_pools
  enable_pod_security_policy  = true
  compute_engine_service_account = module.gke-service-account.email //that's my service account with proper permissions to use shared network
  master_authorized_networks = [
    {
      cidr_block   = "10.0.0.0/32"
      display_name = "empty"
    },
  ]
}`

**Comment by morgante** [comment]
Can you try applying the `gke-service-account` module first? We don't support passing a dynamic value here.

**Comment by mateuszm123111** [comment]
Hi, it seems like first applying this module works with this error, but unfortunately I have another one, and it is very confusing for me, the thing is that I applied service account, I checked that it exists on my host VPN project with proper permission "Kubernetes Engine Host Service Agent User", but when I try then to apply gke it gives me an error:
`Error: googleapi: Error 403: Kubernetes Engine Service Agent is missing required permissions on this project. See https://cloud.google.com/kubernetes-engine/docs/troubleshooting#gke_service_account_deleted for more info: required "container.hostServiceAgent.use" permission(s) for "projects/project-which-host-shared-vpc"., forbidden`

Could you help me with this one also? Because I do not understand why it happens.

Maybe it somehow uses the other service account? I really don't know

Thanks in advance.

**Comment by morgante** [comment]
Hi @mateuszm123111, you need to provide the Kubernetes service account with the service agent user on your Shared VPC host project as [explained here](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc#grant_host_service_agent_role).

**Comment by mateuszm123111** [comment]
I'm sorry, but I guess that I do not understand this. I just already gave that permission to my service account which I wanted to use with nodes, or am I wrong? 

Or another thing, during kubernetes creation it uses default service account? So `service-service-project-num@container-engine-robot.iam.gserviceaccount.com` this one? And I should give permissions to that service account?

Sorry for that, but I'd like to understand this, thank you very much for your time!

**Comment by morgante** [comment]
@mateuszm123111 Please read the entire GKE docs: https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-shared-vpc#grant_host_service_agent_role

There are multiple service accounts involved, both a *node* service account _and_ a GKE service account.

**Comment by mateuszm123111** [comment]
OK, thank you 👍
