### ISSUE TITLE
gcloud: command not found (running on Terraform Cloud)

### ISSUE THREAD

**Issue by dassaf1** [terraform-google-modules/terraform-google-kubernetes-engine#721]
Hi,

Running on Terraform Cloud, and after upgrading to v12 and trying to create a cluster, on the final step (after the cluster is actually created) I get the following error:

Error: Error running command 'PATH=/google-cloud-sdk/bin:$PATH
.terraform/modules/gke_cluster.gke/modules/beta-private-cluster-update-variant/scripts/wait-for-cluster.sh <clustername> <clustername>
': signal: interrupt. Output: Waiting for cluster <clustername> in project <projectname> to reconcile...
.terraform/modules/gke_cluster.gke/modules/beta-private-cluster-update-variant/scripts/wait-for-cluster.sh: line 29: gcloud: command not found

**Comment by bharathkkb** [comment]
Hi @dassaf1 
- Before the upgrade to v12, were you using `gcloud_skip_download = false`? If so you will need to follow the upgrade guide [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/upgrading_to_v12.0.md#dropped-support-for-gcloud_skip_download-variable) and set the env variable to download gcloud within Terraform cloud.

- Alternatively you can turn off provisioners by setting `skip_provisioners = true`

**Comment by dassaf1** [comment]
HI @bharathkkb,

Thank you for your reply, that helped resolving this error :) however I now have a new related error which indicates that gcloud cannot find a way to authenticate.

I assume I need to use the "use_tf_google_credentials_env_var = true" in the [terraform-google-gcloud helper module](https://github.com/terraform-google-modules/terraform-google-gcloud#downloading) (that is used by the GKE module)

But I am not sure how I can pass that variable from the main/parent module (terraform-google-kubernetes-engine) which is what I am using.

Or maybe I am wrong here and there is a different way this should be done?

The exact error as following:

> module.gke_cluster.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): WARNING: Could not open the configuration file: [/home/terraform/.config/gcloud/configurations/config_default].
> 
> module.gke_cluster.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): ERROR: (gcloud.container.clusters.list) You do not currently have an active account selected.
> 
> module.gke_cluster.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): Please run:
>
> module.gke_cluster.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec):   $ gcloud auth login
>
> module.gke_cluster.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): to obtain new credentials, or if you have already logged in with a
> module.gke_cluster.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): different account:
>
> module.gke_cluster.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec):   $ gcloud config set account ACCOUNT
>
> module.gke_cluster.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): to select an already authenticated account to use.

Thank you!
Dafna

**Comment by bharathkkb** [comment]
@dassaf1 Could you try setting `GOOGLE_APPLICATION_CREDENTIALS` field. This should allow gcloud to pick it up for auth.

**Comment by dassaf1** [comment]
@bharathkkb Thank you for your reply.
If I understand correctly, the GOOGLE_APPLICATION_CREDENTIALS env var expects a path to the json key of the service account, however I cannot access the file system of the docker container running in TF Cloud.

**Comment by bharathkkb** [comment]
@dassaf1 gotcha, in that case we should consider exposing `use_tf_google_credentials_env_var` via the module and then you can put the json key in the `GOOGLE_CREDENTIALS`  env var.

**Comment by dassaf1** [comment]
@bharathkkb That sounds great! thank you.

**Comment by jclarksnps** [comment]
@bharathkkb Setting the env var doesn't work with tf cloud agents as they won't have curl either.   I'm guessing that this module isn't really intended to be used in environments like tf cloud (agents without anything on them).

**Comment by morgante** [comment]
@jclarksnps It actually is possible to use this with Terraform Cloud. That's why we have the `gcloud` module which handles installs.

**Comment by arbourd** [comment]
I couldn't get it working, even by setting the env vars. We jumped back to `11.x` for the time being.

**Comment by morgante** [comment]
What was working that isn't working now?

**Comment by jclarksnps** [comment]
For me the gcloud modules all fail trying to download via curl, I should note we run our own agents (which uses hashicorps tfc agent docker image).  I would assume that is the same image they use to run the remote agents.

Error: Error running command 'curl -sL -o .terraform/modules/gke.gcloud_delete_default_kube_dns_configmap/cache/c0da97ee/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x .terraform/modules/gke.gcloud_delete_default_kube_dns_configmap/cache/c0da97ee/jq': exit status 127. Output: /bin/sh: 1: curl: not found

**Comment by johntrabajo** [comment]
I just ran into this issue today actually. I have GOOGLE_CREDENTIALS (also tried GOOGLE_APPLICATION_CREDENTIALS ) and GCLOUD_TF_DOWNLOAD added as environment variables in the Terraform Cloud console. Unfortunately, I'm still seeing the installation missing (gcloud: command not found). After I cleared out my workspace and created this from scratch, I was able to get gcloud to install, but it's still missing auth. Happy to provide more details if I can.

**Comment by zonnie** [comment]
I'm having the exact same issue...no matter what I do, even if I see `gcloud` being installed in TF Cloud's terminal it still missing and fails on
```
module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): .terraform/modules/gke/scripts/wait-for-cluster.sh: line 29: gcloud: command not found
```
I tried setting `GCLOUD_TF_DOWNLOAD` as well...
Nothing works...

**Comment by morgante** [comment]
@zonnie Can you confirm that install actually succeeded? I'm guessing this might be the issue with `curl` that @jclarksnps raised.

You should be able to workaround this by setting `skip_provisioners = true`.

**Comment by zonnie** [comment]
@morgante It didn't work...nothing works really.
I tried `skip_provisioners = true` solution in another issue here, it didn't work for me...

**Comment by jai** [comment]
Having this issue too:

* `skip_provisioners = true` is set
* gcloud CLI is actually installed and usable (not through this module, through my own Terraform code). This is confirmed because I'm able to activate credentials for my cluster and get the output `Activated service account credentials for: [terraform@test-api-cloud-infrastructure.iam.gserviceaccount.com]`

It started failing on the upgrade to 12.0 it seems - at that point I was not setting `skip_provisioners`, but it doesn't seem to make a difference since I've set it, and it's still failing.

Error output:
```bash
Error: Error running command 'PATH=/google-cloud-sdk/bin:$PATH
modules/terraform-gcp-gke/gcp-gke/modules/terraform-google-kubernetes-engine/modules/beta-private-cluster-update-variant/scripts/wait-for-cluster.sh test-api-cloud-infrastructure test-api-cloud-infrastructure-1-64b77e2a asia-southeast2 
': exit status 1. Output: Waiting for cluster test-api-cloud-infrastructure/asia-southeast2/test-api-cloud-infrastructure-1-64b77e2a to reconcile...
modules/terraform-gcp-gke/gcp-gke/modules/terraform-google-kubernetes-engine/modules/beta-private-cluster-update-variant/scripts/wait-for-cluster.sh: line 35: gcloud: command not found
Unable to get status for test-api-cloud-infrastructure/asia-southeast2/test-api-cloud-infrastructure-1-64b77e2a
```

**Comment by ellisio** [comment]
> I'm having the exact same issue...no matter what I do, even if I see `gcloud` being installed in TF Cloud's terminal it still missing and fails on
> 
> ```
> module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): .terraform/modules/gke/scripts/wait-for-cluster.sh: line 29: gcloud: command not found
> ```
> 
> I tried setting `GCLOUD_TF_DOWNLOAD` as well...
> Nothing works...

@zonnie Have your tried setting `GCLOUD_TF_DOWNLOAD=always`, and then setting the Terraform Version to 13.5.0 under Settings -> General on your Terraform Cloud workspace?

If you have recently created a workspace, you'll be on Terraform v14.x which is not supported by this module.

<img width="295" alt="Screen Shot 2020-12-28 at 10 55 33 PM" src="https://user-images.githubusercontent.com/127468/103261769-e7866f00-495f-11eb-9b96-b094ca4a65fd.png">
