### ISSUE TITLE
Kubernetes Engine Service Agent does not have firewall rule create permission in host VPC project

### ISSUE THREAD

**Issue by xingao267** [terraform-google-modules/terraform-google-kubernetes-engine#723]
Both the host VPC project the GKE project was created using the project factory module 9.2.0. The network host project has `enable_shared_vpc_host_project` set to true and the GKE project has `shared_vpc` and `shared_vpc_subnets` specified. The instance of GKE module has `network_project_id`, `network` and `subnetwork` specified. Not sure what I'm missing. But I see a lot of compute.firewalls.get and create permission issues on the Kubernetes Engine Service Agent in the host VPC project. When I create an ingress for GKE with a global IP in the GKE project, I got additional permission issue where the Kubernetes Engine Service Agent tries to create a GCE L7 firewall rule for the load balancer health check, and the GKE ingress failed to work with `All backend services are in UNHEALTHY state` error. Should this module or the project factory handle either granting the Service Agent permission to modify firewall rules in the host VPC project or just create those firewall rules?

**Comment by bharathkkb** [comment]
Hi @xingao267 
I believe we do not add `Compute Security Admin` role or (compute.firewalls.* and compute.networks.updatePolicy permissions) to that SA via [shared_vpc_access](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/shared_vpc_access/main.tf) and hence the GKE is unable to modify FW rules for ing. Generally this is considered best practice for prod as changes to FW rules should go through further scrutiny. However I do I think this makes most sense to add as an optional via flag in [shared_vpc_access](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/shared_vpc_access/main.tf)

**Comment by morgante** [comment]
Yeah I think it would be a reasonable optional flag for shared_vpc_access.

**Comment by xingao267** [comment]
Sounds good. I can add that support when I get a chance.
