### ISSUE TITLE
Issue with generating the kube config on first run

### ISSUE THREAD

**Issue by k-mitevski** [terraform-google-modules/terraform-google-kubernetes-engine#725]
I've tried multiple code examples but the kube config file, or the raw output is empty on the first run/apply. But running terraform apply a second time fixes the issue and populates the kube config with the correct info.

The below images are outputs from this example https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/simple_regional_with_kubeconfig

Terraform version: v0.13.5
Everything else works correctly and it's properly generated.

First apply:
<img src="https://i.imgur.com/50qdMZC.png">

Second:
<img src="https://i.imgur.com/6mwvjMJ.png">

**Comment by bharathkkb** [comment]
Hi @k-mitevski 
Was the example modified? I just tested this example with TF0.13.5 and it seems to work as intended.

**Comment by k-mitevski** [comment]
Hey @bharathkkb, 
I tried multiple times using the example in a 1:1 fashion, with only added the required variables. 
I've tried to run everything from a separate folder as to not mix them from the previous cluster creation, but still to no avail. I'm unsure what is causing this.

If you have any suggestions or configs you want me to test please provide them.

**Comment by bharathkkb** [comment]
Yeah this is odd if you are using the example as-is. Could you give me your terraform config just to confirm?

**Comment by k-mitevski** [comment]
@bharathkkb Here are the configs, please check if something is wrong.

```
locals {
  cluster_type = "simple-regional"
}

provider "google" {
  version = "~> 3.42.0"
  region  = var.region
}

module "gke" {
  source                 = "terraform-google-modules/kubernetes-engine/google"
  project_id             = var.project_id
  name                   = "${local.cluster_type}-cluster${var.cluster_name_suffix}"
  regional               = true
  region                 = var.region
  network                = var.network
  subnetwork             = var.subnetwork
  ip_range_pods          = var.ip_range_pods
  ip_range_services      = var.ip_range_services
  create_service_account = false
  service_account        = var.compute_engine_service_account
  skip_provisioners      = var.skip_provisioners
}

module "gke_auth" {
  source = "terraform-google-modules/kubernetes-engine/google//modules/auth"

  project_id   = var.project_id
  location     = module.gke.location
  cluster_name = module.gke.name
}

```
```
output "kubernetes_endpoint" {
  sensitive = true
  value     = module.gke_auth.host
}

output "client_token" {
  sensitive = true
  value     = module.gke_auth.token
}

output "ca_certificate" {
  value = module.gke_auth.cluster_ca_certificate
}

output "kubeconfig_raw" {
  value = module.gke_auth.kubeconfig_raw
}

output "service_account" {
  description = "The default service account used for running nodes."
  value       = module.gke.service_account
}
```

```
variable "project_id" {
  default = "project-id"
  description = "The project ID to host the cluster in"
}

variable "cluster_name_suffix" {
  description = "A suffix to append to the default cluster name"
  default     = "-test"
}

variable "region" {
  default = "europe-west1"
  description = "The region to host the cluster in"
}

variable "network" {
  default = "default"
  description = "The VPC network to host the cluster in"
}
//I've created the subnetwork manually
variable "subnetwork" {
  default = "cluster-subnet"
  description = "The subnetwork to host the cluster in"
}

variable "ip_range_pods" {
  default = "pod-subnet"
  description = "The secondary ip range to use for pods"
}

variable "ip_range_services" {
  default = "service-subnet"
  description = "The secondary ip range to use for services"
}
//tried with and without service account.
variable "compute_engine_service_account" {
  default     = "x-compute@developer.gserviceaccount.com"
  description = "Service account to associate to the nodes in the cluster"
}
variable "skip_provisioners" {
  type        = bool
  description = "Flag to skip local-exec provisioners"
  default     = false
}
```

**Comment by bharathkkb** [comment]
This does seem odd. Apart from the `kubeconfig_raw` output  are the `ca_certificate` and `kubernetes_endpoint` being populated in the first run?

**Comment by bharathkkb** [comment]
It looks like from your first screenshot `ca_certificate` is not being populated. Could you try adding an output for `module. gke.ca_certificate` and `module.gke.endpoint` to test if that works?

**Comment by k-mitevski** [comment]
Yeah, they weren't getting populated. But with your changes for the output, there seems to be an improvement.

![image](https://user-images.githubusercontent.com/51249239/97747810-d1d60400-1aec-11eb-8eb9-d15378843794.png)
I've added them, it seems the original ones with gke_auth don't like to work in my case.
```
output "ca_cert" {
  value = module.gke.ca_certificate
}

output "endpoint" {
  value = module.gke.endpoint
}
```
The original outputs:
```
output "ca_certificate" {
  value = module.gke_auth.cluster_ca_certificate
}

output "kubernetes_endpoint" {
  sensitive = true
  value     = module.gke_auth.host
}
```

**Comment by bharathkkb** [comment]
Yeah this is interesting and looks like maybe a dependency issue. FWIW I tried 2-3 runs and did not run into this. It seems like `data.google_container_cluster.gke_cluster.endpoint` and `data.google_container_cluster.gke_cluster.master_auth` are reporting as `null` causing it to default to `""`. 

The order of creation also seems correct. For me it was 
```
module.example.module.gke.google_container_cluster.primary: Still creating... [2m30s elapsed]
module.example.module.gke.google_container_cluster.primary: Creation complete after 2m36s [id=projects/...]
module.example.module.gke_auth.data.google_container_cluster.gke_cluster: Reading...
module.example.module.gke.google_container_node_pool.pools["default-node-pool"]: Creating...
module.example.module.gke_auth.data.google_container_cluster.gke_cluster: Read complete after 1s [id=projects/...]
module.example.module.gke_auth.data.template_file.kubeconfig: Reading...
module.example.module.gke_auth.data.template_file.kubeconfig: Read complete after 0s [id=f329ff52bce79cd3033b7851a70d3b4e9dc3efeb95c3a4415a5b999b79033221]
module.example.module.gke.google_container_node_pool.pools["default-node-pool"]: Still creating... [10s elapsed]
```
I would expect since `google_container_cluster.primary` creation is complete, `gke_auth.data.google_container_cluster.gke_cluster` read should return the updated values. 

@rileykarson do you know any edge cases that may cause this?

**Comment by rileykarson** [comment]
I haven't seen that happen before!

**Comment by k-mitevski** [comment]
Here is the same output from my tests. Could it be from wrong ordering in the console output? In your case @bharathkkb there is first reading for the auth.data and then the node pool gets created. In my case, it's the opposite.
```
module.gke.google_container_cluster.primary: Still creating... [2m40s elapsed]
module.gke.google_container_cluster.primary: Creation complete after 2m49s [id=projects/project/]

> module.gke.google_container_node_pool.pools["default-node-pool"]: Creating...
> module.gke_auth.data.google_container_cluster.gke_cluster: Reading...

module.gke_auth.data.google_container_cluster.gke_cluster: Read complete after 0s
module.gke_auth.data.template_file.kubeconfig: Reading...
module.gke_auth.data.template_file.kubeconfig: Read complete after 0s [id=cb028d56daa3562cd311733915bfbb449e2a76d1ccaa3676184accd3280234a5]
module.gke.google_container_node_pool.pools["default-node-pool"]: Still creating... [10s elapsed]
module.gke.google_container_node_pool.pools["default-node-pool"]: Still creating... [20s elapsed]
```

**Comment by bharathkkb** [comment]
@k-mitevski I think the order should be creation of `google_container_cluster` and then read of `gke_auth.data.google_container_cluster.gke_cluster` which is true for your case as well. Since you are on TF 0.13 can you try an explicit module depends_on to see if that can be a possible fix?

So like
```hcl
module "gke" {
}

module "gke_auth" {
depends_on = [module.gke]
}
```

**Comment by k-mitevski** [comment]
I think that was the fix, I added the depend on in the auth module and it populated the kube config on the first run :). Will give it a couple of runs and close this issue.

```module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0]: Creation complete after 2s [id=7115733932052527816]
module.gke_auth.data.google_client_config.provider: Reading...
module.gke_auth.data.google_container_cluster.gke_cluster: Reading...
module.gke_auth.data.google_client_config.provider: Read complete after 0s [id=projects//regions/europe-west1/zones/]
module.gke_auth.data.google_container_cluster.gke_cluster: Read complete after 5s [id=projects/project]
module.gke_auth.data.template_file.kubeconfig: Reading...
module.gke_auth.data.template_file.kubeconfig: Read complete after 0s [id=7d47b998b65458e80b56deb5a082e6f812573e5473e7eca77019ed1e1c66d753]
```
Also I'm seeing now, that in my previous output there is a line missing where it denotes the read complete of the project. In the previous output example, this line was missing:
```
module.gke_auth.data.google_container_cluster.gke_cluster: Read complete after 5s [id=projects/project]
```
