### ISSUE TITLE
Confidential computing

### ISSUE THREAD

**Issue by sudipju** [terraform-google-modules/terraform-google-kubernetes-engine#737]
Hello,

We are using this module for the cluster creation for our project. We are planning to use some of our applications to be running with confidential computing. I didn't notice that support yet by this module. Could you please enlighten, in case you have some plan in near future.
Any response on this topic will be well appreciated !

Thanks,
Sudip

**Comment by bharathkkb** [comment]
Hi @sudipju Looks like this will need to be added in the provider first

**Comment by bharathkkb** [comment]
Looks like this was added in the latest release. Happy to review a PR to add this
https://github.com/GoogleCloudPlatform/magic-modules/pull/4136

**Comment by sudipju** [comment]
I observed that latest release is 12.0.0, which is released 24 days back. But, this specific change is merged 17 days back to master. Is there any beta release available after this merge? Not able to find the same. Or am I missing something?

As didn't see this variable in 12.0.0 version.
Thanks in advance.

**Comment by bharathkkb** [comment]
So currently this feature was only added to the provider. In order to use it in the module, we need to make some changes to the source code in this repository. [Here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/601) is an example PR of how to add a new feature to a beta module.

**Comment by sudipju** [comment]
Thanks for the reply. I wait for this to be integrated in the source code repo. Is there any way to know the priority of this issue to be integrated? Or can our need be an influencer of the priority?
Thanks in advance.

**Comment by bharathkkb** [comment]
@sudipju currently its best effort, but happy to review if you can open a PR

**Comment by AlfredHudson** [comment]
Is there any news about this issue?

**Comment by safag05** [comment]
@bharathkkb  Is there an ETA on this?

**Comment by stenalpjolly** [comment]
@bharathkkb Since we have added the beta support, can we close this issue?
