### ISSUE TITLE
Feature req: Option to disable maintenance policy

### ISSUE THREAD

**Issue by dpkirchner** [terraform-google-modules/terraform-google-kubernetes-engine#739]
It would be useful to have a way to disable the cluster maintenance policy entirely, similar to selecting "Disabled" under "Maintenance window" on the GCP console. Best I can tell this can only be done manually by commenting out the `maintenance_policy` block in the module files (e.g. `.terraform/modules/project.staging.gke/modules/beta-private-cluster/cluster.tf`).

**Comment by morgante** [comment]
Why do you want to disable the maintenance window?

Our best practice is to have one.

**Comment by dpkirchner** [comment]
I'd like to be able to make my tf files match the state of the cluster as created in the console, and as far as I can tell this is the only toggle that isn't configurable using the module.

As for disabling the maintenance window, I can't see why I would want it. It's not possible (to my knowledge) to know when maintenance will actually happen or how long it will take, so it's not possible to make plans around it. The best you can do is just declare a multi-hour "hands-off" period during which some requests may fail.

In a situation where maintenance is required, I would much rather create a new cluster and migrate traffic over, to avoid that unknowable amount of downtime. Terraform makes this really easy (one of the reasons I dig it).

**Comment by morgante** [comment]
The intent of the module is not to expose every possible GKE options. We take opinionated stances on best practices.

If you want total flexibility, you should fork the module or use the underlying resources.

The maintenance window is used to determine when Google conducts maintenance tasks on your behalf: https://cloud.google.com/kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions

> In a situation where maintenance is required, I would much rather create a new cluster and migrate traffic over, to avoid that unknowable amount of downtime. Terraform makes this really easy (one of the reasons I dig it).

Nothing about a maintenance window precludes you from doing that instead.
