### ISSUE TITLE
Example `simple_regional_private` doesn't work

### ISSUE THREAD

**Issue by inigohu** [terraform-google-modules/terraform-google-kubernetes-engine#742]
I get this error when planning `terraform-google-kubernetes-engine/examples/simple_regional_private` v12.0.0

```
Error: Required attribute is not set

  on ../../modules/private-cluster/cluster.tf line 22, in resource "google_container_cluster" "primary":
  22: resource "google_container_cluster" "primary" {
```

The error disapears when I change the `cidr_block` attribute.

Terraform version: v0.13.5

**Comment by bharathkkb** [comment]
Hi @inigohu 
Thanks for the report. Did you mean it works when you remove 
`cidr_block   = data.google_compute_subnetwork.subnetwork.ip_cidr_range`?

**Comment by inigohu** [comment]
Hi @bharathkkb 
>  Did you mean it works when you remove
cidr_block = data.google_compute_subnetwork.subnetwork.ip_cidr_range?

Yes

**Comment by inigohu** [comment]
When I remove `cidr_block`, the plans works, but when I applied it I get this error message:

```
Error: googleapi: Error 400: 
	(1) network "test-net" does not exist
```

**Comment by inigohu** [comment]
```
Error: googleapi: Error 400: 
	(1) network "test-net" does not exist
```
The last error was my fault. I thought the `private-cluster` module creates the network automatically.

**Comment by bharathkkb** [comment]
@inigohu if this error still persists, you can take a look at this [example](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/simple_regional_with_networking/main.tf) which showcases how to create the network and connect it to the GKE module. Feel free to reopen if needed.

**Comment by brianpham** [comment]
@inigohu How did you solve the issue? Removing the cidr doesn't work because its a required variable for me. Did you have to do anything else?

**Comment by inigohu** [comment]
>@inigohu How did you solve the issue? Removing the cidr doesn't work because its a required variable for me. Did you have to do anything else?

I authorized to anyone:
```
master_authorized_networks = [
  {
    cidr_block   = "0.0.0.0/0"
    display_name = "Anyone"
  },
]
```
