### ISSUE TITLE
Issue with wait-for-cluster.sh and clusters with similar names.

### ISSUE THREAD

**Issue by jclarksnps** [terraform-google-modules/terraform-google-kubernetes-engine#744]
We tried to create a private cluster using this module and we ended up in a never ending loop, due to the filter syntax used to wait for a cluster to be "RUNNING" (https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/scripts/wait-for-cluster.sh).  To reproduce, just have a cluster named "mycluster-foo", and then try and create one called "mycluster-bar" wait-for-cluster.sh will wait until the end of time :)

**Comment by bharathkkb** [comment]
Hi @jclarksnps 
Thanks for the report, we have a [fix](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/734) on main and should be solved with the [12.1.0 release](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/732). Were you using the 12.0 release or did this happen on main?

**Comment by jclarksnps** [comment]
@bharathkkb we are using 12.0

**Comment by bharathkkb** [comment]
@jclarksnps just released `v12.1.0` that should fix this. Feel free to reopen if you run into this.
