### ISSUE TITLE
lifecycle for kubernetes master

### ISSUE THREAD

**Issue by elie-synopsys** [terraform-google-modules/terraform-google-kubernetes-engine#746]
I want to use this module to create my production clusters but I faced issues where the master gets recreated. In order to avoid this I would to have the option to set a lifecycle to the resource to ensure that it will not be destroyed unless explicitly overriding the lifecycle var. I do believe that this should be only set at the resource level instead of the module level to allow the module to do its thing will ensuring I don't accidentally delete my master and lose all my setup.

I just want to add this to the master:
` lifecycle {
    prevent_destroy = true
  }`

This is an extra layer of security in case someone did not read the plan correctly.

**Comment by bharathkkb** [comment]
Hi @elie-synopsys 
Thanks for the feedback. Unfortunately AFAIK, variables cannot be used within `lifecycle` blocks and hence we are unable to parameterize this.

**Comment by bharathkkb** [comment]
Closing this as currently infeasible
