### ISSUE TITLE
Hub registration for non GKE Clusters

### ISSUE THREAD

**Issue by abhinavrau** [terraform-google-modules/terraform-google-kubernetes-engine#747]
I have a working terraform module based on the [hub](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/hub) module that works for registering non GKE clusters. The current hub module only works with GKE clusters.  I wanted to ask if I can contribute it to this project?

**Comment by bharathkkb** [comment]
Hi @abhinavrau 
Happy to accept a PR! I have some thoughts around this here https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/637

**Comment by abhinavrau** [comment]
Hi @bharathkkb. Thanks for the quick reply. Currently I have the hub registration for K8s as a separate module (called hub_k8s) in the my repo on a branch [here](https://github.com/abhinavrau/terraform-google-kubernetes-engine/tree/hub_k8s/modules). 

I would assume from #637 it would be better to have this feature integrated into the current hub module?

**Comment by bharathkkb** [comment]
@abhinavrau yes I think having it in one place makes sense and abstract the logic (gke-cluster vs non-gke) into the module.

**Comment by abhinavrau** [comment]
Thanks for the feedback @bharathkkb. I will update the code and send a PR. I will also work on an example module with accompanying tests. This is my first time working on inspec tests. Any guidance you can provide on what would be acceptable for a good unit and integration test?

**Comment by bharathkkb** [comment]
@abhinavrau apologies, missed this comment. Orchestrating a kind cluster test maybe flaky, at least in our current pipeline. If can use the kubeconfig method with GKE cluster, that maybe the easiest. Failing that we can investigate other routes. I am closing this to track via #637
