### ISSUE TITLE
Networks and Subnetworks are updated everytime

### ISSUE THREAD

**Issue by lantier** [terraform-google-modules/terraform-google-kubernetes-engine#75]
Everytime the module is executed, it try to change the network and subnetworks internal links. Effectively this causes nothing, but the internal Google Api only writes the pattern: `projects/project-id/global/networks/network-name`
```  
~ module.kubernetes.google_container_cluster.primary
      network:    "projects/my-project/global/networks/my-network" => "https://www.googleapis.com/compute/v1/projects/my-project/global/networks/my-network"
      subnetwork: "projects/my-project/regions/southamerica-east1/subnetworks/my-subnet" => "https://www.googleapis.com/compute/v1/projects/my-project/regions/southamerica-east1/subnetworks/my-subnet"
```

I believe this [commit](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/commit/e997e6604fce1e9d9e77f89c483792f26cc934de#diff-f0f63d17be26a4d7704a6642c9c51d1a) may be the cause. This change was made by some issue? I couldn't find a related one

**Comment by morgante** [comment]
This was a workaround for an [upstream issue](https://github.com/terraform-providers/terraform-provider-google/issues/1566). You should probably open a new upstream issue because *either* subnet format (full URI or just postfix) is meant to be acceptable.

**Comment by aaron-lane** [comment]
The workaround should be removed when this module implements support for [Terraform v0.12](https://github.com/hashicorp/terraform/issues/18209#issuecomment-465157613).

**Comment by aaron-lane** [comment]
@lantier can you please confirm that the 4.0.0 release of this module fixes your issue?
