### ISSUE TITLE
Support Terraform v0.14

### ISSUE THREAD

**Issue by cooperbenson-qz** [terraform-google-modules/terraform-google-kubernetes-engine#754]
Hashicorp [released v0.14 yesterday](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-14-general-availability) and this module is preventing us from updating. Looking at the errors it seems like only the version constraint prevents it from working with Terraform v0.14 (there's also a small syntax warning)

```
Warning: Version constraints inside provider configuration blocks are deprecated

  on .terraform/modules/web.gke/modules/beta-private-cluster-update-variant/auth.tf line 30, in provider "kubernetes":
  30:   version                = "~> 1.10, != 1.11.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.


Error: Unsupported Terraform Core version

  on .terraform/modules/web.gke/modules/beta-private-cluster-update-variant/versions.tf line 18, in terraform:
  18:   required_version = ">=0.12.6, <0.14"

Module module.web.module.gke (from
terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster-update-variant)
does not support Terraform version 0.14.0. To proceed, either choose another
supported Terraform version or update this version constraint. Version
constraints are normally set for good reason, so updating the constraint may
lead to other errors or unexpected behavior.
```

**Comment by bharathkkb** [comment]
Hi @cooperbenson-qz 
Happy to accept a PR to relax this. Example PR https://github.com/terraform-google-modules/terraform-google-project-factory/pull/505

**Comment by bharathkkb** [comment]
fixed via #757

**Comment by cpumanaz** [comment]
@bharathkkb What is the lag time before the module update is available:
https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest

Just wondering if this is CI, or if there is another step that needs to be accomplished.

Thanks.

**Comment by bharathkkb** [comment]
Hi @cpumanaz
It is automatically picked up by the registry after a release. I just cut a release for [v12.2](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/releases/tag/v12.2.0) that has this fix.
