### ISSUE TITLE
Computed attribute cannot be set in Terraform

### ISSUE THREAD

**Issue by tvvignesh** [terraform-google-modules/terraform-google-kubernetes-engine#760]
Hi. I just upgraded to the latest version of Terraform `v0.14` and tried using the `beta-private-cluster-update-variant` module which used to work well in the previous version. When doing so, I get this error:

<img width="465" alt="1" src="https://user-images.githubusercontent.com/1165845/101389125-f80a7300-38e6-11eb-88fd-9f644f7e4c25.PNG">

and a warning asking me to move the provider version to `required_providers` which I did.

And if I comment out the node_pool block, I get this error strangely:

<img width="442" alt="2" src="https://user-images.githubusercontent.com/1165845/101390966-a6171c80-38e9-11eb-8fe8-1a048eea1561.PNG">

Any changes I have to make to get this to work with `0.14`? Thanks.

**Comment by bharathkkb** [comment]
Hi @tvvignesh 
I think this might be a core issue that was fixed by https://github.com/hashicorp/terraform/pull/27141. 
We do make use of ignore_changes within the module https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/2e4f36aef7da1840303ff0a445acc6b560aa8a7c/modules/beta-private-cluster-update-variant/cluster.tf#L191

**Comment by tvvignesh** [comment]
@bharathkkb Hmm. Was just looking at it 😅 Any workarounds? Or should I roll back to 0.13?

**Comment by tvvignesh** [comment]
Never mind. I will roll back to 0.13 and come back to 0.14 once they release it. Hope it will work without changing anything. Thanks.

**Comment by bharathkkb** [comment]
@tvvignesh I was able to repro the error and removing `ignore_changes` does allow it to proceed but not recommended as it will create unintended changes. However, this does confirm that it is probably related to the upstream issue. I will keep this issue open to check with the next patch release of 0.14.

**Comment by tvvignesh** [comment]
@bharathkkb Thanks for the clarification 🙂 No issues since this is not a blocker for me. I will wait till the new version of the core is released. Some day I have to read through the code within all my modules. I don't even know what is happening within 😂

**Comment by ivanblack19** [comment]
Extremely fix needed to be able to run with 0.14.1 since current one is not working 

```
Error: Error running command 'PATH=/google-cloud-sdk/bin:$PATH
modules/edge-cluster/modules/beta-private-cluster/scripts/wait-for-cluster.sh xxxxxxxxx
': exit status 1. Output: Waiting for cluster xxxxxxxx/asia-southeast1/xxxxxxxxx-asia-southeast1 to reconcile...
modules/edge-cluster/modules/beta-private-cluster/scripts/wait-for-cluster.sh: line 35: gcloud: command not found
Unable to get status for xxxxxxxxx/asia-southeast1/xxxxxxxx-asia-southeast1
```

**Comment by bharathkkb** [comment]
Hi @ivanblack19 I dont think this issue is related. Do you have gcloud installed where you are running this TF config, if not you can have this module download it by following [these instructions](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine#gcloud) or you can skip provisioners all together by setting `skip_provisioners = true`

**Comment by bharathkkb** [comment]
@tvvignesh wanted to check in if you were able to test with the new 0.14 release.

**Comment by tvvignesh** [comment]
@bharathkkb Didn't notice that there was a new release. I will test it out now and report back.

**Comment by tvvignesh** [comment]
@bharathkkb Just upgraded and tested it out now with `0.14.2` and everything seems to be working properly now. 

Awesome. Closing this.
