### ISSUE TITLE
Removing a node pool causes cycle

### ISSUE THREAD

**Issue by ctrox** [terraform-google-modules/terraform-google-kubernetes-engine#767]
After creating a cluster with multiple node pools and then trying to remove one of the node pools, I get the following Terraform error:

> Error: Cycle: module.gke.module.gcloud_wait_for_cluster.null_resource.module_depends_on[0], module.gke.google_container_node_pool.pools["pool-02"] (destroy), module.gke.random_id.name["pool-02"] (destroy), module.gke.module.gcloud_delete_default_kube_dns_configmap.module.gcloud_kubectl.null_resource.module_depends_on[0]

I have tested this with the latest module version, Terraform 0.13.5 and 0.14.2 both resulting in the same error. I was able to reproduce the error with this simple cluster config (I just slightly changed one of the examples):

```terraform
module "gke" {
  source                            = "../../modules/beta-public-cluster-update-variant/"
  project_id                        = var.project_id
  name                              = "${local.cluster_type}-cluster${var.cluster_name_suffix}"
  region                            = var.region
  zones                             = var.zones
  network                           = var.network
  subnetwork                        = google_compute_subnetwork.gke_cluster_subnet.name
  ip_range_pods                     = google_compute_subnetwork.gke_cluster_subnet.secondary_ip_range[0].range_name
  ip_range_services                 = google_compute_subnetwork.gke_cluster_subnet.secondary_ip_range[1].range_name
  create_service_account            = false
  remove_default_node_pool          = true
  disable_legacy_metadata_endpoints = false

  node_pools = [
    {
      name         = "pool-01"
      min_count    = 1
      max_count    = 2
      auto_upgrade = true
    },
    {
      name         = "pool-02"
      min_count    = 1
      max_count    = 2
      auto_upgrade = true
    },
  ]
}
```

This was applied and on a subsequent apply, I just removed the second element in `node_pool` and ran a `terraform apply` again. This is where I ran into the above error. I was able to work around the issue by commenting out [this line](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/beta-public-cluster-update-variant/cluster.tf#L508).

**Comment by bharathkkb** [comment]
Hi @ctrox 
Thanks for the report, seems related to this https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/690
I'll take a look, could you test a native module depends on with 0.13/4.x to see if that fixes the issue.

**Comment by thirdeyenick** [comment]
Hi @bharathkkb ,
could you please explain a bit more what a native module depends on means as there is already a module_depends_on in use [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/2c4a2b11b9be01c392c9d3a0c5c720973dbffebf/modules/beta-public-cluster-update-variant/cluster.tf#L506)? Thanks

**Comment by thirdeyenick** [comment]
Sorry, ignore my last comment. I mixed up `module_depends_on` with `depends_on`.

**Comment by thirdeyenick** [comment]
So I used a native depends_on instead of [the module_depends_on here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/2c4a2b11b9be01c392c9d3a0c5c720973dbffebf/modules/beta-public-cluster-update-variant/cluster.tf#L506). When I do a `terraform plan` with (terraform version 0.13.5) I am getting this:

```bash
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
module.gke.data.google_container_engine_versions.region: Refreshing state...
module.gke.data.google_compute_zones.available: Refreshing state...
module.gke.data.google_client_config.default: Refreshing state...
module.gke.data.google_container_engine_versions.zone: Refreshing state...
------------------------------------------------------------------------
Error: Invalid count argument
  on .terraform/modules/gke.gcloud_wait_for_cluster/main.tf line 57, in resource "random_id" "cache":
  57:   count = (! local.skip_download) ? 1 : 0
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

which seems to correlate to [this bug](https://github.com/terraform-google-modules/terraform-google-gcloud/issues/82). I get the same error when testing with terraform 0.14.2.

**Comment by thirdeyenick** [comment]
Hi @bharathkkb ,
can we do anything here to help with this issue?

**Comment by bharathkkb** [comment]
Hi @thirdeyenick 
Apologies for the late response. Since it is blocked by https://github.com/terraform-google-modules/terraform-google-gcloud/issues/82, as a workaround could you try setting `skip_provisioners = true` which will disable the gcloud module?

**Comment by grugnog** [comment]
@bharathkkb I tried out `skip_provisioners = true` - while this disables the gcloud module functionality, it doesn't disable the module_depends_on null resource within it, leaving the following cycle:
```module.gke.google_container_node_pool.pools["general-node-pool-a"] (destroy deposed ...)
module.gke.module.gcloud_delete_default_kube_dns_configmap.module.gcloud_kubectl.var.module_depends_on (expand)
module.gke.module.gcloud_delete_default_kube_dns_configmap.module.gcloud_kubectl.null_resource.module_depends_on (expand)
module.gke.module.gcloud_delete_default_kube_dns_configmap.module.gcloud_kubectl.null_resource.module_depends_on[0]
module.gke.module.gcloud_wait_for_cluster.var.module_depends_on (expand)
module.gke.module.gcloud_wait_for_cluster.null_resource.module_depends_on (expand)
module.gke.module.gcloud_wait_for_cluster.null_resource.module_depends_on[0]
module.gke.google_container_node_pool.pools["general-node-pool-b"] (destroy)
module.gke.random_id.name["general-node-pool-b"] (destroy)
module.gke.google_container_node_pool.pools["general-node-pool-a"]
module.gke.module.gcloud_delete_default_kube_dns_configmap.var.module_depends_on (expand)```

Not sure if there are other workarounds to try?

**Comment by clgx-skakauridze** [comment]
Having the same problem in here @bharathkkb

**Comment by walkamongus** [comment]
I am running into this issue when removing a node pool and `skip_provisioners = true` does not work around the problem.
