### ISSUE TITLE
Autoscaling broken `does not have an attribute named "autoscaling_resource_limits".`

### ISSUE THREAD

**Issue by rchenzheng** [terraform-google-modules/terraform-google-kubernetes-engine#768]
It seems that the autoscaling part is broken, I also fixed the typo in the module on my forked version from `autoscalling_resource_limits` to `autoscaling_resource_limits`

This is what I have defined in the module:

Module

```
locals {

.
.
.

  autoscaling_resource_limits = var.cluster_autoscaling.enabled ? [{
    resource_type = "cpu"
    minimum       = var.cluster_autoscaling.min_cpu_cores
    maximum       = var.cluster_autoscaling.max_cpu_cores
    }, {
    resource_type = "memory"
    minimum       = var.cluster_autoscaling.min_memory_gb
    maximum       = var.cluster_autoscaling.max_memory_gb
  }] : []
}

resource "google_container_cluster" "cluster" {
.
.
.

    cluster_autoscaling {
    enabled = var.cluster_autoscaling.enabled
    dynamic "resource_limits" {
      for_each = local.autoscaling_resource_limits
      content {
        resource_type = lookup(resource_limits.value, "resource_type")
        minimum       = lookup(resource_limits.value, "minimum")
        maximum       = lookup(resource_limits.value, "maximum")
      }
    }
  }



}
```

```
 cluster_autoscaling = {
  enabled       = true,
  max_cpu_cores = 0,
  min_cpu_cores = 0,
  max_memory_gb = 0,
  min_memory_gb = 0
  }
```

Error:

```
  on main.tf line 59, in resource "google_container_cluster" "cluster":
  59:       for_each = local.autoscaling_resource_limits

This object does not have an attribute named "autoscaling_resource_limits".
```

Versions:

```
Terraform v0.12.23
+ provider.google v2.20.3
+ provider.kubernetes v1.13.3
+ provider.random v3.0.0
+ provider.template v2.2.0
```

**Comment by morgante** [comment]
Sorry, are you using a forked version?

If you correct the typo, you need to do it in the source as well.

**Comment by rchenzheng** [comment]
> Sorry, are you using a forked version?
> 
> If you correct the typo, you need to do it in the source as well.

Yes I did and referred it using ?ref=my-fork

**Comment by morgante** [comment]
Ok, so just to be clear do you get that error when referencing the module itself (our master version) or only your fork?

If you update line 59, you also need to update the local definition: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/685a2db99f5943c2f74f931cde6923e596896d02/modules/beta-private-cluster/main.tf#L51

It seems like you only updated one.

**Comment by rchenzheng** [comment]
> Ok, so just to be clear do you get that error when referencing the module itself (our master version) or only your fork?
> 
> If you update line 59, you also need to update the local definition:
> 
> https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/685a2db99f5943c2f74f931cde6923e596896d02/modules/beta-private-cluster/main.tf#L51
> 
> It seems like you only updated one.

I forked off master, fixed the typo and tested. I added my modifications to it


```
locals {

.
.
.

  autoscaling_resource_limits = var.cluster_autoscaling.enabled ? [{
    resource_type = "cpu"
    minimum       = var.cluster_autoscaling.min_cpu_cores
    maximum       = var.cluster_autoscaling.max_cpu_cores
    }, {
    resource_type = "memory"
    minimum       = var.cluster_autoscaling.min_memory_gb
    maximum       = var.cluster_autoscaling.max_memory_gb
  }] : []
}

resource "google_container_cluster" "cluster" {
.
.
.

    cluster_autoscaling {
    enabled = var.cluster_autoscaling.enabled
    dynamic "resource_limits" {
      for_each = local.autoscaling_resource_limits
      content {
        resource_type = lookup(resource_limits.value, "resource_type")
        minimum       = lookup(resource_limits.value, "minimum")
        maximum       = lookup(resource_limits.value, "maximum")
      }
    }
  }



}
```

**Comment by morgante** [comment]
Ok so what's the error?

**Comment by rchenzheng** [comment]
> Ok so what's the error?

```

This object does not have an attribute named "autoscaling_resource_limits".
```

**Comment by morgante** [comment]
On `master` nothing at all refers to `autoscaling_resource_limits` so this is an issue with your fork: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/search?q=autoscaling_resource_limits

**Comment by rchenzheng** [comment]
> On `master` nothing at all refers to `autoscaling_resource_limits` so this is an issue with your fork: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/search?q=autoscaling_resource_limits

It's referred in the main.tf https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/5623d51885b5d3ed44b29264ae86b5d537feb506/main.tf#L51

How does one go about defining autoscaling?

**Comment by morgante** [comment]
Config like this should work:

```
 cluster_autoscaling = {
  enabled       = true,
  max_cpu_cores = 0,
  min_cpu_cores = 0,
  max_memory_gb = 0,
  min_memory_gb = 0
  }
  ```
