### ISSUE TITLE
how to import a gke cluster

### ISSUE THREAD

**Issue by IamGabrielWu** [terraform-google-modules/terraform-google-kubernetes-engine#772]
my gke cluster name is gke-pro-xxx-1
And i tried running import command as follow.
```
terragrunt import terraform-google-modules.terraform-google-kubernetes-engine gke-pro-xxx-1
```

Please correct me if it's in wrong use.
I believe ```terragrunt import terraform-google-modules.terraform-google-kubernetes-engine gke-pro-xxx-1``` will download  and use this module from internet.  I don't need to clone it into my source code, right ?

And ```terragrunt import terraform-google-modules.terraform-google-kubernetes-engine gke-pro-xxx-1``` will it import all gke resources into my state file ?

**Comment by bharathkkb** [comment]
Hi @IamGabrielWu 
I am not familiar with `terragrunt import` but assuming it works like `terraform import` it could be something like `terraform import module.gke. google_container_cluster.primary projects/my-gcp-project/locations/us-central1/clusters/my-cluster` for a config like below
```hcl
module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google"
  project_id                 = "my-gcp-project"
  name                       = "my-cluster"
  region                     = "us-central1"
```

**Comment by bharathkkb** [comment]
Feel free to reopen if this is still an issue.

**Comment by dotfree** [comment]
Terraform main.tf for achiving the same

provider "google" {

    credentials = file("~/gcpserv/mbcamp2021-terraform-admin.json")
    project = "mbcamp2021"
}

resource "google_container_cluster" "default" {
  name        = "autopilot-cluster-1"
  project     = "mbcamp2021"
  description = ""
  location    = "australia-southeast1"

  remove_default_node_pool = true
  initial_node_count       = 1

  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
      
      
    }
  }
}

resource "google_container_node_pool" "default" {
  
  project     = "mbcamp2021"
  
  location    = "australia-southeast1"
  cluster    = google_container_cluster.default.name
  node_count = 1

  autoscaling {
    min_node_count = 1
    max_node_count = 3
  }

  
}
