### ISSUE TITLE
How to add node config with linux_node_config

### ISSUE THREAD

**Issue by namcxn** [terraform-google-modules/terraform-google-kubernetes-engine#775]
how to use `linux_node_config` in resource [google_container_cluster](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#linux_node_config)?

Tks

**Comment by bharathkkb** [comment]
Hi @namcxn 
This has not been added to the module yet, but we have a tracking issue here https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/715
Happy to review a PR
