### ISSUE TITLE
creating node groups at the same time causes repairing

### ISSUE THREAD

**Issue by matti** [terraform-google-modules/terraform-google-kubernetes-engine#776]
![image](https://user-images.githubusercontent.com/3893/103914679-e0efb880-5112-11eb-8d9f-679d3b05b8e5.png)

from https://www.reddit.com/r/googlecloud/comments/gewqaq/brand_new_gke_cluster_goes_straight_into/g63g98e/

**Comment by morgante** [comment]
I believe the reason is that clusters are initially "small" but when two node pools are created, a larger master is needed so the cluster needs to be updated to support that.

This isn't related to the module though, it's GCP API behavior.

**Comment by matti** [comment]
thanks, you are most likely right.

**Comment by matti** [comment]
although imo gke says "upgrading", not "repairing"
