### ISSUE TITLE
Disabling pod security policy is failing

### ISSUE THREAD

**Issue by dimilov** [terraform-google-modules/terraform-google-kubernetes-engine#783]
terraform: v0.12.28
gke module: 12.3.0
source: terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster

Setting **enable_pod_security_policy = true** - enables admission controller and works fine. 
After enabling the admission controller setting  **enable_pod_security_policy = fasle** fails with error 

`module.gke.google_container_cluster.primary: Still modifying... [id=projects/***********/locations/...west2/clusters/*****************, 20s elapsed]

Error: googleapi: Error 400: Must specify a field to update., badRequest`

**Comment by morgante** [comment]
This sounds like a provider bug. Please open an issue there.

**Comment by nabiltntn** [comment]
@vilovgh Hi, Were you able to solve this issue ? still facing it in module version 23.3 and provider version 4.42 ?
thank

**Comment by Shelby-Jiao** [comment]
@morgante @vilovgh same issue in module 25.0, provider version 4.84, seems it's shouldn't be a`[]` when we set `enable_pod_security_policy = false`
