### ISSUE TITLE
Module should expose more Kubernetes auth related outputs

### ISSUE THREAD

**Issue by xingao267** [terraform-google-modules/terraform-google-kubernetes-engine#789]
Expose resource output [master_auth.0.client_certificate](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#master_auth.0.client_certificate) and [master_auth.0.client_key](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#master_auth.0.client_key) as module output.

In some cases, these two values also need to be supplied in the `kubernetes` provider configs for authentication purpose, but they are currently not exposed by the module. The workaround we use is to specify another [google_container_cluster](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/container_cluster) data resource to fetch those values aside from the module. It would be convenient to just output those from the module.

**Comment by xingao267** [comment]
cc @jordan83

**Comment by bharathkkb** [comment]
@xingao267 we should not be using client cert to auth https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#restrict_authn_methods
Any reason why you need these to auth? You should be able to use just the ca cert and access token for k8s/helm providers.

**Comment by xingao267** [comment]
Thanks @bharathkkb for the pointers. Yes, client cert are not necessary.
