### ISSUE TITLE
Recreating cluster causes name collision (beta-private-cluster-update-variant)

### ISSUE THREAD

**Issue by jordan83** [terraform-google-modules/terraform-google-kubernetes-engine#791]
Updates to the module configuration which force the cluster to be destroyed and recreated cause name collisions because it seems like the new cluster is created before the old one is destroyed.

This can be worked around by doing a `terraform destroy` then `terraform apply`  but depending on your deployment that is not always practical.

**Comment by morgante** [comment]
Can you paste the exact error message / resource where this occurs?

Also which module version / submodule are you using?
