### ISSUE TITLE
authenticator_groups_config=gke-security-groups@ triggers creation failure with "Error: googleapi: Error 404: Not found: GAIA email lookup., notFound"

### ISSUE THREAD

**Issue by hayorov** [terraform-google-modules/terraform-google-kubernetes-engine#793]
Some examples (latest) were reported here https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/34 I believe non-relevant to that issue (VPC shared)

# Problem statement

Starting from some January 2021 (google API change?), GKE cluster creation API responses with Error: googleapi: Error 404: Not found: GAIA email lookup., notFound

After debugging, I fired out that an option `authenticator_groups_config` that allows defining Google Group in your domain, named gke-security-groups@yourdomain.com

in my case,  when I define set the parameter to gke-security-groups@MYORG it raises an error:

# Environment
- terraform 0.14.x
- provider 3.51.x
- terraform-gogole-kubernetes-engine 11.x

TF_LOG logs

- API response
```
2021-01-25T05:08:28.550Z  {
2021-01-25T05:08:28.550Z  "error": {
2021-01-25T05:08:28.550Z  "code": 404,
2021-01-25T05:08:28.550Z  "message": "Not found: GAIA email lookup.",
2021-01-25T05:08:28.550Z  "errors": [
2021-01-25T05:08:28.550Z 

{ 2021-01-25T05:08:28.550Z  "message": "Not found: GAIA email lookup.", 2021-01-25T05:08:28.550Z  "domain": "global", 2021-01-25T05:08:28.550Z  "reason": "notFound" 2021-01-25T05:08:28.550Z  }
2021-01-25T05:08:28.550Z  ],
2021-01-25T05:08:28.550Z  "status": "NOT_FOUND"
2021-01-25T05:08:28.550Z  }
```

# Possible fix
Google updated (Last updated 2021-01-20 UTC.) the doc about `gke-security-groups` https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#groups-setup-gsuite. Looks like gke-security-groups@ does not exist anymore and must be created by the user.

```
Create a Google Group in your domain, named gke-security-groups@yourdomain.com. The group must be named exactly gke-security-groups. Make sure the gke-security-groups group has the "View Members" permission for "Group Members".
```

**Comment by morgante** [comment]
Since this is action you need to take on your side (and the Google documentation covers it), there's no action to be taken on this module.
