### ISSUE TITLE
Not able to specify scopes for node template 

### ISSUE THREAD

**Issue by wrogrammer** [terraform-google-modules/terraform-google-kubernetes-engine#795]
I'm not able to add additional scope to the service account in the GKE node.

After the creation of GKE, the nodes have only default scope to use all Cloud APIs -> 

```
Cloud API access scopes
Allow full access to all Cloud APIs
``` 
in the node details. 

I need to add in the ```node_config``` variable to set up the scopes. 

```gcloud compute instances describe gke-node-1 --format "json"```

```
  "selfLink": "https://www.googleapis.com/compute/v1/projects/.../zones/europe-.../instances/gke-node-1
  "serviceAccounts": [
    {
      "email": "...@....iam.gserviceaccount.com",
      "scopes": [
        "https://www.googleapis.com/auth/cloud-platform"
      ]
    }
  ],
  ```

**Comment by morgante** [comment]
You can use the `node_pools_oauth_scopes` variable.
