### ISSUE TITLE
customizing more tunables in safer-cluster-iap-bastion module

### ISSUE THREAD

**Issue by shermanericts** [terraform-google-modules/terraform-google-kubernetes-engine#797]
Hey there!
Sorry this may be a naive question, somewhat newer to terraform and these modules.  Looks great!

So I'm quite interested in the safer-cluster-iap-bastion module.
I see there are some parameters such as region,cluster_name, etc.

Is there any way to customize/add additional tunables such as `machine_type` and `zones`?  I could see that being useful in the future.

If not, no worries I can make do. 
Thanks in advance!

**Comment by bharathkkb** [comment]
Hi @shermanericts 
The suggested approach with `examples/` is to fork/clone to tweak the code and not use it as a module. Feel free to reopen if needed.

**Comment by shermanericts** [comment]
sounds great. thanks!
