### ISSUE TITLE
wait-for-cluster.sh permission issue during validation when running from Terraform Enterprise

### ISSUE THREAD

**Issue by Sinble** [terraform-google-modules/terraform-google-kubernetes-engine#798]
Getting the below error when trying to build a private cluster on Terraform Enterprise. 

```
ERROR: (gcloud.container.clusters.list) ResponseError: code=403, message=Required "container.clusters.list" permission(s) for "projects/**********".
```

I can only set environment variables and I'm not in control of the machine in which terraform runs. I have set GOOGLE_CREDENTIALS which allows for the build of the cluster but when it comes to the wait-for-cluster.sh script I get the above permission problem. Inspecting the file it looks like its using application default credentials which can be set only by providing a file?

I have a work around but would like to see if it can be pulled in our you guys have a better solution. Submitting my PR for review.

**Comment by morgante** [comment]
Thanks for looking into this. I think we probably actually want to address this directly in the gcloud module: https://github.com/terraform-google-modules/terraform-google-gcloud/issues/87
