### ISSUE TITLE
Remove wait-for-cluster.sh

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-kubernetes-engine#800]
In the provider we already[ check that cluster is in a ready state](https://github.com/hashicorp/terraform-provider-google/blob/287a89e3c5086bdb484871b3973a523b5f014672/google/resource_container_cluster.go#L2358) before return both after cluster creation  and [recently after nodepool creation](https://github.com/GoogleCloudPlatform/magic-modules/pull/4256) which should catch the cases of resizes for bigger nodepools. These should be sufficient to catch most cases.

/cc @morgante

**Comment by morgante** [comment]
Sounds good, let's go ahead and remove the wait. We can add later if it introduces regressions.
