### ISSUE TITLE
Workload-Identity: Allow different names for GCP and K8s service account

### ISSUE THREAD

**Issue by parthmishra** [terraform-google-modules/terraform-google-kubernetes-engine#805]
Is it possible for the workload-identity submodule to support a different name for the K8s service account and the GCP service account upon initial creation i.e. without having to use an existing k8s service account? 

Currently, the provided name is used for both the GCP and K8 service account.  Is there a constraint for why they have to be the same? I get that you can create a separate K8 SA and then use it as an existing one, but it would be convenient to support this all in the same module.

**Comment by morgante** [comment]
In general, I think it's simpler to use the same name for both though there's no fundamental limitation that _requires_ they be the same.

We could accept an update which allows the existing `k8s_sa_name` variable to override the k8s service account name.
