### ISSUE TITLE
Allow setting GPUs limits in cluster autoscaling

### ISSUE THREAD

**Issue by parthmishra** [terraform-google-modules/terraform-google-kubernetes-engine#807]
When configuring node auto-provisioning, it would be helpful to also be able to include GPU-specific resource limits. Currently, this module only allows setting CPU and Memory limits while the [API](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.ResourceLimit) allows for GPU-specific strings. 

I imagine supporting this option may require a slight change to the cluster_autoscaling block since the type is any valid GPU string identifier. Example usage might look something like:

```hcl
cluster_autoscaling = {
    enabled       = true
    min_cpu_cores = 0
    max_cpu_cores = 128
    min_memory_gb = 0
    max_memory_gb = 2000
    min_gpu       = 0
    max_gpu       = 16
    gpu_type      = "nvidia-tesla-k80"
  }
```

Is something like this currently possible? Apologies if this has been asked before. Thanks!

**Comment by morgante** [comment]
No, it's not currently possible, but definitely a good idea.

I don't currently have time to implement this, but we would be happy to review a PR adding it.

**Comment by max-sixty** [comment]
Is this closed by https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/944?

**Comment by morgante** [comment]
Yes, I think so.
