### ISSUE TITLE
Kubernetes Provider v2 Support

### ISSUE THREAD

**Issue by Harjot1Singh** [terraform-google-modules/terraform-google-kubernetes-engine#816]
Hi!

Any plans to support the new 2.x Kubernetes provider?

The upgrade path doesn't look too bad: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide.

**Comment by bharathkkb** [comment]
Hi @Harjot1Singh 

Happy to review a PR with the update.

**Comment by Harjot1Singh** [comment]
Brilliant! Would you like me to version bump the module in the PR? Or will you cut the release separately?

**Comment by lhriley** [comment]
Curious if there has been any progress on this in the last ~2 months. The provider is still locked at `1.x`:
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/e853cdd94b81dd114f9a71b49e7ef4e15c0dbdf3/versions.tf#L28

**Comment by morgante** [comment]
No progress as it's still on our backlog, but we'd be happy to review a PR.

**Comment by lhriley** [comment]
Unfortunately, I don't have the bandwidth to tackle all of the testing required before submitting a PR for this, or I would be more than happy to write something up.

**Comment by Harjot1Singh** [comment]
I did fork and make the change to get the bare minimum running here: https://github.com/Harjot1Singh/terraform-google-kubernetes-engine

Haven't run it against the test criteria, but if https://github.com/Harjot1Singh/terraform-google-kubernetes-engine/commit/768d5b674f76c2491aac3ebddcfb381fd78fbc35 looks suitable then can PR it in. For other folks trying to get this to work meanwhile, set `source = "github.com/Harjot1Singh/terraform-google-kubernetes-engine"`

**Comment by morgante** [comment]
@Harjot1Singh Thanks, those look to be along the lines of what we'd need but note the updates need to be made in `autogen/` first.

**Comment by DrFaust92** [comment]
@apeabody  this can be closed

**Comment by apeabody** [comment]
Updated in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/892
