### ISSUE TITLE
Enable global access for private clusters

### ISSUE THREAD

**Issue by nstogner** [terraform-google-modules/terraform-google-kubernetes-engine#820]
Expose the ability to enable global access for `modules/private-cluster/`.

https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#cp-global-access
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#master_global_access_config

**Comment by darkn3rd** [comment]
There are some examples of these:
* [Shared VPC Cluster Example](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/shared_vpc)
* [Simple Regional Private Cluster](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/simple_regional_private) 
* [Simple Regional Private Cluster with Beta Features](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/simple_regional_private_beta)
* [Private Cluster Docs](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/private_clusters.md)

**Comment by nstogner** [comment]
Closing, looks like this is enabled on the beta version: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/beta-private-cluster
