### ISSUE TITLE
kubectl_destroy_command is incorrect

### ISSUE THREAD

**Issue by Aricg** [terraform-google-modules/terraform-google-kubernetes-engine#826]
as you can see the destroy command is truncated.

kubectl_destroy_command = "kubectl annotate sa -n ${local.output_k8s_namespace} ${local.k8s_given_name} iam.gke.io/gcp-service-account-"

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/5562cd6c993166aa6b0f89b53b618a95f0b14e72/modules/workload-identity/main.tf#L59

**Comment by bharathkkb** [comment]
@Aricg the minus at the end should remove the annotation, did this throw an error?

**Comment by Aricg** [comment]
Uh... yes it was.... But I have cleared out my environment and it is no longer happening.
I will close this out, thanks for the feedback.

**Comment by bharathkkb** [comment]
Gotcha, we are using [this method](https://github.com/ahmetb/kubernetes.github.io/blame/master/docs/user-guide/kubectl/kubectl_annotate.md#L73), feel free to reopen if it pops up again
