### ISSUE TITLE
Autoscaling cannot be disabled

### ISSUE THREAD

**Issue by nixsticks** [terraform-google-modules/terraform-google-kubernetes-engine#83]
It appears that users must either specify `min_node_count` and `max_node_count` or have them default to 1 and 100; the `autoscaling` block is always created. Is this by design, or might we in future be able to specify a static node count and disable autoscaling?

**Comment by morgante** [comment]
Autoscaling is our best practice by default - do you have a use case where specifying max_node_count isn't sufficient?

**Comment by nixsticks** [comment]
Hi @morgante! That's my current workaround, yes -- but one use case where it's insufficient is where we want to freeze the current nodepool at zero without additional commands, and prevent it from spinning up new nodes, since `max_node_count` must be at least 1.

**Comment by morgante** [comment]
Got it - unfortunately it's tough to have a conditional block in Terraform. If this is a major issue, could you file a provider bug requesting a disabled/enabled flag on the autoscaling block? If there is one, we'd be happy to add it to the module.

**Comment by aaron-lane** [comment]
Hi @nixsticks. Would you like to proceed with an issue on the Google provider or can we close this issue?

**Comment by nixsticks** [comment]
Hey @aaron-lane , sorry I didn't follow up on this! We've managed to work around it for now, so no need to file a provider bug / add to the module, I think.
