### ISSUE TITLE
modules/workload-identity - cluster name should not be required if annotate-sa disabled

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-kubernetes-engine#833]

**Comment by morgante** [comment]
@naseemkullah While it's not strictly necessary, is this actually an issue? I'm inclined to keep the interface more consistent where we can.

**Comment by naseemkullah** [comment]
Hi @morgante!

The following assumes service annotation is done outside of this module.

I think the workload identity binding need not share the lifecycle of a cluster, i.e. the GSA and binding can be done before the cluster and the KSA are deployed. Then that cluster and KSA can be recreated and so on.

Furthermore in a situation where same KSA is on many clusters, which cluster do we say it belongs to?

I have not tried  (am about to) but could we put a dummy cluster name?

**Comment by morgante** [comment]
Can you try passing an empty string? I think that might work.

**Comment by naseemkullah** [comment]
Setting an empty string for both cluster and location worked like a charm! Thanks @morgante
