### ISSUE TITLE
Autopilot Support

### ISSUE THREAD

**Issue by cmcga1125** [terraform-google-modules/terraform-google-kubernetes-engine#835]
So, when can we expect to see some [Autopilot](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview) Enabled Cluster Terraform :)

**Comment by cmcga1125** [comment]
FWIW: i went digging around this morning the GCP provider and i don't see it mentioned anywhere, but did find this related issue:
https://github.com/hashicorp/terraform-provider-google/issues/8553

**Comment by hcharley** [comment]
Note that upstream of the GCP provider is the GCP Go library. [It was just updated](https://github.com/googleapis/google-api-go-client/pull/875):

https://github.com/hashicorp/terraform-provider-google/issues/8553#issuecomment-794156420

**Comment by cmcga1125** [comment]
anyone watching this, i was able to manually click a cluster into existence, then use a data object to let us start using it. like this:
```
data "google_container_cluster" "gke" {
  name     = local.cluster_name
  location = local.region
  project = local.project_id
}
data "google_client_config" "default" {
}
provider "kubernetes" {
  # load_config_file       = false
  host                   = "https://${data.google_container_cluster.gke.private_cluster_config.0.public_endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(data.google_container_cluster.gke.master_auth.0.cluster_ca_certificate)
}
```

**Comment by paulwilljones** [comment]
https://github.com/hashicorp/terraform-provider-google/pull/8632

**Comment by cmcga1125** [comment]
i'll take a stab at updating the modules here :)

**Comment by groksrc** [comment]
FWIW, it looks like when you enable autopilot with the `enable_autopilot` it prevents you from being able to specify a custom service account. To me that's a bit of a blocker.

**Comment by BenCoughlan15** [comment]
> FWIW, it looks like when you enable autopilot with the `enable_autopilot` it prevents you from being able to specify a custom service account. To me that's a bit of a blocker.

Have you tried using workload identity, and SA's per service?

**Comment by dahlmo** [comment]
Seems support for this was added in `v3.63.0`? 

https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.63.0

**Comment by cmcga1125** [comment]
This is live!
