### ISSUE TITLE
using the workload identity module with a private cluster

### ISSUE THREAD

**Issue by shermanericts** [terraform-google-modules/terraform-google-kubernetes-engine#836]
Hey there!

I'm trying to leverage the [workload identity module](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/workload-identity) with a [private cluster](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/safer_cluster).

One of the errors I get is a timeout like so when running the workload-identity module.  
```
Error: Post "https://10.0.0.2/api/v1/namespaces/tausight/serviceaccounts": dial tcp 10.0.0.2:443: i/o timeout

  on .terraform/modules/zzz-dev-workload-identity/modules/workload-identity/main.tf line 35, in resource "kubernetes_service_account" "main":
  35: resource "kubernetes_service_account" "main" {
```

I may be off, but I'm wondering if this is because it cannot resolve [these kubectl commands](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/workload-identity/main.tf#L58-L59)

any pointers most welcome.
thanks!

**Comment by bharathkkb** [comment]
Hi @shermanericts 
When utilizing WI module, you will need to have direct network connectivity to the control plane to be able to annotate the KSA. You can run the TF config in a VM that has access, more info [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/private_clusters.md#private-cluster-endpoints). Feel free to reopen if needed.

**Comment by shermanericts** [comment]
thank you @bharathkkb , super helpful!
