### ISSUE TITLE
Upgrade from v12.3.0 -> v13.0.0 wants to replace node-pool

### ISSUE THREAD

**Issue by raj-saxena** [terraform-google-modules/terraform-google-kubernetes-engine#842]
We are on `v12.3.0` and want to upgrade to the latest `v14.0.0`.

We don't see any changes when running `terraform plan` on version  `v12.3.0` but when we run the same with `v13.0.0`, terraform wants to replace the node-pool.

```terraform
  # module.gke.module.private-gke-k8s-with-nat.module.gke.google_container_node_pool.pools["gke-cluster-node-pool"] must be replaced
+/- resource "google_container_node_pool" "pools" {
      ~ id                  = "projects/myproject-staging/locations/europe-west3-a/clusters/tf-gke-cluster-staging/nodePools/gke-cluster-node-pool-04b2" -> (known after apply)
      ~ instance_group_urls = [
          - "https://www.googleapis.com/compute/v1/projects/myproject-staging/zones/europe-west3-a/instanceGroupManagers/gke-tf-gke-cluster-s-gke-cluster-node-764e5a78-grp",
        ] -> (known after apply)
      ~ max_pods_per_node   = 110 -> (known after apply)
      ~ name                = "gke-cluster-node-pool-04b2" -> (known after apply) # forces replacement
      + name_prefix         = (known after apply)
      ~ node_count          = 3 -> (known after apply)
      ~ node_locations      = [
          - "europe-west3-a",
        ] -> (known after apply)
      ~ version             = "1.17.14-gke.400" -> (known after apply)
        # (4 unchanged attributes hidden)



      ~ node_config {
            tags              = [
                "gke-tf-gke-cluster-staging",
                "gke-tf-gke-cluster-staging-gke-cluster-node-pool",
            ]
          ~ taint             = [] -> (known after apply)
            # (11 unchanged attributes hidden)


            # (2 unchanged blocks hidden)
        }


      ~ upgrade_settings {
          ~ max_surge       = 1 -> (known after apply)
          ~ max_unavailable = 0 -> (known after apply)
        }
        # (3 unchanged blocks hidden)
    }


  # module.gke.module.private-gke-k8s-with-nat.module.gke.random_id.name["gke-cluster-node-pool"] must be replaced
+/- resource "random_id" "name" {
      ~ b64_std     = "gke-cluster-node-pool-BLI=" -> (known after apply)
      ~ b64_url     = "gke-cluster-node-pool-BLI" -> (known after apply)
      ~ dec         = "gke-cluster-node-pool-1202" -> (known after apply)
      ~ hex         = "gke-cluster-node-pool-04b2" -> (known after apply)
      ~ id          = "BLI" -> (known after apply)
      ~ keepers     = { # forces replacement
          + "taints"            = ""
            # (12 unchanged elements hidden)
        }
        # (2 unchanged attributes hidden)
    }

```

As you can imagine, this would be disruptive to the running workloads & hence unacceptable.

Any suggestions?

**Comment by raj-saxena** [comment]
Bug introduced here https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/717 as [commented](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/717#issuecomment-780066135) by @jmymy 
> FYI this forces recreation of all node pools since the random_id has a change
> 
> ```
> +/- resource "random_id" "name" {
>       ~ b64_std     = "pool-01-XXX=" -> (known after apply)
>       ~ b64_url     = "pool-01-XXX" -> (known after apply)
>       ~ dec         = "pool-01-XXXX" -> (known after apply)
>       ~ hex         = "pool-01-XXXX" -> (known after apply)
>       ~ id          = "Thg" -> (known after apply)
>       ~ keepers     = { # forces replacement
>           + "taints"            = ""
>             # (12 unchanged elements hidden)
>         }
>         # (2 unchanged attributes hidden)
>     }
> 
> +/- resource "google_container_node_pool" "pools" {
>       ~ id                  = "<REMOVED/pool-01-XXX" -> (known after apply)
>       ~ instance_group_urls = [ ] -> (known after apply)
>       ~ max_pods_per_node   = 110 -> (known after apply)
>       ~ name                = "pool-01-XXX" -> (known after apply) # forces replacement
> ```

**Comment by morgante** [comment]
@raj-saxena You should be able to work around this by importing the old random ID:

```
terraform import 'module.gke.module.private-gke-k8s-with-nat.module.gke.random_id.name["gke-cluster-node-pool"]' 'gke-cluster-node-pool-,BLI'
```

**Comment by davidholsgrove** [comment]
I ended up doing the following to update the random_id resource in place without trashing existing node-pools;
* `terraform state pull > default.tfstate`
* edit the random_id resources to add in the new `taints` attribute to `keepers` specified as forcing replacement by `terraform plan`
* (bump the serial)
* `terraform state push default.tfstate`

@morgante should this be added as a note to the https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/upgrading_to_v13.0.md guide?

**Comment by morgante** [comment]
@davidholsgrove Yes, I think that would be helpful information. Could you open a pull request to add it?
