### ISSUE TITLE
Error coming while executing the script: Error: value must be known

### ISSUE THREAD

**Issue by jitender1278** [terraform-google-modules/terraform-google-kubernetes-engine#843]
![image](https://user-images.githubusercontent.com/11955901/110728325-d6bd6980-81ea-11eb-9684-a7884fb69f72.png)
Getting the following error when executing Terraform Apply
[9:44 PM] Jitender Kumar
    
module.gke.random_string.cluster_service_account_suffix: Creating...
module.gke.random_string.cluster_service_account_suffix: Creation complete after 0s [id=qplv]
module.gke.random_shuffle.available_zones: Creating...
module.gke.google_service_account.cluster_service_account[0]: Creating...
module.gke.random_shuffle.available_zones: Creation complete after 0s [id=-]

Error: value must be known

**Comment by basphilippus** [comment]
I am also experiencing this issue with version 14.0.0. Pinning the version to 13.1.0 works for me.

**Comment by bharathkkb** [comment]
Hi @jitender1278 @basphilippus 
Could you share an example config I can use to reproduce the issue

**Comment by basphilippus** [comment]
Hi @bharathkkb,

I can reproduce the issue with the following config:
`terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.55.0"
    }
    kubernetes = {
      source = "kubernetes"
      version = "1.13.3"
    }
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.11.0"
    }
  }
}

locals {
  project = terraform.workspace
}

provider "google" {
  project = local.project
  region  = "europe-west1"
  zone    = "europe-west1-b"
}

resource "google_service_account" "tf_gke_service_account" {
  account_id = "tf-gke-test"
  description = "Terraform managed service account for test k8s cluster"
}

# Following three IAM bindings give service account correct permissions for monitoring purposes
# See https://cloud.google.com/stackdriver/docs/solutions/gke/troubleshooting#write_permissions
resource "google_project_iam_member" "tf_gke_service_account-logWriter" {
  role = "roles/logging.logWriter"
  member = "serviceAccount:${google_service_account.tf_gke_service_account.email}"
}

resource "google_project_iam_member" "tf_gke_service_account-metricWriter" {
  role    = "roles/monitoring.metricWriter"
  member = "serviceAccount:${google_service_account.tf_gke_service_account.email}"
}

resource "google_project_iam_member" "tf_gke_service_account-stackdriverDataWriter" {
  role = "roles/stackdriver.resourceMetadata.writer"
  member = "serviceAccount:${google_service_account.tf_gke_service_account.email}"
}

# Add permissions to read images from google cloud registry on ewx-global
resource "google_project_iam_member" "tf_gke_service_account-googleCloudRegistryReader" {
  project = "ewx-global"
  role = "roles/storage.objectViewer"
  member = "serviceAccount:${google_service_account.tf_gke_service_account.email}"
}

module "gke_cluster" {
  // kubernetes-engine module that implements cluster deployment according to google owns opinionated best practices
  // Reference:
  // https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest
  source                     = "terraform-google-modules/kubernetes-engine/google"
  version                    = "14.0.0"
  project_id                 = local.project
  name                       = "test"
  regional                   = false  // CHANGING REGIONAL AFTER CLUSTER CREATION IS DESTRUCTIVE
  region                     = "europe-west1"
  zones                      = ["europe-west1-b", "europe-west1-c", "europe-west1-d"]
  network                    = "default"
  subnetwork                 = "default"
  ip_range_pods              = ""
  ip_range_services          = ""
  http_load_balancing        = false
  horizontal_pod_autoscaling = false
  network_policy             = true
  create_service_account     = false
  service_account            = google_service_account.tf_gke_service_account.email
  remove_default_node_pool   = true

  node_pools = [
    {
      name               = "no-data-pool"
      machine_type       = "e2-standard-2"
      node_locations     = join(",", ["europe-west1-b", "europe-west1-c"])
      min_count          = 1
      max_count          = 5
      local_ssd_count    = 0
      disk_size_gb       = 100
      disk_type          = "pd-standard"
      image_type         = "COS"
      auto_repair        = true
      auto_upgrade       = true
      autoscaling        = true
      preemptible        = false
    },
    {
      name               = "data-pool"
      machine_type       = "e2-highmem-2"
      node_locations     = join(",", ["europe-west1-b", "europe-west1-c"])
      min_count          = 1
      max_count          = 5
      local_ssd_count    = 0
      disk_size_gb       = 100
      disk_type          = "pd-standard"
      image_type         = "COS"
      auto_repair        = true
      auto_upgrade       = true
      autoscaling        = true
      preemptible        = false
    },
    {
      name               = "helper-pool"
      machine_type       = "e2-standard-2"
      node_locations     = "europe-west1-b"
      min_count          = 0
      max_count          = 3
      local_ssd_count    = 0
      disk_size_gb       = 30
      disk_type          = "pd-standard"
      image_type         = "COS"
      auto_repair        = true
      auto_upgrade       = true
      autoscaling        = true
      preemptible        = false
    }
  ]

  node_pools_labels = {
    all = {}

    no-data-pool = {
      default-node-pool = true
      nodeType = "noData"
    }

    data-pool = {
      nodeType = "data"
    }

    helper-pool = {
      nodeType = "helper"
    }
  }
}
`

Let me know if you need anything else.

**Comment by jitender1278** [comment]
yes, 13.1.0 works but 14.0.0 fails. we should get this fixed

**Comment by shanedownes-dmi** [comment]
I started running into this issue recently. In my case, downgrading to 13 alone did not resolve it. I usually use the `-out` flag on the plan command, and then reference it when applying. When I applied without specifying a pre-generated plan file, it worked as expected. 

I suspect that a value is re-evaluated after generating the initial plan. Not sure if it's a bug, or known limitation.

**Comment by bharathkkb** [comment]
@basphilippus thanks, I tried https://gist.github.com/bharathkkb/ef9ee3facfcdc93621964f46ebb9a8eb (your example with minimal modifications) and was able to repro for TF `0.14.5`, works okay with `0.13.5` which is why our CI did not flag this.

@morgante looks like the issue is the dynamic blueprint name, hardcoding that seems to resolve for `0.14.5`

**Comment by rwkarg** [comment]
Would it be a good idea to put a cap on the supported `terraform` version matching the highest version tested in CI?

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/versions.tf#L23

**Comment by morgante** [comment]
@bharathkkb Sounds like a core regression, let's file an upstream bug.

@rwkarg We did that historically but the reality is that in the vast majority of cases it is forward-compatible and people complain when you can't use the latest Terraform version.

**Comment by bharathkkb** [comment]
@morgante will do, after some more debugging seems to only happen when using a local. A quick fix seems to be to remove the locals and do it inline which seems to work on 0.14.5
```
module_name = "blueprints/terraform/${join("/", compact([var._parent_module, "terraform-google-kubernetes-engine/v14.0.0"]))}"
```

**Comment by bharathkkb** [comment]
@basphilippus @jitender1278 @rwkarg @shanedownes-dmi release `14.0.1` should contain the fix for this

**Comment by jitender1278** [comment]
Thank you so much
