### ISSUE TITLE
Module version 13.1 is failing to recreate a deleted cluster, because of kube_dns_configmap module dependency error

### ISSUE THREAD

**Issue by shako92** [terraform-google-modules/terraform-google-kubernetes-engine#852]
We had a cluster, which got accidentally deleted from Console and when we tried to recreate from terraform receiving such error and cluster can not be re-provisioned.

Can you please help us to overcome this issue? 

16:20:56  
16:20:56  Error: Invalid count argument
16:20:56  
16:20:56    on .terraform/modules/project-cluster-gke.gcloud_delete_default_kube_dns_configmap/main.tf line 63, in resource "null_resource" "module_depends_on":
16:20:56    63:   count = length(var.module_depends_on) > 0 ? 1 : 0
16:20:56  
16:20:56  The "count" value depends on resource attributes that cannot be determined
16:20:56  until apply, so Terraform cannot predict how many instances will be created.
16:20:56  To work around this, use the -target argument to first apply only the
16:20:56  resources that the count depends on.

**Comment by morgante** [comment]
I recommend clearing your state entirely:

`terraform state rm module.project-cluster-gke`
