### ISSUE TITLE
Error: "node_config.0.taint" - module doesn't work with 2.0.0 google provider

### ISSUE THREAD

**Issue by mkubaczyk** [terraform-google-modules/terraform-google-kubernetes-engine#86]
```
Error: module.demo-euw1.google_container_node_pool.zonal_pools: "node_config.0.taint": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.test-euw1.google_container_node_pool.zonal_pools: "node_config.0.taint": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.
```

Deprecation warnings from 1.20.0 google provider became errors for 2.0.0, as expected. To fix this we might need to change the way providers are defined inside the module, right? Any quick fix for such thing?

**Comment by morgante** [comment]
The module isn't currently compatible with 2.0.0, so in the interim the only fix is to pin your provider version.

**Comment by mkubaczyk** [comment]
Thanks, @morgante, that is more than enough for now. :-)

**Comment by morgante** [comment]
Closing in favor of #27.

**Comment by wadadli** [comment]
I tried the instructions in #27  and they no longer work.  Did something change?
