### ISSUE TITLE
beta-node-pool-update variant updates node pools, even if nothing changes in node pools?

### ISSUE THREAD

**Issue by lindsjan** [terraform-google-modules/terraform-google-kubernetes-engine#873]
Trying to understand have i picked wrong variant.  

```
module "gke" {
  source     = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster-update-variant"
  version  = "14.0.1"

...

  node_pools = [
    {
      name               = "pool-n1-standard-8"
      machine_type       = "n1-standard-8"
      node_locations     = "europe-north1-a"
      min_count          = 1
      max_count          = 5
      disk_size_gb       = 100
      disk_type          = "pd-ssd"
      image_type         = "COS"
      auto_repair        = true
      auto_upgrade       = true
      preemptible        = false
      initial_node_count = 1
      autoscaling        = true      
    },  
  ]

```

changing something outside node pools, such as enable cloudrun. Outcome when running plan.. cloudrun gets enabled as in-place update like it should but then the node pool gets recreated as well, because pool name changes because its created with random.

```
   module.gke.google_container_node_pool.pools["pool-n1-standard-8"] must be replaced
+/- resource "google_container_node_pool" "pools" {
      ~ id                  = "projects/xxxxx/locations/europe-north1-a/clusters/xxx/nodePools/pool-n1-standard-8-334b" -> (known after apply)
      ~ instance_group_urls = [
          - "https://www.googleapis.com/compute/v1/projects/xxxx/zones/europe-north1-a/instanceGroupManagers/xxxx-pool-n1-standard-8-334b-97c47b62-grp",
        ] -> (known after apply)
      ~ max_pods_per_node   = 64 -> (known after apply)
      ~ name                = "pool-n1-standard-8-334b" -> (known after apply) # forces replacement
      + name_prefix         = (known after apply)
      ~ node_count          = 2 -> (known after apply)
      + operation           = (known after apply)
      ~ version             = "1.18.16-gke.502" -> (known after apply)
        # (5 unchanged attributes hidden)



      ~ node_config {
            tags              = [
                "xxxx",
      
            ]
          ~ taint             = [] -> (known after apply)
            # (11 unchanged attributes hidden)


            # (2 unchanged blocks hidden)
        }


        # (4 unchanged blocks hidden)
    }

 module.gke.random_id.name["pool-n1-standard-8"] must be replaced
+/- resource "random_id" "name" {
      ~ b64_std     = "pool-n1-standard-8-M0s=" -> (known after apply)
      ~ b64_url     = "pool-n1-standard-8-M0s" -> (known after apply)
      ~ dec         = "pool-n1-standard-8-13131" -> (known after apply)
      ~ hex         = "pool-n1-standard-8-334b" -> (known after apply)
      ~ id          = "M0s" -> (known after apply)
      ~ keepers     = { # forces replacement
          + "taints"            = ""
            # (12 unchanged elements hidden)
        }
        # (2 unchanged attributes hidden)

```

Is there a way to limit the node pool recreation only to changes which actually affect the nodes ( such as node_pools - configurations) ?

**Comment by morgante** [comment]
Hmm, what taints do you have specified? Something is changing in the keepers.

**Comment by lindsjan** [comment]
None:

  node_pools_taints = {
    all           = []
    pool-n1-standard-8 = []
  }

in plan:

            ]
          ~ taint             = [] -> (known after apply)
            # (11 unchanged attributes hidden)


            # (2 unchanged blocks hidden)
        }



Could this be due to module version change? We had version 13.3 in use,  no explicit version attribute and now set the module version attribute to 14.0.1.  It does look like that this unwanted node pool change happens only once and can modify now other, non-node pool attributes without node pool recreation. 

The reason for having update variant was the benefit of changing the node pools attributes without causing major distruptions to existing workloads.  If this problem happens again, then maybe have to think again is it worth it.

**Comment by morgante** [comment]
Ahhh, yes this was likely due to a version change (where we had to add additional values to the keepers, more info [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/upgrading_to_v13.0.md#node-pool-random-id-keepers-modified)). It should not happen again.

Sorry for the issue!

**Comment by lindsjan** [comment]
ok, thanks for the info! it helps to know this happens just once.
