### ISSUE TITLE
Using service account impersonation for terraform invoking this module

### ISSUE THREAD

**Issue by yashbhutwala** [terraform-google-modules/terraform-google-kubernetes-engine#874]
I have a use-case where I'm using shared Terraform Cloud Agents, and my TF Cloud workspace is isolated by using service account impersonation, i.e.: the GSA that terraform agent runs terraform by default does not have GKE Admin IAM.  Problem is since this module uses the [kubectl-wrapper](https://github.com/terraform-google-modules/terraform-google-gcloud/tree/master/modules/kubectl-wrapper) module [like this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/1fe90e9e99112ad3fcbd3f87fcc652b7c38ee3bf/dns.tf#L23
), which uses this gcloud command [here](https://github.com/terraform-google-modules/terraform-google-gcloud/blob/master/modules/kubectl-wrapper/scripts/kubectl_wrapper.sh#L52), it uses the agent terraform IAM instead of the impersonating ones, hence not being able to create GKE.  Is there any potential workarounds/idea for such setup?

**Comment by bharathkkb** [comment]
Hi @yashbhutwala 
IIUC your agent GSA has the necessary permissions to impersonate an SA that has GKE Admin IAM? If that is the case, we could add a var in the kubectl-wrapper module to optionally add a `--impersonate-service-account=${var.impersonate_sa}` flag and that can then be exposed here. Related: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/867 we were planning to remove this, but this usecase seems useful.

If you want a quick workaround if you are not interested in stub_domains and upstream_nameservers is to set `skip_provisioners` true.

**Comment by yashbhutwala** [comment]
Yes @bharathkkb you're right! A --impersonate-service-account=${var.impersonate_sa} flag in kubectl-wrapper module is what I need.

Unfortunately, I cannot use skip_provisioner because we do use the stub_domain functionality currently.
