### ISSUE TITLE
New ASM installer script requres curl, which is explicitly removed from CFT build images

### ISSUE THREAD

**Issue by matthewkrupnik** [terraform-google-modules/terraform-google-kubernetes-engine#878]
Hi.

We have recently tried to update from using v12.0.0 of the ASM module to v14.2.0 and we discovered that the new install script requires `curl`:
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/110adb6ba085a028ae4fa6505959ebef464272a3/modules/asm/scripts/install_asm.sh#L32

The script being downloaded also requires `curl`, but we didn't even get that far
https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/0cac367f5dfd945e7cdfd8ad719a688b08acb91b/scripts/asm-installer/install_asm#L1432

v12 of the module was using `kpt` which was being installed as `gcloud` component so there were no issues. If the new version is being used with CFT builder image, there is no `curl` installed. Here's a link to the CFT builder image Dockerfile:
https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/3c21b4695f3a48314bab3ff3804e38f853b1afd1/modules/cloudbuild/cloudbuild_builder/Dockerfile#L37

I keep getting an error saying `curl` was not found and I have to now create a custom build images. Are these modules tested with Google's CFT images?

**Comment by bharathkkb** [comment]
Hi @matthewkrupnik 
Thanks for the detailed report, we should update the bootstrap image to have curl. Closing this as I have opened https://github.com/terraform-google-modules/terraform-google-bootstrap/issues/105 to track.
