### ISSUE TITLE
Enable the use of a service account to install ASM with the module

### ISSUE THREAD

**Issue by alexbrand-au** [terraform-google-modules/terraform-google-kubernetes-engine#879]
In our terraform setup, we configure the `google` and `google-beta` providers to use a service account access token to interact with the GCP APIs:

```
provider "google" {
  access_token = data.google_service_account_access_token.default.access_token
}

provider "google-beta" {
  access_token = data.google_service_account_access_token.default.access_token
}
```

Ideally, the ASM module would impersonate this service account as well during the ASM installation. However, this does not seem to be the case, given that the module shells out to the gcloud CLIs, which are not guaranteed to be configured with the service account (e.g. they are configured with personal accounts).

**Comment by alexbrand-au** [comment]
Related to #874

**Comment by yashbhutwala** [comment]
@alexbrand-au I did add `impersonate_service_account` to the `asm` module as part of [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/903/files#diff-1791dcd3e78c4dba51173c1f465f494cbe4f30691b998d0243de701e366575c3R45).  Hopefully, it resolves the issue for you as well 😃

**Comment by bharathkkb** [comment]
This should now be possible via https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/57fca4b1f1ebe597ff9ae521a339a63295877c1f/modules/asm/variables.tf#L90

**Comment by ignaciojcano** [comment]
Was this removed in newer versions?
