### ISSUE TITLE
Destroy command does not delete the asm-system namespace

### ISSUE THREAD

**Issue by alexbrand** [terraform-google-modules/terraform-google-kubernetes-engine#881]
Currently, the Anthos Service Mesh module does not delete the `asm-system` namespace, which houses the Canonical service.

**Comment by bharathkkb** [comment]
Thanks for the report, looks like using the install_asm script installs the `Canonical Service controller` to the [asm-system ns](https://cloud.google.com/service-mesh/docs/canonical-service-controller-enable-and-disable). We should clean this up, happy to review a PR.
