### ISSUE TITLE
Add the cluster ID to the outputs

### ISSUE THREAD

**Issue by ferrarimarco** [terraform-google-modules/terraform-google-kubernetes-engine#885]
Hi team!

While working with your module, I wasn't able to find the [id](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#id) of the cluster in the outputs of the [kubernetes-engine](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google) module (tested with version `14.2.0`).

Having the ID is useful for all the resources that need an explicit cluster ID, such as [gke_hub_membership](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_membership).

A possible workaround is to use the [google_container_cluster data source](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/container_cluster) (feeding it with the `name` and `location` outputs of the module to implicitly create a dependency). Example:

```hcl
data "google_container_cluster" "source-cluster" {
  name     = module.kubernetes-engine-source.name
  location = module.kubernetes-engine-source.location
}
```

Having that ID in the module outputs would save a couple of trips to the API server, and simplify the Terraform descriptors. Thoughts?

Thanks!

**Comment by morgante** [comment]
Yes, I agree we should add this. Adding to the backlog, though a PR would also be welcome.
