### ISSUE TITLE
Creating Firewall gets 400 error resourceNotReady

### ISSUE THREAD

**Issue by tonyjchong** [terraform-google-modules/terraform-google-kubernetes-engine#888]
Hi everyone, 

I'm trying to provision a private gke cluster using the gke module but there is one issue that I cannot seem to figure out. 

```
Error: Error creating Firewall: googleapi: Error 400: The resource 'projects/<projectname>/global/networks/tony-gke' is not ready, resourceNotReady

  on .terraform\modules\gke\modules\beta-private-cluster\firewall.tf line 61, in resource "google_compute_firewall" "master_webhooks":
  61: resource "google_compute_firewall" "master_webhooks" {
```

The Global network resource is available in the GCP Cloud console, and other objects in Terraform seem to find it without any issues. If I run terraform again, the firewall gets created without any errors, but then for some unknown reason, terraform destroys my node pool and is never able to recreate it. I'm not sure where exactly the problem is and was hoping I could get some help. Happy to post the HCL. Not sure if these are 2 different issues or related to the same root cause. 

Thanks in advance!

**Comment by morgante** [comment]
I haven't seen this before.

Are you attempting to create the network in the same Terraform config as the cluster?

**Comment by tonyjchong** [comment]
@morgante Thanks for the tip. It never occurred to me to split up the various components of my stack. I was able to run `terraform apply -target=module.module_name` with my VPC first, Bastion 2nd, and GKE 3rd and it all provisioned with 0 errors. Thanks again!
