### ISSUE TITLE
Unresolvable module version constraint

### ISSUE THREAD

**Issue by apallares19** [terraform-google-modules/terraform-google-kubernetes-engine#898]
hello everyone. can you please lend me a hand with this? i dont know why this is happening. the code was working about 3 days ago.

i'm running terraform init & terraform init -upgrade with no success. what should i do?

 There is no available version of module "terraform-google-modules/kubernetes-engine/google" (k8s-cluster.tf:3) which matches the given version constraint. The newest
│ available version is 14.3.0.

**Comment by morgante** [comment]
Please share your config.

**Comment by apallares19** [comment]
provider "google-beta" {
  region  = var.region
  project = var.project_id
  credentials = file(var.gcp-credentials)
}

provider "google" {
  region  = var.region
  project = var.project_id
  credentials = file(var.gcp-credentials)
}

module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google"
  project_id                 = var.project_id
  name                       = "gke-stage-tf"
  region                     = var.region
  zones                      = ["us-east1-b", "us-east1-c", "us-east1-d"]
  network                    = "${format("%s","${var.company}-${var.env}-vpc")}"
  subnetwork                 = "${format("%s","${var.company}-${var.env}-public1b-subnet")}"
  ip_range_pods              = "stage-public1b-subnet-gke-01-pods"
  ip_range_services          = "stage-public1b-subnet-gke-01-services"
  http_load_balancing        = false
  horizontal_pod_autoscaling = false
  network_policy             = false
  version                    = "1.18.17-gke.1900"
  
  node_pools = [
    {
      name               = "node-pool-gke-1"
      machine_type       = "e2-medium"
      node_locations     = "us-east1-b,us-east1-c,us-east1-d"
      min_count          = 1
      max_count          = 2
      local_ssd_count    = 0
      disk_size_gb       = 20
      disk_type          = "pd-standard"
      image_type         = "COS"
      auto_repair        = true
      auto_upgrade       = true
      service_account    = "default"
      preemptible        = false
    }
  ]

  node_pools_tags = {
    node-pool-gke-1 = [
      "gke-stage-tf",
    ]
  }
}

is this what you mean when you said "config"?

**Comment by morgante** [comment]
Yes, I see the issue.

`version` should be used to specify the *module* version. To specify the Kubernetes version, you must use the `kubernetes_version` variable.

```
  horizontal_pod_autoscaling = false
  network_policy             = false
  kubernetes_version      = "1.18.17-gke.1900"
```

**Comment by apallares19** [comment]
works like a charm. thank you soy much for your time and help!
