### ISSUE TITLE
Cluster resource ephemeral_storage_config for localSSD

### ISSUE THREAD

**Issue by jeremyrcampb** [terraform-google-modules/terraform-google-kubernetes-engine#899]
I'd like to [use localSSDs for ephemeral storage](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/local-ssd) for specific node pools.  It looks like the Google provider has exposed this on the beta provider for the [container_cluster](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#ephemeral_storage_config) resource.  Is it on the radar to get added to this module?

Thank you!

**Comment by morgante** [comment]
We'd be happy to review a PR adding this.

**Comment by jeremyrcampb** [comment]
Addressed in merged PR.  Thanks!
