### ISSUE TITLE
modules/workload-identity using iam_member vs iam_binding

### ISSUE THREAD

**Issue by fkowal** [terraform-google-modules/terraform-google-kubernetes-engine#900]
Hello

I've been setting the workload identity permissions for my k8s cluster
so that istio can access stackdriver.

when using the 

```
module "istio-workload-identity" {
  source    = "terraform-google-modules/kubernetes-engine/google//modules/workload-identity"
  version = "14.3.0"

  use_existing_k8s_sa = true
  account=istio-telemetry@popshopdev.iam.gserviceaccount.com
  name                = "istio-telemetry"
  k8s_sa_name         = "istio-mixer-service-account"
  namespace           = "istio-system"
  project_id          = var.project_id
  roles = [
      "roles/logging.logWriter",
      "roles/monitoring.metricWriter",
      "roles/monitoring.viewer",
  ]
}
```

and the result was that the istio telemetry mixer pod was still unable to write the logs / metrics

what I found that the above terraform module uses a `google_service_account_iam_member` to setup the workloadIdentityUser role
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/workload-identity/main.tf#L62

```
resource "google_service_account_iam_member" "main" {
  service_account_id = google_service_account.cluster_service_account.name
  role               = "roles/iam.workloadIdentityUser"
  member             = local.k8s_sa_gcp_derived_name
}
```

This is not what this article https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity recommends

After copying the logic from the workload module and replacing the 

`google_service_account_iam_member` with `google_service_account_iam_binding`

Which is in what the above article recommends.

My istio mixer was allowed to access stackdriver/monitoring

**Comment by morgante** [comment]
Can you please explain what else went on in your environment? I highly suspect it's something different, not the change you made.

Changing from `google_service_account_iam_member` to `google_service_account_iam_binding` should not cause a difference. (In fact, `google_service_account_iam_member` is the equivalent of the `gcloud iam service-accounts add-iam-policy-binding` command from the linked article.)
