### ISSUE TITLE
Enabling and disabling node pools fields or extracing node pools logic out of the module into a seperate one

### ISSUE THREAD

**Issue by ksiadz** [terraform-google-modules/terraform-google-kubernetes-engine#906]
I am aware it's a big one, but I think many people may need this or are in a pain because of it.

I am using beta-public-cluster-update-variant submodule, but as a generic template for clusters provisioning. Meaning I need to be able to parametrize cluster input vars depending on team usage or a cluster purpose. I would assume that most users of this module may have clusters creation pipelines with some parameters and it's expected to support that. Which I do by setting up TF_VARs in my pipeline. Except for node pools as those have to be hardcoded as fields. 

Terraform doesn't support dynamic field types for modules so I have to create node pools which I don't need and sadly GCP doesn't allow max_node_count to be 0 so it always generates costs and node types not required which are always being enabled to at least 1 node of each pool. 

The alternative is to copy and paste usage of your module in all possible node pools combinations, but this quickly grows into an unsustainable solution. 

I believe the easiest solution would be to extract node pools logic out of the main module. Maybe except for the default node pool. And then simply have count condition in each node pool module usage. 

Potentially it could also be solved by 'enable_ssd_pool' matching the name of each node pool in all corresponding fields and not include those fields which are false by using a terraform null value with a dynamic field inside of a module. 
Meaning: node_pools list, node_pools_oauth_scopes, node_pools_labels, node_pools_metadata etc.

**Comment by morgante** [comment]
I am missing something in your set up, because it should not require splitting into multiple modules. I suspect some way of how you're using Terraform doesn't follow best practices (for instance, we do *not* recommend directly invoking the module but instead you should have your own root configuration which references the module).

Can you share an example of your configuration which is not working where you believe it would somehow work if node pools were a separate module?

**Comment by ksiadz** [comment]
I am using this module dynamically, meaning our pipeline is setting TF_VARs like node types and other inputs of your module. We do not copy and paste use of this module.

Simple example would be:
```hcl
module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google//modules/beta-public-cluster-update-variant"
  project_id                 = var.project_id
  name                       = var.cluster_name
  regional                   = var.regional
  region                     = var.region
  zones                      = var.zones
  network                    = google_compute_network.container_network.name
  subnetwork                 = local.subnet_name
  ip_range_pods              = local.pods_range_name
  ip_range_services          = local.svc_range_name
  cluster_resource_labels    = var.cluster_resource_labels

  node_pools = [
    {
      name               = "default-node-pool"
      machine_type       = var.default_pool_node_type
      min_count          = var.default_pool_min_count
      max_count          = var.default_pool_max_count
      local_ssd_count    = 0
      disk_size_gb       = var.default_pool_disk_size
      disk_type          = var.default_pool_disk_type
      image_type         = var.image_type
      auto_repair        = true
      auto_upgrade       = true
      preemptible        = false
      initial_node_count = var.default_pool_node_count
    },
  ]

  node_pools_oauth_scopes = {
    all = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]

    default-node-pool = []
  }

  node_pools_labels = {
    all = {
      cluster_name = var.cluster_name
      managed_by   = "terraform"
    }

    default-node-pool = {
      default-node-pool = true
    }
  }

  node_pools_metadata = {
    all = {}

    default-node-pool = {}
  }

  node_pools_taints = {
    all = []

    default-node-pool = [
      {
        key    = "default-node-pool"
        value  = true
        effect = "PREFER_NO_SCHEDULE"
      },
    ]
  }

  node_pools_tags = {
    all = []

    default-node-pool = [
      "default-node-pool",
    ]
  }
}
```

As u can see I can provide all params. This allows me to reuse this config from a pipeline for many different use cases, but node pools are not easily parametrized as they are multiple fields of different types. I would expect to be able to attach a node pool after creating a cluster somehow without changing a tf file that is used by other clusters/pipelines.

I know the basic setup of having a .tf file per cluster won't have this issue as then tf code will be copied and pasted everywhere, but I think most places currently have automation of this sort to generate multiple clusters using the same .tf generic cluster template while passing TF_VARS from a CI/CD tool into it.


I would expect to have a separate nodes pool module which I can attach allowing me to use tf `count` to disable or enable specific node pools based on TF_VAR param.

**Comment by morgante** [comment]
Can you explain what the actual blockers have been in trying to parameterize the inputs? With Terraform 0.13+ features, it should be possible to automate construction of the `node_pools` block based on variables.

> I think most places currently have automation of this sort to generate multiple clusters using the same .tf generic cluster template while passing TF_VARS from a CI/CD tool into it.

This module *is* the generic cluster template. If you want to have your own custom wrapping logic, you should build your own module to wrap this and implement the conversion from your TF_VARS to module inputs.

**Comment by ksiadz** [comment]
So maybe I lack tf skills (I usually avoid programming in tf to keep it simple), but when I tried to create a map per each node pool and then merge() them while still using condition statement like the following it was not building up all 3 maps in the new map.

```hcl
  node_pools = [
    merge(
      var.enable_ssd_node_pools ? local.ssd_node_pool : null,
      var.enable_gpu_node_pools ? local.gpu_node_pool : null,
      local.default_node_pool
    )
  ]
```
It was including local.ssd_node_pool and local.default_node_pool, but not local.gpu_node_pool.

I have to do similar for other fields like node_pools_taints, node_pools_tags etc. which also had issues.

**Comment by morgante** [comment]
You should not use `merge` here. That is to merge multiple objects into one.

What is your input format?

**Comment by ksiadz** [comment]
Hi, sorry for the delay in responding. Yes, you may be right I need to use proper terraform programming in this case or hardcode the values. 

My input is from a CI tool via passing TF_VARS for each node pool option. Like TF_VAR_node_count, using the same naming convention your module is using. 
So my variables.tf is a list of all options your module takes and duplicated vars for each node pool. 

So all inputs to your module are exposed and defined by a pipeline running them one level above. I did succeed with the above merge, but only with one optional and only one conditional node pool, and one default one. Merge doesn't seem to work if there are 2 or more conditional groups inside. 

Sorry for asking, but what is the right approach if not a merge one.

**Comment by morgante** [comment]
I'm a bit confused about what your set up entails. If you are trying to create multiple node pools, what does the value `TF_VAR_node_count` apply to? Which node pool?

If you give me a full example of your module configuration, the environment variable provided, and the expected output, I can try to help with the right configuration. In general though, I think you should really reconsider your approach. Dynamically switching off different variables and putting all your config logic into environment variables is an error prone approach.

**Comment by ksiadz** [comment]
Okay, sure I will provide more details. 

variables.tf
```hcl
# DEFAULT POOL
variable "default_pool_node_count" {
  type    = number
  default = 2
}

variable "default_pool_node_type" {
  type    = string
  default = "e2-medium"
}

variable "default_pool_disk_type" {
  type    = string
  default = "pd-standard"
}

variable "default_pool_disk_size" {
  type    = number
  default = 100
}

variable "default_pool_min_count" {
  type    = number
  default = 2
}

variable "default_pool_max_count" {
  type    = number
  default = 60
}

# SECOND POOL
variable "enable_second_node_pools" {
  type    = bool
  default = false
}

variable "second_pool_node_count" {
  type    = number
  default = 2
}

variable "second_pool_node_type" {
  type    = string
  default = "e2-medium"
}

variable "second_pool_disk_type" {
  type    = string
  default = "pd-standard"
}

variable "second_pool_disk_size" {
  type    = number
  default = 100
}

variable "second_pool_min_count" {
  type    = number
  default = 2
}

variable "second_pool_max_count" {
  type    = number
  default = 60
}
```
All of them have defaults which can but don't have to be overwriten from CI tool running it.

Use of a module in a terraform file used by all pipelines runs, different teams, dynamic provisioning of clusters on-demand, epithermal testing clusters etc:
```hcl
module "default-k8s-template-cluster" {
  source = "../modules/k8s_cluster_gcp"

  cluster_name     = var.cluster_name
  project_id       = var.project
  regional         = var.is_regional
  region           = var.region
  zones            = var.zones
  credentials_path = var.gcp_credentials_path
  image_type       = var.node_image_type
  // default node pool
  default_pool_node_count = var.default_pool_node_count
  default_pool_node_type  = var.default_pool_node_type
  default_pool_disk_type  = var.default_pool_disk_type
  default_pool_disk_size  = var.default_pool_disk_size
  default_pool_min_count  = var.default_pool_min_count
  default_pool_max_count  = var.default_pool_max_count
  // second node pool
  enable_second_node_pools = var.enable_second_node_pools
  second_pool_node_count   = var.second_pool_node_count
  second_pool_node_type    = var.second_pool_node_type
  second_pool_disk_type    = var.second_pool_disk_type
  second_pool_disk_size    = var.second_pool_disk_size
  second_pool_min_count    = var.second_pool_min_count
  second_pool_max_count    = var.second_pool_max_count
}
```

Example of a simple cluster config overwrites in CI file to make it smaller and change node type to a less expensive ones and make it a GCP type:
```yaml
.gcp_my_cluster:
  extends:
    - .common_gcp_clusters_tf_vars
  variables:
    ENV: "my-cluster"
    CLOUD: "gcp"
    TF_VAR_default_pool_node_count: "2"
    TF_VAR_default_pool_node_type: "e2-medium"
    TF_VAR_enable_second_node_pools: false
```

Usage of your module with provided configs. I haven't work on this branch in a while, but I believe this merge approach below with only two node pools actually worked. It was failing when I was trying to have 3 node pools or more. 

```hcl
locals {
  default_node_pool = {
    name               = "default-node-pool"
    machine_type       = var.default_pool_node_type
    min_count          = var.default_pool_min_count
    max_count          = var.default_pool_max_count
    local_ssd_count    = 0
    disk_size_gb       = var.default_pool_disk_size
    disk_type          = var.default_pool_disk_type
    image_type         = var.image_type
    auto_repair        = true
    auto_upgrade       = true
    preemptible        = false
    initial_node_count = var.default_pool_node_count
  }

  second_node_pool = {
    name               = "second-node-pool"
    machine_type       = var.second_pool_node_type
    min_count          = var.second_pool_min_count
    max_count          = var.second_pool_max_count
    local_ssd_count    = 100
    disk_size_gb       = var.second_pool_disk_size
    disk_type          = var.second_pool_disk_type
    image_type         = "COS"
    auto_repair        = true
    auto_upgrade       = true
    preemptible        = false
    initial_node_count = var.second_pool_node_count
  }

  node_pools = [
    merge(
      var.enable_second_node_pools ? local.second_node_pool : null,
      local.default_node_pool
    )
  ]
}

module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google//modules/beta-public-cluster-update-variant"
  project_id                 = var.project_id
  name                       = var.cluster_name
  regional                   = var.regional
  region                     = var.region
  zones                      = var.zones
  network                    = google_compute_network.container_network.name
  subnetwork                 = local.subnet_name
  ip_range_pods              = local.pods_range_name
  ip_range_services          = local.svc_range_name
  cluster_resource_labels    = var.cluster_resource_labels
  http_load_balancing        = false
  horizontal_pod_autoscaling = true
  network_policy             = false
  istio                      = false
  cloudrun                   = false
  dns_cache                  = false
  grant_registry_access      = true

  node_pools = local.node_pools

  node_pools_oauth_scopes = {
    all = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]

    default-node-pool = []
    second-node-pool     = var.enable_second_node_pools ? [] : null
  }

  node_pools_labels = {
    all = {
      cluster_name = var.cluster_name
      managed_by   = "terraform"
    }

    default-node-pool = { default-node-pool = true }
    second-node-pool     = var.enable_second_node_pools ? { second-node-pool = true } : null

  }

  node_pools_metadata = {
    all = {}

    default-node-pool = {}
    second-node-pool     = var.enable_second_node_pools ? {} : null
  }

  node_pools_taints = {
    all = []

    default-node-pool = [
      {
        key    = "default-node-pool"
        value  = true
        effect = "PREFER_NO_SCHEDULE"
      },
    ]

    second-node-pool = var.enable_second_node_pools ? [
      {
        key    = "second-node-pool"
        value  = true
        effect = "PREFER_NO_SCHEDULE"
      },
    ] : null

  }

  node_pools_tags = {
    all = []

    default-node-pool = [
      "default-node-pool",
    ]

    second-node-pool = var.enable_second_node_pools ? [
      "second-node-pool",
    ] : null

  }

  depends_on = [
    google_compute_network.container_network,
    google_compute_subnetwork.container_subnetwork
  ]
}
```

If there is a better way to be able to serve a lot of clusters with some parametrization from CI in your opinion I may consider it, but all params have defaults which makes them relatively error-prone in my opinion. The other way I know of doing it is using something like pulumi or jsonnet, which supports dynamic clusters creation with params slightly better than terraform, but it's not as mature as terraform is.

**Comment by morgante** [comment]
How are you handling Terraform state?

**Comment by ksiadz** [comment]
Each cluster has a subdirectory like this:
```bash
-backend-config="prefix=terraform-${CLOUD}-${ENV}/terraform_state"
``` 
I've seen this approach used internally by gitlab in their terraform docker image and in few other places.
