### ISSUE TITLE
HTTP to HTTPS redirection & FrontendConfig

### ISSUE THREAD

**Issue by pvanliefland** [terraform-google-modules/terraform-google-kubernetes-engine#908]
Hi!

Now that GKE has implemented a clean way for HTTP to HTTPS redirection (see [HTTP to HTTPS redirects](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect) in the official documentation), it would be awesome to be able to use it in terraform 🙏

Any thought on this?

**Comment by morgante** [comment]
This module is not meant to manage resources *inside* your cluster (including FrontendConfig). I recommend using Kubernetes tooling for that.

**Comment by pvanliefland** [comment]
@morgante understood. I created this issue here because `FrontendConfig` is a GKE-specific concept. Do you think it makes sense to create the issue in https://github.com/hashicorp/terraform-provider-kubernetes?
