### ISSUE TITLE
cluster deletion

### ISSUE THREAD

**Issue by sreejesh123** [terraform-google-modules/terraform-google-kubernetes-engine#912]
getting this error while terraform plan doing the cluster deletion   and version.tf does have  the following 

terraform {
  required_version = ">= 0.13"
  backend "remote" {}
  
  required_providers {
       
    google = {
      source  = "hashicorp/google"
      version = "3.65.0"
      }
    
    google-beta = {
      source  = "hashicorp/google-beta"
      version = ">= 3.32.0, <4.0.0"
      }
    kubernetes = {
      version = "~> 1.10, != 1.11.0"
    }
 
    time = {
      version = "~> 0.6"
    }
    
    null = {
      source  = "hashicorp/null"
      version = "3.0.0"
      }
    
     random = {
      source  = "hashicorp/random"
      version = "3.0.0"
      }
    }
}

ERROR during terraform plan phase  

To work with module.gke.google_container_cluster.primary its original provider
configuration at provider["registry.terraform.io/hashicorp/google-beta"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.gke.google_container_cluster.primary, after which you can remove the
provider configuration again.

**Comment by morgante** [comment]
You also need a provider block, like this:

```
provider "google-beta" {  version = "~> 3.63.0"}
```

**Comment by sreejesh123** [comment]
google-beta  already there  like this in my version.tf
 
google-beta = {
  source  = "hashicorp/google-beta"
  version = ">= 3.32.0, <4.0.0"
  }

I tried your recommendation , but plan is erroring our stating    "Error: Unsupported block type"

**Comment by morgante** [comment]
No, this is separate from the versions.tf. Please read more about how provider configuration works: https://www.terraform.io/docs/language/providers/configuration.html#provider-configuration-1

**Comment by sreejesh123** [comment]
thanks plan is working fine. 👍
