### ISSUE TITLE
vpc native private cluster

### ISSUE THREAD

**Issue by gnalsa** [terraform-google-modules/terraform-google-kubernetes-engine#913]
This request is open to track adding support for managing VPC-native clusters. Would specifically like the terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster module updated.

the google_container_cluster resource has the following options:

ip_allocation_policy - (Optional) Configuration of cluster IP allocation for VPC-native clusters. Adding this block enables IP aliasing, making the cluster VPC-native instead of routes-based. Structure is documented below.

networking_mode - (Optional, [Beta]) Determines whether alias IPs or routes will be used for pod IPs in the cluster. Options are VPC_NATIVE or ROUTES. VPC_NATIVE enables IP aliasing, and requires the ip_allocation_policy block to be defined. By default when this field is unspecified, GKE will create a ROUTES-based cluster.

**Comment by bharathkkb** [comment]
Hi @gnalsa 
[In the module code](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/beta-private-cluster/cluster.tf#L179-L183)
- networking_mode is always `VPC_NATIVE` as that is a best practice and recommended
- ip_allocation_policy is exposed via two vars `ip_range_pods` and `ip_range_services`

 Feel free to reopen if needed
