### ISSUE TITLE
Changing node_pools_oauth_scopes causes unrelated node pools to be updated

### ISSUE THREAD

**Issue by erkolson** [terraform-google-modules/terraform-google-kubernetes-engine#917]
The way `node_pools_oauth_scopes` is handled is unusable for production environments.

Steps to reproduce:
1.  Create a cluster with default configurations (i.e. not providing any values for `node_pools_oauth_scopes`)
2. Create a second node pool with a specific set of oauth scopes.
3. During apply, the first node pool will be deleted and recreated at the same time the second node pool is created.

Once a cluster is created with the default values, it is not possible to create a new node pool with a different oauth scope configuration that does not cause downtime.

**Comment by morgante** [comment]
Please share a copy of your configuration and the `terraform plan` which showed this.

Hyperbole is not helpful.

**Comment by erkolson** [comment]
Adding this block where previously the `node_pools_oauth_scopes` was not specified:
```
...
  node_pools_oauth_scopes = {
    all = []

    super-secure-pool = [
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring.write",
      "https://www.googleapis.com/auth/trace.append",
      "https://www.googleapis.com/auth/devstorage.read_only"
    ]
  }
...
```

Causes the `main-pool`, which is the only node pool at the time terraform is run, to be recreated:
```
  # module.gke.google_container_node_pool.pools["main-pool"] must be replaced
-/+ resource "google_container_node_pool" "pools" {
      ~ id                  = "<redacted>" -> (known after apply)
      ~ instance_group_urls = [
          - "<redacted",
        ] -> (known after apply)
      ~ max_pods_per_node   = 110 -> (known after apply)
        name                = "main-pool"
      + name_prefix         = (known after apply)
      ~ node_count          = 3 -> (known after apply)
      ~ node_locations      = [
          - "us-central1-b",
        ] -> (known after apply)
      ~ version             = "1.18.17-gke.700" -> (known after apply)
        # (4 unchanged attributes hidden)



      ~ node_config {
          ~ oauth_scopes      = [
              - "https://www.googleapis.com/auth/cloud-platform",
            ] -> (known after apply) # forces replacement
            tags              = [
                "gke-online-boutique-demo",
                "gke-online-boutique-demo-main-pool",
            ]
          ~ taint             = [] -> (known after apply)
            # (10 unchanged attributes hidden)


            # (2 unchanged blocks hidden)
        }


      ~ upgrade_settings {
          ~ max_surge       = 1 -> (known after apply)
          ~ max_unavailable = 0 -> (known after apply)
        }
        # (3 unchanged blocks hidden)
    }
```

**Comment by morgante** [comment]
Setting this part is what caused it:
```
  node_pools_oauth_scopes = {
    all = []
```

You chose to change the oauth scopes for all your node pools from the default (`"https://www.googleapis.com/auth/cloud-platform"`) to remove them.

Reviewing the Terraform plan makes that clear.

If you want to keep the existing defaults for node pools, simply keep the default value:

```
  node_pools_oauth_scopes = {
    all = ["https://www.googleapis.com/auth/cloud-platform"]

    super-secure-pool = [
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring.write",
      "https://www.googleapis.com/auth/trace.append",
      "https://www.googleapis.com/auth/devstorage.read_only"
    ]
  }
```

**Comment by erkolson** [comment]
I believe that will cause all node pools to get the `cloud-platform` scope.

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/cluster.tf#L283-L286

**Comment by morgante** [comment]
If you truly want to manage scopes granularly, then you will need to list each node pool explicitly.
