### ISSUE TITLE
tf-gke service account needs 'container.clusters.get' permission after enabling Cloud Operations

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [terraform-google-modules/terraform-google-kubernetes-engine#926]
Without certain permission, we are getting below errors after enabled Cloud Operations

Error retrieving gcp metadata: rpc error: code = PermissionDenied desc = Required "container.clusters.get" permission(s) for "projects/xxxxxx/locations/xxxxx/clusters/xxxxxxx".
emergency Serving Prometheus metrics

After contacting with google support, we got advised that 'container.clusters.get'  is needed to send logs to Stackdriver. Least privileged role containing this permission is 'roles/container.clusterViewer'. 

Ref: service account: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/beta-private-cluster-update-variant/sa.tf#L39

**Comment by morgante** [comment]
Where is this error showing up?

Do you mind sending your case ID? I'd like to confer internally to see the guidance you were given. (Feel free to email it to morgantep@google.com if you prefer.)

Giving GKE permission to view all other clusters seems potentially dangerous.

**Comment by CharmanderJieniJieni** [comment]
Hi @morgante , sent through email

**Comment by morgante** [comment]
@CharmanderJieniJieni I've checked around internally and it turns out you actually *don't* need this permission. That error doesn't impact functionality (and we're going to investigate silencing it), but you can safely ignore it.

**Comment by CharmanderJieniJieni** [comment]
Sure, thanks for confirming that.
