### ISSUE TITLE
Upgrading from 12.3.0 to 13.0.0 (null resource deletions)

### ISSUE THREAD

**Issue by esn89** [terraform-google-modules/terraform-google-kubernetes-engine#928]
I read this document and acknowledged that my plan shows those 3 things are going to be destroyed and will be okay.

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/docs/upgrading_to_v13.0.md#node-pool-random-id-keepers-modified

I have a fourth one which wants to be replaced and wasn't detailed in the document:

```

  # module.gke.module.gcloud_delete_default_kube_dns_configmap.module.gcloud_kubectl.null_resource.module_depends_on[0] must be replaced
-/+ resource "null_resource" "module_depends_on" {
      ~ id       = "5136633051006002223" -> (known after apply)
      ~ triggers = { # forces replacement
          ~ "value" = "15" -> "14"
        }
    }
 ```
 
 I was wondering if this is safe for the health and uptime of my cluster?

**Comment by morgante** [comment]
That is safe to delete.

**Comment by esn89** [comment]
Thank you @morgante
