### ISSUE TITLE
Not able to decide control plane version for GKE. Always takes default value.

### ISSUE THREAD

**Issue by ArunKumarT1995** [terraform-google-modules/terraform-google-kubernetes-engine#929]
Hi,

I'm trying to create a cluster of control plane version 1.17 through terraform scripts but it always takes the default value. 

Scenario : 

1. Set release_channel to "UNSPECIFIED" to create static version cluster
2. Disabled auto upgrade and enabled version argument in node pool section.
3. Passing lastest version in 1.17 as variable through data.tf to kubernetes_version in cluster section and version in node pool section (since auto upgrade is false).

Output:

1. Control plane is getting created using default value of static version which is "1.19.9-gke.1900"
2. Node pool is getting created with desired version mention in data.tf file.

My configurations:

data.tf:

data "google_container_engine_versions" "gke" {
  provider       = google-beta
  project        = var.project_id
  location       = var.cluster_zone[0]
  version_prefix = "1.17.17-"
}

main.tf:

module "gke" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster"
  
  project_id             = var.project_id
  name                   = "${var.cluster_name}-${terraform.workspace}-gke"
  regional               = var.regional
  zones                  = var.cluster_zone
  kubernetes_version     = data.google_container_engine_versions.gke.latest_master_version

Node pool section arguments:

  auto_repair        = true
  auto_upgrade       = false
  version            = data.google_container_engine_versions.gke.latest_node_version

terraform version: 0.14.11

PS: Is there anyway to disable maintenance window (not relevant to the issue, just wanted to know).

**Comment by morgante** [comment]
Please share your *full* module config and your Terraform plan output.

**Comment by ArunKumarT1995** [comment]
[conf&Plan.zip](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/files/6654262/conf.Plan.zip)

Adding Full module Config and Plan output as requested. Let me know if you anything else. Thanks!

**Comment by morgante** [comment]
I think the issue is probably that you're setting `release_channel`. If you want to control the Kubernetes version, you should set `release_channel` to [none](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/cluster.tf#L54).

**Comment by ArunKumarT1995** [comment]
@morgante - when set release_channel as "NONE" or as an empty string i face below errors.

**When set as NONE**
Error: expected release_channel.0.channel to be one of [UNSPECIFIED RAPID REGULAR STABLE], got NONE

  on .terraform\modules\b-gke.gke\modules\beta-private-cluster\cluster.tf line 22, in resource "google_container_cluster" "primary":
  22: resource "google_container_cluster" "primary" {

**When set as empty string**
Error: expected release_channel.0.channel to be one of [UNSPECIFIED RAPID REGULAR STABLE], got

  on .terraform\modules\b-gke.gke\modules\beta-private-cluster\cluster.tf line 22, in resource "google_container_cluster" "primary":
  22: resource "google_container_cluster" "primary" {

Also below link says to use "UNSPECIFIED" to unenroll from release channel.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#release_channel

**Note : When release_channel is set "UNSPECIFIED" , cluster getting created reflects "None" for release channel in Kubernetes Console.**

**Comment by morgante** [comment]
@ArunKumarT1995 You need to set it to `null`.

**Comment by ArunKumarT1995** [comment]
@morgante still same error

Error: expected release_channel.0.channel to be one of [UNSPECIFIED RAPID REGULAR STABLE], got null

  on .terraform\modules\b-gke.gke\modules\beta-private-cluster\cluster.tf line 22, in resource "google_container_cluster" "primary":
  22: resource "google_container_cluster" "primary" {

**Comment by morgante** [comment]
The way it's set up, a value of `null` shouldn't even make it to the config: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/main.tf#L52

I think something odd is going on with your configuration. Can you try a fresh Terraform state and make sure you're using the latest provider version?

**Comment by ArunKumarT1995** [comment]
The error shown above are captured when doing terraform plan and not apply. So that means it is not making to config right?.

I use google provider version 3.45.0 . let me try latest version and revert back.

**Comment by ArunKumarT1995** [comment]
@morgante - updated google provider version to 3.72.0 which is the latest version but issue still exist.

**Comment by morgante** [comment]
Have you ever applied this config though? I'm not able to reproduce this issue.

**Comment by ArunKumarT1995** [comment]
@morgante - I was setting value release_channel as "null" which was causing the issue. After the setting it as null without quotes it worked. 

Closing this ticket.
