### ISSUE TITLE
Recurring maintenance window

### ISSUE THREAD

**Issue by uzugic** [terraform-google-modules/terraform-google-kubernetes-engine#932]
Hello,

I would like to set a maintenance window for the cluster to be `From 2:00 AM to 2:00 AM Weekly on Saturday, Sunday` but the `maintenance_start_time` says that the format should be RFC3339. How can I set days in the RFC3339 format or is there a way to have the window on some days of the week rather than daily?

**Comment by morgante** [comment]
Unfortunately this is not currently possible.
