### ISSUE TITLE
Spurious error with enable_autopilot and remove_default_node_pool

### ISSUE THREAD

**Issue by talonx** [terraform-google-modules/terraform-google-kubernetes-engine#935]
Adding "remove_default_node_pool" with "enable_autopilot", and setting the latter to its default value throws this error

```
"remove_default_node_pool": conflicts with enable_autopilot
```
I have set remove_default... to true as I want self-managed node pools, and autopilot is also set to false (the default). If I remove enable_autopilot the error goes away even though the end result is the same.

```
    google = {
      source = "hashicorp/google"
      version = "3.73.0"
    }
```

**Comment by morgante** [comment]
Since the module has no autopilot variable, I'm guessing you're not using this module.

Please file provider issues on the provider repo: https://github.com/hashicorp/terraform-provider-google
