### ISSUE TITLE
Error waiting for updating GKE node pool version: timeout while waiting for state to become 'DONE'

### ISSUE THREAD

**Issue by clgx-skakauridze** [terraform-google-modules/terraform-google-kubernetes-engine#939]
When upgrading large clusters, seeing such timeouts. Is there a way to avoid this? Was not able to see any timeout related value which can be set.

```
12:54:03  Error: Error waiting for updating GKE node pool version: timeout while waiting for state to become 'DONE' (last state: 'RUNNING', timeout: 45m0s)
```

**Comment by morgante** [comment]
We inherit the standard timeout. I recommend just applying again later.

**Comment by clgx-skakauridze** [comment]
Ok, got it. Thanks @morgante  for such a quick reply, will mark this as closed.
