### ISSUE TITLE
When changing nodepool Name or VM Type its retuning "Error: Cycle:"

### ISSUE THREAD

**Issue by clgx-skakauridze** [terraform-google-modules/terraform-google-kubernetes-engine#943]
Hello,
Related issue: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/767

We tried to remove a node pool, but its giving such error:
```
Error: Cycle: module.MASKED-anthos-kf-cluster["us-w1"].module.gke.module.gcloud_delete_default_kube_dns_configmap.module.gcloud_kubectl.null_resource.module_depends_on[0], module.MASKED-anthos-kf-cluster["us-w1"].module.gke.google_container_node_pool.pools["kf-node-pool-2"] (destroy), module.MASKED-anthos-kf-cluster["us-w1"].module.gke.random_id.name["kf-node-pool-2"] (destroy), module.MASKED-anthos-kf-cluster["us-c1"].module.gke.random_id.name["kf-node-pool-2"] (destroy), module.MASKED-anthos-kf-cluster["us-c1"].module.gke.module.gcloud_delete_default_kube_dns_configmap.module.gcloud_kubectl.null_resource.module_depends_on[0], module.MASKED-anthos-kf-cluster["us-c1"].module.gke.google_container_node_pool.pools["kf-node-pool-2"] (destroy)
```

Is there a reasonable solution for this? How we should proceed?

**Comment by bharathkkb** [comment]
Hi @clgx-skakauridze 
Could you provide an example config I can try to reproduce. IIRC `skip_provisioners = true` seemed to resolve it in one of the issues we received.

**Comment by clgx-skakauridze** [comment]
This can be closed.
In our case skip_provisioners = true was giving the same cycle Error.
So we have a fork on this repo and just deleted whole dns.tf because we manage it separately when we need.

Thanks for the reply though!
