### ISSUE TITLE
Terraform destroy -target = (any single nodepool) is deleting all of my nodepools

### ISSUE THREAD

**Issue by tstarun990** [terraform-google-modules/terraform-google-kubernetes-engine#950]
Terraform destroy -target = (any single nodepool id)  is destroying my all nodepools.

I am using terraform   source = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster-update-variant" to create cluster with two nodepools.

Now the requirement is to delete first nodepool without touching the code.

I tried :-

terragrunt destroy -target='module.gke.module.gke.google_container_node_pool.pools["dev-gusc1-ee-vpc-defnp01"]'  -target ='module.gke.module.gke.random_id.name["dev-gusc1-ee-vpc-defnp01"]'

and its showing to delete two nodepools.

why its destroying second nodepool as well.

Is it a bug from registry side or I am doing something wrong?

**Comment by morgante** [comment]
Sounds like a bug in Terragrunt.
