### ISSUE TITLE
creating anthos clutser in a single apply

### ISSUE THREAD

**Issue by pavithranagaraj26** [terraform-google-modules/terraform-google-kubernetes-engine#953]
Hi, 

I would like to know whether we can implement modules like GKE, HUB, ASM, ACM integration in a single terraform apply? The depends on is not working due to count which is used in the root module. Can you please suggest some best way to do it in a single apply to create a cluster, register it with hub and install asm and acm features with anthos workload?

**Comment by morgante** [comment]
What's the error you're getting? It should be possible to apply all in a single run.

This example shows combining them: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/simple_zonal_with_acm

**Comment by pavithranagaraj26** [comment]
╷
│ Error: Error in function call
│
│   on .terraform/modules/asm/modules/asm/main.tf line 47, in locals:
│   47:   asm_iam_member = var.enable_gcp_iam_roles ? coalesce(var.impersonate_service_account, var.service_account, var.iam_member) : ""
│     ├────────────────
│     │ var.iam_member is ""
│     │ var.impersonate_service_account is ""
│     │ var.service_account is ""
│
│ Call to function "coalesce" failed: no non-null, non-empty-string arguments.

**Comment by pavithranagaraj26** [comment]
│ Error: Invalid count argument
│
│   on .terraform/modules/asm.asm_install/main.tf line 57, in resource "random_id" "cache":
│   57:   count = (! local.skip_download) ? 1 : 0
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many
│ instances will be created. To work around this, use the -target argument to first apply only the resources that the count
│ depends on.

**Comment by morgante** [comment]
Can you share your configuration?

As noted in the ASM readme, "If enable_gcp_iam_roles, one of impersonate_service_account, service_account, or iam_member must be set."

**Comment by pavithranagaraj26** [comment]
Hi, I have cleared the other error. This is the error which I am facing
│ Error: Invalid count argument
│
│   on .terraform/modules/asm.asm_install/main.tf line 57, in resource "random_id" "cache":
│   57:   count = (! local.skip_download) ? 1 : 0
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so
│ Terraform cannot predict how many instances will be created. To work around this, use the -target
│ argument to first apply only the resources that the count depends on.

**Comment by morgante** [comment]
@pavithranagaraj26 I need to see a copy of your config to reproduce / understand the issue.

**Comment by gaurav517** [comment]
I am getting the same error when I add `depends_on` in `acm` module.. but I believe this is being fixed in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/945?

**Comment by bharathkkb** [comment]
@pavithranagaraj26  this maybe due module level depend_on usage. Check out the suggestion here https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/957#issuecomment-883841633 or feel free to reopen with you particular configuration so we can help debug.
