### ISSUE TITLE
Enable an existing GSA to be used by the workload-identity module

### ISSUE THREAD

**Issue by jackwhelpton** [terraform-google-modules/terraform-google-kubernetes-engine#956]
The workload identity module currently supports using an existing KSA, but not the alternate configuration where an existing GSA is present. This is a common requirement for us, as we'll have two identical clusters set up within the same project, in different regions, for disaster recovery purposes.

It would be really handy to be able to create a single GSA, and then have the workload identity module bind that to a new KSA in each cluster. I've raised PR https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/955 that should do this, let me know if it looks reasonable.

**Comment by morgante** [comment]
This seems like a good ask, thanks for opening a PR. Will discuss details there.
