### ISSUE TITLE
cluster autoscaling profile

### ISSUE THREAD

**Issue by hhcauldwell** [terraform-google-modules/terraform-google-kubernetes-engine#958]
Would it be possible to add a way to configure a cluster's autoscaling profile? I want to be able to set it to "OPTIMIZE_UTILIZATION" for a more aggressive scale down compared to the default value of "BALANCED".

**Comment by bharathkkb** [comment]
@hhcauldwell this is supported in our `beta-*` modules
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/712fc54983eccd072b49a7d75078334ef11baef4/modules/beta-public-cluster/variables.tf#L239
