### ISSUE TITLE
ACM: git-importer being OOMKilled

### ISSUE THREAD

**Issue by gaurav517** [terraform-google-modules/terraform-google-kubernetes-engine#963]
When adding big manifests (`cert-manager` in my case), `git-importer` gets OOM Killed. Current memory limit for the container is `200Mi`. Is there a way to customize this? I am using `acm` module in this repo for anthos-config-management setup.

```
Warning  OOMKilling  28m                  kernel-monitor  Memory cgroup out of memory: Killed process 621834 (git-importer) total-vm:953624kB, anon-rss:201560kB, file-rss:34400kB, shmem-rss:0kB, UID:1000 pgtables:572kB oom_score_adj:994
  Warning  SystemOOM   28m                  kubelet         System OOM encountered, victim process: git-importer, pid: 622271
  Warning  OOMKilling  28m                  kernel-monitor  Memory cgroup out of memory: Killed process 622271 (git-importer) total-vm:953304kB, anon-rss:201508kB, file-rss:33120kB, shmem-rss:0kB, UID:1000 pgtables:552kB oom_score_adj:994
  Warning  SystemOOM   27m                  kubelet         System OOM encountered, victim process: git-importer, pid: 622838
  Warning  OOMKilling  27m                  kernel-monitor  Memory cgroup out of memory: Killed process 622838 (git-importer) total-vm:953304kB, anon-rss:201372kB, file-rss:32736kB, shmem-rss:0kB, UID:1000 pgtables:556kB oom_score_adj:994
```
Thanks.

**Comment by morgante** [comment]
This is not an issue with the Terraform module. Please open a support case with Google for help with triaging the OOM error.

As a workaround, you can try manually increasing the memory limit.

**Comment by gaurav517** [comment]
Thanks. I can't set memory limit manually. It gets reset in few seconds automatically to 200Mi. 

I understand that it's not an issue with terraform module but if module allows is to set memory limit somehow then that would help until this issue is fixed properly.

**Comment by morgante** [comment]
@gaurav517 Unfortunately there isn't a way for the module to override the memory limit.

**Comment by gaurav517** [comment]
Thanks created https://issuetracker.google.com/issues/194634010.
