### ISSUE TITLE
Unable to download modules from terraform registry

### ISSUE THREAD

**Issue by gautham-jagan** [terraform-google-modules/terraform-google-kubernetes-engine#969]
I tied to automate the gke cluster using terraform deafult module https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest But I'm getting the following error

Error: Failed to download module │ │ Could not download module "gke" (maingk.tf:12) source code from │ "github.com/terraform-google-modules/terraform-google-kubernetes-engine": │ error downloading │ 'https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git': │ git must be available and on the PATH ╵

I'm using the binary version of terraform and not the snap version. My version is 1.0.3. Not sure what is causing this issue? Any help would be appreciated

**Comment by bharathkkb** [comment]
Hi @gautham-jagan 
Looks like Git is not available in PATH. After you install git and add to path it should work.
