### ISSUE TITLE
Using safer_cluster_iap_bastion module gives Invalid for_each argument in beta-private-cluster/sa.tf

### ISSUE THREAD

**Issue by shermanericts** [terraform-google-modules/terraform-google-kubernetes-engine#975]
Hi There!

When leveraging the [safer_cluster_iap_bastion](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest/examples/safer_cluster_iap_bastion) terraform module, I'm getting this error:

I am on Terraform v1.0.0.  I am using the default params in the above module.
Any help much appreciated.  Any more background info folks need please let me know.
Thanks in advance!

```
│ Error: Invalid for_each argument
│
│   on .terraform/modules/arms-dev.kubernetes-engine_example_safer_cluster_iap_bastion/modules/beta-private-cluster/sa.tf line 75, in resource "google_project_iam_member" "cluster_service_account-gcr":
│   75:   for_each = var.create_service_account && var.grant_registry_access ? toset(local.registry_projects_list) : []
│     ├────────────────
│     │ local.registry_projects_list is list of string with 1 element
│     │ var.create_service_account is true
│     │ var.grant_registry_access is true
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many
│ instances will be created. To work around this, use the -target argument to first apply only the resources that the for_each depends
│ on.
```

**Comment by bharathkkb** [comment]
Hi @shermanericts 
The [safer cluster iap bastion](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/safer_cluster_iap_bastion) is an example and not to be used directly as a module from the registry. Are you passing a pre created `project_id` or dynamically creating it in the same configuration ( a configuration to reproduce this would be helpful)

**Comment by shermanericts** [comment]
> Hi @shermanericts
> The [safer cluster iap bastion](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/safer_cluster_iap_bastion) is an example and not to be used directly as a module from the registry. Are you passing a pre created `project_id` or dynamically creating it in the same configuration ( a configuration to reproduce this would be helpful)

Hi @bharathkkb 
Thank you firstly for the quick reply!

You are correct.  I was initially doing the latter (dynamically creating it in the same configuration).  When I create the `project_id` ahead of time and subsequently passing this pre-created `project_id` the error does not reproduce.

Here's a [gist](https://gist.github.com/shermanericts/9fb0c8eb67a1f3ab3af47b426c4dc4cd) that I used to recreate the issue.  I have a local project folder that calls a local module, again created the project id dynamically.

If this is as designed, feel free to close this issue.  Would be cool to figure out how to dynamically do this all in one state though :) 

----

As for not using the bastion module directly, I remember you telling me that before - apologies.  I did that as a quick example.  In my normal workflow, I've created a private fork of the repo and call my fork, making local modifications as needed.  I like what's there already and I feel like this method keeps things DRY for me.  Let me know if you have a better approach for this as well.


Again, thanks so much!

**Comment by shermanericts** [comment]
> @shermanericts yeah this is unfortunately a TF core issue and something we cannot fix within the module. General best practice is to have a separate configuration for projects and then pass that into the GKE configuration.
> 
> It's fine to bundle up multiple modules like in the safer cluster example, I was just mentioning it because we don't have compatibility guarantees across versions for examples. As long as you have a fork that problem wont be there :)

perfect.  thanks!
