### ISSUE TITLE
asm and acm on the private cluster configurations

### ISSUE THREAD

**Issue by pavithranagaraj26** [terraform-google-modules/terraform-google-kubernetes-engine#977]
Hi ,

I am dealing with the error "Unable to connect to the server: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" due to private cluster. Is there any example which is using private cluster with asm and acm feature ?

**Comment by bharathkkb** [comment]
Hi @pavithranagaraj26 
You can run the TF for ASM/ACM from a GCE instance that has network access to the control plane to workaround this issue. This workaround would not be needed for ACM once we have https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/945 but may still be needed for ASM.

**Comment by elebioda** [comment]
@bharathkkb I don't think #945 solves the problem as the acm module still attempts to do a kubectl apply command. Which will fail on a private cluster unless SSH to a bastion.
