### ISSUE TITLE
Compute Engine persistent disk CSI Driver add-on support

### ISSUE THREAD

**Issue by andrewnazarov** [terraform-google-modules/terraform-google-kubernetes-engine#978]
It seems that there is no way to set `--update-addons=GcePersistentDiskCsiDriver=ENABLED` using this module. Any plans to support this? Or it's not relevant for K8s 1.21+?

**Comment by bharathkkb** [comment]
Hi @andrewnazarov Our beta modules support the CSI driver
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/b208d5cbd2ffd10e7889150428bb17bc1486c686/modules/beta-public-cluster/variables.tf#L426
Feel free to reopen if needed.

**Comment by daxmc99** [comment]
When will this graduate to this module? This is no longer in beta

**Comment by morgante** [comment]
@daxmc99 If you need this in the GA module, feel free to open a pull request.
