### ISSUE TITLE
Is there any way to specify a  min_cpu_platform?

### ISSUE THREAD

**Issue by shermanericts** [terraform-google-modules/terraform-google-kubernetes-engine#985]
Hey there!
I'm looking for a way to set a minimum cpu platform, preferably at the [node pool level](https://cloud.google.com/kubernetes-engine/docs/how-to/min-cpu-platform#gcloud_1), or secondly at a cluster level.

I noticed that the Terraform resource google_container_cluster has a [min_cpu_platform](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#min_cpu_platform) in Beta.  

I didn't see anything when going through this module.

Thanks in advance!

**Comment by morgante** [comment]
Not currently, it would need to be added [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/bb36cbf7b0574b5e38daa6598ff42feeca893734/autogen/main/cluster.tf.tmpl#L86).

Happy to review a PR.

**Comment by shermanericts** [comment]
thanks @morgante  - i'll check it out.
