### ISSUE TITLE
GKE modules squash ASM cluster labels

### ISSUE THREAD

**Issue by bjhshadow** [terraform-google-modules/terraform-google-kubernetes-engine#990]
GKE submodules will delete cluster labels on any subsequent run after creation.  

ASM uses 'asmv" and "mesh_id" for observability and mesh management and are created dutifully by ASM module.   Any run with a GKE module (beta-private-cluster-update-variant, beta-private-cluster, private-cluster) will remove ASM cluster resource labels acting as the authorative source.    The module does not allow the use of the lifecycle meta argement to ignore them.    The modules cannot be used in conjuction or with separate terraform plans on the same cluster.

The ASM module never recognizes that the cluster resource labels are removed regardless of the 'enable_cluster_labels' input setting.

GKE should allow lifecycle meta or ignore labels as an 'additive' option.   ASM module should recognize and replace if removed.

**Comment by morgante** [comment]
Unfortunately the current ASM model does not work very well with the declarative approach of Terraform.

The best workaround is just to add the `asmv` and `mesh_id` as labels in your Terraform config. Is there a reason this wouldn't work?

**Comment by richiefrich** [comment]
So again I am using managed control planes so how do I match the ASM major and minor versions without knowing what version is being installed, so I can download the correct version of **istioctl**.  I do know you shouldn't be using just any version of **istioctl** to create the secrets.   I get that you can set the ASM version in this module but that isn't the minor version.  So how do you create your secrets? I posted the article for you. I do not want to manually add these secrets, I make to many environments to keep track of these. Thanks!

**Comment by morgante** [comment]
@richiefrich Please open a ticket with your Google support account. I don't think you actually need to use istioctl with the managed control plane at this point.

**Comment by richiefrich** [comment]
@morgante  You are correct this is an ASM issue and this is the ASM module. If I cant get the version of ASM I cant install the secrets. I did open a support ticket with them and they said I still need the secrets, with managed control planes.  So how else can get the version of ASM?  I really don't want to fork this module, can you export the version to a file within TF? That way I can use it from there. Thanks!

**Comment by morgante** [comment]
> @morgante You are correct this is an ASM issue and this is the ASM module. If I cant get the version of ASM I cant install the secrets. I did open a support ticket with them and they said I still need the secrets, with managed control planes.

I'm still confused by you need the `asmv` label to create the secrets.  You can set the ASM version with the `asm_version` variable. Moreover, I think you should really consider hardcoding your istioctl download.

**Comment by bjornsen** [comment]
I found an easier workaround. Terraform's [ignore_changes](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes) allows you to ignore specific keys in maps. When you declare your GKE cluster, ignore `resource_labels["asmv"]` and `resource_labels["mesh_id"]` and Terraform will preserve them on subsequent runs.

**Comment by morgante** [comment]
@bjhshadow That's a great workaround. i didn't realize you can ignore a specific key in a map, this would make sense to add.

**Comment by richiefrich** [comment]
I know this is closed and I see it merged in  version 17.2.0. but its still removing them for me. Which is odd.

**Comment by morgante** [comment]
@richiefrich This hasn't been released yet. It will go in the next release: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1063

**Comment by richiefrich** [comment]
@morgante   thanks
