### ISSUE TITLE
Pin Kubernetes version

### ISSUE THREAD

**Issue by datacabinet** [terraform-google-modules/terraform-google-kubernetes-engine#996]
Hi , Is there a way to pin Kubernetes version in the latest GKE terraform provider? We could do it before in earlier versions of the provider but now it only provides us specifying the minimum version . Is it hard to just keep updating and testing our whole stack without even knowing when terraform would give a new version of kubernetes.

**Comment by morgante** [comment]
I'm not entirely sure what you're referring to. For using this module, you can set the `kubernetes_version` to a specific version.

**Comment by pankajkumar229** [comment]
It is not documented here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster

**Comment by morgante** [comment]
That is the reference documentation for the *provider resource*. You are commenting on the *module* repo.

Please learn about the difference between modules and providers/resources. They are not the same.
